In [1]:
import optuna

In [2]:
name = "GDSC2_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df = df[
    ~(
        (df["values_0"] == float("-inf"))
        | (df["values_1"] == float("-inf"))
        | (df["values_2"] == float("-inf"))
        | (df["values_3"] == float("-inf"))
    )
]
df

[I 2025-03-22 11:43:24,465] Using an existing study with name 'GDSC2_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
11,11,0.780596,0.897198,0.904858,0.741584,2025-03-21 18:30:52.844003,2025-03-21 18:31:13.200357,0 days 00:00:20.356354,NaN,swish,...,True,SGD,3.0,Plateau,NaN,0.002575,0.000005,NaN,NaN,COMPLETE

In [3]:
name = "GDSC2"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df = df[
    ~(
        (df["values_0"] == float("-inf"))
        | (df["values_1"] == float("-inf"))
        | (df["values_2"] == float("-inf"))
        | (df["values_3"] == float("-inf"))
    )
]
df

[I 2025-03-22 11:43:27,976] Using an existing study with name 'GDSC2' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
0,0,0.737520,0.917582,0.915013,0.658281,2025-03-21 18:30:47.028472,2025-03-21 18:32:03.952397,0 days 00:01:16.923925,NaN,swish,...,NaN,AdamW,NaN,Step,30.0,NaN,0.000002,NaN,NaN,COMPLETE
1,1,0.683977,0.916411,0.917369,0.551685,2025-03-21 18:30:47.039103,2025-03-21 18:32:11.482431,0 days 00:01:24.443328,NaN,swish,...,NaN,AdamW,9.0,Plateau,NaN,0.000122,0.005874,NaN,NaN,COMPLETE
3,3,0.716989,0.912845,0.917864,0.624265,2025-03-21 18:30:47.060929,2025-03-21 18:31:42.949192,0 days 00:00:55.888263,NaN,gelu,...,NaN,AdamW,8.0,Plateau,NaN,0.001495,0.000299,NaN,NaN,COMPLETE
4,4,0.721014,0.917896,0.915877,0.626817,2025-03-21 18:30:47.074361,2025-03-21 18:32:11.765006,0 days 00:01:24.690645,35.0,relu,...,NaN,Adam,NaN,Cosine,NaN,NaN,0.000002,NaN,NaN,COMPLETE
7,7,0.710950,0.920788,0.920546,0.607650,2025-03-21 18:30:47.131602,2025-03-21 18:31:52.860565,0 days 00:01:05.728963,NaN,swish,...,NaN,AdamW,NaN,None,NaN,NaN,0.000003,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,189,0.683977,0.913720,0.922984,0.552707,2025-03-21 18:48:34.888682,2025-03-21 18:53:39.625030,0 days 00:05:04.736348,NaN,swish,...,False,SGD,7.0,Plateau,NaN,0.004391,0.000775,NaN,NaN,COMPLETE
190,190,0.667874,0.912627,0.920650,0.518950,2025-03-21 18:48:51.377303,2025-03-21 18:53:57.070034,0 days 00:05:05.692731,NaN,swish,...,False,SGD,7.0,Plateau,NaN,0.004015,0.000135,NaN,NaN,COMPLETE
191,191,0.667874,0.916487,0.924412,0.518950,2025-03-21 18:48:52.103111,2025-03-21 18:53:53.012979,0 days 00:05:00.909868,NaN,swish,...,False,SGD,7.0,Plateau,NaN,0.004324,0.000041,NaN,NaN,COMPLETE
192,192,0.741948,0.925182,0.923742,0.665274,2025-03-21 18:49:01.229578,2025-03-21 18:54:01.087633,0 days 00:04:59.858055,NaN,swish,...,False,SGD,NaN,None,NaN,NaN,0.000475,NaN,NaN,COMPLETE
193,193,0.684783,0.917254,0.922023,0.554354,2025-03-21 18:49:04.814674,2025-03-21 18:53:59.395018,0 days 00:04:54.580344,NaN,swish,...,False,SGD,NaN,None,NaN,NaN,0.001265,NaN,NaN,COMPLETE