In [1]:
import optuna

In [8]:
name = "GDSC2_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df = df[
    ~(
        (df["values_0"] == float("-inf"))
        | (df["values_1"] == float("-inf"))
        | (df["values_2"] == float("-inf"))
        | (df["values_3"] == float("-inf"))
    )
]
df

[I 2025-03-22 16:27:20,340] Using an existing study with name 'GDSC2_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,state
0,0,0.829308,0.927425,0.925547,0.812555,2025-03-22 13:59:37.841880,2025-03-22 14:02:03.909817,0 days 00:02:26.067937,22.0,relu,...,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000005,NaN,COMPLETE
1,1,0.803140,0.932451,0.935243,0.770530,2025-03-22 14:02:03.939534,2025-03-22 14:02:16.334481,0 days 00:00:12.394947,NaN,swish,...,NaN,NaN,Adam,NaN,Step,26.0,NaN,0.000007,NaN,COMPLETE
2,2,0.517311,0.875129,0.903760,0.066926,2025-03-22 14:07:40.919232,2025-03-22 14:07:54.185308,0 days 00:00:13.266076,32.0,swish,...,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000002,NaN,COMPLETE
3,3,0.825684,0.902634,0.910708,0.827421,2025-03-22 14:07:40.931369,2025-03-22 14:08:01.312912,0 days 00:00:20.381543,NaN,relu,...,NaN,NaN,Adam,NaN,Step,27.0,NaN,0.000045,NaN,COMPLETE
4,4,0.827295,0.951282,0.952776,0.801113,2025-03-22 14:07:40.948893,2025-03-22 14:10:52.264001,0 days 00:03:11.315108,49.0,relu,...,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.007576,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,591,0.841385,0.952622,0.954364,0.821558,2025-03-22 16:08:46.308957,2025-03-22 16:10:14.016831,0 days 00:01:27.707874,NaN,gelu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.001711,NaN,COMPLETE
592,592,0.801932,0.952247,0.953994,0.760467,2025-03-22 16:08:56.931744,2025-03-22 16:10:23.910480,0 days 00:01:26.978736,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000001,NaN,COMPLETE
593,593,0.803945,0.954035,0.956507,0.763936,2025-03-22 16:09:03.720819,2025-03-22 16:10:28.164058,0 days 00:01:24.443239,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000001,NaN,COMPLETE
594,594,0.842593,0.952079,0.953909,0.823795,2025-03-22 16:09:05.863183,2025-03-22 16:10:25.049539,0 days 00:01:19.186356,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000002,NaN,COMPLETE
596,596,0.829308,0.948166,0.949748,0.804067,2025-03-22 16:09:54.363778,2025-03-22 16:10:44.962114,0 days 00:00:50.598336,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000001,NaN,COMPLETE

In [9]:
df.params_gnn_layer.value_counts()

params_gnn_layer
Transformer    275
GAT             72
GATv2           68
Name: count, dtype: int64

In [6]:
name = "GDSC2"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df = df[
    ~(
        (df["values_0"] == float("-inf"))
        | (df["values_1"] == float("-inf"))
        | (df["values_2"] == float("-inf"))
        | (df["values_3"] == float("-inf"))
    )
]
df

[I 2025-03-22 16:27:17,476] Using an existing study with name 'GDSC2' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,state
0,0,0.677939,0.911260,0.914927,0.540758,2025-03-22 14:11:16.206835,2025-03-22 14:12:59.922622,0 days 00:01:43.715787,NaN,relu,...,0.902912,False,SGD,7.0,Plateau,NaN,0.001631,0.000003,NaN,COMPLETE
1,1,0.731079,0.918561,0.923645,0.648791,2025-03-22 14:11:16.231456,2025-03-22 14:11:33.144860,0 days 00:00:16.913404,42.0,swish,...,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000957,NaN,COMPLETE
2,2,0.661433,0.902575,0.907227,0.504420,2025-03-22 14:11:16.278792,2025-03-22 14:11:40.406697,0 days 00:00:24.127905,NaN,relu,...,NaN,NaN,Adam,NaN,None,NaN,NaN,0.003887,NaN,COMPLETE
3,3,0.769726,0.922095,0.916900,0.715706,2025-03-22 14:11:16.293268,2025-03-22 14:13:24.170633,0 days 00:02:07.877365,NaN,swish,...,0.808312,False,SGD,NaN,None,NaN,NaN,0.000001,NaN,COMPLETE
4,4,0.694847,0.917169,0.924348,0.577951,2025-03-22 14:11:16.307974,2025-03-22 14:12:59.297024,0 days 00:01:42.989050,NaN,swish,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.006684,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,402,0.695652,0.919517,0.925755,0.578125,2025-03-22 15:55:47.027594,2025-03-22 15:58:38.911148,0 days 00:02:51.883554,NaN,swish,...,NaN,NaN,Adam,NaN,None,NaN,NaN,0.007513,NaN,COMPLETE
403,403,0.683575,0.918183,0.919948,0.550857,2025-03-22 15:58:13.917280,2025-03-22 15:59:21.478780,0 days 00:01:07.561500,NaN,swish,...,NaN,NaN,Adam,NaN,None,NaN,NaN,0.006974,NaN,COMPLETE
405,405,0.596216,0.910483,0.919121,0.327297,2025-03-22 15:58:33.891253,2025-03-22 15:59:36.277745,0 days 00:01:02.386492,NaN,swish,...,NaN,NaN,Adam,NaN,None,NaN,NaN,0.008385,NaN,COMPLETE
406,406,0.786634,0.921452,0.923867,0.750000,2025-03-22 15:58:37.499446,2025-03-22 15:59:37.667293,0 days 00:01:00.167847,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000113,NaN,COMPLETE
407,407,0.702093,0.914211,0.906958,0.583802,2025-03-22 15:58:37.841700,2025-03-22 15:59:37.688823,0 days 00:00:59.847123,NaN,relu,...,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.007713,NaN,COMPLETE

In [7]:
df.params_gnn_layer.value_counts()

params_gnn_layer
GCN     263
MPNN     72
Name: count, dtype: int64