In [2]:
import optuna

In [3]:
name = "GDSC2_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df

[I 2025-03-31 13:08:42,183] Using an existing study with name 'GDSC2_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
0,0,0.848388,0.969878,0.970678,0.825877,2025-03-28 13:46:35.490221,2025-03-28 14:18:17.608014,0 days 00:31:42.117793,37.0,relu,...,0.000513,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002933,COMPLETE
1,1,0.628422,0.957340,0.958747,0.361241,2025-03-28 13:49:31.741367,2025-03-28 13:51:02.083606,0 days 00:01:30.342239,NaN,swish,...,0.003206,NaN,NaN,Adam,5.0,Plateau,NaN,0.001124,0.000036,COMPLETE
2,2,0.846749,0.963235,0.965034,0.824068,2025-03-28 13:49:31.746399,2025-03-28 13:57:44.504041,0 days 00:08:12.757642,NaN,relu,...,0.000036,NaN,NaN,Adam,NaN,Step,18.0,NaN,0.000002,COMPLETE
3,3,0.830282,0.966511,0.967357,0.799202,2025-03-28 13:49:32.871110,2025-03-28 14:00:58.948574,0 days 00:11:26.077464,45.0,swish,...,0.000048,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000005,COMPLETE
4,4,0.500000,0.760099,0.743745,0.000000,2025-03-28 13:49:32.872404,2025-03-28 13:51:11.768434,0 days 00:01:38.896030,NaN,gelu,...,0.000031,0.841668,False,SGD,8.0,Plateau,NaN,0.003496,0.000476,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,330,0.649034,0.925631,0.937672,0.449824,2025-03-29 18:50:29.748593,2025-03-29 19:31:16.911727,0 days 00:40:47.163134,25.0,gelu,...,0.006680,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000334,COMPLETE
334,334,0.851022,0.971375,0.971539,0.829051,2025-03-29 19:31:28.626485,2025-03-29 19:54:33.017196,0 days 00:23:04.390711,23.0,gelu,...,0.000293,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000226,COMPLETE
335,335,0.764757,0.961347,0.962254,0.685618,2025-03-29 19:54:33.052159,2025-03-29 20:04:46.760087,0 days 00:10:13.707928,NaN,gelu,...,0.000691,NaN,NaN,AdamW,6.0,Plateau,NaN,0.000256,0.000003,COMPLETE
336,336,0.665588,0.927706,0.939212,0.428290,2025-03-29 20:04:46.802720,2025-03-29 20:18:22.682729,0 days 00:13:35.880009,49.0,relu,...,0.009823,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.007632,COMPLETE
340,340,0.604826,0.959170,0.959892,0.320195,2025-03-29 20:18:34.232144,2025-03-29 20:19:28.327291,0 days 00:00:54.095147,40.0,gelu,...,0.001149,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000188,COMPLETE

In [4]:
tmp = df.loc[
    df[["values_0", "values_1", "values_2", "values_3"]]
    .max(axis=1)
    .sort_values(ascending=False)
    .index
]
tmp[tmp["params_gnn_layer"] == "GAT"].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
211,211,0.839858,0.971239,0.971393,0.813026,2025-03-29 11:02:09.606170,2025-03-29 11:33:14.383459,0 days 00:31:04.777289,37.0,gelu,...,0.000487,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000233,COMPLETE
311,311,0.843835,0.970667,0.971178,0.818938,2025-03-29 16:59:01.788530,2025-03-29 17:19:57.757267,0 days 00:20:55.968737,46.0,gelu,...,0.000875,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000207,COMPLETE
305,305,0.846138,0.970433,0.971091,0.822349,2025-03-29 16:49:21.716961,2025-03-29 17:19:36.777517,0 days 00:30:15.060556,39.0,gelu,...,0.000646,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000056,COMPLETE
113,113,0.817476,0.970358,0.970947,0.779674,2025-03-28 18:52:33.481824,2025-03-28 18:59:36.411816,0 days 00:07:02.929992,NaN,swish,...,0.000258,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000943,COMPLETE
328,328,0.844463,0.970110,0.970769,0.819748,2025-03-29 18:01:51.990840,2025-03-29 18:18:30.016709,0 days 00:16:38.025869,41.0,gelu,...,0.000620,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000282,COMPLETE

In [6]:
tmp[tmp["params_gnn_layer"] == "GATv2"].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
289,289,0.818017,0.971696,0.971751,0.780580,2025-03-29 15:43:10.153090,2025-03-29 16:14:19.748477,0 days 00:31:09.595387,NaN,gelu,...,0.000265,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000397,COMPLETE
77,77,0.835340,0.971648,0.971701,0.806127,2025-03-28 17:54:30.862970,2025-03-28 18:27:05.028213,0 days 00:32:34.165243,46.0,gelu,...,0.000362,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.001398,COMPLETE
29,29,0.843469,0.970414,0.971172,0.818798,2025-03-28 14:18:17.645414,2025-03-28 14:50:07.861976,0 days 00:31:50.216562,24.0,gelu,...,0.009889,0.941590,True,SGD,NaN,Cosine,NaN,NaN,0.007318,COMPLETE
248,248,0.842806,0.970556,0.970997,0.817531,2025-03-29 13:34:32.122670,2025-03-29 14:19:28.564959,0 days 00:44:56.442289,41.0,gelu,...,0.000066,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
38,38,0.842422,0.969931,0.970970,0.817224,2025-03-28 15:24:20.009969,2025-03-28 15:56:15.738518,0 days 00:31:55.728549,38.0,gelu,...,0.003901,0.934876,True,SGD,NaN,Cosine,NaN,NaN,0.003662,COMPLETE

In [7]:
tmp[tmp["params_gnn_layer"] == "Transformer"].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
278,278,0.852610,0.972680,0.972722,0.830889,2025-03-29 15:13:15.003478,2025-03-29 15:43:10.108661,0 days 00:29:55.105183,43.0,gelu,...,0.000632,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000295,COMPLETE
317,317,0.859606,0.972683,0.972462,0.840672,2025-03-29 17:31:52.000865,2025-03-29 18:01:49.148792,0 days 00:29:57.147927,37.0,gelu,...,0.000939,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000002,COMPLETE
219,219,0.854005,0.972592,0.972438,0.833094,2025-03-29 11:47:21.012066,2025-03-29 12:17:16.938529,0 days 00:29:55.926463,44.0,gelu,...,0.000636,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000190,COMPLETE
181,181,0.858611,0.972394,0.972481,0.839491,2025-03-29 09:19:55.304236,2025-03-29 09:54:05.896136,0 days 00:34:10.591900,44.0,gelu,...,0.000814,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000333,COMPLETE
218,218,0.857233,0.972054,0.972327,0.837550,2025-03-29 11:46:35.820799,2025-03-29 12:16:32.605737,0 days 00:29:56.784938,44.0,gelu,...,0.000621,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000201,COMPLETE

In [3]:
df.params_gnn_layer.value_counts()

params_gnn_layer
Transformer    70
GATv2          46
GAT            24
Name: count, dtype: int64

In [8]:
name = "GDSC2"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df

[I 2025-03-31 13:09:36,332] Using an existing study with name 'GDSC2' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
1,1,0.790140,0.955189,0.953871,0.739497,2025-03-28 13:33:15.048504,2025-03-28 13:51:42.311340,0 days 00:18:27.262836,37.0,relu,...,0.000055,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000012,COMPLETE
2,2,0.824401,0.957638,0.956261,0.792577,2025-03-28 13:33:15.072339,2025-03-28 13:51:40.566781,0 days 00:18:25.494442,NaN,relu,...,0.000528,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000003,COMPLETE
4,4,0.752232,0.956388,0.956467,0.673779,2025-03-28 13:33:15.104328,2025-03-28 13:38:27.166297,0 days 00:05:12.061969,NaN,swish,...,0.000046,NaN,NaN,Adam,NaN,Step,30.0,NaN,0.000002,COMPLETE
5,5,0.768544,0.955482,0.954777,0.702822,2025-03-28 13:33:15.121408,2025-03-28 13:41:24.766236,0 days 00:08:09.644828,39.0,relu,...,0.000107,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000082,COMPLETE
7,7,0.804218,0.955599,0.955483,0.762671,2025-03-28 13:33:15.155502,2025-03-28 13:44:18.855970,0 days 00:11:03.700468,NaN,gelu,...,0.001960,NaN,NaN,AdamW,NaN,Step,20.0,NaN,0.000006,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,187,0.837555,0.964517,0.961210,0.810274,2025-03-29 09:19:55.300083,2025-03-29 10:01:42.341384,0 days 00:41:47.041301,NaN,relu,...,0.000280,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000047,COMPLETE
188,188,0.837572,0.964392,0.961193,0.810252,2025-03-29 09:19:55.435043,2025-03-29 10:01:31.649970,0 days 00:41:36.214927,NaN,relu,...,0.000265,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000039,COMPLETE
190,190,0.837380,0.964095,0.961262,0.810013,2025-03-29 09:19:55.530341,2025-03-29 10:02:01.374317,0 days 00:42:05.843976,NaN,relu,...,0.000265,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000048,COMPLETE
193,193,0.834031,0.961476,0.958101,0.805453,2025-03-29 09:19:55.359330,2025-03-29 09:48:08.176928,0 days 00:28:12.817598,NaN,relu,...,0.000026,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000045,COMPLETE
194,194,0.833194,0.962838,0.959882,0.804383,2025-03-29 09:19:55.356912,2025-03-29 10:01:50.395733,0 days 00:41:55.038821,NaN,relu,...,0.000260,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000046,COMPLETE

In [9]:
tmp = df.loc[
    df[["values_0", "values_1", "values_2", "values_3"]]
    .max(axis=1)
    .sort_values(ascending=False)
    .index
]
tmp[tmp["params_gnn_layer"] == "MPNN"].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
86,86,0.843067,0.965665,0.963593,0.818104,2025-03-28 13:55:58.194732,2025-03-28 15:09:14.798339,0 days 01:13:16.603607,NaN,relu,...,0.000857,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000008,COMPLETE
135,135,0.848075,0.965184,0.962684,0.825404,2025-03-28 15:16:35.185749,2025-03-28 16:40:48.430475,0 days 01:24:13.244726,NaN,relu,...,0.000560,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000052,COMPLETE
134,134,0.842492,0.965147,0.963736,0.817650,2025-03-28 15:15:10.421216,2025-03-28 16:39:37.553967,0 days 01:24:27.132751,NaN,relu,...,0.001173,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000016,COMPLETE
159,159,0.833194,0.965065,0.962387,0.804124,2025-03-29 09:19:55.306034,2025-03-29 10:28:43.621563,0 days 01:08:48.315529,NaN,relu,...,0.000501,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000056,COMPLETE
88,88,0.835305,0.965003,0.962829,0.807081,2025-03-28 13:56:18.540502,2025-03-28 15:13:13.568095,0 days 01:16:55.027593,NaN,relu,...,0.000757,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000006,COMPLETE

In [10]:
tmp[tmp["params_gnn_layer"] == "GCN"].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
2,2,0.824401,0.957638,0.956261,0.792577,2025-03-28 13:33:15.072339,2025-03-28 13:51:40.566781,0 days 00:18:25.494442,NaN,relu,...,0.000528,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000003,COMPLETE
20,20,0.823040,0.956706,0.954420,0.790530,2025-03-28 13:34:50.496992,2025-03-28 13:49:10.864347,0 days 00:14:20.367355,NaN,gelu,...,0.000106,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.002370,COMPLETE
60,60,0.500000,0.955477,0.953860,0.000000,2025-03-28 13:49:36.287862,2025-03-28 13:54:28.630844,0 days 00:04:52.342982,NaN,relu,...,0.008874,0.805501,False,SGD,5.0,Plateau,NaN,0.000113,0.000075,COMPLETE
1,1,0.790140,0.955189,0.953871,0.739497,2025-03-28 13:33:15.048504,2025-03-28 13:51:42.311340,0 days 00:18:27.262836,37.0,relu,...,0.000055,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000012,COMPLETE
9,9,0.500000,0.954209,0.952076,0.000000,2025-03-28 13:33:17.946617,2025-03-28 13:35:36.585631,0 days 00:02:18.639014,NaN,gelu,...,0.000213,NaN,NaN,Adam,7.0,Plateau,NaN,0.003241,0.000110,COMPLETE

In [5]:
df.params_gnn_layer.value_counts()

params_gnn_layer
MPNN    38
GCN     34
Name: count, dtype: int64