In [1]:
# mypy: ignore-errors
# ruff: noqa
import gc
import math
import os
import sys
import warnings

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

warnings.simplefilter("ignore")
from sklearn.model_selection import KFold

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
# ruff: noqa
%load_ext autoreload
%autoreload 2
from drGAT import drGAT
from drGAT.load_data import load_data
from drGAT.sampler import NewSampler
from get_params import get_params
from metrics import compute_metrics_stats

In [3]:
name = "nci"

In [4]:
(
    res,
    pos_num,
    null_mask,
    drug_sim,
    cell_sim,
    gene_sim,
    A_cg,
    A_dg,
    _,
    _,
    _,
) = load_data(name)
res = res.T
cell_sum = np.sum(res, axis=1)
drug_sum = np.sum(res, axis=0)

target_dim = [
    0,  # Cell
    # 1  # Drug
]

load nci
unique drugs: 177
unique genes: 251
DTI unique genes:  251
Top 90% variable genes:  2383
Total:  2582
Final gene exp shape: (60, 2582)
Final drug Act shape: (1005, 60)

100%|██████████| 25/25 [00:03<00:00,  6.42it/s]

Done!

In [5]:
def drGAT_new(
    res_mat,
    null_mask,
    target_dim,
    target_index,
    S_d,
    S_c,
    S_g,
    A_cg,
    A_dg,
    PATH,
    params,
    device,
    seed,
):
    sampler = NewSampler(
        res_mat,
        null_mask,
        target_dim,
        target_index,
        S_d,
        S_c,
        S_g,
        A_cg,
        A_dg,
        PATH,
        seed,
    )

    (_, _, _, best_val_labels, best_val_prob, best_metrics, _, _, _) = drGAT.train(
        sampler, params=params, device=device, verbose=False
    )

    return best_val_labels, best_val_prob

In [6]:
method = "Transformer"
PATH = f"../{name}_data/"
params = {
    "dropout1": 0.45000000000000007,
    "dropout2": 0.35,
    "hidden1": 614,
    "hidden2": 133,
    "hidden3": 70,
    "heads": 2,
    "activation": "gelu",
    "optimizer": "Adam",
    "lr": 1.8989543676298613e-05,
    "weight_decay": 1.0800574802927777e-06,
    "scheduler": "Cosine",
    "T_max": 22,
}

params.update(
    {
        "n_drug": drug_sim.shape[0],
        "n_cell": cell_sim.shape[0],
        "n_gene": gene_sim.shape[0],
        "epochs": 1,
        "gnn_layer": method,
    }
)

In [7]:
n_kfold = 1
true_datas = pd.DataFrame()
predict_datas = pd.DataFrame()
for dim in target_dim:
    for seed, target_index in tqdm(enumerate(np.arange(res.shape[dim]))):
        if dim:
            if drug_sum[target_index] < 10:
                continue
        else:
            if cell_sum[target_index] < 10:
                continue

        for fold in range(n_kfold):
            true_data, predict_data = drGAT_new(
                res_mat=res,
                null_mask=null_mask.T.values,
                target_dim=dim,
                target_index=target_index,
                S_d=drug_sim,
                S_c=cell_sim,
                S_g=gene_sim,
                A_cg=A_cg,
                A_dg=A_dg,
                PATH=PATH,
                params=params,
                device=device,
                seed=seed,
            )

            for i in true_datas.index:
                if len(true_datas.iloc[i].dropna()) != len(
                    predict_datas.iloc[i].dropna()
                ):

                    print(i)

            true_datas = pd.concat(
                [true_datas, pd.DataFrame(true_data).T], ignore_index=True
            )
            predict_datas = pd.concat(
                [predict_datas, pd.DataFrame(predict_data).T], ignore_index=True
            )

0it [00:00, ?it/s]

Using device: cuda

1it [00:05,  5.09s/it]

Best model found at epoch 1
Using device: cuda

2it [00:08,  4.19s/it]

Best model found at epoch 1
Using device: cuda

3it [00:12,  3.93s/it]

Best model found at epoch 1
Using device: cuda

4it [00:15,  3.63s/it]

Best model found at epoch 1
Using device: cuda

5it [00:18,  3.51s/it]

Best model found at epoch 1
Using device: cuda

6it [00:22,  3.46s/it]

Best model found at epoch 1
Using device: cuda

7it [00:25,  3.39s/it]

Best model found at epoch 1
Using device: cuda

8it [00:28,  3.30s/it]

Best model found at epoch 1
Using device: cuda

9it [00:31,  3.29s/it]

Best model found at epoch 1
Using device: cuda

10it [00:35,  3.32s/it]

Best model found at epoch 1
Using device: cuda

11it [00:38,  3.30s/it]

Best model found at epoch 1
Using device: cuda

12it [00:41,  3.30s/it]

Best model found at epoch 1
Using device: cuda

13it [00:44,  3.29s/it]

Best model found at epoch 1
Using device: cuda

14it [00:48,  3.26s/it]

Best model found at epoch 1
Using device: cuda

15it [00:51,  3.29s/it]

Best model found at epoch 1
Using device: cuda

16it [00:55,  3.44s/it]

Best model found at epoch 1
Using device: cuda

17it [00:58,  3.36s/it]

Best model found at epoch 1
Using device: cuda

18it [01:01,  3.36s/it]

Best model found at epoch 1
Using device: cuda

19it [01:05,  3.34s/it]

Best model found at epoch 1
Using device: cuda

20it [01:08,  3.33s/it]

Best model found at epoch 1
Using device: cuda

21it [01:11,  3.34s/it]

Best model found at epoch 1
Using device: cuda

22it [01:14,  3.28s/it]

Best model found at epoch 1
Using device: cuda

23it [01:18,  3.35s/it]

Best model found at epoch 1
Using device: cuda

24it [01:21,  3.41s/it]

Best model found at epoch 1
Using device: cuda

25it [01:25,  3.44s/it]

Best model found at epoch 1
Using device: cuda

26it [01:28,  3.28s/it]

Best model found at epoch 1
Using device: cuda

27it [01:31,  3.36s/it]

Best model found at epoch 1
Using device: cuda

28it [01:35,  3.30s/it]

Best model found at epoch 1
Using device: cuda

29it [01:38,  3.38s/it]

Best model found at epoch 1
Using device: cuda

30it [01:41,  3.36s/it]

Best model found at epoch 1
Using device: cuda

31it [01:45,  3.35s/it]

Best model found at epoch 1
Using device: cuda

32it [01:48,  3.32s/it]

Best model found at epoch 1
Using device: cuda

33it [01:51,  3.30s/it]

Best model found at epoch 1
Using device: cuda

34it [01:55,  3.31s/it]

Best model found at epoch 1
Using device: cuda

35it [01:58,  3.31s/it]

Best model found at epoch 1
Using device: cuda

36it [02:01,  3.32s/it]

Best model found at epoch 1
Using device: cuda

37it [02:04,  3.28s/it]

Best model found at epoch 1
Using device: cuda

38it [02:08,  3.25s/it]

Best model found at epoch 1
Using device: cuda

39it [02:11,  3.30s/it]

Best model found at epoch 1
Using device: cuda

40it [02:14,  3.29s/it]

Best model found at epoch 1
Using device: cuda

41it [02:18,  3.29s/it]

Best model found at epoch 1
Using device: cuda

42it [02:21,  3.35s/it]

Best model found at epoch 1
Using device: cuda

43it [02:24,  3.34s/it]

Best model found at epoch 1
Using device: cuda

44it [02:28,  3.36s/it]

Best model found at epoch 1
Using device: cuda

45it [02:31,  3.35s/it]

Best model found at epoch 1
Using device: cuda

46it [02:34,  3.32s/it]

Best model found at epoch 1
Using device: cuda

47it [02:38,  3.34s/it]

Best model found at epoch 1
Using device: cuda

48it [02:41,  3.37s/it]

Best model found at epoch 1
Using device: cuda

49it [02:44,  3.33s/it]

Best model found at epoch 1
Using device: cuda

50it [02:48,  3.33s/it]

Best model found at epoch 1
Using device: cuda

51it [02:51,  3.37s/it]

Best model found at epoch 1
Using device: cuda

52it [02:55,  3.52s/it]

Best model found at epoch 1
Using device: cuda

53it [02:58,  3.45s/it]

Best model found at epoch 1
Using device: cuda

54it [03:02,  3.50s/it]

Best model found at epoch 1
Using device: cuda

55it [03:06,  3.53s/it]

Best model found at epoch 1
Using device: cuda

56it [03:09,  3.45s/it]

Best model found at epoch 1
Using device: cuda

57it [03:12,  3.40s/it]

Best model found at epoch 1
Using device: cuda

58it [03:16,  3.43s/it]

Best model found at epoch 1
Using device: cuda

59it [03:19,  3.37s/it]

Best model found at epoch 1
Using device: cuda

60it [03:23,  3.38s/it]

Best model found at epoch 1

In [8]:
# true_datas.to_csv(f"new_true_cell_{method}_{name}.csv")
# predict_datas.to_csv(f"new_pred_cell_{method}_{name}.csv")

In [9]:
for i in true_datas.index:
    if len(true_datas.iloc[i].dropna()) != len(predict_datas.iloc[i].dropna()):
        print(i)

In [2]:
from sklearn.metrics import (accuracy_score, average_precision_score,
                             balanced_accuracy_score, brier_score_loss,
                             cohen_kappa_score, f1_score, fbeta_score,
                             log_loss, matthews_corrcoef, precision_score,
                             recall_score, roc_auc_score)

In [7]:
pd.read_csv("true.csv", index_col=0)

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,1,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,1

In [6]:
pd.read_csv("predict.csv", index_col=0)

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,0.511648,0.513699,0.515666,0.510779,0.509528,0.513440,0.514309,0.513470,0.512479,0.505680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.544317,0.526723,0.543802,0.538528,0.540408,0.535675,0.521471,0.534704,0.534066,0.564699,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.406567,0.406803,0.412412,0.402568,0.399753,0.408749,0.406332,0.404743,0.402686,0.392220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.502762,0.483847,0.491273,0.505699,0.525262,0.494320,0.481926,0.487437,0.496101,0.563798,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.544347,0.542379,0.544922,0.546526,0.552721,0.543106,0.541894,0.547131,0.545134,0.547978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.509879,0.494683,0.503544,0.507457,0.517769,0.505619,0.491662,0.498580,0.506248,0.536222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.468031,0.470296,0.472486,0.470128,0.466359,0.469003,0.480951,0.476047,0.475331,0.453262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.602529,0.603873,0.600130,0.604341,0.604983,0.600364,0.605916,0.605216,0.603815,0.610163,...,0.475438,0.477021,0.477569,0.477143,0.477493,0.477661,NaN,NaN,NaN,NaN
8,0.514172,0.497095,0.508529,0.521425,0.509963,0.499345,0.501487,0.534187,0.528366,0.506168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.546345,0.539741,0.534704,0.535007,0.539377,0.539529,0.536890,0.540439,0.545377,0.536920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.478042,0.477311,0.486675,0.471664,0.481241,0.475894,0.478483,0.484578,0.483831,0.473551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.558628,0.552147,0.556249,0.556309,0.555224,0.555556,0.549610,0.557815,0.558146,0.558056,...,0.488405,0.487917,0.488764,0.487734,0.488634,0.487910,0.487955,0.488230,0.488489,0.488215
12,0.472410,0.485249,0.476686,0.475834,0.470873,0.479290,0.489389,0.477478,0.455108,0.484837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.488619,0.485981,0.488581,0.487109,0.489092,0.486652,0.485767,0.484982,0.488047,0.492097,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0.354433,0.360039,0.354545,0.355216,0.352870,0.354768,0.359701,0.358353,0.354880,0.351756,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.605099,0.588061,0.600950,0.602295,0.612483,0.602588,0.587056,0.592549,0.600188,0.620679,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0.502239,0.482719,0.488672,0.512677,0.487902,0.500727,0.557785,0.483313,0.508056,0.463323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,0.355663,0.352648,0.362743,0.349089,0.348867,0.360039,0.353763,0.355216,0.357119,0.333612,...,0.452596,0.457440,0.461441,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0.510809,0.505344,0.508392,0.509414,0.512319,0.508102,0.503422,0.506820,0.508407,0.516489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0.560223,0.546375,0.552841,0.559832,0.567817,0.555104,0.547978,0.588594,0.575707,0.550668,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0.455229,0.457864,0.457652,0.456289,0.457349,0.457440,0.457258,0.454533,0.455289,0.456501,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.468456,0.473140,0.467757,0.469931,0.473018,0.468061,0.466906,0.470113,0.469794,0.487628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.512319,0.521273,0.517845,0.510664,0.503553,0.517693,0.519369,0.518836,0.511152,0.487757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.486537,0.498941,0.494499,0.489267,0.499716,0.492428,0.495381,0.493676,0.491075,0.489946,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0.614857,0.603757,0.607372,0.614741,0.621081,0.611092,0.599661,0.602062,0.611440,0.633183,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0.553596,0.548613,0.560102,0.550638,0.540803,0.543045,0.563678,0.553113,0.553596,0.552479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0.517937,0.519080,0.518287,0.516336,0.517937,0.515452,0.515163,0.513150,0.519080,0.516352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0.702530,0.693992,0.699460,0.705785,0.697094,0.701713,0.703448,0.700485,0.703040,0.697815,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.534126,0.534278,0.538467,0.532243,0.531969,0.537223,0.533276,0.530981,0.532273,0.523451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.472273,0.476580,0.478788,0.475803,0.465722,0.468821,0.491814,0.483786,0.472151,0.472455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0.367611,0.367838,0.370339,0.373190,0.371593,0.370909,0.365004,0.365457,0.371365,0.373190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.581541,0.555978,0.572245,0.581719,0.600071,0.574275,0.551393,0.576423,0.638159,0.615088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,0.363873,0.371935,0.369543,0.364551,0.373076,0.367497,0.367951,0.366136,0.370339,0.361728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0.429370,0.437343,0.425546,0.439206,0.439146,0.432723,0.450057,0.445047,0.442576,0.429729,...,0.482856,0.483923,0.488726,0.485523,0.488032,0.492905,0.488848,0.488139,0.484487,NaN
34,0.564399,0.562957,0.561125,0.564399,0.566018,0.560433,0.562777,0.563618,0.566258,0.566018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0.696681,0.703855,0.714329,0.706494,0.707304,0.737725,0.717210,0.713332,0.710226,0.712332,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,0.480616,0.480463,0.480250,0.479763,0.479854,0.480875,0.480555,0.480844,0.479123,0.479351,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0.543833,0.547494,0.550003,0.543923,0.551483,0.547918,0.540045,0.546224,0.537497,0.533397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,0.551966,0.533549,0.541894,0.556550,0.556369,0.542257,0.544226,0.544226,0.575648,0.525338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,0.424531,0.430626,0.420243,0.433981,0.436562,0.432063,0.427875,0.405508,0.434581,0.445831,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.526054,0.499935,0.507919,0.524745,0.541712,0.512990,0.498668,0.510893,0.582610,0.566438,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,0.609757,0.598664,0.603932,0.610047,0.618262,0.605216,0.597490,0.601828,0.607081,0.632843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0.517723,0.520359,0.520344,0.515414,0.514751,0.515216,0.519978,0.515833,0.514050,0.516397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,0.567997,0.557364,0.558116,0.569494,0.572842,0.559501,0.557123,0.561275,0.565539,0.590189,...,0.399109,0.380932,0.403919,0.414840,0.389140,0.383526,0.394901,0.389314,0.386474,0.382891
44,0.670392,0.662797,0.675337,0.662360,0.662797,0.669961,0.651355,0.654784,0.665302,0.662141,...,0.573499,0.562898,0.576244,0.578984,0.578984,0.580174,0.579341,0.579460,NaN,NaN
45,0.357119,0.348645,0.349422,0.354992,0.351200,0.341912,0.345768,0.369543,0.347094,0.351422,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,0.678966,0.671363,0.668014,0.669529,0.696475,0.651355,0.653901,0.665193,0.671471,0.675444,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0.506355,0.481393,0.500750,0.500794,0.500877,0.502882,0.481439,0.492104,0.502934,0.497734,...,0.379148,0.381680,0.383930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,0.358016,0.335242,0.319121,0.327346,0.357680,0.286868,0.338296,0.305801,0.384797,0.312370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,0.591015,0.580590,0.586582,0.587056,0.591310,0.581957,0.580174,0.585812,0.585812,0.610686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,0.507770,0.504509,0.512761,0.510237,0.509139,0.522979,0.518348,0.503534,0.512624,0.512449,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,0.433921,0.442215,0.434101,0.435061,0.426680,0.436982,0.444655,0.442486,0.439086,0.416381,...,0.429848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,0.343562,0.354657,0.350866,0.346431,0.337859,0.353094,0.357231,0.350199,0.352202,0.314787,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,0.488291,0.486675,0.481195,0.489839,0.492646,0.481058,0.488207,0.489976,0.488306,0.508041,...,0.436142,0.434281,0.429370,0.439838,0.439838,0.440770,0.441282,0.440770,0.439146,NaN
54,0.412234,0.424889,0.417984,0.405861,0.413004,0.424531,0.419410,0.416263,0.394201,0.400632,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,0.529431,0.528701,0.525141,0.535190,0.530389,0.528838,0.536313,0.538589,0.533489,0.534096,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,0.496975,0.491029,0.495281,0.493595,0.495152,0.493336,0.489786,0.492165,0.492798,0.502792,...,0.430626,0.431524,0.430447,0.430327,0.429848,0.430207,0.430447,0.430447,NaN,NaN
57,0.487681,0.488459,0.486812,0.466420,0.480174,0.487254,0.490510,0.488230,0.486309,0.490533,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,0.505645,0.490114,0.499497,0.502851,0.512548,0.501281,0.484350,0.491784,0.505253,0.523892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,0.457106,0.453746,0.456894,0.459531,0.463141,0.461684,0.459228,0.457440,0.459167,0.458773,...,0.451538,0.454926,0.450148,0.451327,0.452687,0.453201,0.450843,0.451931,0.452778,0.453685

In [11]:
res = pd.DataFrame()
for i in true_datas.index:
    # データ前処理
    true_labels = true_datas.loc[i].dropna()
    pred_values = predict_datas.loc[i].dropna()
    pred_labels = np.round(pred_values).astype(int)

    # メトリクス計算
    metrics = {
        "ACC": accuracy_score(true_labels, pred_labels),
        "Precision": precision_score(true_labels, pred_labels, zero_division=0),
        "Recall": recall_score(true_labels, pred_labels, zero_division=0),
        "F1": f1_score(true_labels, pred_labels, zero_division=0),
        "AUROC": roc_auc_score(true_labels, pred_values),
        "AUPR": average_precision_score(true_labels, pred_values),
        "MCC": matthews_corrcoef(true_labels, pred_labels),
        "Specificity": recall_score(
            true_labels, pred_labels, pos_label=0, zero_division=0
        ),
        "Balanced_ACC": balanced_accuracy_score(true_labels, pred_labels),
        "LogLoss": log_loss(true_labels, pred_values),
        "Brier": brier_score_loss(true_labels, pred_values),
    }
    res = pd.concat([res, pd.DataFrame([metrics])], ignore_index=True)

In [15]:
for i in true_datas.index:
    print(len(true_datas.iloc[i].dropna()))
    print(len(predict_datas.iloc[i].dropna()))

912
912
975
975
906
906
984
984
646
646
971
971
965
965
997
997
766
766
344
344
478
478
1001
1001
690
690
988
988
904
904
951
951
824
824
994
994
864
864
868
868
969
969
988
988
977
977
816
816
976
976
516
516
932
932
164
164
981
981
504
504
710
710
890
890
482
482
1000
1000
984
984
636
636
442
442
408
408
720
720
712
712
888
888
985
985
750
750
1001
1001
999
999
594
594
446
446
994
994
778
778
972
972
560
560
992
992
938
938
1000
1000
902
902
656
656
999
999
504
504
991
991
1001
1001

,ACC,Precision,Recall,F1,AUROC,AUPR,MCC,Specificity,Balanced_ACC,LogLoss,Brier
0,0.502193,1.000000,0.004386,0.008734,0.623310,0.611025,0.046881,1.000000,0.502193,0.775197,0.287570
1,0.381538,0.083333,0.001686,0.003306,0.522273,0.584829,-0.120026,0.971204,0.486445,0.717344,0.262073
2,0.500000,0.000000,0.000000,0.000000,0.501796,0.518156,0.000000,1.000000,0.500000,0.736651,0.270672
3,0.540650,0.540650,1.000000,0.701847,0.475558,0.549234,0.000000,0.000000,0.500000,1.017193,0.356954
4,0.500000,0.500000,0.984520,0.663191,0.437688,0.472319,0.000000,0.015480,0.500000,0.699084,0.252945
5,0.416066,0.000000,0.000000,0.000000,0.413423,0.532852,0.000000,1.000000,0.500000,0.914562,0.348406
6,0.359585,0.000000,0.000000,0.000000,0.502740,0.655153,0.000000,1.000000,0.500000,0.952668,0.367215
7,0.498495,0.000000,0.000000,0.000000,0.557090,0.515479,-0.031718,0.997992,0.498996,0.762394,0.282279
8,0.498695,0.454545,0.013055,0.025381,0.579317,0.579480,-0.010973,0.984334,0.498695,0.711133,0.258721
9,0.566860,0.701754,0.232558,0.349345,0.644504,0.641212,0.179825,0.901163,0.566860,0.678837,0.242710
10,0.500000,0.000000,0.000000,0.000000,0.636220,0.626852,0.000000,1.000000,0.500000,0.783885,0.291327
11,0.654346,0.654000,1.000000,0.790810,0.543062,0.691235,0.043413,0.002882,0.501441,0.650710,0.228606
12,0.495652,0.285714,0.005797,0.011364,0.535803,0.511592,-0.043387,0.985507,0.495652,0.732553,0.268953
13,0.648785,0.648785,1.000000,0.786986,0.504784,0.673256,0.000000,0.000000,0.500000,0.647264,0.227608
14,0.504425,0.514286,0.159292,0.243243,0.461506,0.497791,0.012231,0.849558,0.504425,0.697993,0.252423
15,0.619348,0.619914,0.988055,0.761842,0.410971,0.540882,0.056712,0.027397,0.507726,0.680493,0.243667
16,0.500000,0.500000,1.000000,0.666667,0.472750,0.500193,0.000000,0.000000,0.500000,0.856621,0.319247
17,0.460765,0.300000,0.011364,0.021898,0.419239,0.479261,-0.066386,0.969957,0.490660,0.784412,0.292910
18,0.500000,0.000000,0.000000,0.000000,0.518331,0.530915,0.000000,1.000000,0.500000,0.749051,0.276403
19,0.455069,0.314286,0.076037,0.122449,0.450357,0.451446,-0.137787,0.834101,0.455069,0.700550,0.253688
20,0.485036,0.000000,0.000000,0.000000,0.426052,0.473783,0.000000,1.000000,0.500000,0.746991,0.275749
21,0.287449,0.000000,0.000000,0.000000,0.461053,0.715654,0.000000,1.000000,0.500000,1.085725,0.423703
22,0.501535,0.505447,0.933602,0.655830,0.512010,0.549088,-0.025671,0.054167,0.493884,0.703485,0.255106
23,0.463235,0.478814,0.830882,0.607527,0.387657,0.415053,-0.108491,0.095588,0.463235,0.700492,0.253663
24,0.267418,0.000000,0.000000,0.000000,0.516470,0.757193,0.000000,1.000000,0.500000,0.966357,0.377126
25,0.519380,0.510000,0.988372,0.672823,0.434176,0.436998,0.111803,0.050388,0.519380,0.705072,0.255853
26,0.496781,0.285714,0.004292,0.008457,0.511807,0.520357,-0.037282,0.989270,0.496781,0.740682,0.272436
27,0.512195,0.533333,0.195122,0.285714,0.486169,0.541746,0.031544,0.829268,0.512195,0.698842,0.252783
28,0.423038,0.846154,0.106452,0.189112,0.620262,0.741076,0.130507,0.966759,0.536605,0.734832,0.270513
29,0.500000,0.500000,1.000000,0.666667,0.687390,0.671347,0.000000,0.000000,0.500000,0.710798,0.258746
30,0.488732,0.482759,0.315493,0.381601,0.479441,0.488352,-0.024023,0.661972,0.488732,0.699708,0.253240
31,0.502247,0.501126,1.000000,0.667667,0.552774,0.565471,0.047458,0.004494,0.502247,0.747340,0.275498
32,0.502075,0.501040,1.000000,0.667590,0.525929,0.502227,0.045596,0.004149,0.502075,0.707784,0.256927
33,0.388000,1.000000,0.001631,0.003257,0.550189,0.682055,0.025139,1.000000,0.500816,0.776474,0.290476
34,0.585366,0.585366,1.000000,0.738462,0.495200,0.602553,0.000000,0.000000,0.500000,0.687273,0.246753
35,0.500000,0.500000,0.025157,0.047904,0.557167,0.554710,0.000000,0.974843,0.500000,0.716313,0.261223
36,0.500000,0.500000,1.000000,0.666667,0.456921,0.494225,0.000000,0.000000,0.500000,0.900475,0.334308
37,0.492647,0.000000,0.000000,0.000000,0.431337,0.436719,-0.086066,0.985294,0.492647,0.713526,0.260026
38,0.466667,0.481595,0.872222,0.620553,0.524128,0.543874,-0.113981,0.061111,0.466667,0.704393,0.255373
39,0.500000,0.000000,0.000000,0.000000,0.520231,0.521932,0.000000,1.000000,0.500000,0.862686,0.321579
40,0.498874,0.000000,0.000000,0.000000,0.432600,0.459996,-0.033577,0.997748,0.498874,0.771902,0.286222
41,0.398985,0.000000,0.000000,0.000000,0.502689,0.589794,0.000000,1.000000,0.500000,0.899817,0.343770
42,0.505333,0.611111,0.029333,0.055980,0.521675,0.516373,0.034847,0.981333,0.505333,0.701265,0.253981
43,0.416583,0.666667,0.006826,0.013514,0.467213,0.581615,0.012807,0.995181,0.501003,0.863967,0.328016
44,0.582583,0.615116,0.860163,0.717288,0.492179,0.619163,-0.002553,0.138021,0.499092,0.680725,0.243828
45,0.493266,0.333333,0.013468,0.025890,0.523042,0.525238,-0.047864,0.973064,0.493266,0.782628,0.290772
46,0.491031,0.375000,0.026906,0.050209,0.476271,0.477736,-0.048224,0.955157,0.491031,0.706109,0.256383
47,0.457746,0.000000,0.000000,0.000000,0.428533,0.499580,0.000000,1.000000,0.500000,1.196335,0.423246
48,0.505141,0.502646,0.976864,0.663755,0.529943,0.543970,0.031016,0.033419,0.505141,0.730204,0.267658
49,0.504115,1.000000,0.008230,0.016327,0.470963,0.495134,0.064282,1.000000,0.504115,0.757608,0.279893
50,0.516071,0.604651,0.092857,0.160991,0.620548,0.615797,0.060362,0.939286,0.516071,0.692685,0.249516
51,0.673387,0.674490,0.992492,0.803159,0.531918,0.701639,0.060004,0.021472,0.506982,0.633614,0.220736
52,0.397655,0.833333,0.242511,0.375691,0.547067,0.797160,0.104335,0.856540,0.549525,0.712899,0.259839
53,0.497000,0.000000,0.000000,0.000000,0.459599,0.497565,0.000000,1.000000,0.500000,0.762788,0.282375
54,0.471175,0.480882,0.725055,0.578249,0.439831,0.458008,-0.066918,0.217295,0.471175,0.699898,0.253345
55,0.500000,0.000000,0.000000,0.000000,0.512906,0.507499,0.000000,1.000000,0.500000,0.711849,0.259122
56,0.474474,0.000000,0.000000,0.000000,0.486452,0.551121,0.000000,1.000000,0.500000,0.742708,0.273614
57,0.472222,0.354167,0.067460,0.113333,0.489386,0.484811,-0.094629,0.876984,0.472222,0.701068,0.253933
58,0.627649,0.627907,0.998392,0.770950,0.507100,0.663698,0.011874,0.002710,0.500551,0.690367,0.246361
59,0.562438,0.559305,0.987365,0.714099,0.474436,0.542289,0.076841,0.035794,0.511579,0.689020,0.247926