In [1]:
import pandas as pd
import optuna

/tmp/ipykernel_2113061/806890219.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
task = 'cell'
method = 'GATv2'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 10:03:27,656] Using an existing study with name 'GATv2' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,state
0,0,None,None,None,None,2025-04-08 22:01:07.402318,2025-04-08 22:01:07.445030,0 days 00:00:00.042712,FAIL
1,1,None,None,None,None,2025-04-08 22:02:47.362478,2025-04-08 22:02:47.416524,0 days 00:00:00.054046,FAIL
2,2,None,None,None,None,2025-04-08 22:10:29.616051,2025-04-08 22:10:29.657217,0 days 00:00:00.041166,FAIL

In [3]:
method = 'GAT'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 10:03:27,777] Using an existing study with name 'GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 21:56:25.428841,2025-04-08 21:56:25.473115,0 days 00:00:00.044274,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
1,1,None,None,None,None,2025-04-08 22:03:58.979977,2025-04-08 22:03:59.020795,0 days 00:00:00.040818,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
2,2,None,None,None,None,2025-04-08 22:13:47.952523,2025-04-08 22:13:48.015760,0 days 00:00:00.063237,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
3,3,None,None,None,None,2025-04-08 23:02:06.233390,2025-04-08 23:02:08.959141,0 days 00:00:02.725751,NaN,gelu,...,7.0,861.0,406.0,71.0,0.001921,AdamW,None,0.000009,0.0,PRUNED
4,4,None,None,None,None,2025-04-08 23:02:08.984284,2025-04-08 23:02:10.734009,0 days 00:00:01.749725,23.0,relu,...,5.0,562.0,492.0,205.0,0.000011,AdamW,Cosine,0.001601,0.0,PRUNED
5,5,None,None,None,None,2025-04-08 23:02:10.758875,2025-04-08 23:02:13.316107,0 days 00:00:02.557232,NaN,gelu,...,2.0,522.0,326.0,145.0,0.000022,Adam,None,0.000008,0.0,PRUNED
6,6,None,None,None,None,2025-04-08 23:02:13.341292,2025-04-08 23:02:15.464288,0 days 00:00:02.122996,50.0,relu,...,3.0,334.0,265.0,67.0,0.000146,Adam,Cosine,0.000226,0.0,PRUNED
7,7,None,None,None,None,2025-04-08 23:02:15.489454,2025-04-08 23:02:17.635819,0 days 00:00:02.146365,NaN,relu,...,2.0,906.0,437.0,142.0,0.003933,Adam,None,0.009341,0.0,PRUNED
8,8,None,None,None,None,2025-04-08 23:02:17.661505,2025-04-08 23:02:19.395671,0 days 00:00:01.734166,NaN,relu,...,6.0,834.0,415.0,135.0,0.000165,Adam,None,0.000002,0.0,PRUNED
9,9,None,None,None,None,2025-04-08 23:02:19.419411,2025-04-09 00:52:00.036599,0 days 01:49:40.617188,NaN,gelu,...,4.0,734.0,147.0,118.0,0.000292,AdamW,None,0.000006,0.0,FAIL

In [4]:
method = 'Transformer'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 10:03:27,869] Using an existing study with name 'Transformer' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 21:58:18.464278,2025-04-08 21:58:18.525169,0 days 00:00:00.060891,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
1,1,None,None,None,None,2025-04-08 22:15:27.526256,2025-04-08 22:15:30.879849,0 days 00:00:03.353593,NaN,relu,...,8.0,816.0,413.0,138.0,0.000135,AdamW,None,0.000139,0.0,PRUNED
2,2,None,None,None,None,2025-04-08 22:15:30.918661,2025-04-08 22:15:32.571504,0 days 00:00:01.652843,NaN,relu,...,5.0,984.0,253.0,58.0,0.000014,AdamW,None,0.000007,0.0,PRUNED
3,3,None,None,None,None,2025-04-08 22:15:32.612025,2025-04-08 22:15:34.487521,0 days 00:00:01.875496,20.0,gelu,...,8.0,701.0,511.0,144.0,0.000052,Adam,Cosine,0.000123,0.0,PRUNED
4,4,None,None,None,None,2025-04-08 22:15:34.524600,2025-04-08 22:15:36.551307,0 days 00:00:02.026707,NaN,gelu,...,3.0,409.0,349.0,131.0,0.000065,AdamW,None,0.006558,0.0,PRUNED
5,5,None,None,None,None,2025-04-08 22:15:36.588471,2025-04-08 22:15:38.320258,0 days 00:00:01.731787,NaN,relu,...,4.0,575.0,263.0,100.0,0.000995,AdamW,None,0.000324,0.0,PRUNED
6,6,None,None,None,None,2025-04-08 22:15:38.359344,2025-04-08 22:15:40.490132,0 days 00:00:02.130788,48.0,gelu,...,4.0,840.0,479.0,180.0,0.002270,AdamW,Cosine,0.000142,0.0,PRUNED
7,7,None,None,None,None,2025-04-08 22:15:40.526196,2025-04-08 22:15:42.362236,0 days 00:00:01.836040,23.0,gelu,...,4.0,608.0,203.0,50.0,0.000023,Adam,Cosine,0.000218,0.0,PRUNED
8,8,None,None,None,None,2025-04-08 22:15:42.398379,2025-04-08 22:15:44.498393,0 days 00:00:02.100014,39.0,gelu,...,6.0,969.0,281.0,180.0,0.001078,AdamW,Cosine,0.000018,0.0,PRUNED
9,9,None,None,None,None,2025-04-08 22:15:44.538817,2025-04-08 22:15:46.498083,0 days 00:00:01.959266,41.0,relu,...,8.0,261.0,198.0,46.0,0.000056,Adam,Cosine,0.000254,0.0,PRUNED
10,10,None,None,None,None,2025-04-08 22:15:46.537441,2025-04-08 22:15:48.414054,0 days 00:00:01.876613,30.0,gelu,...,7.0,909.0,386.0,256.0,0.000884,AdamW,Cosine,0.000187,0.0,PRUNED
11,11,None,None,None,None,2025-04-08 22:15:48.459819,2025-04-08 22:15:50.891163,0 days 00:00:02.431344,NaN,gelu,...,7.0,464.0,191.0,155.0,0.001041,AdamW,None,0.001058,0.0,PRUNED
12,12,None,None,None,None,2025-04-08 22:15:50.934846,2025-04-08 22:15:52.633267,0 days 00:00:01.698421,NaN,relu,...,8.0,355.0,320.0,64.0,0.000102,AdamW,None,0.000002,0.0,PRUNED
13,13,None,None,None,None,2025-04-08 22:15:52.667951,2025-04-08 22:15:55.155994,0 days 00:00:02.488043,NaN,relu,...,6.0,380.0,100.0,98.0,0.000221,AdamW,None,0.000024,0.0,PRUNED
14,14,None,None,None,None,2025-04-08 22:15:55.191608,2025-04-08 22:15:56.957097,0 days 00:00:01.765489,NaN,relu,...,3.0,611.0,236.0,154.0,0.000092,Adam,None,0.000486,0.0,PRUNED
15,15,None,None,None,None,2025-04-08 22:15:56.993067,2025-04-08 22:15:58.820969,0 days 00:00:01.827902,24.0,relu,...,5.0,282.0,169.0,153.0,0.000084,Adam,Cosine,0.000003,0.0,PRUNED
16,16,None,None,None,None,2025-04-08 22:15:58.855523,2025-04-08 22:16:00.825534,0 days 00:00:01.970011,NaN,relu,...,7.0,962.0,287.0,185.0,0.002108,AdamW,None,0.001360,0.0,PRUNED
17,17,None,None,None,None,2025-04-08 22:16:00.861494,2025-04-08 22:16:02.761480,0 days 00:00:01.899986,NaN,relu,...,3.0,629.0,293.0,44.0,0.000856,Adam,None,0.002443,0.0,PRUNED
18,18,None,None,None,None,2025-04-08 22:16:02.796886,2025-04-08 22:16:04.487348,0 days 00:00:01.690462,46.0,gelu,...,6.0,479.0,164.0,47.0,0.001395,AdamW,Cosine,0.000070,0.0,PRUNED
19,19,None,None,None,None,2025-04-08 22:16:04.521785,2025-04-08 22:16:06.692280,0 days 00:00:02.170495,NaN,gelu,...,8.0,856.0,411.0,118.0,0.000392,AdamW,None,0.000310,0.0,PRUNED
20,20,None,None,None,None,2025-04-08 22:16:06.728248,2025-04-08 22:16:08.863684,0 days 00:00:02.135436,30.0,relu,...,5.0,970.0,216.0,170.0,0.000269,AdamW,Cosine,0.000076,0.0,PRUNED
21,21,None,None,None,None,2025-04-08 22:16:08.897160,2025-04-08 22:16:10.503850,0 days 00:00:01.606690,NaN,relu,...,5.0,665.0,187.0,181.0,0.000247,Adam,None,0.000277,0.0,PRUNED
22,22,None,None,None,None,2025-04-08 22:16:10.537924,2025-04-08 22:16:12.452885,0 days 00:00:01.914961,49.0,relu,...,3.0,678.0,351.0,50.0,0.000022,AdamW,Cosine,0.000374,0.0,PRUNED
23,23,None,None,None,None,2025-04-08 22:16:12.488230,2025-04-08 22:16:14.369242,0 days 00:00:01.881012,NaN,relu,...,2.0,845.0,499.0,182.0,0.000036,Adam,None,0.000019,0.0,PRUNED
24,24,None,None,None,None,2025-04-08 22:16:14.403627,2025-04-08 22:16:16.320656,0 days 00:00:01.917029,22.0,relu,...,3.0,264.0,110.0,96.0,0.000930,Adam,Cosine,0.000417,0.0,PRUNED
25,25,None,None,None,None,2025-04-08 22:16:16.355809,2025-04-08 22:16:18.274282,0 days 00:00:01.918473,40.0,gelu,...,5.0,992.0,391.0,127.0,0.000582,AdamW,Cosine,0.000526,0.0,PRUNED
26,26,None,None,None,None,2025-04-08 22:16:18.308778,2025-04-08 22:16:20.500695,0 days 00:00:02.191917,23.0,gelu,...,6.0,724.0,289.0,225.0,0.003339,AdamW,Cosine,0.003899,0.0,PRUNED
27,27,None,None,None,None,2025-04-08 22:16:20.534895,2025-04-08 22:16:22.459815,0 days 00:00:01.924920,NaN,relu,...,8.0,436.0,257.0,197.0,0.000360,Adam,None,0.000077,0.0,PRUNED
28,28,None,None,None,None,2025-04-08 22:16:22.497242,2025-04-08 22:16:24.580032,0 days 00:00:02.082790,NaN,relu,...,2.0,707.0,269.0,77.0,0.001495,Adam,None,0.000105,0.0,PRUNED
29,29,None,None,None,None,2025-04-08 22:16:24.614845,2025-04-08 22:16:26.265673,0 days 00:00:01.650828,35.0,gelu,...,6.0,779.0,158.0,150.0,0.000092,AdamW,Cosine,0.009423,0.0,PRUNED
30,30,None,None,None,None,2025-04-08 22:16:26.304076,2025-04-08 22:16:28.193205,0 days 00:00:01.889129,38.0,gelu,...,3.0,494.0,457.0,186.0,0.000032,AdamW,Cosine,0.000035,0.0,PRUNED
31,31,None,None,None,None,2025-04-08 22:16:28.227749,2025-04-08 22:16:29.981465,0 days 00:00:01.753716,NaN,relu,...,4.0,633.0,319.0,174.0,0.007734,Adam,None,0.000767,0.0,PRUNED
32,32,None,None,None,None,2025-04-08 22:16:30.017545,2025-04-08 22:16:32.256669,0 days 00:00:02.239124,NaN,gelu,...,4.0,449.0,392.0,156.0,0.000018,AdamW,None,0.000004,0.0,PRUNED
33,33,None,None,None,None,2025-04-08 22:16:32.294166,2025-04-08 22:16:34.079007,0 days 00:00:01.784841,37.0,gelu,...,8.0,538.0,75.0,57.0,0.000130,Adam,Cosine,0.000097,0.0,PRUNED
34,34,None,None,None,None,2025-04-08 22:16:34.116106,2025-04-08 22:16:35.986800,0 days 00:00:01.870694,NaN,relu,...,6.0,438.0,164.0,66.0,0.000024,Adam,None,0.000064,0.0,PRUNED
35,35,None,None,None,None,2025-04-08 22:16:36.029447,2025-04-08 22:16:37.916387,0 days 00:00:01.886940,28.0,gelu,...,6.0,390.0,295.0,154.0,0.000073,Adam,Cosine,0.000367,0.0,PRUNED
36,36,None,None,None,None,2025-04-08 22:16:37.950660,2025-04-08 22:16:39.912555,0 days 00:00:01.961895,NaN,relu,...,8.0,909.0,82.0,32.0,0.001734,AdamW,None,0.000212,0.0,PRUNED
37,37,None,None,None,None,2025-04-08 22:16:39.950362,2025-04-08 22:16:41.873039,0 days 00:00:01.922677,20.0,relu,...,7.0,503.0,292.0,108.0,0.000105,Adam,Cosine,0.000004,0.0,PRUNED
38,38,None,None,None,None,2025-04-08 22:16:41.908011,2025-04-08 22:16:43.824741,0 days 00:00:01.916730,NaN,relu,...,2.0,394.0,194.0,152.0,0.004091,AdamW,None,0.000003,0.0,PRUNED
39,39,None,None,None,None,2025-04-08 22:16:43.860641,2025-04-08 22:16:45.711591,0 days 00:00:01.850950,41.0,gelu,...,6.0,333.0,325.0,98.0,0.000392,Adam,Cosine,0.000023,0.0,PRUNED
40,40,None,None,None,None,2025-04-08 22:16:45.746782,2025-04-08 22:16:47.598547,0 days 00:00:01.851765,NaN,gelu,...,3.0,1011.0,377.0,219.0,0.000012,Adam,None,0.007486,0.0,PRUNED
41,41,None,None,None,None,2025-04-08 22:16:47.634496,2025-04-08 22:16:49.508109,0 days 00:00:01.873613,50.0,relu,...,3.0,657.0,434.0,156.0,0.000158,Adam,Cosine,0.000148,0.0,PRUNED
42,42,None,None,None,None,2025-04-08 22:16:49.543472,2025-04-08 22:16:51.528638,0 days 00:00:01.985166,30.0,gelu,...,2.0,671.0,220.0,47.0,0.000621,AdamW,Cosine,0.000297,0.0,PRUNED
43,43,None,None,None,None,2025-04-08 22:16:51.563986,2025-04-08 23:25:58.800553,0 days 01:09:07.236567,41.0,relu,...,2.0,587.0,103.0,99.0,0.001784,Adam,Cosine,0.000027,0.0,FAIL

In [5]:
method = 'GCN'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 10:03:27,981] Using an existing study with name 'GCN' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_activation,params_dropout1,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 21:58:18.449026,2025-04-08 21:58:18.493092,0 days 00:00:00.044066,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
1,1,None,None,None,None,2025-04-08 22:15:27.526539,2025-04-08 22:16:01.334876,0 days 00:00:33.808337,gelu,0.5,...,2.0,1017.0,481.0,134.0,0.004441,AdamW,NaN,0.001884,0.0,FAIL
2,2,None,None,None,None,2025-04-08 22:49:55.132951,2025-04-08 23:20:33.213639,0 days 00:30:38.080688,relu,0.3,...,4.0,985.0,512.0,107.0,0.003055,Adam,NaN,0.000946,0.0,FAIL

In [6]:
method = 'MPNN'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 10:03:28,066] Using an existing study with name 'MPNN' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 21:58:18.450527,2025-04-08 21:58:18.494992,0 days 00:00:00.044465,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
1,1,None,None,None,None,2025-04-08 22:03:58.983068,2025-04-08 22:03:59.028566,0 days 00:00:00.045498,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
2,2,None,None,None,None,2025-04-08 22:13:47.941198,2025-04-08 22:13:47.986404,0 days 00:00:00.045206,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL
3,3,None,None,None,None,2025-04-08 22:49:55.139945,2025-04-08 23:15:49.659823,0 days 00:25:54.519878,45.0,gelu,...,7.0,371.0,99.0,60.0,0.000033,Adam,Cosine,0.000053,0.0,FAIL