In [1]:
import numpy as np
import optuna
import pandas as pd

In [19]:
name = "CTRP_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df

[I 2025-03-31 12:57:49,450] Using an existing study with name 'CTRP_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
0,0,0.817641,0.892432,0.898734,0.810869,2025-03-28 13:42:26.672297,2025-03-28 13:43:39.077700,0 days 00:01:12.405403,NaN,gelu,...,0.000049,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000935,COMPLETE
1,1,0.734029,0.808461,0.822512,0.620973,2025-03-28 13:43:39.103921,2025-03-28 13:48:22.545780,0 days 00:04:43.441859,NaN,swish,...,0.004928,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000567,COMPLETE
3,3,0.702481,0.876589,0.882087,0.584341,2025-03-28 13:48:22.927208,2025-03-28 13:49:04.880124,0 days 00:00:41.952916,NaN,relu,...,0.000563,0.869109,True,SGD,NaN,None,NaN,NaN,0.000182,COMPLETE
4,4,0.820572,0.897242,0.899471,0.814598,2025-03-28 13:49:04.906250,2025-03-28 14:12:35.253803,0 days 00:23:30.347553,NaN,swish,...,0.000091,NaN,NaN,Adam,NaN,Step,12.0,NaN,0.003351,COMPLETE
5,5,0.597730,0.847468,0.866533,0.270710,2025-03-28 13:53:44.719033,2025-03-28 14:04:28.140293,0 days 00:10:43.421260,24.0,swish,...,0.000011,0.924749,False,SGD,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,483,0.817747,0.897101,0.899331,0.808635,2025-03-29 09:42:36.744976,2025-03-29 10:05:11.170442,0 days 00:22:34.425466,NaN,gelu,...,0.001256,0.886645,True,SGD,NaN,Step,18.0,NaN,0.000149,COMPLETE
486,486,0.820265,0.892844,0.898693,0.815231,2025-03-29 10:05:11.216092,2025-03-29 10:08:30.785001,0 days 00:03:19.568909,NaN,swish,...,0.000025,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000516,COMPLETE
487,487,0.820412,0.896953,0.899673,0.813402,2025-03-29 10:08:30.822783,2025-03-29 10:12:54.260810,0 days 00:04:23.438027,23.0,swish,...,0.000034,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000078,COMPLETE
488,488,0.815119,0.896456,0.898882,0.804956,2025-03-29 10:12:54.297779,2025-03-29 10:18:49.398670,0 days 00:05:55.100891,NaN,relu,...,0.000711,NaN,NaN,AdamW,8.0,Plateau,NaN,0.008111,0.000044,COMPLETE
490,490,0.816260,0.891352,0.896828,0.807914,2025-03-29 10:19:01.163949,2025-03-29 10:20:56.611058,0 days 00:01:55.447109,NaN,gelu,...,0.000043,NaN,NaN,AdamW,NaN,Step,29.0,NaN,0.000058,COMPLETE

In [20]:
tmp = df.loc[
    df[["values_0", "values_1", "values_2", "values_3"]]
    .max(axis=1)
    .sort_values(ascending=False)
    .index
]
tmp[tmp["params_gnn_layer"] == "GAT"]

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
157,157,0.820740,0.898305,0.900861,0.813128,2025-03-28 16:48:19.436369,2025-03-28 17:33:18.831906,0 days 00:44:59.395537,45.0,gelu,...,0.000639,0.853541,True,SGD,NaN,Cosine,NaN,NaN,0.004981,COMPLETE
477,477,0.815675,0.897939,0.900531,0.805324,2025-03-28 23:24:52.936518,2025-03-28 23:28:14.952464,0 days 00:03:22.015946,44.0,swish,...,0.000993,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000053,COMPLETE
275,275,0.813540,0.896094,0.900442,0.802348,2025-03-28 18:20:06.098087,2025-03-28 18:30:03.283821,0 days 00:09:57.185734,38.0,relu,...,0.001631,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000729,COMPLETE
466,466,0.814290,0.897868,0.900358,0.803773,2025-03-28 22:17:42.737242,2025-03-28 22:21:02.694136,0 days 00:03:19.956894,NaN,gelu,...,0.000059,NaN,NaN,AdamW,NaN,Step,16.0,NaN,0.000129,COMPLETE
52,52,0.810883,0.896071,0.900123,0.798139,2025-03-28 14:50:59.246485,2025-03-28 15:02:21.245883,0 days 00:11:21.999398,NaN,gelu,...,0.000113,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000403,COMPLETE
88,88,0.801384,0.896800,0.900017,0.781509,2025-03-28 15:51:38.382752,2025-03-28 15:59:53.961727,0 days 00:08:15.578975,47.0,relu,...,0.000293,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000093,COMPLETE
393,393,0.817498,0.895579,0.899915,0.811310,2025-03-28 21:01:26.801387,2025-03-28 21:19:21.934731,0 days 00:17:55.133344,31.0,gelu,...,0.000049,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.002993,COMPLETE
407,407,0.811527,0.896377,0.899906,0.799389,2025-03-28 21:21:46.085620,2025-03-28 21:24:36.787761,0 days 00:02:50.702141,NaN,swish,...,0.000716,NaN,NaN,AdamW,NaN,Step,29.0,NaN,0.000094,COMPLETE
473,473,0.820681,0.898430,0.899770,0.815355,2025-03-28 22:24:57.000060,2025-03-28 22:43:31.731605,0 days 00:18:34.731545,42.0,gelu,...,0.000407,0.806638,False,SGD,NaN,Cosine,NaN,NaN,0.000688,COMPLETE
414,414,0.822223,0.894483,0.899733,0.817998,2025-03-28 21:23:52.188310,2025-03-28 21:24:57.405767,0 days 00:01:05.217457,NaN,swish,...,0.000094,NaN,NaN,AdamW,NaN,Step,16.0,NaN,0.000001,COMPLETE
11,11,0.795114,0.895260,0.899706,0.771844,2025-03-28 14:04:28.169840,2025-03-28 14:08:26.393424,0 days 00:03:58.223584,NaN,relu,...,0.000211,0.848380,False,SGD,NaN,None,NaN,NaN,0.000292,COMPLETE
467,467,0.814450,0.896677,0.899607,0.803915,2025-03-28 22:18:45.323224,2025-03-28 22:22:06.776456,0 days 00:03:21.453232,NaN,gelu,...,0.000063,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000120,COMPLETE
374,374,0.818517,0.897159,0.899602,0.810760,2025-03-28 20:44:49.130599,2025-03-28 21:13:54.160369,0 days 00:29:05.029770,NaN,gelu,...,0.000059,NaN,NaN,AdamW,NaN,Step,14.0,NaN,0.003980,COMPLETE
380,380,0.816799,0.895060,0.899599,0.808217,2025-03-28 20:47:42.063761,2025-03-28 20:51:13.387267,0 days 00:03:31.323506,40.0,swish,...,0.000057,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000010,COMPLETE
276,276,0.815536,0.895198,0.899471,0.807366,2025-03-28 18:20:28.124307,2025-03-28 18:30:21.326910,0 days 00:09:53.202603,38.0,relu,...,0.000014,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000087,COMPLETE
262,262,0.819279,0.894594,0.899409,0.811994,2025-03-28 18:08:33.288203,2025-03-28 18:14:57.686787,0 days 00:06:24.398584,NaN,relu,...,0.000048,NaN,NaN,Adam,3.0,Plateau,NaN,0.000164,0.000112,COMPLETE
427,427,0.809022,0.895594,0.899393,0.794700,2025-03-28 21:41:03.713020,2025-03-28 21:43:33.899203,0 days 00:02:30.186183,NaN,swish,...,0.000121,NaN,NaN,Adam,6.0,Plateau,NaN,0.001380,0.000024,COMPLETE
256,256,0.820799,0.895451,0.899365,0.816695,2025-03-28 17:59:26.216967,2025-03-28 18:03:15.746343,0 days 00:03:49.529376,35.0,swish,...,0.000054,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.006151,COMPLETE
63,63,0.817246,0.897197,0.899350,0.810029,2025-03-28 15:07:36.808550,2025-03-28 15:51:40.936198,0 days 00:44:04.127648,NaN,gelu,...,0.000054,0.901070,True,SGD,NaN,None,NaN,NaN,0.000925,COMPLETE
62,62,0.821978,0.896333,0.899030,0.817551,2025-03-28 15:05:51.358724,2025-03-28 15:46:45.514595,0 days 00:40:54.155871,NaN,gelu,...,0.000065,0.901915,True,SGD,6.0,Plateau,NaN,0.001407,0.001112,COMPLETE
274,274,0.803539,0.893974,0.898893,0.785760,2025-03-28 18:18:58.915087,2025-03-28 18:22:20.499033,0 days 00:03:21.583946,NaN,relu,...,0.000062,NaN,NaN,AdamW,NaN,Step,17.0,NaN,0.000273,COMPLETE
67,67,0.819721,0.892603,0.898891,0.815216,2025-03-28 15:24:16.519781,2025-03-28 15:27:19.081135,0 days 00:03:02.561354,NaN,swish,...,0.000056,NaN,NaN,AdamW,8.0,Plateau,NaN,0.000108,0.001732,COMPLETE
488,488,0.815119,0.896456,0.898882,0.804956,2025-03-29 10:12:54.297779,2025-03-29 10:18:49.398670,0 days 00:05:55.100891,NaN,relu,...,0.000711,NaN,NaN,AdamW,8.0,Plateau,NaN,0.008111,0.000044,COMPLETE
0,0,0.817641,0.892432,0.898734,0.810869,2025-03-28 13:42:26.672297,2025-03-28 13:43:39.077700,0 days 00:01:12.405403,NaN,gelu,...,0.000049,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000935,COMPLETE
486,486,0.820265,0.892844,0.898693,0.815231,2025-03-29 10:05:11.216092,2025-03-29 10:08:30.785001,0 days 00:03:19.568909,NaN,swish,...,0.000025,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000516,COMPLETE
220,220,0.813881,0.893728,0.898252,0.805858,2025-03-28 17:37:11.117408,2025-03-28 17:38:25.904236,0 days 00:01:14.786828,44.0,gelu,...,0.001069,0.817448,True,SGD,NaN,Cosine,NaN,NaN,0.000013,COMPLETE
53,53,0.809586,0.889218,0.897879,0.796737,2025-03-28 14:54:23.121299,2025-03-28 14:57:53.618973,0 days 00:03:30.497674,NaN,gelu,...,0.000032,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.001467,COMPLETE
8,8,0.788267,0.890768,0.897509,0.758454,2025-03-28 13:53:44.731430,2025-03-28 14:20:06.945045,0 days 00:26:22.213615,NaN,gelu,...,0.001296,NaN,NaN,AdamW,NaN,Step,20.0,NaN,0.001680,COMPLETE
261,261,0.821128,0.888199,0.896549,0.819371,2025-03-28 18:07:39.190081,2025-03-28 18:10:49.583383,0 days 00:03:10.393302,NaN,swish,...,0.000044,NaN,NaN,AdamW,3.0,Plateau,NaN,0.001911,0.000001,COMPLETE
232,232,0.687695,0.889137,0.896336,0.482809,2025-03-28 17:45:54.822347,2025-03-28 17:47:49.569383,0 days 00:01:54.747036,NaN,relu,...,0.000060,NaN,NaN,AdamW,NaN,Step,21.0,NaN,0.000005,COMPLETE
219,219,0.591154,0.881638,0.892266,0.275336,2025-03-28 17:37:05.164103,2025-03-28 17:39:54.172079,0 days 00:02:49.007976,24.0,gelu,...,0.000044,0.821130,True,SGD,NaN,Cosine,NaN,NaN,0.000642,COMPLETE
250,250,0.594362,0.868252,0.881455,0.271120,2025-03-28 17:56:45.730467,2025-03-28 17:57:39.660846,0 days 00:00:53.930379,NaN,swish,...,0.000045,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000123,COMPLETE
217,217,0.556450,0.864430,0.878605,0.184977,2025-03-28 17:33:18.893247,2025-03-28 17:37:11.072428,0 days 00:03:52.179181,NaN,swish,...,0.000044,0.880173,True,SGD,NaN,Step,16.0,NaN,0.001380,COMPLETE
72,72,0.756494,0.830665,0.832937,0.654855,2025-03-28 15:27:36.125448,2025-03-28 15:30:40.686510,0 days 00:03:04.561062,38.0,gelu,...,0.005520,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000589,COMPLETE
1,1,0.734029,0.808461,0.822512,0.620973,2025-03-28 13:43:39.103921,2025-03-28 13:48:22.545780,0 days 00:04:43.441859,NaN,swish,...,0.004928,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000567,COMPLETE
54,54,0.560638,0.793500,0.806414,0.162917,2025-03-28 14:57:53.659995,2025-03-28 15:00:57.057794,0 days 00:03:03.397799,NaN,relu,...,0.000066,NaN,NaN,AdamW,3.0,Plateau,NaN,0.001253,0.000183,COMPLETE
18,18,0.640015,0.742093,0.765197,0.372595,2025-03-28 14:08:50.648298,2025-03-28 14:09:32.480934,0 days 00:00:41.832636,NaN,gelu,...,0.000098,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000001,COMPLETE
19,19,0.499082,0.757394,0.761643,0.136233,2025-03-28 14:09:32.511250,2025-03-28 14:10:39.279492,0 days 00:01:06.768242,NaN,gelu,...,0.000023,0.806568,True,SGD,3.0,Plateau,NaN,0.000348,0.002603,COMPLETE
308,308,0.500126,0.706627,0.684957,0.000940,2025-03-28 18:56:47.574859,2025-03-28 18:58:09.223145,0 days 00:01:21.648286,34.0,relu,...,0.000040,0.833832,False,SGD,NaN,Cosine,NaN,NaN,0.000073,COMPLETE

In [21]:
tmp[tmp["params_gnn_layer"] == "GATv2"]

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
6,6,0.816841,0.897103,0.902114,0.805693,2025-03-28 13:53:44.723160,2025-03-28 15:03:29.869014,0 days 01:09:45.145854,36.0,gelu,...,0.000061,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.001660,COMPLETE
20,20,0.813321,0.898757,0.901544,0.800680,2025-03-28 14:10:39.310635,2025-03-28 14:15:21.004529,0 days 00:04:41.693894,49.0,relu,...,0.000256,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000086,COMPLETE
84,84,0.805784,0.896093,0.901400,0.788138,2025-03-28 15:48:15.847389,2025-03-28 16:30:01.987447,0 days 00:41:46.140058,24.0,gelu,...,0.000116,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000018,COMPLETE
205,205,0.810988,0.896601,0.901372,0.797051,2025-03-28 17:24:20.727489,2025-03-28 18:06:21.337097,0 days 00:42:00.609608,35.0,gelu,...,0.000046,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000075,COMPLETE
195,195,0.812146,0.896514,0.901226,0.799789,2025-03-28 17:18:31.292562,2025-03-28 17:43:31.133733,0 days 00:24:59.841171,39.0,gelu,...,0.000040,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000093,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,5,0.597730,0.847468,0.866533,0.270710,2025-03-28 13:53:44.719033,2025-03-28 14:04:28.140293,0 days 00:10:43.421260,24.0,swish,...,0.000011,0.924749,False,SGD,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
268,268,0.570121,0.835194,0.854742,0.196701,2025-03-28 18:16:30.521685,2025-03-28 18:58:41.121819,0 days 00:42:10.600134,NaN,gelu,...,0.000038,0.891771,True,SGD,NaN,Step,19.0,NaN,0.000221,COMPLETE
38,38,0.731342,0.769423,0.813643,0.750789,2025-03-28 14:32:12.795382,2025-03-28 14:37:25.662887,0 days 00:05:12.867505,44.0,relu,...,0.009979,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
51,51,0.561779,0.746964,0.777303,0.159006,2025-03-28 14:47:50.098538,2025-03-28 14:50:59.207418,0 days 00:03:09.108880,35.0,relu,...,0.000052,0.801104,True,SGD,NaN,Cosine,NaN,NaN,0.000805,COMPLETE
188,188,0.697876,0.747404,0.752607,0.621576,2025-03-28 16:53:04.708805,2025-03-28 17:17:57.529725,0 days 00:24:52.820920,37.0,gelu,...,0.009107,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.005238,COMPLETE

In [22]:
tmp[tmp["params_gnn_layer"] == "Transformer"]

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
421,421,0.810862,0.897850,0.902545,0.795847,2025-03-28 21:28:35.714268,2025-03-28 21:52:12.546111,0 days 00:23:36.831843,41.0,gelu,...,0.000067,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000250,COMPLETE
444,444,0.815001,0.897254,0.901264,0.803630,2025-03-28 21:57:35.496122,2025-03-28 22:04:11.488957,0 days 00:06:35.992835,NaN,swish,...,0.000372,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000102,COMPLETE
462,462,0.812845,0.896495,0.901205,0.800036,2025-03-28 22:08:41.935073,2025-03-28 22:16:47.869120,0 days 00:08:05.934047,43.0,swish,...,0.000333,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000145,COMPLETE
479,479,0.817043,0.898765,0.901031,0.806931,2025-03-29 09:20:18.964558,2025-03-29 09:43:07.374543,0 days 00:22:48.409985,NaN,gelu,...,0.000231,NaN,NaN,AdamW,NaN,Step,22.0,NaN,0.000097,COMPLETE
476,476,0.809186,0.897930,0.900980,0.793887,2025-03-28 22:43:46.907772,2025-03-28 23:24:52.900734,0 days 00:41:05.992962,NaN,gelu,...,0.000054,NaN,NaN,AdamW,NaN,Step,20.0,NaN,0.000061,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,3,0.702481,0.876589,0.882087,0.584341,2025-03-28 13:48:22.927208,2025-03-28 13:49:04.880124,0 days 00:00:41.952916,NaN,relu,...,0.000563,0.869109,True,SGD,NaN,None,NaN,NaN,0.000182,COMPLETE
60,60,0.700244,0.864697,0.872988,0.533067,2025-03-28 15:03:21.561103,2025-03-28 15:08:59.663705,0 days 00:05:38.102602,NaN,relu,...,0.000074,0.907924,False,SGD,6.0,Plateau,NaN,0.001454,0.006247,COMPLETE
294,294,0.628074,0.852993,0.859532,0.391972,2025-03-28 18:46:36.935763,2025-03-28 18:50:55.763235,0 days 00:04:18.827472,NaN,swish,...,0.000035,0.913416,False,SGD,NaN,Step,23.0,NaN,0.000028,COMPLETE
442,442,0.567287,0.695379,0.698286,0.413750,2025-03-28 21:54:20.213089,2025-03-28 22:00:15.997154,0 days 00:05:55.784065,NaN,relu,...,0.000035,0.800018,False,SGD,NaN,Step,14.0,NaN,0.000104,COMPLETE
441,441,0.505874,0.614294,0.605480,0.131842,2025-03-28 21:54:16.157933,2025-03-28 21:56:09.723537,0 days 00:01:53.565604,NaN,relu,...,0.000033,0.839322,False,SGD,NaN,Step,14.0,NaN,0.000061,COMPLETE

In [3]:
df.params_gnn_layer.value_counts()

params_gnn_layer
GATv2          117
Transformer     63
GAT             39
Name: count, dtype: int64

In [4]:
name = "CTRP"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df.sort_values(["values_0", "values_1", "values_2", "values_3"], ascending=False)

[I 2025-03-31 12:53:10,451] Using an existing study with name 'CTRP' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
446,446,0.819355,0.897722,0.899527,0.811999,2025-03-29 13:01:16.719346,2025-03-29 14:15:05.848306,0 days 01:13:49.128960,NaN,swish,...,0.008568,0.906108,True,SGD,NaN,None,NaN,NaN,0.000211,COMPLETE
300,300,0.818698,0.898037,0.899945,0.810015,2025-03-29 11:01:13.665110,2025-03-29 12:01:02.416940,0 days 00:59:48.751830,NaN,swish,...,0.009086,0.937809,True,SGD,NaN,None,NaN,NaN,0.000341,COMPLETE
282,282,0.818395,0.899485,0.901003,0.808862,2025-03-29 10:53:51.147226,2025-03-29 11:51:41.786813,0 days 00:57:50.639587,NaN,swish,...,0.005661,0.939727,True,SGD,NaN,None,NaN,NaN,0.000167,COMPLETE
467,467,0.818319,0.898608,0.899852,0.809699,2025-03-29 13:56:30.078478,2025-03-29 15:28:22.688849,0 days 01:31:52.610371,NaN,swish,...,0.008214,0.930853,True,SGD,NaN,None,NaN,NaN,0.000207,COMPLETE
181,181,0.818311,0.898355,0.899885,0.810119,2025-03-29 09:21:28.644911,2025-03-29 10:15:19.992136,0 days 00:53:51.347225,NaN,swish,...,0.007418,0.866027,True,SGD,NaN,None,NaN,NaN,0.001191,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,587,0.538070,0.890786,0.894897,0.131068,2025-03-29 15:55:12.476633,2025-03-29 15:57:09.570438,0 days 00:01:57.093805,NaN,swish,...,0.005100,0.880474,False,SGD,NaN,None,NaN,NaN,0.000268,COMPLETE
9,9,0.537358,0.870938,0.879146,0.120925,2025-03-28 13:39:44.342225,2025-03-28 14:15:12.928473,0 days 00:35:28.586248,NaN,swish,...,0.000107,NaN,NaN,AdamW,3.0,Plateau,NaN,0.00012,0.009204,COMPLETE
129,129,0.528077,0.895537,0.897993,0.089533,2025-03-28 15:37:36.030934,2025-03-28 15:39:34.588614,0 days 00:01:58.557680,29.0,swish,...,0.003572,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000002,COMPLETE
201,201,0.516435,0.873398,0.876314,0.060219,2025-03-29 10:34:46.169675,2025-03-29 10:38:13.366399,0 days 00:03:27.196724,NaN,gelu,...,0.000204,0.838971,False,SGD,NaN,None,NaN,NaN,0.001124,COMPLETE
206,206,0.512123,0.826673,0.835359,0.048155,2025-03-29 10:34:46.593074,2025-03-29 10:38:14.867771,0 days 00:03:28.274697,NaN,swish,...,0.000221,0.839362,False,SGD,NaN,None,NaN,NaN,0.001055,COMPLETE

In [15]:
tmp = df.loc[
    df[["values_0", "values_1", "values_2", "values_3"]]
    .max(axis=1)
    .sort_values(ascending=False)
    .index
]
tmp[tmp["params_gnn_layer"] == "MPNN"]

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
410,410,0.808664,0.899109,0.901220,0.793734,2025-03-29 12:42:14.008864,2025-03-29 13:36:02.084256,0 days 00:53:48.075392,NaN,swish,...,0.000082,0.931435,True,SGD,NaN,None,NaN,NaN,0.000299,COMPLETE
19,19,0.808672,0.898528,0.901076,0.794351,2025-03-28 13:53:44.727885,2025-03-28 14:04:59.091839,0 days 00:11:14.363954,NaN,relu,...,0.000299,NaN,NaN,AdamW,10.0,Plateau,NaN,0.008604,0.000831,COMPLETE
249,249,0.814050,0.898715,0.901038,0.802379,2025-03-29 10:45:59.290904,2025-03-29 12:02:05.965684,0 days 01:16:06.674780,NaN,swish,...,0.004484,0.862562,True,SGD,NaN,None,NaN,NaN,0.000599,COMPLETE
17,17,0.806778,0.898729,0.900990,0.791142,2025-03-28 13:51:32.143791,2025-03-28 14:19:01.814422,0 days 00:27:29.670631,NaN,relu,...,0.000239,NaN,NaN,AdamW,10.0,Plateau,NaN,0.006614,0.000621,COMPLETE
510,510,0.787214,0.898105,0.900963,0.755885,2025-03-29 14:18:16.450905,2025-03-29 14:21:31.778183,0 days 00:03:15.327278,32.0,relu,...,0.000140,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000250,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,131,0.725653,0.891371,0.894769,0.631827,2025-03-28 15:38:12.537247,2025-03-28 15:40:01.963213,0 days 00:01:49.425966,29.0,swish,...,0.000173,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000002,COMPLETE
405,405,0.718915,0.891993,0.894673,0.620297,2025-03-29 12:38:51.612528,2025-03-29 12:41:24.364463,0 days 00:02:32.751935,NaN,gelu,...,0.000151,0.929140,False,SGD,3.0,Plateau,NaN,0.001257,0.000398,COMPLETE
407,407,0.720520,0.891660,0.894343,0.623179,2025-03-29 12:39:56.428010,2025-03-29 12:42:36.834451,0 days 00:02:40.406441,NaN,swish,...,0.000287,0.927962,False,SGD,NaN,None,NaN,NaN,0.000007,COMPLETE
134,134,0.775521,0.892218,0.893894,0.736483,2025-03-28 15:39:06.489611,2025-03-28 15:44:15.718417,0 days 00:05:09.228806,NaN,swish,...,0.000055,0.882121,False,SGD,NaN,Step,17.0,NaN,0.000002,COMPLETE
505,505,0.719805,0.871497,0.867539,0.593031,2025-03-29 14:17:21.000496,2025-03-29 14:20:42.181294,0 days 00:03:21.180798,NaN,relu,...,0.000011,NaN,NaN,AdamW,NaN,Step,28.0,NaN,0.000015,COMPLETE

In [16]:
tmp[tmp["params_gnn_layer"] == "GCN"]

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
286,286,0.814770,0.899914,0.901052,0.803341,2025-03-29 10:53:51.300088,2025-03-29 11:53:35.722491,0 days 00:59:44.422403,NaN,swish,...,0.005591,0.872816,True,SGD,NaN,None,NaN,NaN,0.000171,COMPLETE
305,305,0.818286,0.899692,0.901048,0.808744,2025-03-29 11:36:21.422631,2025-03-29 12:27:21.704414,0 days 00:51:00.281783,NaN,relu,...,0.008862,0.941313,True,SGD,NaN,None,NaN,NaN,0.000497,COMPLETE
282,282,0.818395,0.899485,0.901003,0.808862,2025-03-29 10:53:51.147226,2025-03-29 11:51:41.786813,0 days 00:57:50.639587,NaN,swish,...,0.005661,0.939727,True,SGD,NaN,None,NaN,NaN,0.000167,COMPLETE
320,320,0.813532,0.898770,0.901003,0.801440,2025-03-29 11:51:41.980153,2025-03-29 12:35:58.308315,0 days 00:44:16.328162,NaN,relu,...,0.000400,0.943469,True,SGD,NaN,None,NaN,NaN,0.000238,COMPLETE
76,76,0.809493,0.900044,0.900993,0.794762,2025-03-28 14:37:53.329048,2025-03-28 15:37:46.471682,0 days 00:59:53.142634,NaN,swish,...,0.005174,0.897554,True,SGD,NaN,None,NaN,NaN,0.004403,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,0.512123,0.826673,0.835359,0.048155,2025-03-29 10:34:46.593074,2025-03-29 10:38:14.867771,0 days 00:03:28.274697,NaN,swish,...,0.000221,0.839362,False,SGD,NaN,None,NaN,NaN,0.001055,COMPLETE
538,538,0.539405,0.813736,0.812396,0.139470,2025-03-29 14:25:47.529709,2025-03-29 14:28:47.751562,0 days 00:03:00.221853,NaN,swish,...,0.000021,0.899866,True,SGD,NaN,None,NaN,NaN,0.000172,COMPLETE
617,617,0.562379,0.791295,0.805131,0.194251,2025-03-29 16:21:33.149543,2025-03-29 16:24:17.023356,0 days 00:02:43.873813,NaN,swish,...,0.000011,0.902903,True,SGD,4.0,Plateau,NaN,0.003736,0.000165,COMPLETE
208,208,0.563903,0.754489,0.758468,0.268451,2025-03-29 10:34:47.516315,2025-03-29 10:38:02.292460,0 days 00:03:14.776145,NaN,gelu,...,0.000014,0.836174,False,SGD,NaN,None,NaN,NaN,0.001410,COMPLETE
214,214,0.577688,0.749573,0.752990,0.343569,2025-03-29 10:34:49.622345,2025-03-29 10:38:20.469967,0 days 00:03:30.847622,NaN,gelu,...,0.000015,0.837068,False,SGD,NaN,None,NaN,NaN,0.001147,COMPLETE

In [8]:
df.params_gnn_layer.value_counts()

params_gnn_layer
GCN     85
MPNN    14
Name: count, dtype: int64