In [1]:
import pandas as pd

from metrics import get_result

In [2]:
res = pd.DataFrame()
for i in ["nci", "gdsc1", "gdsc2", "ctrp"]:
    for l in [
        "GCN",
        "MPNN",
        "GAT",
        "GATv2",
        "Transformer",
    ]:
        true = pd.read_csv(f"Tuning_{i.upper()}/true_{i}_{l}.csv", index_col=0).T
        true.index = range(0, 5)
        pred = pd.read_csv(f"Tuning_{i.upper()}/pred_{i}_{l}.csv", index_col=0).T
        pred.index = range(0, 5)
        tmp = get_result(true, pred, i)
        tmp.columns = [l + "_" + i]
        res = pd.concat([res, tmp], axis=1)

res = res.T

In [3]:
res

,ACC,Precision,Recall,Specificity,F1,F2,Balanced ACC,G-Mean,AUROC,AUPR,LogLoss,Brier,MCC,Kappa,Youden J,Cost Ratio
GCN_nci,0.534 (± 0.042),0.525 (± 0.309),0.322 (± 0.392),0.746 (± 0.417),0.314 (± 0.260),0.307 (± 0.324),0.534 (± 0.042),0.271 (± 0.220),0.624 (± 0.077),0.609 (± 0.062),0.684 (± 0.008),0.245 (± 0.004),0.090 (± 0.111),0.068 (± 0.084),0.247 (± 0.154),4.547 (± 8.634)
MPNN_nci,0.587 (± 0.049),0.526 (± 0.294),0.364 (± 0.206),0.810 (± 0.109),0.430 (± 0.241),0.387 (± 0.218),0.587 (± 0.049),0.471 (± 0.263),0.659 (± 0.013),0.637 (± 0.020),0.675 (± 0.012),0.241 (± 0.006),0.183 (± 0.103),0.174 (± 0.098),0.317 (± 0.025),0.967 (± 0.543)
GAT_nci,0.667 (± 0.003),0.695 (± 0.015),0.598 (± 0.032),0.736 (± 0.032),0.642 (± 0.013),0.615 (± 0.025),0.667 (± 0.003),0.663 (± 0.004),0.731 (± 0.005),0.725 (± 0.005),0.613 (± 0.004),0.212 (± 0.002),0.338 (± 0.007),0.334 (± 0.006),0.463 (± 0.010),1.737 (± 0.108)
GATv2_nci,0.648 (± 0.023),0.670 (± 0.050),0.614 (± 0.144),0.681 (± 0.160),0.630 (± 0.048),0.618 (± 0.102),0.648 (± 0.023),0.632 (± 0.034),0.717 (± 0.028),0.705 (± 0.032),0.626 (± 0.019),0.218 (± 0.009),0.307 (± 0.041),0.295 (± 0.045),0.434 (± 0.055),2.110 (± 1.261)
Transformer_nci,0.663 (± 0.003),0.686 (± 0.009),0.602 (± 0.032),0.724 (± 0.027),0.641 (± 0.014),0.617 (± 0.026),0.663 (± 0.003),0.660 (± 0.006),0.728 (± 0.002),0.722 (± 0.004),0.614 (± 0.005),0.213 (± 0.002),0.329 (± 0.004),0.326 (± 0.006),0.456 (± 0.005),1.734 (± 0.122)
GCN_gdsc1,0.832 (± 0.010),0.954 (± 0.006),0.699 (± 0.025),0.966 (± 0.006),0.806 (± 0.014),0.738 (± 0.021),0.832 (± 0.010),0.821 (± 0.012),0.953 (± 0.001),0.954 (± 0.001),0.390 (± 0.013),0.121 (± 0.005),0.690 (± 0.014),0.665 (± 0.019),0.906 (± 0.001),3.183 (± 0.258)
MPNN_gdsc1,0.840 (± 0.005),0.949 (± 0.002),0.720 (± 0.009),0.961 (± 0.001),0.819 (± 0.006),0.756 (± 0.008),0.840 (± 0.005),0.832 (± 0.005),0.952 (± 0.001),0.954 (± 0.001),0.384 (± 0.009),0.118 (± 0.003),0.702 (± 0.008),0.681 (± 0.009),0.904 (± 0.001),3.389 (± 0.118)
GAT_gdsc1,0.825 (± 0.010),0.958 (± 0.006),0.679 (± 0.026),0.970 (± 0.006),0.795 (± 0.016),0.721 (± 0.023),0.825 (± 0.010),0.812 (± 0.013),0.959 (± 0.001),0.957 (± 0.001),0.379 (± 0.019),0.121 (± 0.006),0.679 (± 0.014),0.649 (± 0.020),0.918 (± 0.003),3.001 (± 0.228)
GATv2_gdsc1,0.849 (± 0.014),0.942 (± 0.032),0.746 (± 0.061),0.952 (± 0.035),0.831 (± 0.023),0.777 (± 0.047),0.849 (± 0.014),0.842 (± 0.018),0.958 (± 0.006),0.957 (± 0.007),0.350 (± 0.014),0.109 (± 0.004),0.716 (± 0.018),0.698 (± 0.027),0.916 (± 0.012),3.944 (± 1.197)
Transformer_gdsc1,0.849 (± 0.004),0.954 (± 0.003),0.733 (± 0.010),0.965 (± 0.002),0.829 (± 0.006),0.769 (± 0.008),0.849 (± 0.004),0.841 (± 0.005),0.961 (± 0.001),0.960 (± 0.001),0.344 (± 0.010),0.108 (± 0.003),0.717 (± 0.007),0.698 (± 0.008),0.922 (± 0.002),3.582 (± 0.129)
GCN_gdsc2,0.830 (± 0.014),0.966 (± 0.006),0.684 (± 0.033),0.976 (± 0.005),0.800 (± 0.021),0.726 (± 0.029),0.830 (± 0.014),0.817 (± 0.018),0.958 (± 0.001),0.960 (± 0.002),0.407 (± 0.037),0.124 (± 0.010),0.690 (± 0.022),0.659 (± 0.029),0.917 (± 0.003),3.077 (± 0.294)
MPNN_gdsc2,0.851 (± 0.006),0.970 (± 0.003),0.726 (± 0.013),0.977 (± 0.003),0.830 (± 0.008),0.764 (± 0.011),0.851 (± 0.006),0.842 (± 0.007),0.965 (± 0.001),0.967 (± 0.001),0.361 (± 0.023),0.109 (± 0.005),0.726 (± 0.009),0.703 (± 0.011),0.930 (± 0.002),3.538 (± 0.159)
GAT_gdsc2,0.847 (± 0.006),0.975 (± 0.002),0.711 (± 0.013),0.982 (± 0.001),0.823 (± 0.008),0.752 (± 0.011),0.847 (± 0.006),0.836 (± 0.007),0.972 (± 0.001),0.972 (± 0.001),0.346 (± 0.014),0.108 (± 0.004),0.720 (± 0.009),0.693 (± 0.012),0.944 (± 0.001),3.383 (± 0.152)
GATv2_gdsc2,0.848 (± 0.009),0.975 (± 0.003),0.715 (± 0.020),0.981 (± 0.003),0.825 (± 0.013),0.756 (± 0.018),0.848 (± 0.009),0.838 (± 0.011),0.972 (± 0.001),0.972 (± 0.001),0.338 (± 0.017),0.106 (± 0.006),0.723 (± 0.014),0.697 (± 0.018),0.943 (± 0.002),3.439 (± 0.239)
Transformer_gdsc2,0.852 (± 0.004),0.974 (± 0.001),0.723 (± 0.009),0.980 (± 0.001),0.830 (± 0.005),0.762 (± 0.008),0.852 (± 0.004),0.842 (± 0.005),0.972 (± 0.001),0.972 (± 0.001),0.341 (± 0.010),0.106 (± 0.003),0.728 (± 0.006),0.704 (± 0.008),0.944 (± 0.002),3.520 (± 0.109)
GCN_ctrp,0.815 (± 0.005),0.853 (± 0.003),0.763 (± 0.013),0.868 (± 0.005),0.805 (± 0.007),0.779 (± 0.010),0.815 (± 0.005),0.814 (± 0.005),0.900 (± 0.001),0.898 (± 0.001),0.422 (± 0.008),0.133 (± 0.003),0.635 (± 0.008),0.631 (± 0.009),0.800 (± 0.003),3.600 (± 0.186)
MPNN_ctrp,0.810 (± 0.005),0.854 (± 0.004),0.747 (± 0.017),0.872 (± 0.007),0.797 (± 0.008),0.767 (± 0.014),0.810 (± 0.005),0.807 (± 0.006),0.899 (± 0.001),0.897 (± 0.001),0.426 (± 0.004),0.135 (± 0.002),0.624 (± 0.008),0.619 (± 0.010),0.798 (± 0.002),3.393 (± 0.218)
GAT_ctrp,0.819 (± 0.004),0.851 (± 0.005),0.772 (± 0.012),0.865 (± 0.007),0.810 (± 0.005),0.787 (± 0.010),0.819 (± 0.004),0.817 (± 0.004),0.901 (± 0.002),0.896 (± 0.003),0.420 (± 0.007),0.132 (± 0.003),0.640 (± 0.006),0.637 (± 0.007),0.801 (± 0.004),3.741 (± 0.185)
GATv2_ctrp,0.817 (± 0.004),0.859 (± 0.008),0.758 (± 0.019),0.875 (± 0.011),0.805 (± 0.007),0.776 (± 0.015),0.817 (± 0.004),0.814 (± 0.005),0.903 (± 0.001),0.898 (± 0.001),0.416 (± 0.006),0.133 (± 0.002),0.638 (± 0.006),0.633 (± 0.008),0.805 (± 0.001),3.568 (± 0.243)
Transformer_ctrp,0.819 (± 0.001),0.856 (± 0.004),0.766 (± 0.009),0.871 (± 0.006),0.809 (± 0.003),0.783 (± 0.006),0.819 (± 0.001),0.817 (± 0.002),0.903 (± 0.001),0.899 (± 0.001),0.418 (± 0.002),0.131 (± 0.001),0.641 (± 0.002),0.638 (± 0.003),0.806 (± 0.002),3.667 (± 0.115)

In [11]:
!tree | grep _1.csv

│   ├── pred_ctrp_Transformer_1.csv
│   ├── true_ctrp_Transformer_1.csv
│   ├── pred_gdsc1_GAT_1.csv
│   ├── pred_gdsc1_GATv2_1.csv
│   ├── pred_gdsc1_Transformer_1.csv
│   ├── true_gdsc1_GAT_1.csv
│   ├── true_gdsc1_GATv2_1.csv
│   ├── true_gdsc1_Transformer_1.csv
│   ├── pred_gdsc2_GAT_1.csv
│   ├── pred_gdsc2_GATv2_1.csv
│   ├── pred_gdsc2_Transformer_1.csv
│   ├── true_gdsc2_GAT_1.csv
│   ├── true_gdsc2_GATv2_1.csv
│   ├── true_gdsc2_Transformer_1.csv
│   ├── pred_nci_GATv2_1.csv
│   ├── pred_nci_Transformer_1.csv
│   ├── true_nci_GATv2_1.csv
│   ├── true_nci_Transformer_1.csv

In [12]:
res = pd.DataFrame()
for i in [
    "nci",
    "gdsc1",
    "gdsc2",
    # "ctrp"
]:
    for l in [
        "GATv2",
        "Transformer",
    ]:
        true = pd.read_csv(f"Tuning_{i.upper()}/true_{i}_{l}_1.csv", index_col=0).T
        true.index = range(0, 5)
        pred = pd.read_csv(f"Tuning_{i.upper()}/pred_{i}_{l}_1.csv", index_col=0).T
        pred.index = range(0, 5)
        tmp = get_result(true, pred, i)
        tmp.columns = [l + "_" + i]
        res = pd.concat([res, tmp], axis=1)

res = res.T

In [13]:
res

,ACC,Precision,Recall,Specificity,F1,F2,Balanced ACC,G-Mean,AUROC,AUPR,LogLoss,Brier,MCC,Kappa,Youden J,Cost Ratio
GATv2_nci,0.667 (± 0.005),0.702 (± 0.007),0.580 (± 0.021),0.753 (± 0.016),0.635 (± 0.011),0.601 (± 0.018),0.667 (± 0.005),0.661 (± 0.006),0.731 (± 0.006),0.723 (± 0.006),0.614 (± 0.005),0.213 (± 0.002),0.339 (± 0.008),0.333 (± 0.009),0.462 (± 0.012),1.673 (± 0.077)
Transformer_nci,0.668 (± 0.007),0.695 (± 0.007),0.598 (± 0.017),0.737 (± 0.010),0.643 (± 0.011),0.615 (± 0.015),0.668 (± 0.007),0.664 (± 0.008),0.730 (± 0.008),0.724 (± 0.010),0.612 (± 0.007),0.212 (± 0.003),0.339 (± 0.014),0.335 (± 0.014),0.461 (± 0.017),1.732 (± 0.082)
GATv2_gdsc1,0.842 (± 0.007),0.959 (± 0.004),0.715 (± 0.017),0.969 (± 0.004),0.819 (± 0.010),0.753 (± 0.015),0.842 (± 0.007),0.833 (± 0.008),0.961 (± 0.001),0.961 (± 0.001),0.354 (± 0.011),0.112 (± 0.004),0.708 (± 0.010),0.684 (± 0.013),0.922 (± 0.002),3.375 (± 0.182)
Transformer_gdsc1,0.845 (± 0.004),0.959 (± 0.004),0.721 (± 0.011),0.969 (± 0.004),0.823 (± 0.006),0.759 (± 0.009),0.845 (± 0.004),0.836 (± 0.005),0.962 (± 0.001),0.962 (± 0.002),0.353 (± 0.009),0.110 (± 0.003),0.713 (± 0.006),0.691 (± 0.008),0.924 (± 0.003),3.446 (± 0.118)
GATv2_gdsc2,0.837 (± 0.006),0.979 (± 0.003),0.688 (± 0.012),0.985 (± 0.003),0.808 (± 0.008),0.731 (± 0.011),0.837 (± 0.006),0.823 (± 0.007),0.972 (± 0.002),0.972 (± 0.002),0.360 (± 0.010),0.114 (± 0.004),0.705 (± 0.009),0.673 (± 0.011),0.943 (± 0.003),3.139 (± 0.118)
Transformer_gdsc2,0.853 (± 0.005),0.976 (± 0.004),0.724 (± 0.013),0.982 (± 0.003),0.831 (± 0.007),0.764 (± 0.011),0.853 (± 0.005),0.843 (± 0.006),0.973 (± 0.001),0.973 (± 0.001),0.339 (± 0.011),0.105 (± 0.003),0.731 (± 0.007),0.706 (± 0.010),0.946 (± 0.002),3.545 (± 0.150)