In [1]:
import time
import xml.etree.ElementTree as ET

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import seaborn as sns
from IPython.display import HTML, display
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.patches import Patch
from tqdm import tqdm

display(HTML("<style>.container { width:100% !important; }</style>"))

# Preprocess for figure 2.
- Get the paper list
- eseach on PubMed
- make a table.

In [3]:
def search_pubmed(query, max_results=None):
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {"db": "pubmed", "term": query, "retmax": max_results}

    if max_results:
        params["retmax"] = max_results

    response = requests.get(base_url, params=params)

    if response.status_code == 200:
        root = ET.fromstring(response.content)
        pmids = [id_elem.text for id_elem in root.findall("IdList/Id")]
        return pmids
    elif response.status_code == 429:
        time.sleep(2)
        return search_pubmed(query, 300)
    else:
        print("Error: Unable to fetch data from PubMed")
        return []

In [4]:
def fetch_details(pmids):
    ids = ",".join(pmids)
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    params = {"db": "pubmed", "retmode": "xml", "id": ids}

    response = requests.get(base_url, params=params)
    if response.status_code != 200:
        print("Error: Unable to fetch details from PubMed")
        return None

    return response.content

In [5]:
def parse_pubmed_efetch(xml_data):
    root = ET.fromstring(xml_data)

    articles = []
    for article in root.findall(".//PubmedArticle"):
        title = article.find(".//ArticleTitle").text

        journal_title = article.find(".//Journal/Title").text

        authors = []
        for author in article.findall(".//Author"):
            lastname = author.find("LastName")
            firstname = author.find("ForeName")
            if lastname is not None and firstname is not None:
                authors.append(f"{firstname.text} {lastname.text}")

        pmcid = None
        for article_id in article.findall(".//ArticleId"):
            if article_id.get("IdType") == "pmc":
                pmcid = article_id.text
                break

        articles.append(
            {
                "title": title,
                "journal": journal_title,
                "authors": authors,
                "pmcid": pmcid,
            }
        )

    return articles

In [35]:
attention = pd.read_csv("val_attention.csv.gz", index_col=0)
attention.columns = attention.index
attention

/var/folders/y3/ssnk1ytd3m5bjmrchh2lt74srg76p8/T/ipykernel_46111/158792900.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  attention = pd.read_csv("val_attention.csv.gz", index_col=0)

,740,752,755,757,762,1390,1895,3053,3061,3088,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.001354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354
752,0.000000,0.001354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354
755,0.000000,0.000000,0.001354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354
757,0.000000,0.000000,0.000000,0.001354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354
762,0.000000,0.000000,0.000000,0.000000,0.001354,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.001354,0.000000,0.000000,0.000000,0.000000
ZNRD1,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001354,0.000000,0.000000,0.000000
ZP3,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001354,0.000000,0.000000
ZSCAN18,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001354,0.000000
ZYX,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,0.001354,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001354

In [36]:
att_dg = attention.iloc[:1005, 1005+60:]
conv = dict(pd.read_csv("nsc_dti.csv", index_col=0)[["NSC", "Drug Name"]].values)

In [37]:
np.unique(attention.values)

array([0.        , 0.00135364])

In [32]:
for i in att_dg.index:
    tmp = att_dg.loc[i].sort_values(ascending=False).head(5)
    if tmp.iloc[0] != 0.0013536382:
        print(tmp)

0.0013536382

In [19]:
results = []
pmid_list = []
for drug in tqdm(att_dg.index):
    genes = list(att_dg.loc[drug].sort_values(ascending=False).head(5).index)
    if drug == 759263:
        print(genes)

    for gene in genes:

        d = conv[int(drug)]
        if d == "benzaldehyde (BEN)":
            d = "benzaldehyde"
        elif "Derivative" in d:
            d = d[:-11]

        if "ADA" == gene:
            gene = "adenosine deaminase"

        pmids = search_pubmed("{} AND {}".format(d, gene), max_results=300)
        pmid_list.append([drug, gene, pmids])
        if pmids != None:
            details = fetch_details(pmids)
            if details != None:
                details = details.decode("utf-8")
                res = pd.DataFrame(parse_pubmed_efetch(details))
                if len(res) > 0:
                    results.append(
                        [
                            drug,
                            conv[int(drug)],
                            gene,
                            len(pmids),
                            # len(
                            #     (
                            #         res[
                            #             res.journal.str.lower().isin(
                            #                 set(j_list["Title"].str.lower())
                            #             )
                            #         ]
                            #     )
                            # ),
                        ]
                    )
                else:
                    results.append([drug, conv[int(drug)], gene, len(pmids), 0])
            else:
                results.append([drug, conv[int(drug)], gene, len(pmids), 0])
        else:
            results.append([drug, conv[int(drug)], gene, 0, 0])

  0%|          | 0/1005 [00:00<?, ?it/s]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 1/1005 [00:05<1:26:10,  5.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 2/1005 [00:09<1:22:37,  4.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 3/1005 [00:16<1:37:45,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 4/1005 [00:21<1:30:59,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 5/1005 [00:28<1:39:58,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 6/1005 [00:33<1:33:31,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 7/1005 [00:40<1:40:00,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 8/1005 [00:45<1:33:51,  5.65s/it]

Error: Unable to fetch details from PubMed

  1%|          | 8/1005 [00:46<1:36:31,  5.81s/it]

KeyboardInterrupt:

In [21]:
results

[[740, 'METHOTREXATE', 'A2M', 1],
 [740, 'METHOTREXATE', 'PIM1', 8, 0],
 [740, 'METHOTREXATE', 'PLEC', 1],
 [740, 'METHOTREXATE', 'PLEK2', 0, 0],
 [740, 'METHOTREXATE', 'PLEKHG4', 0, 0],
 [752, '6-THIOGUANINE', 'A2M', 0, 0],
 [752, '6-THIOGUANINE', 'PIM1', 0, 0],
 [752, '6-THIOGUANINE', 'PLEC', 0, 0],
 [752, '6-THIOGUANINE', 'PLEK2', 0, 0],
 [752, '6-THIOGUANINE', 'PLEKHG4', 0, 0],
 [755, '6-MERCAPTOPURINE', 'A2M', 0, 0],
 [755, '6-MERCAPTOPURINE', 'PIM1', 0, 0],
 [755, '6-MERCAPTOPURINE', 'PLEC', 1],
 [755, '6-MERCAPTOPURINE', 'PLEK2', 0, 0],
 [755, '6-MERCAPTOPURINE', 'PLEKHG4', 0, 0],
 [757, 'Colchicine', 'A2M', 0, 0],
 [757, 'Colchicine', 'PIM1', 0, 0],
 [757, 'Colchicine', 'PLEC', 0, 0],
 [757, 'Colchicine', 'PLEK2', 0, 0],
 [757, 'Colchicine', 'PLEKHG4', 0, 0],
 [762, 'Nitrogen mustard', 'A2M', 1],
 [762, 'Nitrogen mustard', 'PIM1', 0, 0],
 [762, 'Nitrogen mustard', 'PLEC', 0, 0],
 [762, 'Nitrogen mustard', 'PLEK2', 0, 0],
 [762, 'Nitrogen mustard', 'PLEKHG4', 0, 0],
 [1390, 'Allopurinol', 'A2M', 0, 0],
 [1390, 'Allopurinol', 'PIM1', 0, 0],
 [1390, 'Allopurinol', 'PLEC', 1, 0],
 [1390, 'Allopurinol', 'PLEK2', 0, 0],
 [1390, 'Allopurinol', 'PLEKHG4', 0, 0],
 [1895, 'GUANAZOLE', 'A2M', 0, 0],
 [1895, 'GUANAZOLE', 'PIM1', 0, 0],
 [1895, 'GUANAZOLE', 'PLEC', 0, 0],
 [1895, 'GUANAZOLE', 'PLEK2', 0, 0],
 [1895, 'GUANAZOLE', 'PLEKHG4', 0, 0],
 [3053, 'Actinomycin D', 'A2M', 1, 0],
 [3053, 'Actinomycin D', 'PIM1', 0, 0],
 [3053, 'Actinomycin D', 'PLEC', 0, 0],
 [3053, 'Actinomycin D', 'PLEK2', 1],
 [3053, 'Actinomycin D', 'PLEKHG4', 0, 0]]

In [48]:
results = pd.DataFrame(results)
results.columns = ["NSC", "drug", "gene", "num"]
results

         NSC          drug                 gene  num  num in journals
0        740  METHOTREXATE                 ATIC   58               44
1        740  METHOTREXATE                 TYMS   65                0
2        740  METHOTREXATE                 DHFR  300              210
3        740  METHOTREXATE               MIR330    0                0
4        740  METHOTREXATE              SNORD16    0                0
...      ...           ...                  ...  ...              ...
1340  791785  Sapacitabine                  PGR    0                0
1341  791785  Sapacitabine                ZAP70    0                0
1342  791785  Sapacitabine  adenosine deaminase    0                0
1343  791785  Sapacitabine                EPHB6    0                0
1344  791785  Sapacitabine                  LCK    0                0

[1345 rows x 5 columns]

In [49]:
results.to_csv("result_all.csv", index=False)