In [2]:
import numpy as np
import optuna
import pandas as pd

In [30]:
name = "CTRP_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
study.trials_dataframe().dropna(subset=["values_0", "values_1", "values_2", "values_3"])

[I 2025-03-21 18:02:59,859] Using an existing study with name 'CTRP_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
1,1,0.827248,0.898631,0.900690,0.825767,2025-03-21 17:01:35.918887,2025-03-21 17:02:40.930843,0 days 00:01:05.011956,NaN,gelu,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
3,3,0.829236,0.901413,0.902569,0.828679,2025-03-21 17:01:55.921220,2025-03-21 17:02:32.177075,0 days 00:00:36.255855,NaN,swish,...,False,SGD,NaN,Step,10.0,NaN,0.000929,NaN,NaN,COMPLETE
5,5,0.825922,0.893055,0.900533,0.824217,2025-03-21 17:02:32.558040,2025-03-21 17:03:05.162223,0 days 00:00:32.604183,NaN,relu,...,NaN,Adam,NaN,Step,10.0,NaN,0.000007,NaN,NaN,COMPLETE
6,6,0.795433,0.836451,0.875571,0.785303,2025-03-21 17:02:40.958930,2025-03-21 17:02:50.278460,0 days 00:00:09.319530,NaN,gelu,...,NaN,AdamW,10.0,Plateau,NaN,0.000598,0.000087,NaN,NaN,COMPLETE
7,7,0.827489,0.899327,0.901437,0.826095,2025-03-21 17:02:50.305241,2025-03-21 17:03:30.046804,0 days 00:00:39.741563,NaN,relu,...,True,SGD,5.0,Plateau,NaN,0.006866,0.001877,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,1024,0.500000,0.899399,0.903018,0.000000,2025-03-21 17:58:11.590272,2025-03-21 18:01:02.736669,0 days 00:02:51.146397,NaN,relu,...,NaN,Adam,3.0,Plateau,NaN,0.000848,0.000036,NaN,NaN,COMPLETE
1025,1025,0.500000,0.853998,0.865429,0.666667,2025-03-21 17:58:19.647084,2025-03-21 18:01:06.223417,0 days 00:02:46.576333,NaN,gelu,...,True,SGD,3.0,Plateau,NaN,0.000326,0.000037,NaN,NaN,COMPLETE
1028,1028,0.734514,0.895230,0.899689,0.658661,2025-03-21 17:58:59.900140,2025-03-21 17:59:53.470012,0 days 00:00:53.569872,NaN,gelu,...,NaN,Adam,3.0,Plateau,NaN,0.001771,0.000676,NaN,NaN,COMPLETE
1029,1029,0.765064,0.901655,0.902658,0.715713,2025-03-21 17:59:00.044529,2025-03-21 18:01:13.266762,0 days 00:02:13.222233,NaN,gelu,...,NaN,Adam,3.0,Plateau,NaN,0.000940,0.000036,NaN,NaN,COMPLETE
1030,1030,0.822909,0.836450,0.874763,0.822256,2025-03-21 17:59:53.505051,2025-03-21 18:01:00.685823,0 days 00:01:07.180772,NaN,gelu,...,NaN,AdamW,4.0,Plateau,NaN,0.000964,0.000037,NaN,NaN,COMPLETE

In [31]:
name = "CTRP"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df = df[
    ~(
        (df["values_0"] == float("-inf"))
        | (df["values_1"] == float("-inf"))
        | (df["values_2"] == float("-inf"))
        | (df["values_3"] == float("-inf"))
    )
]
df.sort_values(["values_0", "values_1", "values_2", "values_3"], ascending=False)

[I 2025-03-21 18:03:00,805] Using an existing study with name 'CTRP' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
274,274,0.833394,0.899757,0.903034,0.834342,2025-03-21 17:21:17.267455,2025-03-21 17:21:45.621436,0 days 00:00:28.353981,NaN,relu,...,True,SGD,NaN,Step,29.0,NaN,0.000228,NaN,NaN,COMPLETE
277,277,0.832249,0.899742,0.901843,0.836293,2025-03-21 17:21:21.810980,2025-03-21 17:21:44.547949,0 days 00:00:22.736969,NaN,relu,...,True,SGD,NaN,Step,26.0,NaN,0.000233,NaN,NaN,COMPLETE
264,264,0.831465,0.899856,0.901327,0.835886,2025-03-21 17:21:07.992506,2025-03-21 17:21:28.531674,0 days 00:00:20.539168,NaN,relu,...,True,SGD,NaN,Step,27.0,NaN,0.000248,NaN,NaN,COMPLETE
309,309,0.831044,0.895041,0.897605,0.833452,2025-03-21 17:22:08.830994,2025-03-21 17:22:35.466230,0 days 00:00:26.635236,NaN,relu,...,True,SGD,NaN,None,NaN,NaN,0.000152,NaN,NaN,COMPLETE
260,260,0.830019,0.899362,0.902367,0.831953,2025-03-21 17:20:54.637168,2025-03-21 17:21:21.287107,0 days 00:00:26.649939,NaN,relu,...,True,SGD,NaN,Step,27.0,NaN,0.000225,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,323,0.500000,0.845001,0.832051,0.666667,2025-03-21 17:24:17.969590,2025-03-21 17:25:41.027639,0 days 00:01:23.058049,NaN,relu,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
327,327,0.500000,0.820802,0.848188,0.000000,2025-03-21 17:24:24.256077,2025-03-21 17:25:46.896233,0 days 00:01:22.640156,NaN,relu,...,True,SGD,NaN,None,NaN,NaN,0.000107,NaN,NaN,COMPLETE
325,325,0.500000,0.586537,0.632665,0.666667,2025-03-21 17:24:21.723922,2025-03-21 17:25:45.638026,0 days 00:01:23.914104,NaN,relu,...,True,SGD,NaN,None,NaN,NaN,0.000101,NaN,NaN,COMPLETE
57,57,0.500000,0.493812,0.478909,0.000000,2025-03-21 17:11:53.380862,2025-03-21 17:12:14.938373,0 days 00:00:21.557511,27.0,relu,...,True,SGD,NaN,Cosine,NaN,NaN,0.000008,NaN,NaN,COMPLETE
322,322,0.491022,0.455247,0.419131,0.078944,2025-03-21 17:24:15.892943,2025-03-21 17:25:35.009389,0 days 00:01:19.116446,NaN,relu,...,True,SGD,NaN,None,NaN,NaN,0.000131,NaN,NaN,COMPLETE