In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_3355565/172045269.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-15 13:25:00,501] Using an existing study with name 'GATv2' instead of creating a new one.

(32, 23)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
229,0.6675 (± 0.0035),0.7233 (± 0.0023),0.73 (± 0.0036),0.6675 (± 0.0035),0.6609 (± 0.0138),0.6493 (± 0.0386),0.6746 (± 0.0126),3846.0,relu,0.35,0.30,8200,2,589,164,157,0.000050,AdamW,Cosine,0.000730
226,0.6641 (± 0.0045),0.7232 (± 0.0032),0.7306 (± 0.0028),0.6641 (± 0.0045),0.6296 (± 0.0196),0.5725 (± 0.0415),0.7022 (± 0.0175),NaN,relu,0.20,0.15,4000,3,285,137,39,0.000243,Adam,None,0.000557
112,0.6675 (± 0.0038),0.7224 (± 0.004),0.7298 (± 0.0042),0.6675 (± 0.0038),0.6456 (± 0.0085),0.6061 (± 0.0233),0.6915 (± 0.0129),NaN,gelu,0.45,0.10,8600,3,970,82,56,0.000454,Adam,None,0.000067
319,0.6529 (± 0.0121),0.7223 (± 0.0014),0.7292 (± 0.0031),0.6529 (± 0.0121),0.5852 (± 0.0389),0.4932 (± 0.0603),0.7265 (± 0.0163),NaN,gelu,0.35,0.50,3600,2,675,112,38,0.000056,Adam,None,0.000107
455,0.6669 (± 0.0034),0.722 (± 0.0028),0.73 (± 0.0018),0.6669 (± 0.0034),0.6475 (± 0.007),0.6121 (± 0.0143),0.6874 (± 0.0051),NaN,relu,0.10,0.45,5700,5,525,74,59,0.000607,AdamW,None,0.000017

In [3]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-15 13:25:01,512] Using an existing study with name 'Transformer' instead of creating a new one.

(30, 23)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
64,0.6615 (± 0.0109),0.7235 (± 0.0017),0.7298 (± 0.0018),0.6615 (± 0.0109),0.6369 (± 0.0536),0.6065 (± 0.1187),0.6891 (± 0.0387),816.0,gelu,0.50,0.40,2700,7,293,68,53,0.001674,Adam,Cosine,0.001130
154,0.6696 (± 0.0046),0.723 (± 0.0017),0.7307 (± 0.0022),0.6696 (± 0.0046),0.6608 (± 0.0119),0.6442 (± 0.0278),0.679 (± 0.0087),1099.0,gelu,0.15,0.50,5400,2,646,80,57,0.000462,AdamW,Cosine,0.000002
140,0.6655 (± 0.0052),0.7229 (± 0.002),0.7297 (± 0.0024),0.6655 (± 0.0052),0.6435 (± 0.0098),0.6041 (± 0.023),0.6892 (± 0.0131),NaN,gelu,0.35,0.25,2400,2,623,118,34,0.000013,AdamW,None,0.006016
0,0.6675 (± 0.0048),0.7228 (± 0.0017),0.7308 (± 0.0023),0.6675 (± 0.0048),0.6427 (± 0.0111),0.5985 (± 0.0224),0.6945 (± 0.0065),2229.0,relu,0.35,0.15,9600,2,261,178,139,0.000461,AdamW,Cosine,0.005249
243,0.6665 (± 0.0063),0.7226 (± 0.0018),0.7298 (± 0.0025),0.6665 (± 0.0063),0.6451 (± 0.0148),0.6069 (± 0.0285),0.6892 (± 0.0055),NaN,relu,0.25,0.25,3000,2,708,133,120,0.000611,AdamW,None,0.002530

In [4]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-15 13:25:02,812] Using an existing study with name 'GAT' instead of creating a new one.

(39, 23)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
166,0.6712 (± 0.0043),0.7244 (± 0.0018),0.7318 (± 0.0021),0.6712 (± 0.0043),0.6583 (± 0.007),0.6336 (± 0.0149),0.6853 (± 0.0067),2003.0,relu,0.35,0.40,6000,5,730,82,72,0.001447,Adam,Cosine,0.000023
132,0.669 (± 0.0038),0.724 (± 0.0014),0.7312 (± 0.002),0.669 (± 0.0038),0.6483 (± 0.0174),0.6116 (± 0.0422),0.6919 (± 0.0144),NaN,gelu,0.40,0.25,8600,4,675,68,57,0.000127,Adam,None,0.000056
119,0.6692 (± 0.0051),0.7238 (± 0.0017),0.7309 (± 0.0027),0.6692 (± 0.0051),0.6548 (± 0.0106),0.6281 (± 0.0228),0.6846 (± 0.0082),NaN,relu,0.15,0.50,3100,4,326,81,81,0.002323,Adam,None,0.000015
58,0.669 (± 0.0029),0.7231 (± 0.0016),0.7305 (± 0.0017),0.669 (± 0.0029),0.6798 (± 0.0111),0.7037 (± 0.0389),0.6589 (± 0.0145),3746.0,relu,0.50,0.50,9700,3,735,90,52,0.000106,AdamW,Cosine,0.000056
147,0.6619 (± 0.0115),0.7229 (± 0.0023),0.7306 (± 0.0035),0.6619 (± 0.0115),0.6172 (± 0.0362),0.5491 (± 0.0638),0.7107 (± 0.015),2515.0,gelu,0.10,0.50,8900,2,754,244,114,0.000045,AdamW,Cosine,0.000140

In [5]:
method = "MPNN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-15 13:25:03,527] Using an existing study with name 'MPNN' instead of creating a new one.

KeyError: ['values_0', 'values_1', 'values_2', 'values_3']

In [ ]:
method = "GCN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()