In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_253407/172045269.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-10 14:39:56,209] Using an existing study with name 'GATv2' instead of creating a new one.

(998, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3947,0.6027 (± 0.015),0.654 (± 0.0194),0.6592 (± 0.0133),0.6027 (± 0.015),0.5454 (± 0.0481),0.4818 (± 0.0746),0.6358 (± 0.0072),NaN,gelu,0.10,0.1,2,262,198,150,0.000244,AdamW,None,0.000012
3641,0.6001 (± 0.0082),0.6506 (± 0.0113),0.6577 (± 0.009),0.6001 (± 0.0082),0.5315 (± 0.0665),0.4648 (± 0.1048),0.6459 (± 0.0428),NaN,gelu,0.10,0.1,4,305,147,69,0.000389,AdamW,None,0.000015
859,0.6002 (± 0.0166),0.6504 (± 0.015),0.6571 (± 0.0143),0.6002 (± 0.0166),0.5399 (± 0.073),0.4819 (± 0.1153),0.6367 (± 0.0288),NaN,relu,0.30,0.4,2,604,293,135,0.000164,AdamW,None,0.000007
3846,0.5962 (± 0.016),0.6495 (± 0.0159),0.6569 (± 0.015),0.5962 (± 0.016),0.5019 (± 0.059),0.4129 (± 0.0759),0.6545 (± 0.0239),NaN,relu,0.20,0.1,2,353,319,117,0.000250,AdamW,None,0.000047
3961,0.5958 (± 0.0159),0.6485 (± 0.0116),0.6563 (± 0.0088),0.5958 (± 0.0159),0.5099 (± 0.085),0.4351 (± 0.1209),0.6493 (± 0.0346),NaN,relu,0.25,0.1,3,305,120,56,0.000389,AdamW,None,0.000008

In [3]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-10 14:39:59,425] Using an existing study with name 'Transformer' instead of creating a new one.

(1152, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3646,0.6655 (± 0.0047),0.7168 (± 0.0045),0.7251 (± 0.0036),0.6655 (± 0.0047),0.655 (± 0.0128),0.6358 (± 0.0294),0.6763 (± 0.008),NaN,gelu,0.15,0.40,2,437,351,192,0.000356,AdamW,None,0.001098
3835,0.6622 (± 0.0039),0.7167 (± 0.003),0.7256 (± 0.001),0.6622 (± 0.0039),0.6452 (± 0.0284),0.6187 (± 0.0724),0.6805 (± 0.0236),NaN,gelu,0.10,0.10,4,331,117,87,0.000515,AdamW,None,0.000600
2970,0.6609 (± 0.0043),0.7167 (± 0.001),0.7248 (± 0.001),0.6609 (± 0.0043),0.6448 (± 0.0337),0.6216 (± 0.0841),0.6785 (± 0.0277),NaN,gelu,0.10,0.10,5,325,84,73,0.000515,Adam,None,0.000005
1700,0.6565 (± 0.0125),0.7166 (± 0.006),0.7224 (± 0.0043),0.6565 (± 0.0125),0.6249 (± 0.0478),0.5808 (± 0.0955),0.6885 (± 0.0264),NaN,gelu,0.10,0.15,4,998,84,84,0.000356,AdamW,None,0.000241
2717,0.6628 (± 0.0046),0.7164 (± 0.0021),0.7247 (± 0.0025),0.6628 (± 0.0046),0.6463 (± 0.026),0.6196 (± 0.064),0.6804 (± 0.0208),NaN,gelu,0.10,0.15,3,887,187,67,0.000271,Adam,None,0.000010

In [4]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-10 14:40:02,755] Using an existing study with name 'GAT' instead of creating a new one.

(886, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3571,0.6124 (± 0.0085),0.6516 (± 0.0081),0.6652 (± 0.0084),0.6124 (± 0.0085),0.5943 (± 0.0286),0.5711 (± 0.0616),0.6239 (± 0.0164),NaN,gelu,0.15,0.2,5,377,110,87,0.000735,AdamW,None,0.000102
3786,0.5927 (± 0.0146),0.6499 (± 0.0106),0.6602 (± 0.0098),0.5927 (± 0.0146),0.4856 (± 0.0793),0.3963 (± 0.1096),0.6599 (± 0.0306),NaN,relu,0.15,0.3,5,265,111,48,0.000735,AdamW,None,0.000007
2654,0.5975 (± 0.0097),0.6475 (± 0.0021),0.6596 (± 0.0034),0.5975 (± 0.0097),0.5168 (± 0.046),0.4352 (± 0.0713),0.6463 (± 0.0142),NaN,relu,0.15,0.2,7,455,72,71,0.000735,AdamW,None,0.000007
2065,0.5898 (± 0.0198),0.6473 (± 0.0061),0.6603 (± 0.0079),0.5898 (± 0.0198),0.4761 (± 0.1025),0.3913 (± 0.1383),0.6589 (± 0.0346),NaN,gelu,0.15,0.1,4,326,85,71,0.000735,AdamW,None,0.000102
880,0.5947 (± 0.013),0.6472 (± 0.0051),0.658 (± 0.0072),0.5947 (± 0.013),0.5056 (± 0.0721),0.4247 (± 0.1005),0.6488 (± 0.0261),NaN,gelu,0.10,0.2,7,277,75,54,0.000735,Adam,None,0.000002

In [ ]:
# method = "MPNN"
# study = optuna.create_study(
#     storage=f"sqlite:///{method}_small.sqlite3",
#     study_name=method,
#     load_if_exists=True,
# )
# tmp = study.trials_dataframe().dropna(
#     subset=["values_0", "values_1", "values_2", "values_3"]
# )
# tmp = tmp[[i for i in tmp.columns if "params" in i]]
# df = (
#     study.trials_dataframe()
#     .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
#     .iloc[:, 20:-2]
# )
# df.columns = [i.replace("user_attrs_", "") for i in df.columns]
# print(df.shape)
# parsed_df = get_parsed_df(df)
# parsed_df = pd.concat([parsed_df, tmp], axis=1)
# parsed_df.sort_values("AUPR", ascending=False).head()

In [9]:
method = "GCN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 19:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-10 14:40:39,115] Using an existing study with name 'GCN' instead of creating a new one.

(10000, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
6259,0.5023 (± 0.0051),0.565 (± 0.0341),0.5637 (± 0.0425),0.5023 (± 0.0051),0.0336 (± 0.0752),0.0197 (± 0.0442),0.113 (± 0.2526),21.0,gelu,0.10,0.45,680,300,63,0.000012,Adam,Cosine,0.000702
8767,0.5087 (± 0.0082),0.5586 (± 0.0398),0.5629 (± 0.0375),0.5087 (± 0.0082),0.1459 (± 0.1916),0.1145 (± 0.1775),0.354 (± 0.3263),33.0,relu,0.10,0.25,527,298,221,0.000018,AdamW,Cosine,0.000862
820,0.5281 (± 0.0075),0.5583 (± 0.0422),0.5574 (± 0.0486),0.5281 (± 0.0075),0.4826 (± 0.223),0.5781 (± 0.4021),0.5663 (± 0.0709),NaN,gelu,0.50,0.15,866,406,55,0.000018,AdamW,None,0.007305
1870,0.5058 (± 0.012),0.5561 (± 0.0419),0.5666 (± 0.0376),0.5058 (± 0.012),0.0326 (± 0.0637),0.0179 (± 0.0353),0.4768 (± 0.4552),32.0,gelu,0.25,0.35,926,430,76,0.000012,Adam,Cosine,0.000315
7022,0.5074 (± 0.0082),0.5557 (± 0.0362),0.5636 (± 0.0368),0.5074 (± 0.0082),0.1157 (± 0.1048),0.0701 (± 0.0649),0.5095 (± 0.3105),31.0,gelu,0.10,0.35,948,486,47,0.000018,AdamW,Cosine,0.000315