In [1]:
import optuna

In [12]:
name = "GDSC1_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
df = df[~((df['values_0'] == float('-inf')) | (df['values_1'] == float('-inf')) | 
          (df['values_2'] == float('-inf')) | (df['values_3'] == float('-inf')))]
df

[I 2025-03-21 18:44:15,455] Using an existing study with name 'GDSC1_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
1,1,0.875669,0.931129,0.945648,0.877439,2025-03-21 18:25:13.712491,2025-03-21 18:26:55.139959,0 days 00:01:41.427468,NaN,swish,...,NaN,AdamW,NaN,Step,17.0,NaN,0.000038,NaN,NaN,COMPLETE
6,6,0.645634,0.925831,0.923206,0.737631,2025-03-21 18:25:19.279105,2025-03-21 18:25:36.660308,0 days 00:00:17.381203,49.0,swish,...,NaN,Adam,NaN,Cosine,NaN,NaN,0.000012,NaN,NaN,COMPLETE
7,7,0.882771,0.949777,0.950828,0.881292,2025-03-21 18:25:19.327527,2025-03-21 18:27:01.595067,0 days 00:01:42.267540,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000028,NaN,NaN,COMPLETE
11,11,0.874272,0.951274,0.954906,0.867809,2025-03-21 18:25:26.229550,2025-03-21 18:27:55.464949,0 days 00:02:29.235399,NaN,gelu,...,True,SGD,NaN,Step,21.0,NaN,0.000004,NaN,NaN,COMPLETE
12,12,0.877299,0.947370,0.948630,0.873500,2025-03-21 18:30:46.999823,2025-03-21 18:33:29.871687,0 days 00:02:42.871864,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
13,13,0.881374,0.945055,0.949001,0.881305,2025-03-21 18:30:47.003917,2025-03-21 18:33:30.925138,0 days 00:02:43.921221,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000003,NaN,NaN,COMPLETE
14,14,0.876251,0.949743,0.953679,0.870603,2025-03-21 18:30:47.011546,2025-03-21 18:33:36.703276,0 days 00:02:49.691730,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000002,NaN,NaN,COMPLETE
15,15,0.876251,0.951462,0.952468,0.870350,2025-03-21 18:30:47.025988,2025-03-21 18:33:21.833189,0 days 00:02:34.807201,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000002,NaN,NaN,COMPLETE
16,16,0.885215,0.950022,0.953682,0.883286,2025-03-21 18:30:47.003492,2025-03-21 18:33:31.183439,0 days 00:02:44.179947,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000003,NaN,NaN,COMPLETE
17,17,0.876717,0.952176,0.952313,0.871027,2025-03-21 18:30:47.040401,2025-03-21 18:33:31.708948,0 days 00:02:44.668547,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
18,18,0.871013,0.943084,0.951370,0.863815,2025-03-21 18:30:47.051161,2025-03-21 18:33:28.470179,0 days 00:02:41.419018,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
19,19,0.872875,0.947380,0.952477,0.866144,2025-03-21 18:30:47.062552,2025-03-21 18:33:30.947144,0 days 00:02:43.884592,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000002,NaN,NaN,COMPLETE
20,20,0.880210,0.945908,0.949053,0.879324,2025-03-21 18:30:47.011216,2025-03-21 18:33:30.058050,0 days 00:02:43.046834,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000004,NaN,NaN,COMPLETE
21,21,0.868102,0.948395,0.952974,0.859377,2025-03-21 18:30:47.081334,2025-03-21 18:33:29.693477,0 days 00:02:42.612143,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
22,22,0.855064,0.944067,0.942289,0.841945,2025-03-21 18:33:21.911238,2025-03-21 18:36:11.918340,0 days 00:02:50.007102,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000001,NaN,NaN,COMPLETE
23,23,0.543772,0.617516,0.631396,0.275735,2025-03-21 18:33:28.540443,2025-03-21 18:34:54.851623,0 days 00:01:26.311180,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000006,NaN,NaN,COMPLETE
34,34,0.876368,0.946698,0.951650,0.870929,2025-03-21 18:33:36.324271,2025-03-21 18:37:47.932843,0 days 00:04:11.608572,20.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000004,NaN,NaN,COMPLETE
35,35,0.880210,0.944614,0.949336,0.880168,2025-03-21 18:33:36.355177,2025-03-21 18:37:44.136080,0 days 00:04:07.780903,23.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000003,NaN,NaN,COMPLETE
36,36,0.879511,0.941983,0.949920,0.875855,2025-03-21 18:33:36.760943,2025-03-21 18:36:23.575598,0 days 00:02:46.814655,21.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000004,NaN,NaN,COMPLETE
37,37,0.876019,0.943751,0.951323,0.870799,2025-03-21 18:33:36.930279,2025-03-21 18:36:20.825914,0 days 00:02:43.895635,22.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000004,NaN,NaN,COMPLETE
38,38,0.871362,0.949069,0.949209,0.864000,2025-03-21 18:33:38.505975,2025-03-21 18:36:15.779333,0 days 00:02:37.273358,23.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000153,NaN,NaN,COMPLETE
39,39,0.868917,0.944527,0.951416,0.860919,2025-03-21 18:33:38.533834,2025-03-21 18:36:22.118582,0 days 00:02:43.584748,20.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000132,NaN,NaN,COMPLETE
40,40,0.880093,0.947734,0.951429,0.878164,2025-03-21 18:33:40.885972,2025-03-21 18:36:27.409474,0 days 00:02:46.523502,21.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000227,NaN,NaN,COMPLETE
41,41,0.882654,0.947582,0.951193,0.882845,2025-03-21 18:33:40.910921,2025-03-21 18:36:23.994422,0 days 00:02:43.083501,20.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.009144,NaN,NaN,COMPLETE
42,42,0.879627,0.950797,0.952694,0.875631,2025-03-21 18:34:54.933192,2025-03-21 18:37:42.324475,0 days 00:02:47.391283,23.0,swish,...,False,SGD,NaN,Cosine,NaN,NaN,0.000212,NaN,NaN,COMPLETE
43,43,0.874622,0.950051,0.953645,0.868482,2025-03-21 18:36:11.956236,2025-03-21 18:38:57.320284,0 days 00:02:45.364048,NaN,swish,...,False,SGD,NaN,Step,11.0,NaN,0.000098,NaN,NaN,COMPLETE
52,52,0.871013,0.947905,0.952807,0.864082,2025-03-21 18:36:27.463650,2025-03-21 18:38:01.918599,0 days 00:01:34.454949,NaN,swish,...,True,SGD,NaN,None,NaN,NaN,0.000037,NaN,NaN,COMPLETE
56,56,0.565658,0.897544,0.875613,0.233724,2025-03-21 18:37:42.436315,2025-03-21 18:37:56.887907,0 days 00:00:14.451592,NaN,relu,...,NaN,AdamW,NaN,None,NaN,NaN,0.000002,NaN,NaN,COMPLETE
57,57,0.500000,0.728444,0.785720,0.666667,2025-03-21 18:37:44.189804,2025-03-21 18:37:58.272808,0 days 00:00:14.083004,NaN,relu,...,NaN,AdamW,NaN,None,NaN,NaN,0.000002,NaN,NaN,COMPLETE

In [13]:
name = "GDSC1"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
df = df[~((df['values_0'] == float('-inf')) | (df['values_1'] == float('-inf')) | 
          (df['values_2'] == float('-inf')) | (df['values_3'] == float('-inf')))]
df

[I 2025-03-21 18:44:16,322] Using an existing study with name 'GDSC1' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,user_attrs_status,state
0,0,0.853783,0.947458,0.945834,0.840122,2025-03-21 18:13:21.033223,2025-03-21 18:13:41.050421,0 days 00:00:20.017198,28.0,relu,...,True,SGD,NaN,Cosine,NaN,NaN,0.000496,NaN,NaN,COMPLETE
1,1,0.860070,0.950797,0.950630,0.848194,2025-03-21 18:13:21.038567,2025-03-21 18:15:18.080777,0 days 00:01:57.042210,NaN,swish,...,NaN,Adam,4.0,Plateau,NaN,0.003882,0.000037,NaN,NaN,COMPLETE
2,2,0.667637,0.932984,0.924931,0.505456,2025-03-21 18:13:21.042889,2025-03-21 18:13:41.241211,0 days 00:00:20.198322,29.0,relu,...,NaN,AdamW,NaN,Cosine,NaN,NaN,0.001342,NaN,NaN,COMPLETE
9,9,0.865076,0.948642,0.948125,0.854744,2025-03-21 18:13:23.199409,2025-03-21 18:14:59.262323,0 days 00:01:36.062914,NaN,gelu,...,True,SGD,NaN,None,NaN,NaN,0.000285,NaN,NaN,COMPLETE
10,10,0.861932,0.952185,0.951129,0.850592,2025-03-21 18:13:23.532275,2025-03-21 18:14:30.263932,0 days 00:01:06.731657,NaN,gelu,...,NaN,AdamW,NaN,Step,24.0,NaN,0.000624,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,355,0.867520,0.948610,0.948562,0.858634,2025-03-21 18:41:54.246700,2025-03-21 18:42:33.787412,0 days 00:00:39.540712,NaN,relu,...,NaN,Adam,NaN,Step,27.0,NaN,0.000004,NaN,NaN,COMPLETE
356,356,0.856228,0.947454,0.947472,0.843532,2025-03-21 18:41:55.807819,2025-03-21 18:42:34.369924,0 days 00:00:38.562105,NaN,gelu,...,NaN,Adam,NaN,Step,27.0,NaN,0.000628,NaN,NaN,COMPLETE
360,360,0.852503,0.945185,0.944214,0.838660,2025-03-21 18:42:03.670281,2025-03-21 18:42:19.083996,0 days 00:00:15.413715,25.0,gelu,...,NaN,Adam,NaN,Cosine,NaN,NaN,0.000023,NaN,NaN,COMPLETE
361,361,0.865425,0.949417,0.949452,0.855174,2025-03-21 18:42:04.614542,2025-03-21 18:42:16.064273,0 days 00:00:11.449731,26.0,gelu,...,NaN,Adam,NaN,Cosine,NaN,NaN,0.000606,NaN,NaN,COMPLETE
362,362,0.857858,0.949139,0.949059,0.845541,2025-03-21 18:42:05.767313,2025-03-21 18:42:17.251053,0 days 00:00:11.483740,25.0,gelu,...,NaN,Adam,NaN,Cosine,NaN,NaN,0.000603,NaN,NaN,COMPLETE