In [2]:
import optuna

In [3]:
name = "GDSC1_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df

[I 2025-03-31 13:04:53,391] Using an existing study with name 'GDSC1_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
0,0,0.838276,0.956796,0.958168,0.814906,2025-03-28 13:29:05.640265,2025-03-28 13:40:54.319950,0 days 00:11:48.679685,NaN,swish,...,0.000029,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000002,COMPLETE
1,1,0.840220,0.941538,0.946478,0.822532,2025-03-28 13:40:54.360760,2025-03-28 13:58:26.760115,0 days 00:17:32.399355,NaN,swish,...,0.000147,NaN,NaN,Adam,5.0,Plateau,NaN,0.001525,0.000122,COMPLETE
2,2,0.824396,0.955090,0.956713,0.794337,2025-03-28 13:46:35.461294,2025-03-28 13:56:19.266781,0 days 00:09:43.805487,NaN,relu,...,0.000020,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000090,COMPLETE
4,4,0.542792,0.803894,0.793972,0.133394,2025-03-28 13:46:36.347021,2025-03-28 13:47:25.533104,0 days 00:00:49.186083,NaN,gelu,...,0.006171,NaN,NaN,Adam,NaN,Step,12.0,NaN,0.000002,COMPLETE
5,5,0.697711,0.947428,0.948868,0.482821,2025-03-28 13:46:37.115233,2025-03-28 13:47:29.272200,0 days 00:00:52.156967,NaN,relu,...,0.000600,NaN,NaN,AdamW,5.0,Plateau,NaN,0.000156,0.000152,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,314,0.860029,0.954162,0.956707,0.847243,2025-03-29 13:35:20.402159,2025-03-29 13:40:03.145333,0 days 00:04:42.743174,NaN,swish,...,0.000436,NaN,NaN,AdamW,10.0,Plateau,NaN,0.002090,0.004472,COMPLETE
315,315,0.862617,0.952511,0.956022,0.851290,2025-03-29 13:40:03.180747,2025-03-29 13:44:46.201230,0 days 00:04:43.020483,NaN,swish,...,0.000508,NaN,NaN,AdamW,10.0,Plateau,NaN,0.000172,0.004449,COMPLETE
316,316,0.818916,0.953178,0.955859,0.786579,2025-03-29 13:44:46.236840,2025-03-29 13:48:49.502265,0 days 00:04:03.265425,NaN,gelu,...,0.000679,NaN,NaN,Adam,10.0,Plateau,NaN,0.000169,0.004878,COMPLETE
317,317,0.699801,0.944584,0.948212,0.512942,2025-03-29 13:48:49.538524,2025-03-29 13:52:09.543029,0 days 00:03:20.004505,38.0,swish,...,0.000601,0.923505,True,SGD,NaN,Cosine,NaN,NaN,0.000001,COMPLETE
319,319,0.835668,0.944791,0.948539,0.814571,2025-03-29 13:52:11.653258,2025-03-29 13:54:32.112601,0 days 00:02:20.459343,NaN,gelu,...,0.000556,0.898090,False,SGD,NaN,Step,26.0,NaN,0.002311,COMPLETE

In [4]:
tmp = df.loc[df[["values_0", "values_1", "values_2", "values_3"]].max(axis=1).sort_values(ascending=False).index]
tmp[tmp['params_gnn_layer'] == 'GAT'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
114,114,0.830902,0.957527,0.959105,0.803482,2025-03-28 17:07:49.039891,2025-03-28 17:38:57.451579,0 days 00:31:08.411688,NaN,gelu,...,0.000668,NaN,NaN,Adam,NaN,None,NaN,NaN,0.001313,COMPLETE
67,67,0.835346,0.957297,0.958818,0.810741,2025-03-28 16:06:24.783250,2025-03-28 16:13:43.597784,0 days 00:07:18.814534,NaN,gelu,...,0.000445,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000459,COMPLETE
33,33,0.830041,0.957375,0.958646,0.802437,2025-03-28 15:16:48.510132,2025-03-28 15:46:37.384874,0 days 00:29:48.874742,20.0,gelu,...,0.000315,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.003264,COMPLETE
222,222,0.834623,0.956704,0.958261,0.809133,2025-03-29 03:43:48.715061,2025-03-29 04:07:54.352469,0 days 00:24:05.637408,NaN,relu,...,0.000732,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000003,COMPLETE
173,173,0.836283,0.956579,0.957953,0.811929,2025-03-28 21:43:56.955996,2025-03-28 21:53:37.844813,0 days 00:09:40.888817,40.0,swish,...,0.000426,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000096,COMPLETE

In [5]:
tmp[tmp['params_gnn_layer'] == 'GATv2'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
166,166,0.833402,0.958313,0.959405,0.807129,2025-03-28 21:05:11.665447,2025-03-28 21:41:57.267636,0 days 00:36:45.602189,NaN,swish,...,0.000501,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000057,COMPLETE
167,167,0.845494,0.958141,0.959211,0.825151,2025-03-28 21:07:22.654383,2025-03-28 21:43:56.918966,0 days 00:36:34.264583,NaN,swish,...,0.000159,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000059,COMPLETE
220,220,0.811238,0.957885,0.959070,0.771829,2025-03-29 03:34:19.777033,2025-03-29 03:49:02.957921,0 days 00:14:43.180888,NaN,relu,...,0.000601,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000003,COMPLETE
147,147,0.829534,0.957782,0.958952,0.801613,2025-03-28 18:29:53.785399,2025-03-28 18:58:43.784577,0 days 00:28:49.999178,44.0,swish,...,0.000229,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000071,COMPLETE
168,168,0.844039,0.957694,0.958730,0.823269,2025-03-28 21:10:12.313939,2025-03-28 21:46:49.608707,0 days 00:36:37.294768,NaN,swish,...,0.000150,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000056,COMPLETE

In [6]:
tmp[tmp['params_gnn_layer'] == 'Transformer'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
158,158,0.844361,0.960730,0.961217,0.822598,2025-03-28 20:12:15.739846,2025-03-28 20:46:28.449070,0 days 00:34:12.709224,NaN,swish,...,0.000295,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000040,COMPLETE
157,157,0.849870,0.960354,0.960984,0.830949,2025-03-28 20:06:57.044411,2025-03-28 20:41:09.843734,0 days 00:34:12.799323,NaN,swish,...,0.000321,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000053,COMPLETE
146,146,0.845709,0.960506,0.960954,0.824598,2025-03-28 18:17:08.022476,2025-03-28 18:51:11.077375,0 days 00:34:03.054899,NaN,gelu,...,0.000127,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.001937,COMPLETE
210,210,0.854197,0.959923,0.960871,0.836750,2025-03-29 03:00:10.089566,2025-03-29 03:34:13.982489,0 days 00:34:03.892923,NaN,relu,...,0.000415,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000004,COMPLETE
226,226,0.853894,0.960223,0.960854,0.836289,2025-03-29 04:07:56.125572,2025-03-29 04:41:52.891602,0 days 00:33:56.766030,NaN,relu,...,0.000427,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000004,COMPLETE

In [6]:
df.params_gnn_layer.value_counts()

params_gnn_layer
Transformer    112
GAT             24
GATv2           18
Name: count, dtype: int64

In [7]:
name = "GDSC1"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
df

[I 2025-03-31 13:06:58,549] Using an existing study with name 'GDSC1' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
1,1,0.523081,0.912071,0.906838,0.075267,2025-03-28 13:30:49.358333,2025-03-28 13:37:49.102074,0 days 00:06:59.743741,NaN,gelu,...,0.000013,0.932008,True,SGD,7.0,Plateau,NaN,0.001305,0.000309,COMPLETE
2,2,0.505773,0.947164,0.947692,0.021865,2025-03-28 13:30:49.383556,2025-03-28 13:33:13.675938,0 days 00:02:24.292382,33.0,swish,...,0.002738,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000005,COMPLETE
3,3,0.506427,0.767329,0.762145,0.024574,2025-03-28 13:30:49.400896,2025-03-28 13:45:47.811355,0 days 00:14:58.410459,NaN,swish,...,0.000039,0.828791,True,SGD,7.0,Plateau,NaN,0.000437,0.000063,COMPLETE
8,8,0.784553,0.947625,0.948610,0.734621,2025-03-28 13:30:52.062468,2025-03-28 13:49:11.009027,0 days 00:18:18.946559,NaN,gelu,...,0.000093,0.825836,True,SGD,NaN,None,NaN,NaN,0.000012,COMPLETE
9,9,0.548281,0.938828,0.938386,0.131651,2025-03-28 13:30:53.933713,2025-03-28 14:01:52.113270,0 days 00:30:58.179557,NaN,swish,...,0.000129,NaN,NaN,Adam,6.0,Plateau,NaN,0.001232,0.000008,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,611,0.691567,0.942432,0.942630,0.505528,2025-03-29 12:34:59.116107,2025-03-29 12:43:50.844196,0 days 00:08:51.728089,NaN,swish,...,0.004801,NaN,NaN,Adam,9.0,Plateau,NaN,0.000133,0.000005,COMPLETE
612,612,0.736492,0.941351,0.941157,0.604031,2025-03-29 12:35:56.988489,2025-03-29 12:44:34.933370,0 days 00:08:37.944881,NaN,swish,...,0.004653,NaN,NaN,Adam,9.0,Plateau,NaN,0.000131,0.000008,COMPLETE
613,613,0.804021,0.948429,0.950294,0.766225,2025-03-29 12:37:03.442366,2025-03-29 12:43:52.260511,0 days 00:06:48.818145,NaN,swish,...,0.001540,NaN,NaN,Adam,9.0,Plateau,NaN,0.000139,0.000005,COMPLETE
614,614,0.780244,0.947419,0.949298,0.724028,2025-03-29 12:37:25.013959,2025-03-29 12:44:15.798119,0 days 00:06:50.784160,NaN,swish,...,0.001549,NaN,NaN,AdamW,9.0,Plateau,NaN,0.000519,0.000002,COMPLETE
615,615,0.595048,0.943534,0.943141,0.260179,2025-03-29 12:38:00.548435,2025-03-29 12:45:13.832333,0 days 00:07:13.283898,NaN,swish,...,0.005758,NaN,NaN,Adam,9.0,Plateau,NaN,0.000420,0.009952,COMPLETE

In [8]:
tmp = df.loc[df[["values_0", "values_1", "values_2", "values_3"]].max(axis=1).sort_values(ascending=False).index]
tmp[tmp['params_gnn_layer'] == 'MPNN'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
580,580,0.840464,0.953156,0.951228,0.818423,2025-03-29 11:46:14.816283,2025-03-29 12:36:48.125937,0 days 00:50:33.309654,NaN,gelu,...,0.000524,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000374,COMPLETE
139,139,0.829114,0.952970,0.952494,0.802527,2025-03-28 15:30:20.549456,2025-03-28 16:12:44.300903,0 days 00:42:23.751447,35.0,gelu,...,0.004549,0.907018,True,SGD,NaN,Cosine,NaN,NaN,0.000014,COMPLETE
355,355,0.824386,0.952953,0.951085,0.794917,2025-03-28 17:32:33.052285,2025-03-28 18:02:37.760517,0 days 00:30:04.708232,NaN,gelu,...,0.000454,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.002539,COMPLETE
589,589,0.821045,0.952847,0.951930,0.789875,2025-03-29 11:46:38.829920,2025-03-29 12:37:54.866126,0 days 00:51:16.036206,NaN,relu,...,0.000490,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000180,COMPLETE
99,99,0.834320,0.952770,0.950891,0.809784,2025-03-28 14:06:25.094165,2025-03-28 14:44:05.830672,0 days 00:37:40.736507,39.0,gelu,...,0.000442,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000004,COMPLETE

In [9]:
tmp[tmp['params_gnn_layer'] == 'GCN'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
206,206,0.835472,0.953244,0.952255,0.811617,2025-03-28 15:48:19.975273,2025-03-28 16:35:23.017924,0 days 00:47:03.042651,NaN,relu,...,0.000563,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000361,COMPLETE
311,311,0.827824,0.952747,0.952376,0.800632,2025-03-28 17:17:19.373237,2025-03-28 17:58:55.013480,0 days 00:41:35.640243,NaN,relu,...,0.000687,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000723,COMPLETE
210,210,0.830579,0.952601,0.951316,0.804567,2025-03-28 16:09:28.305658,2025-03-28 16:44:41.855391,0 days 00:35:13.549733,NaN,relu,...,0.000260,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000234,COMPLETE
310,310,0.831204,0.952423,0.952022,0.805769,2025-03-28 17:17:04.532568,2025-03-28 17:58:34.719652,0 days 00:41:30.187084,NaN,relu,...,0.000726,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000692,COMPLETE
202,202,0.834711,0.952346,0.951202,0.810605,2025-03-28 15:46:25.904048,2025-03-28 16:21:04.503438,0 days 00:34:38.599390,NaN,relu,...,0.000267,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000301,COMPLETE

In [4]:
df.params_gnn_layer.value_counts()

params_gnn_layer
GCN     232
MPNN    122
Name: count, dtype: int64