In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_2671299/172045269.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-17 11:50:34,392] Using an existing study with name 'GATv2' instead of creating a new one.

(10, 24)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,...,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_n_layers,params_optimizer,params_scheduler,params_weight_decay
201,0.6553 (± 0.009),0.7138 (± 0.0113),0.7215 (± 0.0109),0.6553 (± 0.009),0.615 (± 0.026),0.5531 (± 0.051),0.6966 (± 0.0182),NaN,gelu,0.10,...,2900,2,839,159,51,0.000044,3,Adam,None,0.000032
207,0.6444 (± 0.0296),0.6972 (± 0.034),0.7064 (± 0.0322),0.6444 (± 0.0296),0.6371 (± 0.0275),0.6295 (± 0.1018),0.6585 (± 0.0525),NaN,gelu,0.40,...,4200,3,760,109,97,0.002476,2,AdamW,None,0.000013
95,0.6436 (± 0.0308),0.6906 (± 0.0413),0.706 (± 0.0306),0.6436 (± 0.0308),0.6106 (± 0.0541),0.5645 (± 0.0818),0.67 (± 0.0255),NaN,relu,0.15,...,3500,5,785,66,32,0.008122,4,AdamW,None,0.002959
8,0.624 (± 0.0175),0.682 (± 0.0174),0.6907 (± 0.015),0.624 (± 0.0175),0.5541 (± 0.0412),0.4699 (± 0.0549),0.6791 (± 0.0125),185.0,relu,0.20,...,600,3,360,81,69,0.000167,2,AdamW,Cosine,0.001054
74,0.5855 (± 0.0139),0.6427 (± 0.0216),0.651 (± 0.0226),0.5855 (± 0.0139),0.4695 (± 0.0531),0.3722 (± 0.073),0.6574 (± 0.0456),NaN,relu,0.10,...,7400,3,1002,91,91,0.000087,5,AdamW,None,0.000368

In [3]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-17 11:50:35,087] Using an existing study with name 'Transformer' instead of creating a new one.

(11, 24)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,...,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_n_layers,params_optimizer,params_scheduler,params_weight_decay
180,0.6671 (± 0.0062),0.7221 (± 0.0023),0.7292 (± 0.0032),0.6671 (± 0.0062),0.6486 (± 0.0104),0.6149 (± 0.0223),0.6869 (± 0.011),866.0,relu,0.1,...,3200,3,906,87,36,0.000019,2,Adam,Cosine,0.000007
80,0.6667 (± 0.0052),0.7215 (± 0.002),0.7295 (± 0.0029),0.6667 (± 0.0052),0.6474 (± 0.0147),0.6129 (± 0.0336),0.6873 (± 0.0103),NaN,gelu,0.3,...,2400,2,294,148,35,0.000090,3,Adam,None,0.000234
155,0.6683 (± 0.0021),0.7213 (± 0.0023),0.7294 (± 0.002),0.6683 (± 0.0021),0.6636 (± 0.0213),0.6576 (± 0.0609),0.6742 (± 0.0231),NaN,relu,0.2,...,5700,3,491,72,55,0.000251,3,Adam,None,0.000259
189,0.6658 (± 0.0062),0.7194 (± 0.0024),0.7285 (± 0.0032),0.6658 (± 0.0062),0.6429 (± 0.0122),0.6021 (± 0.0239),0.6903 (± 0.0095),NaN,relu,0.4,...,2500,2,444,216,94,0.000091,4,AdamW,None,0.007515
85,0.6662 (± 0.0036),0.7191 (± 0.0019),0.7275 (± 0.0025),0.6662 (± 0.0036),0.6498 (± 0.0058),0.6196 (± 0.018),0.6836 (± 0.0111),NaN,gelu,0.2,...,4000,2,633,143,132,0.000045,3,AdamW,None,0.000010

In [4]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-17 11:50:35,589] Using an existing study with name 'GAT' instead of creating a new one.

KeyError: ['values_0', 'values_1', 'values_2', 'values_3']