In [1]:
import math
import os

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tqdm import tqdm

# Gene Exp

In [2]:
gene_exp = pd.concat(
    [
        pd.read_csv("../nci_data/gene_exp_part1.csv.gz", index_col=0).T,
        pd.read_csv("../nci_data/gene_exp_part2.csv.gz", index_col=0).T,
    ],
    axis=1,
)
gene_exp.columns = list(gene_exp.columns)
gene_exp

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
MCF7,1.545084,1.960664,0.045797,0.048305,0.271383,0.000000,0.000000,0.000000,1.790422,0.000000,...,3.251321,4.553231,0.524880,1.325335,2.719968,0.979052,0.955984,2.997876,1.814542,2.017416
MDA_MB_231,0.577656,0.158440,0.023368,0.033706,0.000000,0.020794,0.000000,0.093408,0.281342,0.000000,...,4.150389,4.835798,0.399802,2.148645,1.286207,0.630559,1.366784,3.193204,0.534567,4.290867
HS578T,2.127485,1.114494,0.057868,0.053825,0.000000,0.122192,0.000000,0.000000,0.437279,0.375008,...,1.569525,2.078446,0.211162,0.425895,1.637754,0.183044,1.275240,6.707759,1.183093,1.404440
BT_549,2.807536,1.545173,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.705958,0.000000,...,1.551910,2.247581,0.538375,0.956725,1.921501,0.578255,1.148797,5.211335,1.806192,1.725314
T47D,2.240504,1.404554,0.014713,0.020456,0.083641,0.000000,0.000000,0.205220,0.775457,0.000000,...,2.328319,4.735132,0.634419,1.509372,2.627329,0.850154,1.326106,3.807767,1.399636,1.188945
SF_268,1.904164,0.224674,0.000000,0.066023,0.000000,0.000000,0.000000,0.256671,0.413970,0.126786,...,1.203840,3.447059,0.264858,0.741443,1.187052,0.000000,1.236389,5.422912,0.959441,1.258356
SF_295,1.645900,1.625902,0.021271,0.029497,0.000000,0.000000,0.000000,0.101272,0.493029,0.000000,...,3.338683,4.622304,0.355396,1.124633,2.284713,0.047663,1.388140,7.781976,1.643824,2.399661
SF_539,1.488978,1.449873,0.018674,0.302848,0.426903,0.000000,0.000000,0.116516,0.843719,0.000000,...,2.522377,3.481312,0.798670,1.482724,2.686960,0.119173,1.572594,7.108138,1.645789,2.314656
SNB_19,1.479329,0.274825,0.061902,0.483726,0.152568,0.076873,0.000000,0.145237,2.341513,0.302242,...,1.154635,1.465687,0.813209,1.270068,2.302293,0.121911,1.727816,4.974814,1.340579,1.763526
SNB_75,0.598351,0.248695,0.010085,6.973255,2.752582,0.027438,0.000000,0.167921,2.501286,0.093693,...,2.404099,4.063770,0.576326,1.084949,2.606243,0.095408,1.763505,6.493543,1.689898,2.246688
U251,0.638753,0.476393,0.041163,0.032769,0.065546,0.000000,0.000000,0.000000,1.569938,0.046399,...,3.543112,4.809898,0.669757,1.510223,2.378484,0.026790,2.086373,5.995444,1.864549,2.799361
COLO205,0.246667,0.000000,1.654981,0.024962,0.089178,0.020235,0.000000,0.185716,0.160210,0.000000,...,2.345189,3.655901,0.170633,0.490213,2.020484,0.047116,0.677649,2.606660,0.974401,0.967547
HCC_2998,0.250535,0.000000,0.373901,0.041253,0.094595,0.000000,0.000000,0.000000,2.512032,0.000000,...,2.401191,4.130478,0.571695,1.031155,2.511450,0.000000,1.430676,5.976073,1.938455,2.047629
HCT_116,0.307237,0.132078,0.068520,0.051264,0.398513,0.030822,0.000000,0.062921,1.069730,0.036591,...,3.128976,4.652573,0.542252,1.510572,2.439958,0.033921,1.933119,5.294235,1.246980,2.860160
HCT_15,0.390396,0.136813,0.000000,0.037231,0.201663,0.000000,0.000000,0.000000,0.401377,0.000000,...,2.140942,4.268554,0.747270,1.222514,2.739924,0.000000,1.679726,5.076414,1.942289,1.963755
HT29,0.521630,0.000000,0.021636,0.023163,0.000000,0.000000,0.000000,0.139856,1.846927,0.000000,...,2.723827,4.194647,0.171753,0.052821,2.653688,0.024624,0.650471,4.781496,0.993440,1.867035
KM12,0.455004,0.000000,0.047178,0.039222,0.067080,2.327751,0.000000,0.117796,1.676308,0.000000,...,3.173849,4.552082,0.167247,0.958492,1.989491,0.043580,1.026311,5.254987,0.948990,1.814567
SW_620,0.123572,0.000000,0.390645,0.064307,0.141200,0.049145,0.000000,0.257192,0.233616,0.000000,...,4.620944,4.561723,0.458652,2.637121,1.293276,0.227906,1.023042,0.495761,0.572585,2.283557
CCRF_CEM,3.415556,2.113584,0.023598,0.093839,0.034637,0.000000,0.000000,0.000000,0.087611,0.000000,...,4.266607,6.229944,0.701538,1.967988,3.482668,0.021588,1.424164,4.744215,1.963156,2.930277
HL_60,0.584909,0.189045,0.021053,0.047634,0.000000,0.032358,0.000000,0.215215,0.209344,0.000000,...,2.206553,3.844396,0.217071,1.212414,2.258242,0.089110,0.803203,5.615696,0.897406,1.945963
K_562,0.417591,0.286014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141922,0.000000,...,2.175831,3.998620,0.066914,0.405356,1.393345,1.343266,1.295053,4.946525,0.982254,1.380064
MOLT_4,2.893638,0.925995,0.048294,0.258310,0.000000,0.052554,0.056831,0.668980,0.406011,0.061282,...,2.244345,4.572017,0.567292,1.138834,2.688968,0.136482,0.623449,1.241181,1.569914,1.686577
RPMI_8226,1.169085,0.912828,0.125867,0.105289,0.126067,0.119677,0.000000,0.412116,0.577380,0.317986,...,2.441191,2.030640,0.347761,0.801423,1.814058,0.529370,0.808631,2.084085,0.592319,0.865066
SR,0.579469,0.634189,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517462,0.000000,...,2.157962,2.399961,0.163282,0.459376,1.622162,0.671210,0.642349,2.113334,0.592544,0.685140
LOXIMVI,0.185936,0.000000,0.043571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.643048,3.752481,0.247937,0.576799,1.557925,0.000000,0.817767,6.441324,1.120193,1.717772
MALME_3M,1.128029,1.686541,0.012960,5.145319,1.266355,0.021861,0.000000,0.000000,1.672462,0.000000,...,2.710287,3.321479,0.470055,1.072387,2.401445,0.000000,1.295235,5.702943,1.753810,1.765827
M14,1.382889,1.548910,0.078594,1.360617,0.673357,0.043225,0.055848,0.235252,0.181754,0.069082,...,2.269838,4.186604,0.305528,0.709368,2.670204,0.638157,1.218837,6.576282,2.070145,1.979685
SK_MEL_2,0.891387,1.708284,0.024977,2.032619,0.523482,0.019269,0.000000,0.086047,2.479383,0.000000,...,2.520900,2.986655,0.828408,1.578470,2.442790,0.018800,1.404195,6.194968,1.461151,1.981312
SK_MEL_28,1.188768,1.785739,0.000000,3.912430,0.725083,0.000000,0.000000,0.000000,0.910857,0.000000,...,1.764635,3.565561,0.438313,0.763754,2.484613,0.261266,1.181491,5.327429,1.539620,2.118699
SK_MEL_5,0.985070,0.321937,0.053715,3.319262,0.139690,0.063177,0.041588,0.257931,0.192075,0.042687,...,1.698605,2.880458,0.280925,0.630757,2.745594,0.074345,0.961779,5.381636,1.757501,1.192194
UACC_257,1.075779,0.612513,0.000000,2.605475,0.221317,0.035406,0.000000,0.193316,0.092515,0.000000,...,2.739410,4.122424,0.215420,0.952929,2.882845,0.037745,1.884563,4.567844,1.632040,2.758857
UACC_62,1.597913,2.124404,0.000000,3.040773,0.304673,0.000000,0.000000,0.000000,0.096365,0.000000,...,2.385795,3.768184,0.496423,1.076894,2.782882,0.030226,1.765072,6.695590,1.645651,1.443463
MDA_MB_435,0.813414,1.264128,0.000000,0.104453,0.000000,0.032089,0.000000,0.000000,0.000000,0.000000,...,2.922293,3.949012,0.427739,1.202073,2.557427,0.306827,1.437158,6.625117,2.311407,1.935486
MDA_N,1.028025,0.468561,0.128165,0.315368,0.343715,0.142585,0.000000,0.281589,0.224244,0.431887,...,1.988812,2.193040,0.332405,0.897409,1.612480,0.292948,0.980711,4.850084,0.956489,0.949319
A549,1.614870,0.417418,0.237778,0.000000,0.138358,0.000000,0.000000,0.000000,1.345135,0.164118,...,2.234161,3.374107,0.364849,0.945305,1.287856,0.489405,0.862357,4.814233,1.242243,0.751751
EKVX,0.618265,0.615816,0.029499,0.706799,0.781613,0.000000,0.000000,0.162985,1.537753,0.000000,...,3.121470,3.727703,0.789787,1.651715,2.089576,0.585060,2.542300,6.388582,1.966899,1.982254
HOP_62,0.584364,0.780409,0.018089,0.058614,0.000000,0.000000,0.000000,0.000000,1.409353,0.000000,...,2.442038,4.112533,0.463545,1.440123,2.774663,1.053660,1.568562,7.107259,1.623647,1.747985
HOP_92,1.137326,1.458041,0.000000,0.035569,0.000000,0.000000,0.000000,0.000000,1.858264,0.000000,...,2.254165,4.086317,0.513951,1.059044,2.436021,0.755965,1.508292,7.305505,1.502275,2.140661
NCI_H226,0.838398,0.286685,0.020127,0.069518,0.035271,0.028547,0.000000,0.264804,0.461380,0.060431,...,3.055124,3.270577,0.501549,1.414888,1.988946,0.040315,1.529901,6.423346,1.313037,2.195215
NCI_H23,0.662504,0.656841,0.000000,0.680351,0.517915,0.000000,0.000000,0.000000,1.200868,0.000000,...,3.119884,4.114867,0.717492,1.289604,2.712233,1.059715,1.729461,7.321189,1.872159,2.052920
NCI_H322M,0.650641,0.627746,0.000000,0.032171,0.198527,0.927342,0.000000,0.000000,3.125208,0.000000,...,2.499484,4.488952,0.409880,1.030774,2.196846,0.090183,1.067315,4.004412,1.371966,1.678744
NCI_H460,1.317466,0.286402,0.060136,0.043719,0.086571,0.095243,0.000000,1.628783,2.236777,0.047102,...,2.202643,3.654447,0.451344,0.811302,1.634463,0.407917,0.847372,4.932496,1.283987,1.037368
NCI_H522,0.870533,1.371235,0.033316,0.072972,0.483322,0.034023,0.000000,0.456816,0.862880,0.041820,...,3.098842,5.087594,1.635884,2.108846,2.239053,1.237790,1.752577,5.347634,1.265557,2.137117
IGROV1,0.524677,0.637974,0.000000,0.000000,0.214661,0.000000,0.000000,0.000000,1.858124,0.000000,...,2.188584,3.847716,0.478634,0.843296,2.085765,0.411463,1.584289,5.884019,1.398296,1.617393
OVCAR_3,0.817811,0.555374,0.022670,0.000000,0.000000,0.067640,0.000000,0.000000,0.490461,0.000000,...,1.761911,3.206415,0.271671,0.488833,1.988972,0.860634,0.700473,5.427707,0.900560,1.377862
OVCAR_4,1.239832,1.277259,0.017954,0.085341,0.096856,0.021942,0.000000,0.139429,1.998315,0.040983,...,1.790226,4.046447,0.295332,0.749709,2.387338,1.184883,1.188717,6.754861,1.114953,1.672231
OVCAR_5,0.361421,0.134705,0.056577,0.056299,0.000000,0.014644,0.000000,0.091694,0.062084,0.030664,...,2.633350,4.384533,0.052474,0.301610,2.040391,0.186418,0.887341,4.067854,0.344686,1.638959
OVCAR_8,1.147079,1.340488,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.868882,0.000000,...,1.573452,4.104630,0.205381,0.448423,2.491538,1.504605,1.263022,7.119616,1.720782,1.597827
SK_OV_3,0.871177,0.826886,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.465086,0.000000,...,2.257174,3.795684,0.374348,0.931595,2.317796,0.985476,1.884891,5.430657,1.297638,1.188901
NCI_ADR_RES,2.422618,2.752160,0.016345,0.024607,0.339376,0.000000,0.000000,0.000000,1.808731,0.000000,...,3.817726,5.635148,0.326622,0.795797,3.352103,1.946461,1.634096,8.637817,1.671239,2.703180
PC_3,0.206131,0.153104,0.225023,0.075167,0.238277,0.000000,0.000000,0.000000,0.624892,0.000000,...,2.823482,5.124841,0.659168,1.943730,1.920179,0.100480,2.242255,7.227934,1.626551,2.436690
DU_145,1.494467,0.384633,0.136934,0.166591,0.859956,0.173804,0.000000,2.073128,1.388250,0.132402,...,1.712054,2.713111,0.533587,0.665578,1.704469,0.843826,0.681730,5.246845,1.251816,0.940434
786_0,0.361155,0.000000,0.029955,0.056167,0.000000,0.016151,0.000000,0.000000,2.006872,0.000000,...,2.518782,4.195119,0.369624,0.660119,1.919836,0.043749,1.246694,6.732405,1.467530,1.762132
A498,0.440222,0.067594,0.078561,0.038646,0.083573,0.037460,0.000000,0.291472,1.424213,0.042165,...,1.470766,2.806258,0.411828,0.598354,1.297315,0.526957,0.662996,6.670161,1.290324,1.072373
ACHN,0.576425,0.220324,0.020986,0.067487,0.302748,0.014374,0.000000,0.332142,1.582792,0.176846,...,2.700318,4.206784,0.488145,0.751780,1.867363,0.064330,1.006600,6.743057,1.471234,1.944997
CAKI_1,0.882482,0.506823,0.000000,0.036152,0.000000,0.000000,0.000000,0.135979,2.266421,0.000000,...,2.167859,2.884453,0.400211,1.215057,1.710098,0.474023,1.266373,6.547058,0.761174,1.465400
RXF_393,0.572572,0.975728,0.019251,0.020413,0.147273,0.022726,0.000000,0.000000,2.311207,0.094547,...,2.707796,3.556245,0.707476,1.232096,1.799465,0.875894,1.497382,6.892488,1.406139,2.112423
SN12C,1.533733,0.660213,0.024985,0.035940,0.000000,0.000000,0.000000,0.000000,1.670165,0.000000,...,1.687773,4.720623,0.465862,0.630736,1.909151,0.920320,1.212538,7.071076,1.007346,0.865705
TK_10,0.076563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.572617,0.000000,...,2.771981,3.864523,0.365028,0.821460,1.604811,0.901689,1.590070,6.747535,0.994256,2.221326
UO_31,0.342318,0.471444,0.000000,0.000000,0.227863,0.000000,0.000000,0.000000,1.941689,0.000000,...,2.862285,4.035386,0.482844,1.157290,2.100184,0.325286,1.640838,7.231327,1.714553,2.178909

# Drug Response

In [3]:
drug_response = pd.read_csv("../nci_data/drugAct.csv", index_col=0)
drug_response.columns = gene_exp.index
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
1,-0.271314,-0.303539,-0.815183,-0.231499,1.934731,-0.357577,-0.719253,-0.380720,-1.281589,-0.175915,...,-0.403983,-0.434885,-0.519867,-1.648059,1.657273,-0.269717,0.002290,-0.390689,-0.379420,1.059515
17,-0.354110,-0.304675,-0.222024,1.483613,1.509397,0.335572,0.424922,1.140166,-0.941890,0.330808,...,1.302516,-0.941890,0.521200,-0.329639,-0.941890,0.717851,-0.239018,-0.315533,-0.761559,1.120673
89,NaN,NaN,NaN,NaN,NaN,-0.184194,-1.429903,-0.165433,-1.429903,-0.216723,...,NaN,NaN,0.368433,-0.655707,-0.144006,0.743888,-0.435620,-0.184805,-0.101929,-0.118807
185,NaN,NaN,NaN,NaN,NaN,0.539343,NaN,0.230402,-0.765829,-1.125208,...,NaN,NaN,-0.061612,NaN,NaN,1.675353,0.918722,1.391604,-0.904724,0.918522
295,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,...,-0.264586,-0.264586,4.822657,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900911,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,...,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,1.594059,-0.167151,-0.167151,-0.167151
900922,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,...,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786
900964,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,...,-0.158754,NaN,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754
900974,-0.132453,-0.132453,-0.132453,NaN,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,...,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,NaN,-0.132453,-0.132453,-0.132453
921923,0.513889,-0.600293,-0.816154,-0.604513,NaN,-0.126943,-0.961518,-0.268661,-0.927258,NaN,...,-0.268102,-0.152586,0.350261,-0.920821,-0.140812,-0.559582,-1.009885,0.705388,1.538064,-0.301852

In [4]:
nsc_smiles = pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
    ["NSC", "SMILES"]
]
nsc_smiles

          NSC                                             SMILES
0           1                                  CC1=CC(=O)C=CC1=O
1          17                   CCCCCCCCCCCCCCCC1=C(C=CC(=C1)O)N
2          89                         CN(C)CCC(=O)C1=CC=CC=C1.Cl
3         185            CC1CC(C(=O)C(C1)C(CC2CC(=O)NC(=O)C2)O)C
4      758187            CC1CC(C(=O)C(C1)C(CC2CC(=O)NC(=O)C2)O)C
...       ...                                                ...
23186  799649  C1CC2=C(C1)SC3=NC=NC(=C23)NC4=C(NN=C4)C(=O)NC5...
23187  803209  CCN1C2C(N(C1=O)CC)N3C(=O)C(=C4C5=CC=CC=C5N(C4=...
23188  803778  C1=CC=C(C=C1)C=NC2=C(C(C3=C(O2)C4=CC=CC=C4C=C3...
23189  807047  CC1=C(C=C(C=C1)NC(=O)C2=CC(=NC=C2)C(F)(F)F)C3=...
23190  707090     COC1=CC=C(C=C1)NC2=NC(=C(S2)C(=O)C3=CC=CC=C3)N

[23191 rows x 2 columns]

In [5]:
drug_response = drug_response[drug_response.index.isin(nsc_smiles["NSC"])]
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
1,-0.271314,-0.303539,-0.815183,-0.231499,1.934731,-0.357577,-0.719253,-0.380720,-1.281589,-0.175915,...,-0.403983,-0.434885,-0.519867,-1.648059,1.657273,-0.269717,0.002290,-0.390689,-0.379420,1.059515
17,-0.354110,-0.304675,-0.222024,1.483613,1.509397,0.335572,0.424922,1.140166,-0.941890,0.330808,...,1.302516,-0.941890,0.521200,-0.329639,-0.941890,0.717851,-0.239018,-0.315533,-0.761559,1.120673
89,NaN,NaN,NaN,NaN,NaN,-0.184194,-1.429903,-0.165433,-1.429903,-0.216723,...,NaN,NaN,0.368433,-0.655707,-0.144006,0.743888,-0.435620,-0.184805,-0.101929,-0.118807
185,NaN,NaN,NaN,NaN,NaN,0.539343,NaN,0.230402,-0.765829,-1.125208,...,NaN,NaN,-0.061612,NaN,NaN,1.675353,0.918722,1.391604,-0.904724,0.918522
295,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,...,-0.264586,-0.264586,4.822657,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830912,-0.376238,-0.376238,1.010516,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,...,-0.376238,-0.376238,-0.376238,3.525174,-0.376238,NaN,0.199423,0.443532,-0.376238,-0.376238
831147,1.072608,-0.972979,0.442335,-0.012315,-0.482196,-1.133923,0.744309,0.248854,-0.165824,0.413759,...,-0.351430,-0.514584,-0.611389,0.472510,-0.823481,0.742079,0.422323,-1.046201,-2.375068,-0.500730
831270,1.851876,-0.987088,-0.356117,-0.421592,-0.611842,-0.608036,-0.403236,-0.540247,-0.689865,-0.317744,...,-0.456405,-0.949046,-0.575863,0.841165,1.539347,2.607703,-0.341227,-0.708900,-0.597473,1.611968
831271,0.439331,-0.178969,-0.121072,0.238512,0.339249,-0.395609,-0.142904,-0.070311,-1.578078,-0.067484,...,0.108510,-0.416719,0.151945,0.340800,-0.311599,0.093151,0.349071,-0.108789,-0.327627,0.522628
831453,-0.407871,0.169410,-0.718427,-0.820520,-0.402455,-0.400405,-0.577882,-0.194282,-0.399358,-0.616924,...,-0.129208,-0.184982,0.406725,NaN,-0.101206,-0.255620,NaN,-0.366483,-0.404886,-0.456849

In [6]:
moa = pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
    ["NSC", "MECHANISM"]
]

In [7]:
moa["MECHANISM"].value_counts()

MECHANISM
Other          22245
Kinase           481
DNA              269
TUBB              45
HDAC              45
Apoptosis         36
HSP90             16
Ho                13
Methylation       13
PSM               13
BRD               11
Acetalax           4
Name: count, dtype: int64

In [8]:
not_other = moa[moa["MECHANISM"] != "Other"]
len(not_other)

946

# Also add drugs which are overwrapped with other datasets

In [9]:
tmp = pd.read_csv("../data/drugSynonym.csv")
tmp = tmp[
    (~tmp.nci60.isna() & ~tmp.ctrp.isna())
    | (~tmp.nci60.isna() & ~tmp.gdsc1.isna())
    | (~tmp.nci60.isna() & ~tmp.gdsc2.isna())
]
tmp = [int(i) for i in set(tmp["nci60"].str.split("|").explode())]
tmp

[788121,
 758662,
 766907,
 756652,
 608210,
 765888,
 778909,
 801011,
 761190,
 758706,
 127716,
 761192,
 791226,
 157035,
 613327,
 138783,
 122819,
 77213,
 764040,
 766270,
 773394,
 777425,
 701852,
 750690,
 750691,
 758247,
 111180,
 797938,
 330507,
 87877,
 758871,
 122758,
 760841,
 777639,
 772868,
 727989,
 606698,
 754362,
 753686,
 758872,
 719276,
 757148,
 179940,
 756656,
 759174,
 287459,
 757441,
 90636,
 764036,
 765866,
 178296,
 734950,
 758873,
 174939,
 782007,
 109724,
 759095,
 758664,
 767124,
 800773,
 618487,
 737754,
 766992,
 758612,
 786099,
 755775,
 767600,
 63878,
 764516,
 761431,
 752840,
 339555,
 759878,
 761910,
 765695,
 756642,
 125066,
 758246,
 100880,
 26980,
 764092,
 757306,
 756876,
 758774,
 765776,
 760087,
 766908,
 774829,
 756647,
 800085,
 759155,
 279836,
 756645,
 781516,
 319726,
 757036,
 727125,
 764239,
 800955,
 778368,
 759659,
 755806,
 777718,
 721517,
 760843,
 755606,
 698037,
 755386,
 656576,
 758645,
 765694,
 706995,
 3053,
 767746,
 756404,
 3088,
 765396,
 758007,
 778305,
 119875,
 758253,
 756236,
 787137,
 760444,
 755761,
 32982,
 754344,
 3061,
 759676,
 606869,
 67574,
 759224,
 782153,
 754354,
 759677,
 740,
 763579,
 791496,
 19893,
 163062,
 757438,
 764039,
 764517,
 757384,
 799348,
 764091,
 756657,
 759263,
 755387,
 628503,
 797771,
 764659,
 775636,
 684363,
 764043,
 765974,
 787326,
 767951,
 767125,
 754349,
 743414,
 791059,
 637037,
 758440,
 123127,
 758186,
 757424,
 800812,
 749712,
 779217,
 26271,
 59687,
 752782,
 755983,
 757804,
 759852,
 129185,
 754352,
 49842,
 758005,
 754357,
 764821,
 718781,
 749227,
 758242,
 758255,
 767048,
 800081,
 756643,
 759857,
 633782,
 141633,
 761217,
 616348,
 102816,
 683864,
 764134,
 766991,
 728073,
 754143,
 760183,
 609699,
 757436,
 630176,
 757439,
 800851,
 761760,
 767128,
 800858,
 726630,
 759850,
 777445,
 758667,
 649890,
 117186,
 799349,
 773261,
 754356,
 767189,
 755809,
 134727,
 744912,
 45388,
 755762,
 759675,
 118218,
 767598,
 759856,
 701554,
 732011,
 780249,
 633781,
 772196,
 757113,
 780042,
 83265,
 734325,
 755770,
 755841,
 820919,
 778747,
 226080,
 776996,
 745750,
 94600,
 301739,
 755384,
 755400,
 761068,
 767952,
 755985,
 706744,
 758591,
 677411,
 681239,
 207895,
 256942,
 758487,
 762831,
 777572,
 756648,
 777194,
 777448,
 799337,
 125973,
 757444,
 713200,
 124463,
 741078,
 266046,
 749226,
 758896,
 801012,
 758485,
 766906,
 755385,
 766271,
 779704,
 761070,
 771650,
 776066,
 782164,
 755880,
 798303,
 673596,
 732517,
 747856,
 800841,
 764041,
 764481,
 768508,
 760766,
 299933,
 715055,
 754771,
 759660,
 782121,
 180973,
 755980,
 781627,
 141540,
 747599,
 312887,
 765436,
 759877,
 758243,
 252844,
 787962]

# To fit into the memory for A100 80GB, we select MoA which is not "Other"

In [10]:
len(set(drug_response.index) & (set(list(not_other["NSC"])) | set(tmp)))

1005

In [11]:
drug_response = drug_response.loc[
    sorted(set(drug_response.index) & (set(list(not_other["NSC"])) | set(tmp)))
]
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.703626,-1.219032,-1.892792,-0.877267,-1.156158,0.510978,0.536910,0.589970,-0.356387,-1.460314,...,0.626838,0.507493,0.682664,-0.891882,0.499337,0.541612,-1.400771,0.602244,-1.641942,0.231533
752,0.475296,-0.312852,-1.089067,-0.441030,-0.058619,0.057507,0.125700,0.111693,-3.285729,-0.114051,...,-0.321691,0.507798,0.384102,-1.314527,-0.318444,0.557175,0.345056,-0.047731,0.155244,-0.160223
755,0.704027,-0.438857,-0.548744,-1.441942,0.496864,0.096265,-0.082186,0.417634,-1.927502,-0.372021,...,0.123647,0.543639,0.623318,-1.374212,-0.173024,0.314436,-1.002183,-0.881252,0.491364,-0.183200
757,0.318209,NaN,NaN,NaN,NaN,0.307045,0.355509,0.385020,0.183820,-0.384083,...,NaN,NaN,0.009710,0.225675,-0.597319,-0.093596,0.357496,0.158630,-3.402035,-1.148675
762,0.547964,-1.033803,-1.399273,-0.538268,1.137432,0.135942,-0.094460,0.562628,-1.398911,-1.050409,...,-0.294845,0.934592,0.591263,-0.552673,1.797227,1.260987,0.172806,0.869675,-0.529810,-0.634413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.088052,0.332208,1.572703,0.816968,-0.194672,0.607785,0.306740,1.381493,-0.240118,1.766007,...,-0.621433,-0.040864,0.201668,1.999485,0.432290,0.532053,1.847915,0.879530,-0.113922,1.113174
812926,-0.692843,-0.198620,-0.091472,-0.363542,0.716930,0.114785,-0.743516,-0.403585,-0.959310,0.424058,...,-0.737629,-0.105010,0.195539,1.856611,2.094631,0.843571,0.602042,-0.385549,3.111755,1.518265
812927,3.663091,0.176469,-0.137450,-0.461071,0.029122,-0.540453,-0.393660,0.141554,-0.019758,2.130226,...,-0.553986,-0.602355,-0.438735,0.000707,-0.047693,-1.150848,0.071027,-0.839514,0.103856,0.116587
813488,0.319494,0.259510,0.959946,1.353693,0.058727,0.236707,-0.821851,0.621550,-0.251549,2.256322,...,-0.563012,-0.240817,0.742293,5.112669,0.323573,-0.185610,1.349165,0.191249,0.266489,1.166435
820919,-0.301627,1.135666,-0.019219,-0.965383,-0.739311,-0.930962,-0.134611,-0.383439,-0.975665,-0.494568,...,-0.588451,-1.325009,-0.422640,0.218031,-0.137432,-0.310064,0.322362,-0.313936,-1.413504,0.710700

In [12]:
df = pd.DataFrame()
for i in drug_response.columns:
    tmp = pd.DataFrame(drug_response[i]).reset_index().dropna()
    tmp["cell"] = [i] * len(tmp)
    tmp.columns = ["Drug", "Value", "Cell"]
    tmp = tmp[["Drug", "Cell", "Value"]]
    df = pd.concat([df, tmp])
df

        Drug   Cell     Value
0        740   MCF7  0.703626
1        752   MCF7  0.475296
2        755   MCF7  0.704027
3        757   MCF7  0.318209
4        762   MCF7  0.547964
...      ...    ...       ...
1000  811429  UO_31  1.113174
1001  812926  UO_31  1.518265
1002  812927  UO_31  0.116587
1003  813488  UO_31  1.166435
1004  820919  UO_31  0.710700

[58019 rows x 3 columns]

# Zero shot prediction

In [13]:
unique_drugs = df["Drug"].unique()
unique_cells = df["Cell"].unique()

# Split drugs and cell lines into training, validation, and test sets
train_drugs, test_val_drugs = train_test_split(
    unique_drugs, test_size=0.5, random_state=42
)
val_drugs, test_drugs = train_test_split(test_val_drugs, test_size=0.5, random_state=42)

train_cells, test_val_cells = train_test_split(
    unique_cells, test_size=0.55, random_state=42
)
val_cells, test_cells = train_test_split(test_val_cells, test_size=0.5, random_state=42)

# Split the dataset
train_df = df[(df["Drug"].isin(train_drugs)) & (df["Cell"].isin(train_cells))]
val_df = df[(df["Drug"].isin(val_drugs)) & (df["Cell"].isin(val_cells))]
test_df = df[(df["Drug"].isin(test_drugs)) & (df["Cell"].isin(test_cells))]


# Function to balance label distribution
def balance_labels(df, threshold=0.5):
    positive = df[df["Value"] > 0]
    negative = df[df["Value"] <= 0]
    min_count = min(len(positive), len(negative))
    balanced_positive = positive.sample(min_count, random_state=42)
    balanced_negative = negative.sample(min_count, random_state=42)
    return pd.concat([balanced_positive, balanced_negative])


# Balance label distribution across all sets
train_df = balance_labels(train_df)
val_df = balance_labels(val_df)
test_df = balance_labels(test_df)

# Separate features and labels
X_train = train_df[["Drug", "Cell"]]
y_train = np.array(train_df["Value"] > 0, dtype=float)

X_val = val_df[["Drug", "Cell"]]
y_val = np.array(val_df["Value"] > 0, dtype=float)

X_test = test_df[["Drug", "Cell"]]
y_test = np.array(test_df["Value"] > 0, dtype=float)

# Calculate total samples
total_samples = len(X_train) + len(X_val) + len(X_test)


# Function to calculate and format label ratios
def get_label_ratio(y):
    unique, counts = np.unique(y, return_counts=True)
    total = len(y)
    ratio_str = ", ".join(
        [f"Label {label}: {count/total:.2%}" for label, count in zip(unique, counts)]
    )
    return ratio_str


# Display results with percentages and label ratios
print("Train:")
print(X_train.shape, y_train.shape)
print(f"Percentage: {len(X_train)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_train)}")

print("\nValidation:")
print(X_val.shape, y_val.shape)
print(f"Percentage: {len(X_val)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_val)}")

print("\nTest:")
print(X_test.shape, y_test.shape)
print(f"Percentage: {len(X_test)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_test)}")

print(f"\nTotal samples: {total_samples}")
print(
    f"Ratio (Train:Validation:Test): {len(X_train):.0f}:{len(X_val):.0f}:{len(X_test):.0f}"
)
print(
    f"Overall Label Ratio: {get_label_ratio(np.concatenate([y_train, y_val, y_test]))}"
)

X_train.to_csv("../nci_data/train.csv", index=False)
X_test.to_csv("../nci_data/test.csv", index=False)
X_val.to_csv("../nci_data/val.csv", index=False)

np.save("../nci_data/train_labels.npy", y_train)
np.save("../nci_data/test_labels.npy", y_test)
np.save("../nci_data/val_labels.npy", y_val)

Train:
(12398, 2) (12398,)
Percentage: 62.93%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Validation:
(3186, 2) (3186,)
Percentage: 16.17%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Test:
(4116, 2) (4116,)
Percentage: 20.89%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Total samples: 19700
Ratio (Train:Validation:Test): 12398:3186:4116
Overall Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

In [14]:
drug_response = drug_response.fillna(0)
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.703626,-1.219032,-1.892792,-0.877267,-1.156158,0.510978,0.536910,0.589970,-0.356387,-1.460314,...,0.626838,0.507493,0.682664,-0.891882,0.499337,0.541612,-1.400771,0.602244,-1.641942,0.231533
752,0.475296,-0.312852,-1.089067,-0.441030,-0.058619,0.057507,0.125700,0.111693,-3.285729,-0.114051,...,-0.321691,0.507798,0.384102,-1.314527,-0.318444,0.557175,0.345056,-0.047731,0.155244,-0.160223
755,0.704027,-0.438857,-0.548744,-1.441942,0.496864,0.096265,-0.082186,0.417634,-1.927502,-0.372021,...,0.123647,0.543639,0.623318,-1.374212,-0.173024,0.314436,-1.002183,-0.881252,0.491364,-0.183200
757,0.318209,0.000000,0.000000,0.000000,0.000000,0.307045,0.355509,0.385020,0.183820,-0.384083,...,0.000000,0.000000,0.009710,0.225675,-0.597319,-0.093596,0.357496,0.158630,-3.402035,-1.148675
762,0.547964,-1.033803,-1.399273,-0.538268,1.137432,0.135942,-0.094460,0.562628,-1.398911,-1.050409,...,-0.294845,0.934592,0.591263,-0.552673,1.797227,1.260987,0.172806,0.869675,-0.529810,-0.634413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.088052,0.332208,1.572703,0.816968,-0.194672,0.607785,0.306740,1.381493,-0.240118,1.766007,...,-0.621433,-0.040864,0.201668,1.999485,0.432290,0.532053,1.847915,0.879530,-0.113922,1.113174
812926,-0.692843,-0.198620,-0.091472,-0.363542,0.716930,0.114785,-0.743516,-0.403585,-0.959310,0.424058,...,-0.737629,-0.105010,0.195539,1.856611,2.094631,0.843571,0.602042,-0.385549,3.111755,1.518265
812927,3.663091,0.176469,-0.137450,-0.461071,0.029122,-0.540453,-0.393660,0.141554,-0.019758,2.130226,...,-0.553986,-0.602355,-0.438735,0.000707,-0.047693,-1.150848,0.071027,-0.839514,0.103856,0.116587
813488,0.319494,0.259510,0.959946,1.353693,0.058727,0.236707,-0.821851,0.621550,-0.251549,2.256322,...,-0.563012,-0.240817,0.742293,5.112669,0.323573,-0.185610,1.349165,0.191249,0.266489,1.166435
820919,-0.301627,1.135666,-0.019219,-0.965383,-0.739311,-0.930962,-0.134611,-0.383439,-0.975665,-0.494568,...,-0.588451,-1.325009,-0.422640,0.218031,-0.137432,-0.310064,0.322362,-0.313936,-1.413504,0.710700

# Masking

In [15]:
# Validation Mask
for _, row in X_val.iterrows():
    drug_response.loc[row["Drug"], row["Cell"]] = 0

# Test Mask
for _, row in X_test.iterrows():
    drug_response.loc[row["Drug"], row["Cell"]] = 0

# DTI

In [16]:
dti = pd.read_csv("../data/full_table.csv")
dti = dti.dropna(subset="NSC").reset_index(drop=True)
dti["NSC"] = dti["NSC"].astype(int)
dti.head()

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
0,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,APOD,122759
1,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,PTGDS,122759
2,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH12,122759
3,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH5,122759
4,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH13,122759

In [17]:
dti = dti[dti["NSC"].isin(drug_response.index)]
dti.head()

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
36,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB5,681239
37,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB1,681239
38,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,DHFR,3061
39,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,DHFR,757306
40,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,HEXB,3061

## All drugs are in drug response.

In [18]:
dti = dti[dti.Gene.isin(set(gene_exp.columns) & set(dti.Gene))]
dti

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
36,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB5,681239
37,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB1,681239
38,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,DHFR,3061
39,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,DHFR,757306
40,Pyrimethamine,DB00205,4993.0,46505987.0,CCC1=C(C(N)=NC(N)=N1)C1=CC=C(Cl)C=C1,HEXB,3061
...,...,...,...,...,...,...,...
1496,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR2,813488
1497,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR3,813488
1498,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR4,813488
1500,BMS-754807,DB15399,NaN,NaN,C[C@]1(CCCN1C1=NN2C=CC=C2C(NC2=NNC(=C2)C2CC2)=...,IGF1R,758243
1502,BMS-754807,DB15399,NaN,NaN,C[C@]1(CCCN1C1=NN2C=CC=C2C(NC2=NNC(=C2)C2CC2)=...,INSR,758243

In [19]:
print("unique drugs:", len(set(dti.NSC)))
print("unique genes:", len(set(dti.Gene)))

unique drugs: 200
unique genes: 251

# Selected highly variable genes

In [20]:
print(
    "Density: ",
    round((len(gene_exp.values.nonzero()[0]) / gene_exp.size) * 100, 2),
    "%",
)

Density:  75.09 %

In [21]:
variance = gene_exp.std()
variance = variance.sort_values(ascending=False)
variance = pd.DataFrame(variance > np.percentile(variance, 90))
variance = list(variance[variance[0]].index)
len(variance)

2383

In [22]:
gene_exp

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
MCF7,1.545084,1.960664,0.045797,0.048305,0.271383,0.000000,0.000000,0.000000,1.790422,0.000000,...,3.251321,4.553231,0.524880,1.325335,2.719968,0.979052,0.955984,2.997876,1.814542,2.017416
MDA_MB_231,0.577656,0.158440,0.023368,0.033706,0.000000,0.020794,0.000000,0.093408,0.281342,0.000000,...,4.150389,4.835798,0.399802,2.148645,1.286207,0.630559,1.366784,3.193204,0.534567,4.290867
HS578T,2.127485,1.114494,0.057868,0.053825,0.000000,0.122192,0.000000,0.000000,0.437279,0.375008,...,1.569525,2.078446,0.211162,0.425895,1.637754,0.183044,1.275240,6.707759,1.183093,1.404440
BT_549,2.807536,1.545173,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.705958,0.000000,...,1.551910,2.247581,0.538375,0.956725,1.921501,0.578255,1.148797,5.211335,1.806192,1.725314
T47D,2.240504,1.404554,0.014713,0.020456,0.083641,0.000000,0.000000,0.205220,0.775457,0.000000,...,2.328319,4.735132,0.634419,1.509372,2.627329,0.850154,1.326106,3.807767,1.399636,1.188945
SF_268,1.904164,0.224674,0.000000,0.066023,0.000000,0.000000,0.000000,0.256671,0.413970,0.126786,...,1.203840,3.447059,0.264858,0.741443,1.187052,0.000000,1.236389,5.422912,0.959441,1.258356
SF_295,1.645900,1.625902,0.021271,0.029497,0.000000,0.000000,0.000000,0.101272,0.493029,0.000000,...,3.338683,4.622304,0.355396,1.124633,2.284713,0.047663,1.388140,7.781976,1.643824,2.399661
SF_539,1.488978,1.449873,0.018674,0.302848,0.426903,0.000000,0.000000,0.116516,0.843719,0.000000,...,2.522377,3.481312,0.798670,1.482724,2.686960,0.119173,1.572594,7.108138,1.645789,2.314656
SNB_19,1.479329,0.274825,0.061902,0.483726,0.152568,0.076873,0.000000,0.145237,2.341513,0.302242,...,1.154635,1.465687,0.813209,1.270068,2.302293,0.121911,1.727816,4.974814,1.340579,1.763526
SNB_75,0.598351,0.248695,0.010085,6.973255,2.752582,0.027438,0.000000,0.167921,2.501286,0.093693,...,2.404099,4.063770,0.576326,1.084949,2.606243,0.095408,1.763505,6.493543,1.689898,2.246688
U251,0.638753,0.476393,0.041163,0.032769,0.065546,0.000000,0.000000,0.000000,1.569938,0.046399,...,3.543112,4.809898,0.669757,1.510223,2.378484,0.026790,2.086373,5.995444,1.864549,2.799361
COLO205,0.246667,0.000000,1.654981,0.024962,0.089178,0.020235,0.000000,0.185716,0.160210,0.000000,...,2.345189,3.655901,0.170633,0.490213,2.020484,0.047116,0.677649,2.606660,0.974401,0.967547
HCC_2998,0.250535,0.000000,0.373901,0.041253,0.094595,0.000000,0.000000,0.000000,2.512032,0.000000,...,2.401191,4.130478,0.571695,1.031155,2.511450,0.000000,1.430676,5.976073,1.938455,2.047629
HCT_116,0.307237,0.132078,0.068520,0.051264,0.398513,0.030822,0.000000,0.062921,1.069730,0.036591,...,3.128976,4.652573,0.542252,1.510572,2.439958,0.033921,1.933119,5.294235,1.246980,2.860160
HCT_15,0.390396,0.136813,0.000000,0.037231,0.201663,0.000000,0.000000,0.000000,0.401377,0.000000,...,2.140942,4.268554,0.747270,1.222514,2.739924,0.000000,1.679726,5.076414,1.942289,1.963755
HT29,0.521630,0.000000,0.021636,0.023163,0.000000,0.000000,0.000000,0.139856,1.846927,0.000000,...,2.723827,4.194647,0.171753,0.052821,2.653688,0.024624,0.650471,4.781496,0.993440,1.867035
KM12,0.455004,0.000000,0.047178,0.039222,0.067080,2.327751,0.000000,0.117796,1.676308,0.000000,...,3.173849,4.552082,0.167247,0.958492,1.989491,0.043580,1.026311,5.254987,0.948990,1.814567
SW_620,0.123572,0.000000,0.390645,0.064307,0.141200,0.049145,0.000000,0.257192,0.233616,0.000000,...,4.620944,4.561723,0.458652,2.637121,1.293276,0.227906,1.023042,0.495761,0.572585,2.283557
CCRF_CEM,3.415556,2.113584,0.023598,0.093839,0.034637,0.000000,0.000000,0.000000,0.087611,0.000000,...,4.266607,6.229944,0.701538,1.967988,3.482668,0.021588,1.424164,4.744215,1.963156,2.930277
HL_60,0.584909,0.189045,0.021053,0.047634,0.000000,0.032358,0.000000,0.215215,0.209344,0.000000,...,2.206553,3.844396,0.217071,1.212414,2.258242,0.089110,0.803203,5.615696,0.897406,1.945963
K_562,0.417591,0.286014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141922,0.000000,...,2.175831,3.998620,0.066914,0.405356,1.393345,1.343266,1.295053,4.946525,0.982254,1.380064
MOLT_4,2.893638,0.925995,0.048294,0.258310,0.000000,0.052554,0.056831,0.668980,0.406011,0.061282,...,2.244345,4.572017,0.567292,1.138834,2.688968,0.136482,0.623449,1.241181,1.569914,1.686577
RPMI_8226,1.169085,0.912828,0.125867,0.105289,0.126067,0.119677,0.000000,0.412116,0.577380,0.317986,...,2.441191,2.030640,0.347761,0.801423,1.814058,0.529370,0.808631,2.084085,0.592319,0.865066
SR,0.579469,0.634189,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517462,0.000000,...,2.157962,2.399961,0.163282,0.459376,1.622162,0.671210,0.642349,2.113334,0.592544,0.685140
LOXIMVI,0.185936,0.000000,0.043571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.643048,3.752481,0.247937,0.576799,1.557925,0.000000,0.817767,6.441324,1.120193,1.717772
MALME_3M,1.128029,1.686541,0.012960,5.145319,1.266355,0.021861,0.000000,0.000000,1.672462,0.000000,...,2.710287,3.321479,0.470055,1.072387,2.401445,0.000000,1.295235,5.702943,1.753810,1.765827
M14,1.382889,1.548910,0.078594,1.360617,0.673357,0.043225,0.055848,0.235252,0.181754,0.069082,...,2.269838,4.186604,0.305528,0.709368,2.670204,0.638157,1.218837,6.576282,2.070145,1.979685
SK_MEL_2,0.891387,1.708284,0.024977,2.032619,0.523482,0.019269,0.000000,0.086047,2.479383,0.000000,...,2.520900,2.986655,0.828408,1.578470,2.442790,0.018800,1.404195,6.194968,1.461151,1.981312
SK_MEL_28,1.188768,1.785739,0.000000,3.912430,0.725083,0.000000,0.000000,0.000000,0.910857,0.000000,...,1.764635,3.565561,0.438313,0.763754,2.484613,0.261266,1.181491,5.327429,1.539620,2.118699
SK_MEL_5,0.985070,0.321937,0.053715,3.319262,0.139690,0.063177,0.041588,0.257931,0.192075,0.042687,...,1.698605,2.880458,0.280925,0.630757,2.745594,0.074345,0.961779,5.381636,1.757501,1.192194
UACC_257,1.075779,0.612513,0.000000,2.605475,0.221317,0.035406,0.000000,0.193316,0.092515,0.000000,...,2.739410,4.122424,0.215420,0.952929,2.882845,0.037745,1.884563,4.567844,1.632040,2.758857
UACC_62,1.597913,2.124404,0.000000,3.040773,0.304673,0.000000,0.000000,0.000000,0.096365,0.000000,...,2.385795,3.768184,0.496423,1.076894,2.782882,0.030226,1.765072,6.695590,1.645651,1.443463
MDA_MB_435,0.813414,1.264128,0.000000,0.104453,0.000000,0.032089,0.000000,0.000000,0.000000,0.000000,...,2.922293,3.949012,0.427739,1.202073,2.557427,0.306827,1.437158,6.625117,2.311407,1.935486
MDA_N,1.028025,0.468561,0.128165,0.315368,0.343715,0.142585,0.000000,0.281589,0.224244,0.431887,...,1.988812,2.193040,0.332405,0.897409,1.612480,0.292948,0.980711,4.850084,0.956489,0.949319
A549,1.614870,0.417418,0.237778,0.000000,0.138358,0.000000,0.000000,0.000000,1.345135,0.164118,...,2.234161,3.374107,0.364849,0.945305,1.287856,0.489405,0.862357,4.814233,1.242243,0.751751
EKVX,0.618265,0.615816,0.029499,0.706799,0.781613,0.000000,0.000000,0.162985,1.537753,0.000000,...,3.121470,3.727703,0.789787,1.651715,2.089576,0.585060,2.542300,6.388582,1.966899,1.982254
HOP_62,0.584364,0.780409,0.018089,0.058614,0.000000,0.000000,0.000000,0.000000,1.409353,0.000000,...,2.442038,4.112533,0.463545,1.440123,2.774663,1.053660,1.568562,7.107259,1.623647,1.747985
HOP_92,1.137326,1.458041,0.000000,0.035569,0.000000,0.000000,0.000000,0.000000,1.858264,0.000000,...,2.254165,4.086317,0.513951,1.059044,2.436021,0.755965,1.508292,7.305505,1.502275,2.140661
NCI_H226,0.838398,0.286685,0.020127,0.069518,0.035271,0.028547,0.000000,0.264804,0.461380,0.060431,...,3.055124,3.270577,0.501549,1.414888,1.988946,0.040315,1.529901,6.423346,1.313037,2.195215
NCI_H23,0.662504,0.656841,0.000000,0.680351,0.517915,0.000000,0.000000,0.000000,1.200868,0.000000,...,3.119884,4.114867,0.717492,1.289604,2.712233,1.059715,1.729461,7.321189,1.872159,2.052920
NCI_H322M,0.650641,0.627746,0.000000,0.032171,0.198527,0.927342,0.000000,0.000000,3.125208,0.000000,...,2.499484,4.488952,0.409880,1.030774,2.196846,0.090183,1.067315,4.004412,1.371966,1.678744
NCI_H460,1.317466,0.286402,0.060136,0.043719,0.086571,0.095243,0.000000,1.628783,2.236777,0.047102,...,2.202643,3.654447,0.451344,0.811302,1.634463,0.407917,0.847372,4.932496,1.283987,1.037368
NCI_H522,0.870533,1.371235,0.033316,0.072972,0.483322,0.034023,0.000000,0.456816,0.862880,0.041820,...,3.098842,5.087594,1.635884,2.108846,2.239053,1.237790,1.752577,5.347634,1.265557,2.137117
IGROV1,0.524677,0.637974,0.000000,0.000000,0.214661,0.000000,0.000000,0.000000,1.858124,0.000000,...,2.188584,3.847716,0.478634,0.843296,2.085765,0.411463,1.584289,5.884019,1.398296,1.617393
OVCAR_3,0.817811,0.555374,0.022670,0.000000,0.000000,0.067640,0.000000,0.000000,0.490461,0.000000,...,1.761911,3.206415,0.271671,0.488833,1.988972,0.860634,0.700473,5.427707,0.900560,1.377862
OVCAR_4,1.239832,1.277259,0.017954,0.085341,0.096856,0.021942,0.000000,0.139429,1.998315,0.040983,...,1.790226,4.046447,0.295332,0.749709,2.387338,1.184883,1.188717,6.754861,1.114953,1.672231
OVCAR_5,0.361421,0.134705,0.056577,0.056299,0.000000,0.014644,0.000000,0.091694,0.062084,0.030664,...,2.633350,4.384533,0.052474,0.301610,2.040391,0.186418,0.887341,4.067854,0.344686,1.638959
OVCAR_8,1.147079,1.340488,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.868882,0.000000,...,1.573452,4.104630,0.205381,0.448423,2.491538,1.504605,1.263022,7.119616,1.720782,1.597827
SK_OV_3,0.871177,0.826886,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.465086,0.000000,...,2.257174,3.795684,0.374348,0.931595,2.317796,0.985476,1.884891,5.430657,1.297638,1.188901
NCI_ADR_RES,2.422618,2.752160,0.016345,0.024607,0.339376,0.000000,0.000000,0.000000,1.808731,0.000000,...,3.817726,5.635148,0.326622,0.795797,3.352103,1.946461,1.634096,8.637817,1.671239,2.703180
PC_3,0.206131,0.153104,0.225023,0.075167,0.238277,0.000000,0.000000,0.000000,0.624892,0.000000,...,2.823482,5.124841,0.659168,1.943730,1.920179,0.100480,2.242255,7.227934,1.626551,2.436690
DU_145,1.494467,0.384633,0.136934,0.166591,0.859956,0.173804,0.000000,2.073128,1.388250,0.132402,...,1.712054,2.713111,0.533587,0.665578,1.704469,0.843826,0.681730,5.246845,1.251816,0.940434
786_0,0.361155,0.000000,0.029955,0.056167,0.000000,0.016151,0.000000,0.000000,2.006872,0.000000,...,2.518782,4.195119,0.369624,0.660119,1.919836,0.043749,1.246694,6.732405,1.467530,1.762132
A498,0.440222,0.067594,0.078561,0.038646,0.083573,0.037460,0.000000,0.291472,1.424213,0.042165,...,1.470766,2.806258,0.411828,0.598354,1.297315,0.526957,0.662996,6.670161,1.290324,1.072373
ACHN,0.576425,0.220324,0.020986,0.067487,0.302748,0.014374,0.000000,0.332142,1.582792,0.176846,...,2.700318,4.206784,0.488145,0.751780,1.867363,0.064330,1.006600,6.743057,1.471234,1.944997
CAKI_1,0.882482,0.506823,0.000000,0.036152,0.000000,0.000000,0.000000,0.135979,2.266421,0.000000,...,2.167859,2.884453,0.400211,1.215057,1.710098,0.474023,1.266373,6.547058,0.761174,1.465400
RXF_393,0.572572,0.975728,0.019251,0.020413,0.147273,0.022726,0.000000,0.000000,2.311207,0.094547,...,2.707796,3.556245,0.707476,1.232096,1.799465,0.875894,1.497382,6.892488,1.406139,2.112423
SN12C,1.533733,0.660213,0.024985,0.035940,0.000000,0.000000,0.000000,0.000000,1.670165,0.000000,...,1.687773,4.720623,0.465862,0.630736,1.909151,0.920320,1.212538,7.071076,1.007346,0.865705
TK_10,0.076563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.572617,0.000000,...,2.771981,3.864523,0.365028,0.821460,1.604811,0.901689,1.590070,6.747535,0.994256,2.221326
UO_31,0.342318,0.471444,0.000000,0.000000,0.227863,0.000000,0.000000,0.000000,1.941689,0.000000,...,2.862285,4.035386,0.482844,1.157290,2.100184,0.325286,1.640838,7.231327,1.714553,2.178909

In [23]:
print("DTI unique genes: ", len(set(dti["Gene"])))
print("Top 90% variable genes: ", len(variance))
print("Total: ", len(set(variance) | (set(dti["Gene"]))))

DTI unique genes:  251
Top 90% variable genes:  2383
Total:  2582

# Preprocessed data dims

In [24]:
genes = sorted(list(set(variance) | (set(dti["Gene"]))))
gene_exp = gene_exp[genes]
gene_exp.shape

(60, 2582)

In [25]:
drug_response.shape

(1005, 60)

# Normalize

In [26]:
gene_norm_cell = pd.DataFrame(
    StandardScaler().fit_transform(gene_exp),
    index=gene_exp.index,
    columns=gene_exp.columns,
)
gene_norm_cell

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,-0.376324,2.310284,-0.370815,-0.397579,-0.579935,-0.932530,1.106057,0.387136,1.421020,-0.736827,...,-0.285390,-0.715825,-0.917886,-2.518276,-0.779108,0.932905,0.615674,1.805885,-0.815677,-1.575934
MDA_MB_231,-0.387264,-1.011604,-0.431717,-0.397579,-0.934955,-0.243114,0.676143,-1.412604,1.663180,-0.716900,...,-1.838190,-0.228654,0.227394,1.423209,-0.779108,-0.855846,1.578712,-0.832061,1.862555,-1.454818
HS578T,-0.372187,-0.980388,-0.325888,-0.225341,-1.300565,-0.591523,-0.370487,-0.159464,-0.827946,0.028936,...,0.802006,-1.185070,-0.243143,-0.324218,-0.114256,0.904508,-1.160363,-0.287149,-0.336022,0.724444
BT_549,-0.412522,1.331116,-0.431717,-0.397579,-1.021722,-0.142835,-1.038877,0.432084,-1.092816,0.217943,...,1.320986,-0.119063,-0.023918,-0.986399,1.449155,-0.673092,-1.450610,1.423024,2.390315,-0.203440
T47D,-0.397193,1.878022,-0.416104,-0.397579,-1.257820,-0.091678,2.024752,-0.322621,-0.186534,-0.118696,...,-0.332664,0.400231,0.451186,0.404201,1.552933,1.229210,1.145791,0.907319,1.683829,-1.073747
SF_268,-0.363046,0.115596,-0.431717,-0.397579,-1.719511,-1.131959,-1.968854,-0.957320,-0.854023,-0.862269,...,0.438404,-0.698035,0.812874,-0.098882,1.110562,-0.351052,-0.947517,-1.084631,-0.700465,-0.072248
SF_295,-0.390418,-0.249157,0.686757,-0.337212,1.219555,1.348892,-0.603617,0.719695,-0.192467,1.009630,...,1.055815,0.292586,-0.003184,0.989731,1.033240,0.322160,0.771929,2.211958,-0.882771,1.390531
SF_539,-0.185578,-1.011043,-0.431717,-0.365347,0.963972,0.293545,-0.435006,1.305936,0.220623,1.781673,...,0.520796,0.151541,-0.239729,-0.093653,0.197136,1.737417,0.314128,0.218988,-0.544703,0.972705
SNB_19,-0.050035,0.419132,-0.369670,-0.297337,-0.980557,1.303514,-0.520841,0.581188,0.084009,0.440593,...,2.691975,1.428340,-0.207826,0.057873,1.589442,0.204382,-1.600902,-1.091802,-0.757313,-0.350099
SNB_75,4.812989,-0.390628,-0.411499,-0.210385,0.746291,0.227105,0.296437,0.528289,-0.825563,1.304365,...,1.572359,1.134967,0.427799,-0.089610,1.824346,0.272590,-0.699092,-0.740624,1.296633,0.591615
U251,-0.387966,-0.620627,-0.230480,-0.397579,1.694171,1.374723,-0.016238,1.431536,0.684640,1.102155,...,0.305400,1.250825,0.640392,1.078655,0.962708,0.873619,-0.007329,-0.969120,-0.771126,0.282760
COLO205,-0.393816,-1.001787,-0.431717,-0.349813,0.138811,1.407657,-1.400144,0.128910,1.578786,0.691353,...,-1.807469,-1.831252,-0.756974,-0.958350,-0.779108,2.009910,-0.091106,0.817431,-0.891164,-1.818514
HCC_2998,-0.381608,-0.653948,-0.431717,-0.397579,1.230581,1.243305,1.097670,0.116560,1.383508,0.834634,...,-0.324316,-0.061510,-0.917886,-2.518276,-0.779108,1.591725,-0.007113,1.997756,-0.969005,0.270749
HCT_116,-0.374107,-0.428186,-0.083649,-0.355141,0.727586,0.111233,0.006738,-0.774246,1.205742,0.043659,...,-0.404518,0.041671,-0.881853,0.523702,-0.779108,-1.249498,1.325443,0.492904,-0.881651,-0.152037
HCT_15,-0.384622,1.544531,2.924612,-0.397579,0.644728,0.246107,-0.746591,-0.622619,0.056404,-0.263913,...,-0.103635,0.498288,-0.917886,-0.854926,-0.779108,1.085331,-0.483432,0.751411,-0.867086,-0.287100
HT29,-0.395164,-0.900272,-0.409384,-0.397579,-0.090345,1.772018,-1.833447,0.274781,1.135259,-0.759611,...,-1.269334,-1.933858,-0.885361,-0.120133,-0.779108,1.458266,0.020062,0.047128,-0.817687,-0.469969
KM12,-0.383130,1.012752,-0.406672,-0.397579,-0.072854,0.041203,-1.076922,-1.132484,2.819189,-0.154407,...,-2.179931,-0.137203,-0.875133,-2.423629,-0.779108,0.770770,0.098893,0.165719,-0.852894,-0.176373
SW_620,-0.364332,-0.927695,0.093071,-0.300697,-1.820210,-0.231994,0.938384,-1.514455,2.059352,-2.251674,...,-2.076198,-1.942947,-0.771045,-2.403439,-0.779108,-0.904660,0.590923,-1.528793,-0.797253,-3.127414
CCRF_CEM,-0.342202,-0.909908,0.110451,-0.361942,0.607104,-1.131959,2.943692,-0.326594,-0.267279,-2.260638,...,0.745790,-0.815727,0.649291,0.986655,-0.670655,-1.732985,3.520655,-0.773170,2.377623,-0.493086
HL_60,-0.376827,-0.827252,-0.396332,-0.361089,-1.111847,-1.050821,0.112309,-0.373536,-0.695170,-1.670426,...,-2.177302,-1.875286,-0.758773,0.084066,-0.779108,-1.652910,2.050291,-0.541100,-0.225396,0.047291
K_562,-0.412522,0.853591,0.026417,-0.397579,-0.109806,-1.131959,0.746618,-1.163972,-2.078436,-1.308958,...,-1.179407,-2.029919,0.188925,0.507101,-0.779108,-1.694218,1.589762,-0.972404,-0.837674,-0.367640
MOLT_4,-0.218953,-0.696978,-0.362249,-0.276261,-0.018417,-0.779673,1.288255,-0.484830,-1.562255,-1.772271,...,-1.713925,-0.657245,0.474653,0.820802,-0.470769,-1.413316,1.637121,0.108246,1.428510,-2.665203
RPMI_8226,-0.333622,-0.531197,0.065426,-0.071027,-2.002778,-0.908230,-0.606488,-0.682447,-0.410917,-0.947643,...,-0.917603,-1.762977,-0.576771,0.849997,1.224776,-1.408058,-0.301813,-0.682600,-0.000201,-2.142546
SR,-0.412522,-0.756697,-0.431717,-0.397579,-1.287040,-1.131959,-0.497409,-0.712458,-0.840823,-1.233904,...,-1.535931,-1.916641,-0.805509,0.061684,0.409525,-1.473036,0.190596,-0.862848,-0.910615,-2.124410
LOXIMVI,-0.412522,-1.024671,-0.431717,-0.397579,-1.043293,-1.084074,-0.577098,-1.135501,-0.882689,-0.353765,...,-0.422053,0.607489,-0.874722,0.203243,-0.779108,0.772310,0.439440,-1.292001,-0.969005,0.559236
MALME_3M,3.443198,-0.863670,-0.431717,2.037170,0.116974,-1.105437,0.225812,2.424287,0.886041,0.007434,...,-0.545689,0.777780,-0.513865,0.825469,-0.779108,0.924387,-0.594111,-0.841510,-0.910650,0.101390
M14,0.607077,-0.775931,-0.003895,-0.141589,-0.683776,-1.018384,1.255308,1.656863,1.917072,0.381550,...,0.618948,1.343957,-0.427528,0.416332,-0.631621,-0.838712,-0.847043,0.174024,-0.623153,0.642919
SK_MEL_2,1.110651,-0.960617,-0.263353,0.717720,-1.089864,-1.070521,-0.310564,2.600784,-0.504241,-0.072106,...,0.025252,0.797144,0.439571,0.351420,0.696162,0.060445,-0.780482,-0.042463,0.433775,0.406478
SK_MEL_28,2.519314,-0.999480,-0.431717,1.944324,-0.314705,-1.094078,0.910472,2.321673,0.708583,-0.369154,...,0.077472,0.822042,0.160860,-0.009224,-0.679993,1.433100,-0.886959,-1.403925,-0.890631,-0.131454
SK_MEL_5,2.074816,-0.587464,0.283818,2.202526,-1.307599,-1.063445,-0.456124,0.153770,-0.499296,0.114938,...,0.383292,-0.414078,-0.245260,0.517098,-0.475695,1.920305,-1.196813,0.956741,-0.721934,-0.097842
UACC_257,1.539929,-1.018908,-0.407906,4.785293,-1.132211,-1.131959,0.395205,1.028575,0.568685,0.222138,...,0.635346,0.067616,0.210369,0.797876,-0.779108,1.748692,0.191783,-1.229744,-0.862086,-0.602448
UACC_62,1.866126,-1.034076,-0.353060,2.323109,0.042429,-1.131959,1.544180,0.505745,0.727482,0.365121,...,0.755606,0.686232,0.891706,0.849516,-0.708944,0.466325,0.613609,0.120038,-0.800225,0.716898
MDA_MB_435,-0.334248,-0.983218,-0.431717,3.341539,-0.122034,-1.131959,0.609704,2.291710,1.333770,0.106623,...,0.761986,1.367465,-0.500030,0.866918,-0.779108,-0.413054,0.088179,-1.026267,-0.853150,0.673200
MDA_N,-0.176196,-0.928908,-0.319464,0.727040,-2.175680,-0.998720,-0.454724,1.389274,0.540219,-1.111123,...,0.317979,-0.371590,-0.417847,-0.161652,-0.779108,-0.899979,-1.624650,-1.019073,-0.633309,-0.427440
A549,-0.412522,0.115472,-0.407906,-0.397579,1.202263,1.439569,-1.534727,-1.095711,-0.609115,0.771827,...,-0.788346,-0.872986,-0.777817,0.090264,-0.779108,-0.535594,-0.918457,0.701517,-0.846226,-0.449670
EKVX,0.117129,1.516467,1.326672,-0.397579,1.586743,2.050263,-0.776119,-0.237235,0.677163,0.358320,...,0.513626,0.590759,-0.529739,0.820022,-0.003211,0.676473,-0.488569,0.501279,-0.413373,0.526533
HOP_62,-0.368599,-0.712512,0.086998,-0.397579,1.140747,0.624351,-0.634773,-0.097342,-0.124034,0.643957,...,0.057525,0.545965,0.361231,0.499590,0.040268,0.698790,0.375819,-1.101469,0.969644,0.972161
HOP_92,-0.385867,-0.620375,-0.431717,-0.397579,0.115615,0.504671,0.994395,0.594397,0.021764,1.339876,...,1.020267,0.495493,-0.003275,1.076711,-0.779108,-0.207803,-0.550679,0.021502,0.858660,1.095087
NCI_H226,-0.360428,-0.172497,-0.403404,-0.346301,-0.139874,0.618499,0.368113,-0.765941,0.059387,1.690584,...,-2.128636,0.388457,-0.720675,1.081478,-0.723607,0.474716,-0.125961,0.519807,-0.620577,0.548089
NCI_H23,0.097309,0.624160,-0.364076,-0.397579,0.745258,0.157004,1.222998,0.778244,-0.050087,0.282831,...,0.469477,0.760700,0.928938,0.381806,-0.779108,-1.107794,-0.194160,1.746977,1.245221,1.104811
NCI_H322M,-0.388414,-0.638158,-0.431717,-0.397579,1.206534,1.041908,-0.699271,-0.740540,1.396147,1.827037,...,0.307477,0.564598,0.439253,0.838778,0.904804,-1.554033,-0.280768,-1.219468,1.130294,-0.951814
NCI_H460,-0.379761,0.285637,-0.199132,0.022488,0.404812,1.068956,-0.774465,0.534856,-0.425208,0.929494,...,0.163785,-0.618148,-0.043575,-0.335919,0.515797,-0.325147,-0.998872,0.306499,0.551755,-0.376339
NCI_H522,-0.357839,1.780157,-0.410753,-0.342513,0.178451,-1.089672,1.484033,-0.087574,0.612760,-1.970527,...,0.929723,0.840495,1.198589,0.982855,3.256823,-0.954013,0.893085,2.444970,1.703797,-0.118926
IGROV1,-0.412522,0.439808,-0.373661,-0.397579,0.153564,-1.053473,-0.225400,-1.019082,-0.605447,-0.673311,...,-0.362640,-2.001117,0.303041,-0.489887,-0.779108,-1.187810,0.235576,-0.920935,0.082223,0.213669
OVCAR_3,-0.412522,-0.947561,-0.431717,-0.284508,-0.017928,-0.729724,-1.422334,-0.912961,-1.511876,-1.457553,...,-0.697638,0.296996,-0.917886,-0.903467,-0.522283,0.828934,-0.695712,-0.839125,0.109650,-0.069275
OVCAR_4,-0.348570,-0.216961,-0.412241,-0.366132,1.478018,-0.548861,-0.180158,0.226136,-0.624140,-0.627473,...,0.966982,0.876060,-0.210888,-0.261028,-0.033089,0.004316,-0.269424,-0.339715,-0.449285,0.753650
OVCAR_5,-0.370334,0.858070,-0.402945,-0.327589,-0.553640,1.415064,1.042340,-1.107004,-0.293503,-1.321075,...,0.338227,0.032561,-0.470363,0.462393,-0.749438,-1.038625,0.081378,-0.096306,-0.894754,-0.912476
OVCAR_8,-0.412522,1.734241,-0.259907,-0.397579,0.901740,-1.131959,-0.016428,-0.881237,-1.194046,0.053859,...,0.588697,0.467901,2.231180,-0.457853,0.775395,0.017439,0.033305,0.158667,1.287863,0.979823
SK_OV_3,-0.412522,0.670331,-0.388386,-0.397579,1.570761,0.452212,-0.787558,-0.654484,-0.664154,-0.315204,...,0.683417,-1.940562,2.713901,-0.530605,1.203235,0.170772,-0.058332,-0.785799,0.982898,-0.067446
NCI_ADR_RES,-0.394082,1.970265,5.916502,-0.397579,1.426236,-1.046980,2.264891,-0.526133,0.037242,1.473709,...,1.185808,-0.214550,3.693867,0.542850,2.539952,-0.015871,2.528447,1.561217,2.266906,1.921210
PC_3,-0.356194,1.064557,-0.431717,-0.397579,0.294594,0.737117,-0.020784,1.553651,-0.232705,0.900614,...,0.616415,0.362175,-0.848434,-2.383058,-0.621706,0.115317,0.148639,0.699065,-0.481323,1.046987
DU_145,-0.287685,0.446013,-0.278865,-0.130602,-0.366911,0.856885,-0.820118,-0.440503,0.104536,0.166059,...,0.258123,-0.201586,-0.390198,-0.358955,0.515992,-0.898040,-0.500302,0.217815,0.669220,-0.181422
786_0,-0.370432,-0.693298,-0.044742,-0.397579,0.297322,0.891908,-0.685529,-0.485696,-0.201143,0.041903,...,-0.181114,0.637731,-0.882948,0.528578,-0.013054,-0.141910,-0.509098,-0.335350,0.591355,0.739726
A498,-0.383562,-0.251763,0.659989,-0.366523,0.565353,1.294461,-0.773281,0.111221,-0.937671,1.699805,...,0.174261,0.413866,-0.852585,-2.381473,-0.703289,0.211338,-1.741676,1.254753,-0.576959,0.701130
ACHN,-0.361949,1.363690,0.287988,-0.356486,1.058970,1.460299,0.099174,-0.802260,-0.535678,0.950918,...,0.549893,1.061001,-0.879049,1.283624,-0.736882,0.180655,-0.625386,1.591469,-0.835957,0.746331
CAKI_1,-0.385430,-0.423729,1.718744,-0.397579,0.052081,0.637048,-1.016331,-0.353674,-1.105135,0.200305,...,0.609479,0.657301,-0.116333,-0.775794,-0.779108,-0.549772,-0.010604,-1.302681,0.029836,0.624798
RXF_393,-0.397225,0.994947,-0.226498,-0.397579,-0.194416,0.417522,-0.246060,0.173245,-0.495245,0.570675,...,0.290635,1.296649,-0.031213,0.350200,-0.779108,-0.555621,-0.888336,-0.516759,-0.823175,0.838988
SN12C,-0.385590,-0.607872,-0.431717,-0.397579,-0.913514,-1.070610,-0.441032,-0.753503,-1.668625,0.175779,...,0.071230,0.720948,3.445401,0.209637,2.153511,0.706708,0.962773,0.216988,0.840155,0.949725
TK_10,-0.412522,1.111490,-0.046114,-0.397579,0.105940,1.236563,-0.021378,-0.843028,-0.865751,-0.303890,...,0.282816,0.816970,-0.917886,-0.169731,0.805199,-0.485298,-0.200232,0.323617,0.742670,0.749108
UO_31,-0.412522,1.918705,2.069072,-0.397579,1.746604,0.728447,0.335499,-0.671492,-0.038543,0.903021,...,0.164655,1.051029,0.464573,0.844101,0.237918,0.313929,-0.306111,0.214178,0.529090,1.049091

In [27]:
gene_norm_gene = pd.DataFrame(
    StandardScaler().fit_transform(gene_exp.T),
    index=gene_exp.columns,
    columns=gene_exp.index,
).T
gene_norm_gene

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,-0.983581,0.567781,-0.976554,-1.004311,-0.030365,-0.867297,0.137685,-0.062226,0.539043,-0.213555,...,0.068459,-0.402870,-1.004311,-1.004311,-1.004311,0.542967,0.475431,0.731664,-0.928765,0.282236
MDA_MB_231,-0.898728,-0.871638,-0.911263,-0.911263,-0.150181,-0.382089,-0.034996,-0.853015,0.518682,-0.217658,...,-0.692272,-0.196866,-0.423512,0.764109,-0.911263,-0.428974,0.738848,-0.558363,0.297709,0.276238
HS578T,-1.124311,-1.083195,-1.096359,-1.059812,-0.282807,-0.737077,-0.379520,-0.397794,-0.536672,0.142348,...,0.681687,-0.719975,-0.781212,0.046884,-0.749300,0.553251,-0.374961,-0.391857,-0.803155,2.051378
BT_549,-1.140064,0.029856,-1.140064,-1.140064,-0.248784,-0.431592,-0.629763,-0.135119,-0.686885,0.166994,...,0.862791,-0.228284,-0.682019,-0.356678,0.118886,-0.454298,-0.546880,0.468719,0.585543,1.191549
T47D,-1.095793,0.218823,-1.097394,-1.104249,-0.341995,-0.415769,0.265066,-0.529092,-0.300487,-0.053781,...,-0.094894,-0.032820,-0.456091,0.276679,0.113188,0.544340,0.546281,0.132026,0.154877,0.469901
SF_268,-0.983777,-0.424864,-1.013360,-1.013360,-0.317088,-1.013360,-0.797695,-0.712112,-0.449568,-0.251269,...,0.505764,-0.376918,-0.125277,0.225690,0.055839,-0.140374,-0.187793,-0.720996,-0.875217,1.416440
SF_295,-1.246225,-0.886228,-0.779467,-1.231423,0.111648,0.342261,-0.674187,-0.221748,-0.477125,0.279519,...,0.414237,-0.260027,-0.836012,0.357588,-0.335897,-0.122908,0.195964,0.563939,-1.218216,1.877669
SF_539,-1.078624,-1.163949,-1.210668,-1.195250,0.201487,-0.215655,-0.526731,0.200238,-0.180523,0.833436,...,0.311800,-0.196296,-0.872054,-0.002342,-0.673155,0.814035,0.157676,-0.259047,-0.998269,1.888544
SNB_19,-0.909958,-0.359886,-1.109004,-1.088003,-0.179095,0.716989,-0.422116,0.010074,-0.081747,0.371134,...,1.795855,0.616581,-0.753023,0.262318,0.284461,0.129253,-0.582339,-0.833562,-1.024613,1.229507
SNB_75,1.775623,-0.964880,-1.296272,-1.215007,0.065035,-0.344336,-0.383487,-0.265073,-0.736815,0.527585,...,0.809050,0.185738,-0.624784,-0.079106,0.147003,-0.089147,-0.378824,-0.839009,-0.156327,1.563645
U251,-1.224706,-1.009561,-1.145643,-1.239024,0.376449,0.514376,-0.423929,0.237040,0.001664,0.473952,...,0.170861,0.289752,-0.459301,0.557335,-0.277957,0.302880,-0.012033,-0.894682,-1.139758,1.380595
COLO205,-0.991109,-0.951446,-1.001859,-0.979290,0.169827,0.749028,-0.620961,-0.182450,0.616703,0.486589,...,-0.731980,-0.910614,-0.922500,-0.234014,-1.001859,1.149411,0.170429,0.240555,-0.963371,0.120701
HCC_2998,-1.109279,-0.905199,-1.128062,-1.128062,0.422778,0.603236,0.080799,-0.268126,0.491763,0.519281,...,-0.011747,-0.172266,-1.128062,-1.128062,-1.128062,0.900602,0.150595,0.816203,-1.128062,1.592828
HCT_116,-1.150455,-0.872805,-1.020443,-1.152376,0.090555,-0.358693,-0.402981,-0.812167,0.206786,-0.058877,...,-0.210501,-0.269229,-1.154538,0.248404,-1.171388,-0.849272,0.534275,-0.148871,-1.130435,0.990473
HCT_15,-1.055803,0.340222,0.698969,-1.074325,0.437241,0.023214,-0.403828,-0.551235,0.017124,0.108179,...,0.280545,0.267057,-1.074325,-0.128495,-1.074325,0.817206,0.079447,0.322370,-1.016112,1.451145
HT29,-1.095725,-1.010906,-1.095493,-1.105422,-0.026568,0.840971,-0.863718,-0.239631,0.277285,-0.344759,...,-0.565797,-1.062531,-1.089828,0.042182,-1.105422,0.687932,0.082058,-0.276094,-1.032687,0.896451
KM12,-1.027426,-0.116854,-1.032570,-1.043408,0.011022,-0.278158,-0.589667,-0.850304,1.007372,-0.024497,...,-0.974823,-0.220937,-1.023458,-0.999329,-1.043408,0.340383,0.145253,-0.179581,-0.989091,1.097768
SW_620,-0.726814,-0.678227,-0.545455,-0.711369,-0.202102,-0.220489,0.184672,-0.735291,0.813724,-0.702283,...,-0.641593,-0.716349,-0.688611,-0.702186,-0.750469,-0.296587,0.508541,-0.702209,-0.677933,-0.568104
CCRF_CEM,-0.915377,-0.873635,-0.749929,-0.934169,0.087338,-0.947591,0.413097,-0.471531,-0.308641,-0.906100,...,0.346158,-0.503062,-0.331486,0.427660,-0.900576,-0.890998,1.260332,-0.598100,0.371421,0.681039
HL_60,-0.825855,-0.727936,-0.829697,-0.828758,-0.104598,-0.794428,-0.096532,-0.334554,-0.300955,-0.543099,...,-0.778509,-0.781048,-0.774438,0.292340,-0.844054,-0.741588,1.036212,-0.351036,-0.517881,1.301422
K_562,-0.856730,0.079024,-0.640296,-0.856730,0.284117,-0.856730,0.213661,-0.661777,-0.856730,-0.324636,...,-0.234151,-0.856730,-0.292893,0.681514,-0.856730,-0.761140,1.122138,-0.507875,-0.789657,1.343671
MOLT_4,-0.818763,-0.746640,-0.890663,-0.867548,0.102212,-0.699666,0.167743,-0.448916,-0.712723,-0.657318,...,-0.630384,-0.349013,-0.298053,0.567640,-0.767698,-0.694429,0.832827,-0.119653,0.153095,-0.435805
RPMI_8226,-0.914530,-0.654445,-0.701325,-0.786924,-0.273517,-0.786976,-0.237725,-0.471459,-0.103257,-0.158367,...,-0.099180,-0.824039,-0.770596,0.974291,0.308768,-0.672963,0.296265,-0.400496,-0.406589,0.083590
SR,-0.875341,-0.703606,-0.875341,-0.875341,-0.049196,-0.875341,-0.185463,-0.445549,-0.299751,-0.295633,...,-0.440509,-0.820667,-0.817099,0.459201,-0.196047,-0.648907,0.487522,-0.462238,-0.845002,0.081067
LOXIMVI,-1.023713,-0.984432,-1.023713,-1.023713,-0.184039,-0.991180,-0.400746,-0.824034,-0.502208,-0.058047,...,-0.034217,0.169997,-1.002735,0.296435,-1.023713,0.418438,0.362794,-0.850087,-1.023713,1.709932
MALME_3M,1.256556,-1.040887,-1.165608,0.091884,0.108726,-1.145620,-0.206657,0.954055,0.268534,0.097665,...,-0.139646,0.243994,-0.947800,0.633548,-1.165608,0.526473,-0.127364,-0.724109,-1.134069,1.519058
M14,-0.552573,-0.987585,-0.946125,-1.021469,-0.186212,-1.064475,0.058096,0.434427,0.639659,0.205477,...,0.425376,0.419112,-0.899572,0.313177,-1.062553,-0.570648,-0.298485,-0.218549,-0.970999,1.712377
SK_MEL_2,-0.161487,-1.075186,-1.066562,-0.556453,-0.202168,-1.105840,-0.344950,1.142082,-0.364036,0.112423,...,0.253206,0.318143,-0.394892,0.447536,-0.244314,0.056658,-0.170535,-0.238096,-0.367554,1.870667
SK_MEL_28,0.663636,-1.056664,-1.110879,0.054486,-0.006016,-1.083373,0.033178,0.878652,0.188172,-0.086733,...,0.225429,0.268652,-0.550565,0.189851,-1.054110,0.817184,-0.246974,-0.984902,-1.070067,1.305421
SK_MEL_5,0.515681,-0.777799,-0.684378,0.296897,-0.190786,-0.989263,-0.312195,-0.135319,-0.279761,0.274545,...,0.517253,-0.232666,-0.679512,0.586088,-0.861037,1.247381,-0.296805,0.388711,-0.907685,1.482711
UACC_257,-0.041460,-1.071055,-1.101221,1.223928,-0.321893,-1.111607,-0.225604,0.088457,0.005727,0.090237,...,0.380489,-0.192809,-0.580916,0.445201,-1.111607,0.801683,0.125791,-0.913558,-1.061188,0.764543
UACC_62,0.071771,-1.175054,-1.174614,0.048247,-0.088621,-1.209821,0.042625,-0.227980,0.005507,0.091537,...,0.383662,0.011062,-0.336397,0.412569,-1.172478,0.055960,0.242532,-0.338883,-1.128150,1.612163
MDA_MB_435,-1.061004,-1.046564,-1.107426,0.715766,0.028964,-1.107426,-0.081149,0.826980,0.451019,0.135023,...,0.576357,0.502859,-0.894755,0.612190,-1.107426,-0.277078,0.184209,-0.786987,-1.048311,1.836976
MDA_N,-0.913574,-0.980286,-1.022373,-0.404123,-0.385433,-0.970185,-0.226191,0.758721,0.404156,-0.301052,...,0.709849,-0.107532,-0.770874,0.405544,-1.088496,-0.400759,-0.452267,-0.683896,-0.874721,1.601656
A549,-1.087997,-0.489760,-1.076478,-1.087997,0.455519,0.787291,-0.728557,-0.853138,-0.400166,0.527842,...,-0.231245,-0.525947,-1.014928,0.270172,-1.087997,-0.308961,-0.235084,0.164203,-1.023785,1.105005
EKVX,-0.994478,-0.023197,-0.459326,-1.320372,0.353288,1.028588,-0.708594,-0.634286,-0.014655,0.099762,...,0.285586,-0.031682,-1.115419,0.438968,-0.868600,0.189437,-0.253467,-0.161253,-1.026234,1.625303
HOP_62,-1.256155,-1.083508,-1.025314,-1.283640,0.287190,0.034844,-0.614466,-0.511572,-0.341804,0.312003,...,0.086448,0.004579,-0.596734,0.333893,-0.798433,0.265368,0.217736,-0.986926,-0.239903,2.049173
HOP_92,-1.170780,-0.950010,-1.186810,-1.186810,0.032796,-0.006001,-0.023213,-0.091674,-0.214113,0.701087,...,0.663879,0.027001,-0.714770,0.665041,-1.186810,-0.225411,-0.172738,-0.307640,-0.241130,2.105606
NCI_H226,-1.160721,-0.783878,-1.176613,-1.166062,-0.163175,-0.059823,-0.327463,-0.830550,-0.303682,0.658446,...,-1.095488,-0.149719,-1.097745,0.468788,-1.160492,0.025491,-0.106545,-0.167249,-1.027574,1.398900
NCI_H23,-0.862199,-0.316516,-1.144180,-1.177468,0.259739,-0.221259,0.094051,0.045065,-0.211544,0.210246,...,0.411349,0.201655,-0.197410,0.358571,-1.177468,-0.727182,0.034896,0.664965,0.000553,2.215106
NCI_H322M,-1.123585,-0.912304,-1.137918,-1.137918,0.372928,0.412595,-0.522507,-0.728972,0.452946,0.973661,...,0.300841,0.094871,-0.445481,0.571625,-0.190522,-0.961573,-0.011914,-0.917714,-0.064089,0.646170
NCI_H460,-1.226997,-0.572698,-1.135375,-1.038990,0.054781,0.341287,-0.648183,-0.181923,-0.480990,0.432282,...,0.129030,-0.568125,-0.795444,-0.122486,-0.509727,-0.353523,-0.440061,-0.216743,-0.459794,0.976332
NCI_H522,-1.014196,0.199973,-1.034565,-1.019240,0.059374,-1.016315,0.133028,-0.377708,0.067421,-0.863288,...,0.561253,0.186159,-0.069909,0.563955,1.003721,-0.573458,0.455981,0.882670,0.189138,1.104569
IGROV1,-1.080957,-0.328123,-1.053004,-1.080957,0.156722,-1.023992,-0.302435,-0.807861,-0.394682,-0.213056,...,0.009233,-1.067030,-0.447066,-0.029863,-1.080957,-0.687233,0.305273,-0.698028,-0.533782,1.586638
OVCAR_3,-1.080201,-0.992744,-1.080201,-1.018247,0.229405,-0.758614,-0.646345,-0.719339,-0.789428,-0.566682,...,-0.085169,0.159137,-1.080201,-0.158436,-0.918233,0.653360,-0.030871,-0.610428,-0.461729,1.630432
OVCAR_4,-1.201698,-0.794102,-1.231921,-1.225462,0.423146,-0.805264,-0.423944,-0.300750,-0.543020,-0.322577,...,0.647193,0.207019,-0.863145,-0.035645,-0.801248,-0.116520,-0.054826,-0.527928,-0.962684,1.915741
OVCAR_5,-1.080932,-0.194931,-1.092047,-1.072085,-0.118256,0.655264,0.024185,-0.888158,-0.313259,-0.594702,...,0.305379,-0.155545,-0.883964,0.365709,-1.089062,-0.647150,0.146548,-0.322675,-1.068433,0.651085
OVCAR_8,-1.176237,0.262471,-1.090068,-1.176237,0.334851,-1.176237,-0.295322,-0.818027,-0.747026,0.115836,...,0.512247,0.081789,0.526841,-0.064058,-0.249194,-0.031529,0.169640,-0.178948,0.047430,2.186018
SK_OV_3,-1.105630,-0.188824,-1.083511,-1.105630,0.634280,0.113385,-0.471770,-0.617581,-0.407026,0.009023,...,0.668959,-1.059823,0.893501,-0.013609,0.097619,0.154587,0.218983,-0.623403,-0.028461,1.504695
NCI_ADR_RES,-1.328301,-0.085672,1.220762,-1.337639,0.001558,-1.286014,-0.016105,-0.897163,-0.512574,0.309386,...,0.297978,-0.602947,0.666511,-0.009905,0.252867,-0.434126,0.716327,0.088417,0.072186,1.940215
PC_3,-1.189159,-0.177506,-1.222891,-1.222891,0.041978,0.119913,-0.387170,0.355218,-0.371671,0.434278,...,0.396931,-0.078028,-1.187198,-1.153533,-1.133691,-0.078422,0.109214,0.009440,-0.971621,2.020766
DU_145,-1.149803,-0.318512,-1.152163,-1.079826,0.089218,0.521721,-0.524346,-0.545338,0.000671,0.343791,...,0.513211,-0.161909,-0.907322,0.125161,-0.336097,-0.553823,0.033069,-0.033772,-0.200148,1.664506
786_0,-1.137047,-0.961219,-0.977572,-1.162293,0.105333,0.294001,-0.537059,-0.619983,-0.295156,0.061382,...,0.018946,0.116458,-1.144309,0.403010,-0.727486,-0.165239,-0.131735,-0.473728,-0.357080,1.863733
A498,-1.176554,-0.747769,-0.631357,-1.178778,0.258427,0.694247,-0.548939,-0.279518,-0.625073,1.040236,...,0.295806,0.072465,-1.158975,-1.119289,-1.148778,0.105503,-0.695834,0.457731,-0.976396,2.049354
ACHN,-1.246053,-0.146791,-0.949405,-1.255590,0.129372,0.491848,-0.445820,-0.913801,-0.599861,0.321400,...,0.226928,0.128500,-1.255849,0.575116,-1.252083,-0.153245,-0.349575,0.340090,-1.209756,1.595731
CAKI_1,-1.205602,-0.884772,-0.175174,-1.222176,0.000160,0.076137,-0.691966,-0.600485,-0.763628,0.107972,...,0.428658,0.091665,-0.801356,-0.309120,-1.222176,-0.446539,0.063670,-1.040366,-0.696444,1.779275
RXF_393,-1.280066,-0.198529,-1.184458,-1.289946,-0.074341,-0.089319,-0.465880,-0.344697,-0.502459,0.316941,...,0.263055,0.427203,-0.798473,0.296965,-1.289946,-0.474700,-0.368718,-0.651522,-1.208908,2.046108
SN12C,-1.086645,-0.874066,-1.101837,-1.101837,-0.231021,-1.060320,-0.440548,-0.720034,-0.923808,0.112955,...,0.140372,0.138328,1.010424,0.216207,0.463635,0.298851,0.506431,-0.180208,-0.223795,1.887265
TK_10,-1.167446,-0.116787,-0.986642,-1.167446,0.024664,0.506647,-0.345431,-0.813448,-0.617224,-0.137956,...,0.244921,0.173041,-1.167446,0.017723,-0.284140,-0.383725,-0.015091,-0.149607,-0.299802,1.811637
UO_31,-1.288981,0.143599,-0.116115,-1.288981,0.358320,0.026282,-0.355053,-0.849094,-0.363217,0.342966,...,0.059506,0.162058,-0.589830,0.408210,-0.721819,-0.049564,-0.184377,-0.327626,-0.529420,1.904454

# Make matrices association matrices by setting 0 threshold and min max scaler.

In [28]:
def min_max_scale(data):
    data = data[data > 0].fillna(0)
    scaler = MinMaxScaler(feature_range=(0, 1))
    return pd.DataFrame(
        scaler.fit_transform(data), index=data.index, columns=data.columns
    )

In [29]:
A_dc = min_max_scale(drug_response)
A_dc

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.159753,0.000000,0.000000,...,0.0,0.162567,0.109683,0.000000,0.000000,0.089914,0.000000,0.000000,0.000000,0.031215
752,0.081408,0.000000,0.000000,0.000000,0.000000,0.024577,0.017263,0.030245,0.000000,0.000000,...,0.0,0.162665,0.061714,0.000000,0.000000,0.092498,0.049962,0.000000,0.039326,0.000000
755,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.113088,0.000000,0.000000,...,0.0,0.174146,0.100148,0.000000,0.000000,0.052200,0.000000,0.000000,0.124472,0.000000
757,0.054502,0.000000,0.000000,0.000000,0.000000,0.131221,0.048824,0.104256,0.130015,0.000000,...,0.0,0.000000,0.000000,0.038995,0.000000,0.000000,0.000000,0.032982,0.000000,0.000000
762,0.093854,0.000000,0.000000,0.000000,0.313990,0.058097,0.000000,0.152350,0.000000,0.000000,...,0.0,0.299381,0.094998,0.000000,0.407777,0.209339,0.025021,0.180820,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.015081,0.102516,0.394201,0.204184,0.000000,0.259748,0.042127,0.374084,0.000000,0.268540,...,0.0,0.000000,0.032402,0.345499,0.098083,0.088327,0.267569,0.182869,0.000000,0.150076
812926,0.000000,0.000000,0.000000,0.000000,0.197910,0.049056,0.000000,0.000000,0.000000,0.064482,...,0.0,0.000000,0.031417,0.320812,0.475256,0.140043,0.087173,0.000000,0.788265,0.204690
812927,0.627408,0.054456,0.000000,0.000000,0.008039,0.000000,0.000000,0.038330,0.000000,0.323923,...,0.0,0.000000,0.000000,0.000122,0.000000,0.000000,0.010284,0.000000,0.026309,0.015718
813488,0.054722,0.080082,0.240613,0.338327,0.016212,0.101161,0.000000,0.168305,0.000000,0.343097,...,0.0,0.000000,0.119264,0.883439,0.073416,0.000000,0.195352,0.039764,0.067507,0.157257
820919,0.000000,0.350455,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.037675,0.000000,0.000000,0.046676,0.000000,0.000000,0.095815

In [30]:
A_cg = min_max_scale(gene_norm_gene + gene_norm_cell)
A_cg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.370515,0.086808,0.512226,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.465915,0.228217,0.762567,0.000000,0.000000
MDA_MB_231,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.191000,0.000000,0.570189,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.484745,0.000000,0.725930,0.000000
HS578T,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.061157,...,0.330604,0.000000,0.000000,0.000000,0.000000,0.460197,0.000000,0.000000,0.000000,0.718860
BT_549,0.000000,0.472878,0.000000,0.000000,0.000000,0.000000,0.000000,0.079342,0.000000,0.137443,...,0.486600,0.000000,0.000000,0.000000,0.368038,0.000000,0.000000,0.568494,1.000000,0.255892
T47D,0.000000,0.728561,0.000000,0.000000,0.000000,0.000000,0.682145,0.000000,0.000000,0.000000,...,0.000000,0.179670,0.000000,0.311285,0.391058,0.559888,0.353917,0.312337,0.617874,0.000000
SF_268,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.210384,0.000000,0.154314,0.057974,0.273768,0.000000,0.000000,0.000000,0.000000,0.348108
SF_295,0.000000,0.000000,0.000000,0.000000,0.603709,0.549280,0.000000,0.133039,0.000000,0.460296,...,0.327564,0.015921,0.000000,0.615968,0.163675,0.062901,0.202446,0.834194,0.000000,0.846372
SF_539,0.000000,0.000000,0.000000,0.000000,0.528543,0.025298,0.000000,0.402412,0.010479,0.933735,...,0.185523,0.000000,0.000000,0.000000,0.000000,0.805463,0.098683,0.000000,0.000000,0.740983
SNB_19,0.000000,0.020586,0.000000,0.000000,0.000000,0.656252,0.000000,0.157970,0.000591,0.289830,...,1.000000,1.000000,0.000000,0.146385,0.439827,0.105325,0.000000,0.000000,0.000000,0.227742
SNB_75,1.000000,0.000000,0.000000,0.000000,0.367942,0.000000,0.000000,0.070325,0.000000,0.654105,...,0.530637,0.645847,0.000000,0.000000,0.462699,0.057911,0.000000,0.000000,0.383186,0.558152
U251,0.000000,0.000000,0.000000,0.000000,0.939039,0.613573,0.000000,0.445802,0.179353,0.562755,...,0.106123,0.753368,0.040642,0.747943,0.160719,0.371406,0.000000,0.000000,0.000000,0.430762
COLO205,0.000000,0.000000,0.000000,0.000000,0.139969,0.700483,0.000000,0.000000,0.573750,0.420589,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.997360,0.016591,0.317939,0.000000,0.000000
HCC_2998,0.000000,0.000000,0.000000,0.000000,0.749809,0.599750,0.351070,0.000000,0.490067,0.483421,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.786797,0.030011,0.845632,0.000000,0.482614
HCT_116,0.000000,0.000000,0.000000,0.000000,0.371032,0.000000,0.000000,0.000000,0.369138,0.000000,...,0.000000,0.000000,0.000000,0.352992,0.000000,0.000000,0.388982,0.103387,0.000000,0.217131
HCT_15,0.000000,0.654868,0.507699,0.000000,0.490680,0.087475,0.000000,0.000000,0.019215,0.000000,...,0.039420,0.374266,0.000000,0.000000,0.000000,0.600608,0.000000,0.322685,0.000000,0.301455
HT29,0.000000,0.000000,0.000000,0.000000,0.000000,0.848690,0.000000,0.009391,0.369142,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.677529,0.021360,0.000000,0.000000,0.110447
KM12,0.000000,0.311285,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.350778,0.051066,0.000000,0.000000,0.238615
SW_620,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334563,0.000000,0.750824,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.229966,0.000000,0.000000,0.000000
CCRF_CEM,0.000000,0.000000,0.000000,0.000000,0.314934,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.243313,0.000000,0.071323,0.646598,0.000000,0.000000,1.000000,0.000000,0.923782,0.048675
HL_60,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004700,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.172085,0.000000,0.000000,0.645578,0.000000,0.000000,0.349279
K_562,0.000000,0.324042,0.000000,0.000000,0.079051,0.000000,0.286071,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.543412,0.000000,0.000000,0.567226,0.000000,0.000000,0.252764
MOLT_4,0.000000,0.000000,0.000000,0.000000,0.038002,0.000000,0.433747,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.039633,0.634769,0.000000,0.000000,0.516619,0.000000,0.531479,0.000000
RPMI_8226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.834030,0.359941,0.000000,0.000000,0.000000,0.000000,0.000000
SR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.238139,0.050106,0.000000,0.141836,0.000000,0.000000,0.000000
LOXIMVI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.380203,0.000000,0.228443,0.000000,0.375905,0.167797,0.000000,0.000000,0.587651
MALME_3M,0.713315,0.000000,0.000000,0.354298,0.102356,0.000000,0.005706,0.902608,0.301727,0.037526,...,0.000000,0.499664,0.000000,0.667035,0.000000,0.458019,0.000000,0.000000,0.000000,0.419650
M14,0.008272,0.000000,0.000000,0.000000,0.000000,0.000000,0.391268,0.558740,0.668154,0.209600,...,0.232701,0.862170,0.000000,0.333518,0.000000,0.000000,0.000000,0.000000,0.000000,0.609955
SK_MEL_2,0.144061,0.000000,0.000000,0.026837,0.000000,0.000000,0.000000,1.000000,0.000000,0.014395,...,0.062047,0.545394,0.010027,0.365267,0.106054,0.036968,0.000000,0.000000,0.022252,0.589717
SK_MEL_28,0.483099,0.000000,0.000000,0.332624,0.000000,0.000000,0.281117,0.855047,0.234350,0.000000,...,0.067494,0.533367,0.000000,0.082579,0.000000,0.710387,0.000000,0.000000,0.000000,0.304024
SK_MEL_5,0.393178,0.000000,0.000000,0.415931,0.000000,0.000000,0.000000,0.004930,0.000000,0.139066,...,0.200664,0.000000,0.000000,0.504355,0.000000,1.000000,0.000000,0.404326,0.000000,0.358642
UACC_257,0.227433,0.000000,0.000000,1.000000,0.000000,0.000000,0.050525,0.298443,0.150112,0.111535,...,0.226353,0.000000,0.000000,0.568311,0.000000,0.805123,0.066424,0.000000,0.000000,0.041978
UACC_62,0.294128,0.000000,0.000000,0.394620,0.000000,0.000000,0.472715,0.074212,0.191553,0.163051,...,0.253857,0.340988,0.124625,0.577001,0.000000,0.164879,0.179072,0.000000,0.000000,0.603161
MDA_MB_435,0.000000,0.000000,0.000000,0.675180,0.000000,0.000000,0.157458,0.833236,0.466421,0.086281,...,0.298216,0.914620,0.000000,0.676220,0.000000,0.000000,0.056973,0.000000,0.000000,0.650065
MDA_N,0.000000,0.000000,0.000000,0.053737,0.000000,0.000000,0.000000,0.573891,0.246795,0.000000,...,0.229026,0.000000,0.000000,0.111503,0.000000,0.000000,0.000000,0.000000,0.000000,0.304089
A549,0.000000,0.000000,0.000000,0.000000,0.751815,0.723276,0.000000,0.000000,0.000000,0.464052,...,0.000000,0.000000,0.000000,0.164784,0.000000,0.000000,0.000000,0.260161,0.000000,0.169713
EKVX,0.000000,0.518845,0.121524,0.000000,0.879816,1.000000,0.000000,0.000000,0.173134,0.163560,...,0.178084,0.273398,0.000000,0.575586,0.000000,0.273357,0.000000,0.102182,0.000000,0.557265
HOP_62,0.000000,0.000000,0.000000,0.000000,0.647578,0.214104,0.000000,0.000000,0.000000,0.341329,...,0.032081,0.269225,0.000000,0.381052,0.000000,0.304373,0.124149,0.000000,0.245220,0.782440
HOP_92,0.000000,0.000000,0.000000,0.000000,0.067305,0.161966,0.289319,0.134315,0.000000,0.728734,...,0.375270,0.255508,0.000000,0.796295,0.000000,0.000000,0.000000,0.000000,0.207513,0.828889
NCI_H226,0.000000,0.000000,0.000000,0.000000,0.000000,0.181456,0.012110,0.000000,0.000000,0.838730,...,0.000000,0.116747,0.000000,0.708752,0.000000,0.157909,0.000000,0.105949,0.000000,0.504215
NCI_H23,0.000000,0.106893,0.000000,0.000000,0.455773,0.000000,0.392354,0.219968,0.000000,0.176055,...,0.196270,0.470608,0.164174,0.338486,0.000000,0.000000,0.000000,0.724821,0.418627,0.859765
NCI_H322M,0.000000,0.000000,0.000000,0.000000,0.716296,0.472417,0.000000,0.000000,0.483226,1.000000,...,0.135548,0.322491,0.000000,0.644809,0.167650,0.000000,0.000000,0.000000,0.358285,0.000000
NCI_H460,0.000000,0.000000,0.000000,0.000000,0.208428,0.458042,0.000000,0.094295,0.000000,0.486227,...,0.065247,0.000000,0.000000,0.000000,0.001425,0.000000,0.000000,0.026973,0.030902,0.155381
NCI_H522,0.000000,0.688008,0.000000,0.000000,0.107855,0.000000,0.481729,0.000000,0.177752,0.000000,...,0.332227,0.502051,0.253304,0.707172,1.000000,0.000000,0.282173,1.000000,0.636097,0.255254
IGROV1,0.000000,0.038806,0.000000,0.000000,0.140716,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.113125,0.000000,0.000000,0.466229
OVCAR_3,0.000000,0.000000,0.000000,0.000000,0.095906,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.223056,0.000000,0.000000,0.000000,0.467942,0.000000,0.000000,0.000000,0.404296
OVCAR_4,0.000000,0.000000,0.000000,0.000000,0.862190,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.359678,0.529644,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.691297
OVCAR_5,0.000000,0.230411,0.000000,0.000000,0.000000,0.672435,0.317722,0.000000,0.000000,0.000000,...,0.143411,0.000000,0.000000,0.378592,0.000000,0.000000,0.047673,0.000000,0.000000,0.000000
OVCAR_8,0.000000,0.693769,0.000000,0.000000,0.560802,0.000000,0.000000,0.000000,0.000000,0.060590,...,0.245317,0.268807,0.618970,0.000000,0.123506,0.000000,0.042448,0.000000,0.448709,0.819863
SK_OV_3,0.000000,0.167302,0.000000,0.000000,1.000000,0.183704,0.000000,0.000000,0.000000,0.000000,...,0.301343,0.000000,0.809592,0.000000,0.305326,0.102712,0.033602,0.000000,0.320727,0.372207
NCI_ADR_RES,0.000000,0.654812,1.000000,0.000000,0.647514,0.000000,0.669922,0.000000,0.000000,0.636661,...,0.330624,0.000000,0.978579,0.243652,0.655508,0.000000,0.678683,0.495737,0.786023,1.000000
PC_3,0.000000,0.308211,0.000000,0.000000,0.152637,0.278360,0.000000,0.510002,0.000000,0.476628,...,0.225799,0.138953,0.000000,0.000000,0.000000,0.011647,0.053933,0.212915,0.000000,0.794462
DU_145,0.000000,0.044301,0.000000,0.000000,0.000000,0.447766,0.000000,0.000000,0.027494,0.182044,...,0.171872,0.000000,0.000000,0.000000,0.042223,0.000000,0.000000,0.055307,0.157626,0.384077
786_0,0.000000,0.000000,0.000000,0.000000,0.182606,0.385179,0.000000,0.000000,0.000000,0.036878,...,0.000000,0.368811,0.000000,0.425904,0.000000,0.000000,0.000000,0.000000,0.078725,0.674222
A498,0.000000,0.000000,0.004012,0.000000,0.373589,0.645926,0.000000,0.000000,0.000000,0.978342,...,0.104743,0.237824,0.000000,0.000000,0.000000,0.100023,0.000000,0.514624,0.000000,0.712298
ACHN,0.000000,0.422819,0.000000,0.000000,0.538920,0.634050,0.000000,0.000000,0.000000,0.454286,...,0.173095,0.581686,0.000000,0.849780,0.000000,0.008653,0.000000,0.580459,0.000000,0.606528
CAKI_1,0.000000,0.000000,0.216269,0.000000,0.023692,0.231640,0.000000,0.000000,0.000000,0.110071,...,0.231323,0.366257,0.000000,0.000000,0.000000,0.000000,0.011099,0.000000,0.000000,0.622587
RXF_393,0.000000,0.276720,0.000000,0.000000,0.000000,0.106599,0.000000,0.000000,0.000000,0.316927,...,0.123376,0.842992,0.000000,0.295872,0.000000,0.000000,0.000000,0.000000,0.000000,0.747159
SN12C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.103094,...,0.047150,0.420200,1.000000,0.194688,0.614275,0.317443,0.307301,0.011053,0.207120,0.734700
TK_10,0.000000,0.345615,0.000000,0.000000,0.059230,0.566189,0.000000,0.000000,0.000000,0.000000,...,0.117593,0.484132,0.000000,0.000000,0.122299,0.000000,0.000000,0.052292,0.148820,0.663161
UO_31,0.000000,0.716559,0.273628,0.000000,0.954596,0.245133,0.000000,0.000000,0.000000,0.444884,...,0.049949,0.593220,0.000000,0.572533,0.000000,0.083457,0.000000,0.000000,0.000000,0.764885

In [31]:
A_dg = (
    pd.DataFrame(
        np.ones([len(A_dc.index), len(A_cg.columns)]),
        index=A_dc.index,
        columns=A_cg.columns,
    )
    / 2
)
for _, i in dti.iterrows():
    A_dg.loc[int(i["NSC"]), i["Gene"]] = 1
A_dg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
752,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
755,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
757,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
762,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812926,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812927,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
813488,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
820919,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

In [32]:
A_dg.sum().sum()

1297758.0

In [33]:
print(
    "Drug Density: ",
    round(len(A_dc.values.nonzero()[0]) / drug_response.size, 4) * 100,
    "%",
)
print("Cell Density: ", round(len(A_cg.values.nonzero()[0]) / A_cg.size, 4) * 100, "%")
print("Gene Density: ", round(len(A_dg.values.nonzero()[0]) / A_dg.size, 5) * 100, "%")

Drug Density:  38.62 %
Cell Density:  45.540000000000006 %
Gene Density:  100.0 %

# Similarity

In [34]:
def normalize_similarity_matrix(df, gamma=None):
    similarity_matrix = rbf_kernel(df.values, gamma=gamma)
    scaler = MinMaxScaler()
    normalized_matrix = scaler.fit_transform(similarity_matrix.reshape(-1, 1))
    normalized_df = pd.DataFrame(
        normalized_matrix.reshape(similarity_matrix.shape),
        index=df.index,
        columns=df.index,
    )

    return normalized_df

In [35]:
cell_sim = normalize_similarity_matrix(drug_response.T)
cell_sim.to_csv("../nci_data/cell_sim.csv")
cell_sim

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
MCF7,1.000000,0.091148,0.097479,0.189910,0.264853,0.260940,0.308346,0.301156,0.168405,0.143665,...,0.275445,0.235828,0.274520,0.090947,0.243209,0.148226,0.261767,0.279787,0.098606,0.144671
MDA_MB_231,0.091148,1.000000,0.236713,0.299046,0.153116,0.282035,0.147971,0.149372,0.258491,0.061478,...,0.347378,0.210362,0.229396,0.049011,0.160505,0.097864,0.205049,0.266621,0.249394,0.121447
HS578T,0.097479,0.236713,1.000000,0.255637,0.142899,0.171487,0.134565,0.153475,0.127367,0.153692,...,0.272006,0.092625,0.166615,0.115165,0.097272,0.075460,0.244480,0.160875,0.178296,0.098436
BT_549,0.189910,0.299046,0.255637,1.000000,0.303038,0.439894,0.278444,0.348725,0.336355,0.143203,...,0.439289,0.309444,0.421629,0.112152,0.244465,0.180701,0.335153,0.389244,0.198106,0.215764
T47D,0.264853,0.153116,0.142899,0.303038,1.000000,0.320490,0.264082,0.229959,0.239270,0.122100,...,0.361556,0.261223,0.293035,0.085810,0.251317,0.181088,0.244079,0.323435,0.178821,0.235660
SF_268,0.260940,0.282035,0.171487,0.439894,0.320490,1.000000,0.399016,0.449761,0.574509,0.145265,...,0.478146,0.598044,0.581712,0.084511,0.440453,0.274908,0.337637,0.663886,0.194951,0.232815
SF_295,0.308346,0.147971,0.134565,0.278444,0.264082,0.399016,1.000000,0.374788,0.268687,0.145373,...,0.352885,0.306691,0.360767,0.096910,0.304306,0.205345,0.300473,0.381351,0.120485,0.181005
SF_539,0.301156,0.149372,0.153475,0.348725,0.229959,0.449761,0.374788,1.000000,0.287546,0.204457,...,0.317757,0.347749,0.478665,0.113540,0.328980,0.198982,0.374695,0.427560,0.101011,0.166793
SNB_19,0.168405,0.258491,0.127367,0.336355,0.239270,0.574509,0.268687,0.287546,1.000000,0.080607,...,0.389389,0.461809,0.407669,0.042424,0.279377,0.157328,0.208455,0.482008,0.156032,0.149653
SNB_75,0.143665,0.061478,0.153692,0.143203,0.122100,0.145265,0.145373,0.204457,0.080607,1.000000,...,0.155035,0.085208,0.149449,0.136039,0.120567,0.090138,0.295595,0.140737,0.063685,0.114384
U251,0.289158,0.213703,0.148160,0.342228,0.266113,0.620630,0.404624,0.491294,0.498391,0.145603,...,0.451150,0.480215,0.501252,0.084818,0.356205,0.216416,0.320520,0.526676,0.128777,0.170331
COLO205,0.188739,0.221370,0.147444,0.165562,0.128880,0.201308,0.168490,0.169146,0.148063,0.087476,...,0.259350,0.161545,0.165238,0.059204,0.146278,0.095007,0.214802,0.218496,0.160914,0.095476
HCC_2998,0.181498,0.384590,0.163610,0.340316,0.233391,0.453630,0.234078,0.245687,0.451962,0.079473,...,0.443283,0.436406,0.392475,0.056470,0.243148,0.158666,0.242671,0.417889,0.224529,0.166085
HCT_116,0.396748,0.250450,0.151102,0.283069,0.235523,0.491328,0.353359,0.420481,0.314343,0.149133,...,0.436333,0.424102,0.447120,0.105323,0.384879,0.259095,0.362856,0.489712,0.177586,0.215900
HCT_15,0.152882,0.257787,0.149366,0.270050,0.169423,0.289453,0.207006,0.188686,0.211350,0.071576,...,0.345860,0.259729,0.266318,0.059269,0.273535,0.239502,0.208063,0.288504,0.211604,0.260165
HT29,0.327392,0.274496,0.172481,0.253364,0.229029,0.348550,0.276059,0.303926,0.243129,0.124387,...,0.398532,0.320299,0.341924,0.096587,0.262032,0.188467,0.301565,0.352810,0.209078,0.191703
KM12,0.145065,0.184358,0.136527,0.174302,0.098845,0.217556,0.183790,0.207899,0.142294,0.079217,...,0.236851,0.186366,0.193195,0.066602,0.144184,0.119604,0.220565,0.234903,0.116603,0.103412
SW_620,0.318816,0.267088,0.139912,0.274435,0.202916,0.489029,0.300049,0.349949,0.381744,0.113541,...,0.424580,0.454268,0.390117,0.071491,0.308449,0.203716,0.301198,0.470582,0.181992,0.168119
CCRF_CEM,0.190411,0.053395,0.030001,0.119523,0.106442,0.223389,0.187115,0.240784,0.134518,0.059096,...,0.170701,0.211569,0.223274,0.025082,0.176036,0.109177,0.130380,0.237655,0.033806,0.070512
HL_60,0.253991,0.119493,0.060360,0.159921,0.139853,0.267778,0.195056,0.233771,0.167340,0.071493,...,0.226625,0.241490,0.261691,0.045550,0.220088,0.152030,0.183439,0.275887,0.084755,0.113240
K_562,0.122332,0.145334,0.072196,0.134591,0.100085,0.209862,0.169175,0.198322,0.140148,0.053998,...,0.194623,0.179908,0.192372,0.036782,0.150208,0.094476,0.133588,0.206316,0.067443,0.083359
MOLT_4,0.245861,0.074165,0.046693,0.171095,0.174280,0.315941,0.244279,0.295262,0.197833,0.077702,...,0.236633,0.290621,0.335551,0.041512,0.262033,0.156824,0.174074,0.322487,0.056640,0.118138
RPMI_8226,0.187452,0.206785,0.103526,0.245301,0.214357,0.295738,0.213473,0.216204,0.218552,0.065993,...,0.376295,0.237282,0.264877,0.047038,0.184861,0.135292,0.183230,0.269834,0.122833,0.135481
SR,0.160331,0.014293,0.013743,0.045737,0.041659,0.096549,0.116499,0.143798,0.043920,0.053857,...,0.063720,0.075602,0.086541,0.023682,0.091869,0.064641,0.091863,0.097721,0.011116,0.034561
LOXIMVI,0.347038,0.221180,0.137184,0.318564,0.268267,0.497586,0.369360,0.469347,0.321885,0.161989,...,0.402908,0.409255,0.501818,0.116343,0.428803,0.282842,0.370952,0.505917,0.144984,0.245330
MALME_3M,0.147316,0.268135,0.158473,0.275100,0.285827,0.285510,0.193392,0.195787,0.237750,0.093128,...,0.337131,0.226881,0.270667,0.081454,0.221872,0.154122,0.225449,0.291511,0.212672,0.214208
M14,0.266268,0.282559,0.138869,0.354982,0.262042,0.503597,0.335994,0.372510,0.354847,0.113982,...,0.417087,0.466015,0.473758,0.103118,0.399237,0.272923,0.317113,0.499638,0.179705,0.264091
SK_MEL_2,0.146041,0.403618,0.250086,0.326929,0.196033,0.339755,0.204815,0.197909,0.271531,0.089342,...,0.365590,0.273212,0.242916,0.073045,0.208065,0.139767,0.265943,0.309120,0.275368,0.149585
SK_MEL_28,0.097865,0.369560,0.167880,0.254092,0.197423,0.261812,0.135441,0.122953,0.268171,0.051314,...,0.319718,0.201806,0.200127,0.039182,0.148648,0.082661,0.164650,0.242463,0.219785,0.129937
SK_MEL_5,0.288825,0.246449,0.154327,0.359084,0.320190,0.493134,0.378835,0.388357,0.361588,0.132108,...,0.465346,0.395608,0.418514,0.097429,0.340159,0.235954,0.311399,0.448582,0.155603,0.209152
UACC_257,0.146232,0.336139,0.141320,0.298632,0.254335,0.349825,0.200156,0.174577,0.301741,0.062890,...,0.346191,0.276420,0.261419,0.053612,0.224476,0.139306,0.189565,0.319304,0.269979,0.186994
UACC_62,0.328188,0.212729,0.127191,0.299082,0.320073,0.484784,0.383012,0.381052,0.308076,0.138409,...,0.381939,0.384091,0.437424,0.113410,0.430008,0.272995,0.313640,0.490402,0.163032,0.245222
MDA_MB_435,0.222205,0.209803,0.153011,0.231942,0.163870,0.268598,0.228786,0.247501,0.177861,0.118552,...,0.333611,0.225463,0.231110,0.075424,0.175785,0.130261,0.258127,0.262091,0.129058,0.136549
MDA_N,0.379290,0.443790,0.297639,0.512497,0.401062,0.640846,0.446564,0.468843,0.473992,0.195764,...,0.656234,0.539239,0.567327,0.151082,0.462777,0.311582,0.470965,0.629097,0.337126,0.330982
A549,0.330847,0.262918,0.171048,0.380541,0.315038,0.596134,0.408308,0.420818,0.495188,0.138034,...,0.513198,0.568235,0.534313,0.096815,0.438354,0.291753,0.325555,0.589126,0.211499,0.262582
EKVX,0.084197,0.290371,0.189378,0.239794,0.182669,0.220886,0.131035,0.094397,0.191024,0.062549,...,0.279102,0.194748,0.175740,0.060764,0.177638,0.126697,0.170409,0.195587,0.338117,0.178707
HOP_62,0.294156,0.269223,0.157502,0.386643,0.306817,0.612315,0.389407,0.461231,0.471379,0.146833,...,0.447231,0.547296,0.586220,0.081097,0.392802,0.266155,0.317575,0.552831,0.171243,0.243991
HOP_92,0.062496,0.049758,0.048499,0.061878,0.063982,0.055012,0.065524,0.044364,0.031580,0.042248,...,0.085222,0.029630,0.052388,0.079614,0.059584,0.048698,0.089704,0.061834,0.048657,0.078014
NCI_H226,0.152916,0.218657,0.150435,0.345688,0.215793,0.426229,0.234109,0.263349,0.342503,0.103255,...,0.293578,0.308908,0.326415,0.084687,0.282456,0.182379,0.248907,0.387023,0.163019,0.184863
NCI_H23,0.256572,0.261758,0.113066,0.362102,0.249210,0.573812,0.360931,0.370382,0.474460,0.094959,...,0.393994,0.546072,0.468895,0.059846,0.374076,0.228896,0.270578,0.579080,0.142014,0.180697
NCI_H322M,0.124343,0.282269,0.175951,0.303205,0.220043,0.350311,0.163677,0.156594,0.308344,0.070925,...,0.314539,0.316981,0.271471,0.071634,0.269536,0.178090,0.181921,0.319770,0.348410,0.198547
NCI_H460,0.351957,0.070707,0.053337,0.168084,0.176643,0.348628,0.318849,0.338278,0.219886,0.082749,...,0.254663,0.338287,0.323657,0.048534,0.302773,0.186008,0.193084,0.351885,0.057507,0.113425
NCI_H522,0.223526,0.177850,0.122639,0.246109,0.256008,0.379710,0.251335,0.300920,0.226385,0.132271,...,0.336200,0.329974,0.303605,0.079059,0.294886,0.216135,0.247188,0.360400,0.175812,0.172197
IGROV1,0.223779,0.286247,0.237244,0.334545,0.310249,0.391493,0.272186,0.263716,0.316287,0.140905,...,0.444395,0.329920,0.374171,0.137689,0.333688,0.227582,0.356289,0.400963,0.349054,0.306344
OVCAR_3,0.222659,0.367566,0.307023,0.411131,0.291697,0.437851,0.285997,0.288238,0.339375,0.130348,...,0.547032,0.386348,0.368670,0.080700,0.244918,0.165401,0.316444,0.384064,0.267839,0.178416
OVCAR_4,0.105950,0.341470,0.201648,0.338918,0.189785,0.290749,0.165050,0.156785,0.245330,0.075329,...,0.301879,0.214285,0.229230,0.055208,0.184332,0.117388,0.196240,0.248812,0.254026,0.167902
OVCAR_5,0.123945,0.343454,0.142341,0.265910,0.187007,0.332591,0.162489,0.146928,0.301970,0.049017,...,0.317824,0.310088,0.256700,0.046083,0.193136,0.123307,0.179944,0.293109,0.266703,0.150713
OVCAR_8,0.223540,0.295041,0.139671,0.359132,0.279943,0.593059,0.334628,0.341727,0.487416,0.093961,...,0.479858,0.598184,0.480416,0.053405,0.369471,0.212473,0.262171,0.556866,0.182704,0.196820
SK_OV_3,0.145088,0.202382,0.140316,0.257824,0.236554,0.288363,0.178399,0.204265,0.220494,0.110340,...,0.283434,0.301098,0.266153,0.073214,0.251039,0.169001,0.209574,0.288917,0.265413,0.181116
NCI_ADR_RES,0.022065,0.082345,0.024451,0.097529,0.059083,0.133903,0.065054,0.043557,0.116564,0.006771,...,0.115839,0.135128,0.110474,0.002523,0.089899,0.102235,0.040776,0.112271,0.051408,0.105636
PC_3,0.275445,0.347378,0.272006,0.439289,0.361556,0.478146,0.352885,0.317757,0.389389,0.155035,...,1.000000,0.394268,0.427933,0.103062,0.282284,0.215064,0.365258,0.461730,0.238089,0.241133
DU_145,0.235828,0.210362,0.092625,0.309444,0.261223,0.598044,0.306691,0.347749,0.461809,0.085208,...,0.394268,1.000000,0.493668,0.049288,0.435884,0.252017,0.245646,0.581304,0.179557,0.197725
786_0,0.274520,0.229396,0.166615,0.421629,0.293035,0.581712,0.360767,0.478665,0.407669,0.149449,...,0.427933,0.493668,1.000000,0.096040,0.425218,0.287374,0.359082,0.526223,0.165602,0.259862
A498,0.090947,0.049011,0.115165,0.112152,0.085810,0.084511,0.096910,0.113540,0.042424,0.136039,...,0.103062,0.049288,0.096040,1.000000,0.099324,0.080612,0.201918,0.092469,0.073245,0.128977
ACHN,0.243209,0.160505,0.097272,0.244465,0.251317,0.440453,0.304306,0.328980,0.279377,0.120567,...,0.282284,0.435884,0.425218,0.099324,1.000000,0.434044,0.293693,0.510089,0.198577,0.341860
CAKI_1,0.148226,0.097864,0.075460,0.180701,0.181088,0.274908,0.205345,0.198982,0.157328,0.090138,...,0.215064,0.252017,0.287374,0.080612,0.434044,1.000000,0.200039,0.307163,0.143791,0.359311
RXF_393,0.261767,0.205049,0.244480,0.335153,0.244079,0.337637,0.300473,0.374695,0.208455,0.295595,...,0.365258,0.245646,0.359082,0.201918,0.293693,0.200039,1.000000,0.331114,0.175407,0.232912
SN12C,0.279787,0.266621,0.160875,0.389244,0.323435,0.663886,0.381351,0.427560,0.482008,0.140737,...,0.461730,0.581304,0.526223,0.092469,0.510089,0.307163,0.331114,1.000000,0.198640,0.264984
TK_10,0.098606,0.249394,0.178296,0.198106,0.178821,0.194951,0.120485,0.101011,0.156032,0.063685,...,0.238089,0.179557,0.165602,0.073245,0.198577,0.143791,0.175407,0.198640,1.000000,0.216054
UO_31,0.144671,0.121447,0.098436,0.215764,0.235660,0.232815,0.181005,0.166793,0.149653,0.114384,...,0.241133,0.197725,0.259862,0.128977,0.341860,0.359311,0.232912,0.264984,0.216054,1.000000

In [36]:
print("Min:", np.min(cell_sim.values))
print("Max:", np.max(cell_sim.values))
print("Mean:", np.mean(cell_sim.values))
print("Median:", np.median(cell_sim.values))

Min: 0.0
Max: 0.9999999999999999
Mean: 0.2599368405695073
Median: 0.2397313158545162

In [37]:
gene_sim = normalize_similarity_matrix(gene_norm_cell.T)
os.makedirs("../nci_data/gene_sim", exist_ok=True)
chunks = np.array_split(gene_sim, 25)

for i, chunk in tqdm(enumerate(chunks)):
    chunk.to_parquet(
        f"../nci_data/gene_sim/gene_sim_part_{i}.parquet", compression="gzip"
    )
gene_sim

/Users/inouey2/base/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
25it [00:06,  4.11it/s]

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
A2M,1.000000,0.060190,0.090301,0.391793,0.099959,0.062216,0.166070,0.340668,0.138102,0.156964,...,0.185882,0.210333,0.128977,0.165382,0.119324,0.222604,0.069420,0.076629,0.097455,0.140388
ABCA3,0.060190,1.000000,0.275980,0.048084,0.215076,0.174623,0.159356,0.058527,0.087342,0.135836,...,0.194404,0.154588,0.187560,0.078862,0.244293,0.101630,0.123893,0.361435,0.203343,0.167400
ABCB1,0.090301,0.275980,1.000000,0.087243,0.240955,0.132595,0.166354,0.080465,0.104796,0.189396,...,0.176134,0.141762,0.229688,0.131027,0.180989,0.128992,0.187949,0.200042,0.174078,0.223905
ABCB5,0.391793,0.048084,0.087243,1.000000,0.063024,0.041796,0.164287,0.373311,0.186304,0.119026,...,0.162311,0.170567,0.114037,0.193312,0.068295,0.224850,0.086748,0.064751,0.059511,0.115838
ABCC1,0.099959,0.215076,0.240955,0.063024,1.000000,0.349966,0.127889,0.114741,0.122463,0.340527,...,0.202791,0.227102,0.182738,0.139628,0.134596,0.157619,0.154868,0.230891,0.160625,0.333414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.222604,0.101630,0.128992,0.224850,0.157619,0.175506,0.071109,0.230201,0.185125,0.284584,...,0.141732,0.190102,0.101912,0.068699,0.103096,1.000000,0.058706,0.178124,0.050863,0.194664
ZNRD1,0.069420,0.123893,0.187949,0.086748,0.154868,0.054900,0.418163,0.054293,0.126994,0.045645,...,0.055761,0.058149,0.244632,0.189314,0.128546,0.058706,1.000000,0.126709,0.250182,0.083467
ZP3,0.076629,0.361435,0.200042,0.064751,0.230891,0.211739,0.172942,0.119484,0.133095,0.218610,...,0.155753,0.153724,0.125526,0.079986,0.181292,0.178124,0.126709,1.000000,0.159002,0.197240
ZSCAN18,0.097455,0.203343,0.174078,0.059511,0.160625,0.085757,0.245629,0.075171,0.062191,0.103212,...,0.188774,0.133152,0.415823,0.193341,0.380405,0.050863,0.250182,0.159002,1.000000,0.135090
ZYX,0.140388,0.167400,0.223905,0.115838,0.333414,0.154194,0.112346,0.214361,0.067639,0.404464,...,0.392216,0.406016,0.217109,0.164701,0.156548,0.194664,0.083467,0.197240,0.135090,1.000000

In [38]:
print("Min:", np.min(gene_sim.values))
print("Max:", np.max(gene_sim.values))
print("Mean:", np.mean(gene_sim.values))
print("Median:", np.median(gene_sim.values))

Min: 0.0
Max: 1.0
Mean: 0.14953670970919472
Median: 0.1275006895525907

# NSC to SMILES

In [39]:
convert = dict(
    pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
        ["NSC", "SMILES"]
    ].values
)
SMILES = [convert[i] for i in drug_response.index]
SMILES

['CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O',
 'C1=NC2=C(N1)C(=S)N=C(N2)N',
 'C1=NC2=C(N1)C(=S)N=CN2',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC',
 'CN(CCCl)CCCl.Cl',
 'C1=NNC2=C1C(=O)NC=N2',
 'C1(=NC(=NN1)N)N',
 'CC1C(C(=O)NC(C(=O)N2CCCC2C(=O)N(CC(=O)N(C(C(=O)O1)C(C)C)C)C)C(C)C)NC(=O)C3=C4C(=C(C=C3)C)OC5=C(C(=O)C(=C(C5=N4)C(=O)NC6C(OC(=O)C(N(C(=O)CN(C(=O)C7CCCN7C(=O)C(NC6=O)C(C)C)C)C)C(C)C)C)N)C',
 'CCC1=C(C(=NC(=N1)N)N)C2=CC=C(C=C2)Cl',
 'C1=CC(=CC=C1CCCC(=O)O)N(CCCl)CCCl',
 'C1CN1P(=S)(N2CC2)N3CC3',
 'C1=CC(=CC=C1CC(C(=O)O)N)N(CCCl)CCCl.Cl',
 'C1CN1C2=NC(=NC(=N2)N3CC3)N4CC4',
 'CCC(=O)OC1CCC2C1(CCC3C2CCC4C3(CC(C(=O)C4)C)C)C',
 'CCN(CC)CCCC(C)NC1=C2C=C(C=CC2=NC3=C1C=CC(=C3)Cl)OC.Cl',
 'C1=C(C(=O)NC(=O)N1)F',
 'CC12CCC3C(C1CCC2OC(=O)CCC4=CC=CC=C4)CCC5=CC(=O)CCC35',
 'CC12CCC3C(C1CCC(=O)O2)CCC4=CC(=O)C=CC34C',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)O)OC8CC(C(C(O8)C)O)(C)O)C(=C4C(=C3C)O)O)O)O',
 'C1CN(CCN1C(=O)CCBr)C(=O)CCBr',
 'C1CNP(=O)(OC1)N(CCCl)CCCl',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N4)N',
 'C1C(C(OC1N2C=C(C(=O)NC2=O)F)CO)O',
 'C(=O)(N)NO',
 'COC1=C(C=CC(=C1)C=CC(=O)CC(=O)C=CC2=CC(=C(C=C2)O)OC)O',
 'COC1=CC=C2C(=CC1=O)C(CCC3=CC(=C(C(=C32)OC)OC)OC)NC(=O)C4=CC=CC=C4',
 'C1=C(C(=O)NC(=O)N1)N(CCCl)CCCl',
 'CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C',
 'C[N+]1=C2C(=C3C=CC(=C(C3=C1)OC)OC)C=CC4=CC5=C(C=C42)OCO5.[Cl-]',
 'C1=CC=C(C(=C1)C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl',
 'CN(C)N=NC1=C(NC=N1)C(=O)N',
 'CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)O.OS(=O)(=O)O',
 'C1CN2C(=CC=N2)N1',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N4C)N',
 'CC(=O)OC1=CC=C(C=C1)C2(C3=CC=CC=C3NC2=O)C4=CC=C(C=C4)OC(=O)C',
 'C1=CC=C2C(=C1)C(C(=O)N2)(C3=CC=C(C=C3)O)C4=CC=C(C=C4)O',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O.Cl',
 'C1C(OC(C1O)N2C=NC3=C(N=CN=C32)N)CO',
 'CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C=O)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)O.OS(=O)(=O)O',
 'C1C(C(OC1N2C=NC3=C2NC(=NC3=S)N)CO)O',
 'CC1=CC2C(CCC3(C2CCC3(C(=O)C)OC(=O)C)C)C4(C1=CC(=O)CC4)C',
 'CC1=C2C=CN=CC2=C(C3=C1NC4=CC=CC=C43)C',
 'C1C(C(OC1N2C=NC3=C2NC(=NC3=S)N)CO)O',
 'CC1=C(C(=O)NC(=O)N1)N(CCF)CCCl',
 'CC(C)NC(=O)C1=CC=C(C=C1)CNNC.Cl',
 'C1CCC(CC1)NC(=O)N(CCCl)N=O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N)O.Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N)O.Cl',
 'C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3)SCC(C(=O)O)N',
 'CN(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O',
 'C1=CC2=C(C=C(C(=C2N=C1)O)N=NC3=CC4=C(C=C3)C=C(C=C4)S(=O)(=O)O)S(=O)(=O)O',
 'CC1CC2=CC(=O)CCC2(C3C1C4CCC(C4(CC3)C)(C)O)C',
 'CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)OC(=O)N(CCCl)CCCl',
 'CCC12CN3CCC4=C(C(CC(C3)C1O2)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)NC1=CC=CC=C41.OS(=O)(=O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C',
 'CC1CCC(CC1)NC(=O)N(CCCl)N=O',
 'C1CC(=O)NC(=O)C1NC(=O)N(CCCl)N=O',
 'C1=CC(=C(N=C1)C=NNC(=S)N)O',
 'CCC(C1=C(C(=O)N2CC3=CC4=CC=CC=C4N=C3C2=C1)CO)(C(=O)O)O.[Na+]',
 'CS(=O)(=O)OCCCNCCCOS(=O)(=O)C.Cl',
 'C1=NC(=NC(=O)N1C2C(C(C(O2)CO)O)O)N',
 'C(C(C(C(C(CBr)O)O)O)O)Br',
 'C1C(C(OC1N2C=NC3=C(N=C(N=C32)Cl)N)CO)O',
 'CCC1C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)O)O',
 'C1=CC(=NC=C1O)C=NNC(=S)N',
 'C1CN(P(=O)(OC1)NCCCl)CCCl',
 'COC(=O)NC1=NC2=CC=CC=C2N1',
 'CC(=O)NC(CS)C(=O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)OC)O',
 'CC(=O)OC1=CC=C(C=C1)C2(C3=CC=CC=C3NC2=O)C4=CC=C(C=C4)OC(=O)C',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)O)F)N',
 'C1=NC2=C(C(=O)N1)N=CN2C(C=O)OC(CO)C=O',
 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CC(=O)O)C)C',
 'COC1=CC(=CC(=C1O)OC)C2C3C(COC3=O)C(C4=CC5=C(C=C24)OCO5)OC6C(C(C7C(O6)COC(O7)C8=CC=CS8)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N)O.Cl',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)O)F)N',
 'CC1=C(N=C(N=C1N)C(CC(=O)N)NCC(C(=O)N)N)C(=O)NC(C(C2=CN=CN2)OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(C(O4)CO)O)OC(=O)N)O)C(=O)NC(C)C(C(C)C(=O)NC(C(C)O)C(=O)NCCC5=NC(=CS5)C6=NC(=CS6)C(=O)NCCC[S+](C)C)O.OS(=O)(=O)[O-]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C',
 'C1=CC=C2C(=C1)C(=C(C(=O)C2=O)CC=C(Cl)Cl)O',
 'C1C(C(OC1N2C=NC(=NC2=O)N)CO)O',
 'CC1=C2COC(=O)C2=C(C(=C1OC)CC=C(C)CCC(=O)O)O',
 'C1C(O1)C(C(C2CO2)O)O',
 'CC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC(=C(C=C3)Cl)C(=O)NC(CC(=O)O)C(=O)O',
 'C1=CC2=C(C=C1CNC3=CC(=C(C=C3)C(=O)NC(CC(=O)O)C(=O)O)Cl)C(=NC(=N2)N)N',
 'CC1=C(C(=O)C(=C(C1=O)N2CC2)C(COC(=O)N)OC)N3CC3',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)NCCO)OC)N4)N',
 'C1CC(NCC1Cl)C2C(=O)NC(C(=O)N2)C3CCC(CN3)Cl.Cl',
 'CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O.Cl',
 'CCS(=O)(=O)O.CC1(N=C(N=C(N1C2=CC(=C(C=C2)OCC3=CC(=CC=C3)C(=O)N(C)C)Cl)N)N)C',
 'CC1OCC2C(O1)C(C(C(O2)OC3C4COC(=O)C4C(C5=CC6=C(C=C35)OCO6)C7=CC(=C(C(=C7)OC)O)OC)O)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.Cl',
 'CC(C)(CCCC(CC(=O)OC)(C(=O)OC1C2C3=CC4=C(C=C3CCN5C2(CCC5)C=C1OC)OCO4)O)O',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)OC8CC(C(C(O8)C)O)(C)O)O)C(=C4C(=C3C)O)O)O)O.[Mg+2]',
 'C(C1C(C(C(O1)C2=NNC(=C2O)C(=O)N)O)O)O',
 'C1=CN2C3C(C(C(O3)CO)O)OC2=NC1=N.Cl',
 'C1CC(OC1)N2C=C(C(=O)NC2=O)F',
 'C(C(C(=O)O)N)[N+](=NO)[O-].[Na+]',
 'CC1C2CC(C(C=CC=C(CC3=CC(=C(C(=C3)OC)Cl)N(C(=O)CC(C4(C1O4)C)OC(=O)C(C)N(C)C(=O)C)C)C)OC)(NC(=O)O2)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.CS(=O)(=O)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.CS(=O)(=O)O',
 'CC1=CCCC2(C(O2)C3C(CC1)C(=C)C(=O)O3)C',
 'CC(C)C12C(O1)C3C4(O3)C5(CCC6=C(C5CC7C4(C2O)O7)COC6=O)C',
 'C1C(ON=C1Cl)C(C(=O)O)N',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=NNC(=O)C6=CC=CC=C6)C)O)N)O.Cl',
 'CCOC(=O)C(CC(C)C)NC(=O)C(CC1=CC=C(C=C1)N(CCCl)CCCl)NC(=O)C',
 'CC(CN1CC(=O)NC(=O)C1)N2CC(=O)NC(=O)C2',
 'C1CCC2(CC1)C(=O)N(C(=O)N2)CCN(CCCl)CCCl',
 'CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C4=CC=CC=C43)C(=O)NC(CCC(=O)O)C(=O)O',
 'CN(C(=S)C1=CC=CC=C1)NC(=O)CC(=O)NN(C)C(=S)C2=CC=CC=C2',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5OC)N=C4C3=C2)O',
 'C(CCl)N(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O',
 'C1=CC(=C(C=C1[N+](=O)[O-])Cl)NC(=O)C2=C(C=CC(=C2)Cl)O',
 'CN1CCN(CC1)C2=CC=C(C3=NO[N+](=C23)[O-])[N+](=O)[O-]',
 'CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3.C(C(=O)O)C(CC(=O)O)(C(=O)O)O',
 'CCOC(=O)NC1=C(C(=O)C(=C(C1=O)N2CC2)NC(=O)OCC)N3CC3',
 'CCC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC=C(C=C3)C(=O)NC(CC(=O)O)C(=O)O',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)SC)OC)OC)OC',
 'CN1CCN(CC1)C2=CC=C(C3=NO[N+](=C23)[O-])[N+](=O)[O-]',
 'C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O',
 'CC(=O)OC1CC2(C(CCC2=O)C3=C1C4(C(OC(=O)C5=COC(=C54)C3=O)COC)C)C',
 'C(C(C(=O)O)NC(=O)CP(=O)(O)O)C(=O)O.[Na+]',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)O)C)C)O)OC)C)C)C)OC',
 'C1CC(C1)(C(=O)O)C(=O)O.[NH2-].[NH2-].[Pt+2]',
 'CCCCC(=O)OCC(=O)C1(CC(C2=C(C1)C(=C3C(=C2O)C(=O)C4=C(C3=O)C=CC=C4OC)O)OC5CC(C(C(O5)C)O)NC(=O)C(F)(F)F)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)Cl)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42',
 'CC(=CCC(C1=CC(=O)C2=C(C=CC(=C2C1=O)O)O)O)C',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)N)C)OC)OC(=O)N)C)C)O)OC',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=CC=CC=C5C4=O)O)(C(=O)C)O)N)O',
 'CC(C)[NH-].CC(C)[NH-].O.O.Cl[Pt+2]Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N)O.Cl',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=C3C=C(C=C4)O)C)C.CC(=O)[O-]',
 'C1N=C(NC(=O)N1C2C(C(C(O2)CO)O)O)N.Cl',
 'C1CCC(C(C1)N)N.C(=O)(C(=O)[O-])[O-].[Pt+4]',
 'CC1CC(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N.Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N(CC6=CC=CC=C6)CC7=CC=CC=C7)O.Cl',
 'CC1(CC(C2=C(C3=C(C=C2C1)C(=O)C4=C5C(=CC(=C4C3=O)O)C6(C(C(C(C(O5)O6)O)N(C)C)O)C)O)OC)O',
 'C1CCC(C(C1)[NH-])[NH-].C1=CC(=C(C=C1C(=O)O)C(=O)O)C(=O)O.[Pt+2]',
 'CC1=C(N=C(N=C1N)C(CC(=O)N)NCC(C(=O)N)N)C(=O)NC(C(C2=CN=CN2)OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(C(O4)CO)O)OC(=O)N)O)C(=O)NC(C)C(C(C)C(=O)NC(C(C)O)C(=O)NCCC5=NC(=CS5)C6=NC(=CS6)C(=O)NCCCNC(C)C7=CC=CC=C7)O.OS(=O)(=O)O',
 'C1=CC(=C2C(=C1NCCNCCO)C(=O)C3=C(C=CC(=C3C2=O)O)O)NCCNCCO',
 'CN1C2=NC=NC3=C2C(=CN3C4C(C(C(O4)COP(=O)(O)O)O)O)C(=N1)N',
 'CC1=C(C=CC(=C1)N(CCOS(=O)(=O)C)CCOS(=O)(=O)C)C=O',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O',
 'COC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC(=O)N5CCOCC5)O)C2=NC6=CC=CC=C61',
 'COC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC(=O)OC)O)C2=NC5=CC=CC=C51',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)OC)O',
 'C1C(O1)CN2C(=O)N(C(=O)N(C2=O)CC3CO3)CC4CO4',
 'CCCCCCCC(=O)OC1C2C(=C(C1OC(=C)C(=CC)C)C)C3C(C(CC2(C)OC(=O)C)OC(=O)CCC)(C(C(=O)O3)(C)O)O',
 'C1=CC(=C2C(=C1NCCNCCO)C(=O)C3=C(C=CC(=C3C2=O)O)O)NCCNCCO.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)O',
 'CC12CCC(C(C1CCC3C24CCC(C(C3)C4)(COC(=O)CN)O)(C)CO)O.Cl',
 'CN(C)CCN1C(=O)C2=CC=CC3=CC(=CC(=C32)C1=O)N',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)COP(=O)(O)O)O)O)F)N',
 'CN1C2=C(C3=CC(=C(C=C3C1=O)OC)OC)C(=O)C4=CC5=C(C=C42)OCO5',
 'CC(=NNC(=S)N1CCC1)C2=CC=CC=N2',
 'COC1=C(C(=C2C(=C1)CCC(C3=CC(=O)C(=CC=C32)SC)NC(=O)C(F)(F)F)OC)OC',
 'C1C2=C(C=CC(=C2)N)N=C3N1C(=O)C4=CC=CC=C43',
 'CCC(C)C1C(=O)NC2CSSCC(C(=O)NC(C(=O)NC(C(=O)N1)CC(C)C)C(C)C)NC2=O',
 'CCCCS(=N)(=O)CCC(C(=O)O)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C(=CC5=C4)OC)OC)O',
 'C(CCCOS(=O)(=O)N)CCCOS(=O)(=O)N',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=CC(=C2O)C1OC)O)C)C)OC(=O)N)C)C)OC)OC',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)NCC=C)C)OC)OC(=O)N)C)C)O)OC',
 'CC1C=CC2C(O2)(C(CC(OC(=O)C3C(O3)CC4CC1OC(=O)C4)C(C)C(C(=CC=CC(=CC5=COC(=N5)C)C)C)OC)O)C',
 'C1CN=C(N1)NN=CC2=C3C=CC=CC3=C(C4=CC=CC=C42)C=NNC5=NCCN5.Cl',
 'CS(=O)(=O)CS(=O)(=O)OCCCl',
 'CCCC=CC=CC(=O)OC1C(=CC(=O)OC)CC2CC(OC(=O)CC(CC3CC(C(C(O3)(CC4CC(=CC(=O)OC)CC(O4)C=CC(C1(O2)O)(C)C)O)(C)C)OC(=O)C)O)C(C)O',
 'CC1=C2C(=CC=C1)C(=C3C=CC=C(C3=N2)C(=O)NC)NC4=C(C=C(C=C4)NS(=O)(=O)C)OC.C(CS(=O)(=O)O)O',
 'C1CN(CCN1CCCCl)CCCl.Cl',
 'C1COS(=O)(=O)CS(=O)(=O)O1',
 'C1=CC(=NCCCN)C2=C(C3=C(C=CC(=O)C3=C4C2=C1N(N4)CCNCCO)O)O.Cl',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=CC=CC=C43)C)C.[I-]',
 'CC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC(=C(C(=C3)OC)OC)OC.C(=O)C(C(C(C(C(=O)O)O)O)O)O',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=CC=CC=C43)C)C.CS(=O)(=O)[O-]',
 'C1=NC(=C2N1C(=O)N(N=N2)CCCl)C(=O)N',
 'C1=NC(=C2C(=N1)N(C(=N2)Cl)C3C(C(C(O3)CO)O)O)N',
 'CC1CC=CC(=O)C2C(O2)CC(C(C3=C(C(=CC(=C3)OC)O)C(=O)O1)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N6CCOCC6)O.Cl',
 'CC(=O)O.CNCCN=C1C=CC2=C3C1=C(C4=C(C=CC(=O)C4=C3NN2CCNCCO)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N6CCOCC6C#N)O',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)SC)OC)OC)O',
 'C1CCC(C(C1)[NH-])[NH-].Cl[Pt+2](Cl)(Cl)Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN(CC)CC.Cl',
 'C1=CC(=C(C=C1C=CC2=CC(=CC(=C2)O)O)O)O',
 'CN(C)CCCN1C2=C3C(=C(C=C2)[N+](=O)[O-])NC4=C(C3=N1)C=C(C=C4)OC.CS(=O)(=O)O',
 'CC1=C(C2=C(C=CC(=C2)F)N=C1C3=CC=C(C=C3)C4=CC=CC=C4F)C(=O)O.[Na+]',
 'CC(C)CN1C=NC2=C1C3=CC=CC=C3N=C2N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)N)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN6CCN(CC6)CCO',
 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CC(=O)NC2=CC=C(C=C2)O)C)C',
 'CCC(C)C(C(CC(=O)N1CCCC1C(C(C)C(=O)NC(CC2=CC=CC=C2)C3=NC=CS3)OC)OC)N(C)C(=O)C(C(C)C)NC(=O)C(C(C)C)N(C)C',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=C1C=C(C=C3)C(=O)OC)OC)OC)OC',
 'C(CCl)NC(=O)N(CCCl)N=O',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)O)OC8CC(C(C(O8)C)O)(C)O)C(=C4C(=C3C)O)O)O)O.[Mg+2]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)OC(=O)CCC(=O)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)OC(=O)CCC(=O)O)C)OC(=O)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5N=C4C3=C2)N)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5[N+](=O)[O-])OC)N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5[N+](=O)[O-])O)N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5NC(=O)C)O)N=C4C3=C2)O',
 'C1CC(OC1CO)N2C=CC(=NC2=O)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C=CC5=C4)C=O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C=CC5=C4)CO)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CNCC.Cl',
 'CCCNCC(=O)OC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)CC.Cl',
 'CCCCNCC(=O)OC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)CC.Cl',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)O)C)C)OC(=O)CN(C)C)OC)C)C)C)OC.CS(=O)(=O)O',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)F)Cl)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CNC.Cl',
 'CCC1=CC2CC(C3=C(CN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC.C(C(C(=O)O)O)(C(=O)O)O',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)OC(=O)CCCC(=O)NCCCN(C)C)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C.Cl',
 'CC1CC2CCC3C(=C)CC(O3)CCC45CC6C(O4)C7C(O6)C(O5)C8C(O7)CCC(O8)CC(=O)OC9C(C3C(CC4C(O3)CC3(O4)CC4C(O3)C(CC3(O4)CC(C4C(O3)CC(O4)C(CC(CO)O)O)C)C)OC9CC(C1=C)O2)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5CN(C)C)O)N=C4C3=C2)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CCC(=O)O.[Na+]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C(CCCCN)N.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OP(=O)(O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C(CCC(=O)O)N.Cl',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)(F)F.Cl',
 'CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=C1C=C(C=C5)OC(=O)N6CCC(CC6)N7CCCCC7.Cl',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)CNC6=O)NC)OC',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN(C)C.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5NC(=O)CN)N=C4C3=C2)O',
 'C1=CC=C(C(=C1)C(=O)NCCCC(C(=O)O)NC(=O)C2=CC=C(C=C2)NCC3=CN=C4C(=N3)C(=NC(=N4)N)N)C(=O)O',
 'CN(C)CCCN1C2=C3C(=C(C=C2)[N+](=O)[O-])NC4=C(C3=N1)C=C(C=C4)OC',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=C3C=C(C=C4)OC)C)C.CC(=O)[O-]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)OC(C)(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5N=C4C3=C2)N)O',
 'CC=C1C(=O)NC(C(=O)OC2CC(=O)NC(C(=O)NC(CSSCCC=C2)C(=O)N1)C(C)C)C(C)C',
 'CCC(C)C(=O)OC1CC(C=C2C1C(C(C=C2)C)CCC3CC(CC(=O)O3)O)C',
 'CCC(C)(C)C(=O)OC1CC(C=C2C1C(C(C=C2)C)CCC3CC(CC(=O)O3)O)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C6C(=CC5=C4)OCO6)O',
 'C1=CC=C(C=C1)COC2=NC(=NC3=C2NC=N3)N',
 'CC1=C2CN(C=CC2=C(C3=C1C4=C(N3)C=CC(=C4)OC)C)C',
 'CC1=C2C=C[N+](=CC2=C(C3=C1SC4=CC=CC=C43)C)C.[I-]',
 'C1COCCN1CCC(=O)N2CC(=CC3=CC(=C(C=C3)Cl)Cl)C(=O)C(=CC4=CC(=C(C=C4)Cl)Cl)C2.Cl',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)C(NC6=O)O)NC)OC',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5NC(=O)CN)N=C4C3=C2)O.Cl',
 'CC1=NC2=C(C=C(C=C2)CN(C)C3=CC=C(S3)C(=O)NC(CCC(=O)O)C(=O)O)C(=O)N1',
 'CCCCCCCCCCCCCCCCCCOP(=O)([O-])OC1CC[N+](CC1)(C)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2Cl)O',
 'CN1CCC(C(C1)O)C2=C(C=C(C3=C2OC(=CC3=O)C4=CC=CC=C4Cl)O)O.Cl',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1O)O)OC(=O)C5=CC=CC=C5)(CO4)OC(=O)C)O)C)O',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)CNC6=O)N(C)C(=O)C9=CC=CC=C9)OC',
 'CC(C(=O)O)OC1=CC=C(C=C1)OC2=CN=C3C=CC(=CC3=N2)Cl.[Na+]',
 'CCCCCC(=O)NC(C1=CC=CC=C1)C(C(=O)OC2CC3(C(C4C(C(CC5C4(CO5)OC(=O)C)OC6C(C(C(CO6)O)O)O)(C(=O)C(C(=C2C)C3(C)C)O)C)OC(=O)C7=CC=CC=C7)O)O',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C2(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)C(=C)C)OC(=O)C7=CC(=CC(=C7)F)F)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C(C)(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)CC(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC6=CC=CC=C6C=C5)NC(=O)C7=CC=CC=C7)O)O)OC(=O)C8=CC=CC=C8)(CO4)OC(=O)C)O)C)OC(=O)C',
 'COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=CC=C3)Br)OC.C(CS(=O)(=O)O)O',
 'CS(=O)(=O)O.C1=CC(=CC(=C1)Br)NC2=NC=NC3=CC(=NC=C32)N',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)OC(C)(C)C)O)O)OC(=O)C6CCCCC6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=CC=CC=C1C(C(C(=O)OC2CC3(C(C4C(C(CC5C4(CO5)OC(=O)C)O)(C(=O)C(C(=C2C)C3(C)C)OC(=O)C)C)OC(=O)C6=CC=CC=C6)O)O)NC(=O)C7=CC=CC=C7',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CO7)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=C(C=C7)F)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=C1C=C(C=C5)O',
 'CC1=C(C=NO1)C(=O)NC2=CC=C(C=C2)C(F)(F)F',
 'COC1=CC=CC(=C1N)C2=CC(=O)C3=CC=CC=C3O2',
 'B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN=C2)(O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CC=C(C=C6)O)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CO)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC(C)C)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CCSC)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(C)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)CN)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C6CCCN6)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CN=CN6)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CNC7=CC=CC=C76)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C6=CC=C(C=C6)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CS)N)O.Cl',
 'CCC(C)C(C(=O)NN=CC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=CC=CC=C51)N.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C[N+](C)(C)C)O.[Cl-]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(=O)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C[N+]6=CC=CC=C6)O.[Cl-]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=C(C=C6)NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=C(C=C6)NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=CC=C6NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=CC=C6NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O.Cl',
 'CC1=C(C2=C(C3(CC3)C(C(=O)C2=C1)(C)O)C)CO',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)OC(=O)C(C)(CO)CO)C)C)O)OC)C)C)C)OC',
 'CC1CCCC2(C(O2)CC(OC(=O)CC(C(C(=O)C(C1O)C)(C)C)O)C(=CC3=CSC(=N3)C)C)C',
 'COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=CC=C3)Cl)OC',
 'COC1=C(C=C2C(=C1)C(=O)N3CC(=C)CC3C=N2)OCCCOC4=C(C=C5C(=C4)N=CC6CC(=C)CN6C5=O)OC',
 'C1COCCN1C2=CC(=O)C3=C(O2)C(=CC=C3)C4=CC=CC=C4',
 'CC1=C(C(=O)C(=C(C1=O)N2CC2)CO)N3CC3',
 'CC(C(=O)O)OC1=CC=C(C=C1)OC2=CN=C3C=CC(=CC3=N2)Cl',

In [40]:
def get_morgan_fingerprint(SMILES):
    # Initialize parser parameters
    params = Chem.SmilesParserParams()
    params.useChirality = True  # Preserve stereochemistry information
    params.removeHs = False  # Keep hydrogen atoms
    mfp = []

    for smi in SMILES:
        mol = None
        # Sanitization attempt strategies
        sanitize_attempts = [
            {"sanitize": True},  # First try with standard sanitization
            {
                "sanitize": False,
                "partial_sanitize": True,
            },  # Fallback: partial sanitization
        ]

        for attempt in sanitize_attempts:
            try:
                # Update parameters for this attempt
                current_params = Chem.SmilesParserParams()
                current_params.sanitize = attempt["sanitize"]
                current_params.useChirality = params.useChirality
                current_params.removeHs = params.removeHs

                # Molecule object creation
                mol = Chem.MolFromSmiles(smi, params=current_params)

                if mol and "partial_sanitize" in attempt:
                    # Perform partial sanitization (skip property validation)
                    Chem.SanitizeMol(mol, Chem.SANITIZE_ALL ^ Chem.SANITIZE_PROPERTIES)

                if mol:  # Successfully processed molecule
                    # Generate Morgan fingerprint
                    fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=2048)
                    mfp.append(np.array(fp))
                    break  # Exit attempt loop on success

            except Exception as e:
                if attempt == sanitize_attempts[-1]:  # Final attempt failed
                    print(f"Processing failed: {smi}")
                    print(f"Error details: {str(e)}")
                continue  # Try next attempt

        if not mol:  # All attempts failed
            print(f"Complete processing failure: {smi}")
            mfp.append(np.zeros(2048))  # Insert zero-vector placeholder

    return np.array(mfp)

In [41]:
mfp = get_morgan_fingerprint(SMILES)
mfp = pd.DataFrame(mfp, index=drug_response.index)

In [42]:
drug_sim = normalize_similarity_matrix(mfp)
drug_sim

,740,752,755,757,762,1390,1895,3053,3061,3088,...,808790,808792,809693,810341,810717,811429,812926,812927,813488,820919
740,1.000000,0.685936,0.685936,0.574218,0.699994,0.685936,0.709376,0.445523,0.704684,0.709376,...,0.509650,0.564967,0.560345,0.537268,0.537268,0.523449,0.597385,0.551107,0.551107,0.551107
752,0.685936,1.000000,0.932532,0.685936,0.813195,0.855989,0.870295,0.528053,0.789502,0.747000,...,0.602025,0.657884,0.625260,0.639228,0.648551,0.597385,0.653216,0.643888,0.643888,0.615959
755,0.685936,0.932532,1.000000,0.714071,0.841703,0.884622,0.860755,0.537268,0.798972,0.775314,...,0.629913,0.676576,0.634569,0.667226,0.667226,0.625260,0.662554,0.671900,0.662554,0.634569
757,0.574218,0.685936,0.714071,1.000000,0.728170,0.714071,0.709376,0.472953,0.676576,0.681255,...,0.564967,0.611312,0.588111,0.564967,0.620608,0.588111,0.597385,0.588111,0.606667,0.560345
762,0.699994,0.813195,0.841703,0.728170,1.000000,0.822688,0.865524,0.541879,0.822688,0.855989,...,0.625260,0.671900,0.629913,0.653216,0.653216,0.592747,0.648551,0.667226,0.657884,0.629913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.523449,0.597385,0.625260,0.588111,0.592747,0.625260,0.629913,0.395444,0.569591,0.574218,...,0.541879,0.551107,0.472953,0.523449,0.523449,1.000000,0.509650,0.564967,0.500463,0.500463
812926,0.597385,0.653216,0.662554,0.597385,0.648551,0.653216,0.676576,0.450089,0.662554,0.620608,...,0.523449,0.625260,0.546492,0.588111,0.569591,0.509650,1.000000,0.555725,0.667226,0.564967
812927,0.551107,0.643888,0.671900,0.588111,0.667226,0.690620,0.667226,0.440959,0.615959,0.611312,...,0.551107,0.569591,0.509650,0.541879,0.541879,0.564967,0.555725,1.000000,0.574218,0.518847
813488,0.551107,0.643888,0.662554,0.606667,0.657884,0.662554,0.676576,0.431838,0.634569,0.620608,...,0.514248,0.597385,0.555725,0.625260,0.514248,0.500463,0.667226,0.574218,1.000000,0.500463
820919,0.551107,0.615959,0.634569,0.560345,0.629913,0.634569,0.639228,0.431838,0.606667,0.592747,...,0.532660,0.634569,0.500463,0.523449,0.671900,0.500463,0.564967,0.518847,0.500463,1.000000

In [43]:
os.makedirs("../nci_data/drug_sim", exist_ok=True)
chunks = np.array_split(drug_sim, 25)

for i, chunk in tqdm(enumerate(chunks)):
    chunk.to_parquet(
        f"../nci_data/drug_sim/drug_sim_part_{i}.parquet", compression="gzip"
    )

/Users/inouey2/base/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
25it [00:02,  9.71it/s]

In [44]:
# # How to read
# def natural_sort_key(s):
#     return [int(c) if c.isdigit() else c for c in re.split(r'(\d+)', s)]

# file_paths = glob.glob("../nci_data/drug_sim/drug_sim_part_*.parquet")
# sorted_file_paths = sorted(file_paths, key=natural_sort_key)

# drug_sim_reconstructed = pd.concat([pd.read_parquet(file) for file in tqdm(sorted_file_paths)])

In [45]:
print("Min:", np.min(drug_sim.values))
print("Max:", np.max(drug_sim.values))
print("Mean:", np.mean(drug_sim.values))
print("Median:", np.median(drug_sim.values))

Min: 0.0
Max: 1.0
Mean: 0.5783090139257747
Median: 0.5834776271411233

# Unified Graph

In [46]:
A_dg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
752,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
755,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
757,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
762,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811429,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812926,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812927,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
813488,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
820919,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

In [47]:
indexes = list(A_dc.index) + list(A_cg.index) + list(A_dg.columns)
n_all = len(indexes)
base = pd.DataFrame(np.zeros([n_all, n_all]), index=indexes, columns=indexes)
base

,740,752,755,757,762,1390,1895,3053,3061,3088,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZNRD1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZP3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZSCAN18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZYX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
base.loc[A_cg.index, A_cg.columns] = A_cg
base.loc[A_cg.columns, A_cg.index] = A_cg.T
base.loc[A_dc.index, A_dc.columns] = A_dc
base.loc[A_dc.columns, A_dc.index] = A_dc.T
base.loc[A_dg.index, A_dg.columns] = A_dg
base.loc[A_dg.columns, A_dg.index] = A_dg.T

In [49]:
np.save(
    "../nci_data/idxs.npy",
    pd.DataFrame([list(range(len(base.index))), base.index]).values,
)

In [50]:
edge_index = np.array(base.values.nonzero())
edge_attr = np.array(base.values[base.values.nonzero()])

In [51]:
os.makedirs("../nci_data/edge_idxs", exist_ok=True)
chunk_size = 3000000

num_chunks_index = math.ceil(edge_index.shape[1] / chunk_size)
for i in range(num_chunks_index):
    start = i * chunk_size
    end = min((i + 1) * chunk_size, edge_index.shape[1])
    chunk = edge_index[:, start:end]
    np.save(f"../nci_data/edge_idxs/edge_idxs_chunk_{i}.npy", chunk)

In [52]:
os.makedirs("../nci_data/edge_attrs", exist_ok=True)
chunk_size = 6000000

num_chunks_attr = math.ceil(edge_attr.shape[0] / chunk_size)
for i in range(num_chunks_attr):
    start = i * chunk_size
    end = min((i + 1) * chunk_size, edge_attr.shape[0])
    chunk = edge_attr[start:end]
    np.save(f"../nci_data/edge_attrs/edge_attr_chunk_{i}.npy", chunk)

In [53]:
# # How to read
# def load_and_combine_chunks(pattern, axis=0):
#     chunk_files = sorted(
#         glob.glob(pattern), key=lambda x: int(x.split("_")[-1].split(".")[0])
#     )

#     chunks = [np.load(f) for f in chunk_files]
#     return np.concatenate(chunks, axis=axis)


# edge_index = load_and_combine_chunks("../nci_data/edge_idxs/*.npy", axis=1)
# edge_attr = load_and_combine_chunks("../nci_data/edge_attrs/*.npy", axis=0)