In [1]:
import math
import os

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tqdm import tqdm

# Gene Exp

In [2]:
gene_exp = pd.concat(
    [
        pd.read_csv("../nci_data/gene_exp_part1.csv.gz", index_col=0).T,
        pd.read_csv("../nci_data/gene_exp_part2.csv.gz", index_col=0).T,
    ],
    axis=1,
)
gene_exp.columns = list(gene_exp.columns)
gene_exp

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
MCF7,1.545084,1.960664,0.045797,0.048305,0.271383,0.000000,0.000000,0.000000,1.790422,0.000000,...,3.251321,4.553231,0.524880,1.325335,2.719968,0.979052,0.955984,2.997876,1.814542,2.017416
MDA_MB_231,0.577656,0.158440,0.023368,0.033706,0.000000,0.020794,0.000000,0.093408,0.281342,0.000000,...,4.150389,4.835798,0.399802,2.148645,1.286207,0.630559,1.366784,3.193204,0.534567,4.290867
HS578T,2.127485,1.114494,0.057868,0.053825,0.000000,0.122192,0.000000,0.000000,0.437279,0.375008,...,1.569525,2.078446,0.211162,0.425895,1.637754,0.183044,1.275240,6.707759,1.183093,1.404440
BT_549,2.807536,1.545173,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.705958,0.000000,...,1.551910,2.247581,0.538375,0.956725,1.921501,0.578255,1.148797,5.211335,1.806192,1.725314
T47D,2.240504,1.404554,0.014713,0.020456,0.083641,0.000000,0.000000,0.205220,0.775457,0.000000,...,2.328319,4.735132,0.634419,1.509372,2.627329,0.850154,1.326106,3.807767,1.399636,1.188945
SF_268,1.904164,0.224674,0.000000,0.066023,0.000000,0.000000,0.000000,0.256671,0.413970,0.126786,...,1.203840,3.447059,0.264858,0.741443,1.187052,0.000000,1.236389,5.422912,0.959441,1.258356
SF_295,1.645900,1.625902,0.021271,0.029497,0.000000,0.000000,0.000000,0.101272,0.493029,0.000000,...,3.338683,4.622304,0.355396,1.124633,2.284713,0.047663,1.388140,7.781976,1.643824,2.399661
SF_539,1.488978,1.449873,0.018674,0.302848,0.426903,0.000000,0.000000,0.116516,0.843719,0.000000,...,2.522377,3.481312,0.798670,1.482724,2.686960,0.119173,1.572594,7.108138,1.645789,2.314656
SNB_19,1.479329,0.274825,0.061902,0.483726,0.152568,0.076873,0.000000,0.145237,2.341513,0.302242,...,1.154635,1.465687,0.813209,1.270068,2.302293,0.121911,1.727816,4.974814,1.340579,1.763526
SNB_75,0.598351,0.248695,0.010085,6.973255,2.752582,0.027438,0.000000,0.167921,2.501286,0.093693,...,2.404099,4.063770,0.576326,1.084949,2.606243,0.095408,1.763505,6.493543,1.689898,2.246688
U251,0.638753,0.476393,0.041163,0.032769,0.065546,0.000000,0.000000,0.000000,1.569938,0.046399,...,3.543112,4.809898,0.669757,1.510223,2.378484,0.026790,2.086373,5.995444,1.864549,2.799361
COLO205,0.246667,0.000000,1.654981,0.024962,0.089178,0.020235,0.000000,0.185716,0.160210,0.000000,...,2.345189,3.655901,0.170633,0.490213,2.020484,0.047116,0.677649,2.606660,0.974401,0.967547
HCC_2998,0.250535,0.000000,0.373901,0.041253,0.094595,0.000000,0.000000,0.000000,2.512032,0.000000,...,2.401191,4.130478,0.571695,1.031155,2.511450,0.000000,1.430676,5.976073,1.938455,2.047629
HCT_116,0.307237,0.132078,0.068520,0.051264,0.398513,0.030822,0.000000,0.062921,1.069730,0.036591,...,3.128976,4.652573,0.542252,1.510572,2.439958,0.033921,1.933119,5.294235,1.246980,2.860160
HCT_15,0.390396,0.136813,0.000000,0.037231,0.201663,0.000000,0.000000,0.000000,0.401377,0.000000,...,2.140942,4.268554,0.747270,1.222514,2.739924,0.000000,1.679726,5.076414,1.942289,1.963755
HT29,0.521630,0.000000,0.021636,0.023163,0.000000,0.000000,0.000000,0.139856,1.846927,0.000000,...,2.723827,4.194647,0.171753,0.052821,2.653688,0.024624,0.650471,4.781496,0.993440,1.867035
KM12,0.455004,0.000000,0.047178,0.039222,0.067080,2.327751,0.000000,0.117796,1.676308,0.000000,...,3.173849,4.552082,0.167247,0.958492,1.989491,0.043580,1.026311,5.254987,0.948990,1.814567
SW_620,0.123572,0.000000,0.390645,0.064307,0.141200,0.049145,0.000000,0.257192,0.233616,0.000000,...,4.620944,4.561723,0.458652,2.637121,1.293276,0.227906,1.023042,0.495761,0.572585,2.283557
CCRF_CEM,3.415556,2.113584,0.023598,0.093839,0.034637,0.000000,0.000000,0.000000,0.087611,0.000000,...,4.266607,6.229944,0.701538,1.967988,3.482668,0.021588,1.424164,4.744215,1.963156,2.930277
HL_60,0.584909,0.189045,0.021053,0.047634,0.000000,0.032358,0.000000,0.215215,0.209344,0.000000,...,2.206553,3.844396,0.217071,1.212414,2.258242,0.089110,0.803203,5.615696,0.897406,1.945963
K_562,0.417591,0.286014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141922,0.000000,...,2.175831,3.998620,0.066914,0.405356,1.393345,1.343266,1.295053,4.946525,0.982254,1.380064
MOLT_4,2.893638,0.925995,0.048294,0.258310,0.000000,0.052554,0.056831,0.668980,0.406011,0.061282,...,2.244345,4.572017,0.567292,1.138834,2.688968,0.136482,0.623449,1.241181,1.569914,1.686577
RPMI_8226,1.169085,0.912828,0.125867,0.105289,0.126067,0.119677,0.000000,0.412116,0.577380,0.317986,...,2.441191,2.030640,0.347761,0.801423,1.814058,0.529370,0.808631,2.084085,0.592319,0.865066
SR,0.579469,0.634189,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517462,0.000000,...,2.157962,2.399961,0.163282,0.459376,1.622162,0.671210,0.642349,2.113334,0.592544,0.685140
LOXIMVI,0.185936,0.000000,0.043571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.643048,3.752481,0.247937,0.576799,1.557925,0.000000,0.817767,6.441324,1.120193,1.717772
MALME_3M,1.128029,1.686541,0.012960,5.145319,1.266355,0.021861,0.000000,0.000000,1.672462,0.000000,...,2.710287,3.321479,0.470055,1.072387,2.401445,0.000000,1.295235,5.702943,1.753810,1.765827
M14,1.382889,1.548910,0.078594,1.360617,0.673357,0.043225,0.055848,0.235252,0.181754,0.069082,...,2.269838,4.186604,0.305528,0.709368,2.670204,0.638157,1.218837,6.576282,2.070145,1.979685
SK_MEL_2,0.891387,1.708284,0.024977,2.032619,0.523482,0.019269,0.000000,0.086047,2.479383,0.000000,...,2.520900,2.986655,0.828408,1.578470,2.442790,0.018800,1.404195,6.194968,1.461151,1.981312
SK_MEL_28,1.188768,1.785739,0.000000,3.912430,0.725083,0.000000,0.000000,0.000000,0.910857,0.000000,...,1.764635,3.565561,0.438313,0.763754,2.484613,0.261266,1.181491,5.327429,1.539620,2.118699
SK_MEL_5,0.985070,0.321937,0.053715,3.319262,0.139690,0.063177,0.041588,0.257931,0.192075,0.042687,...,1.698605,2.880458,0.280925,0.630757,2.745594,0.074345,0.961779,5.381636,1.757501,1.192194
UACC_257,1.075779,0.612513,0.000000,2.605475,0.221317,0.035406,0.000000,0.193316,0.092515,0.000000,...,2.739410,4.122424,0.215420,0.952929,2.882845,0.037745,1.884563,4.567844,1.632040,2.758857
UACC_62,1.597913,2.124404,0.000000,3.040773,0.304673,0.000000,0.000000,0.000000,0.096365,0.000000,...,2.385795,3.768184,0.496423,1.076894,2.782882,0.030226,1.765072,6.695590,1.645651,1.443463
MDA_MB_435,0.813414,1.264128,0.000000,0.104453,0.000000,0.032089,0.000000,0.000000,0.000000,0.000000,...,2.922293,3.949012,0.427739,1.202073,2.557427,0.306827,1.437158,6.625117,2.311407,1.935486
MDA_N,1.028025,0.468561,0.128165,0.315368,0.343715,0.142585,0.000000,0.281589,0.224244,0.431887,...,1.988812,2.193040,0.332405,0.897409,1.612480,0.292948,0.980711,4.850084,0.956489,0.949319
A549,1.614870,0.417418,0.237778,0.000000,0.138358,0.000000,0.000000,0.000000,1.345135,0.164118,...,2.234161,3.374107,0.364849,0.945305,1.287856,0.489405,0.862357,4.814233,1.242243,0.751751
EKVX,0.618265,0.615816,0.029499,0.706799,0.781613,0.000000,0.000000,0.162985,1.537753,0.000000,...,3.121470,3.727703,0.789787,1.651715,2.089576,0.585060,2.542300,6.388582,1.966899,1.982254
HOP_62,0.584364,0.780409,0.018089,0.058614,0.000000,0.000000,0.000000,0.000000,1.409353,0.000000,...,2.442038,4.112533,0.463545,1.440123,2.774663,1.053660,1.568562,7.107259,1.623647,1.747985
HOP_92,1.137326,1.458041,0.000000,0.035569,0.000000,0.000000,0.000000,0.000000,1.858264,0.000000,...,2.254165,4.086317,0.513951,1.059044,2.436021,0.755965,1.508292,7.305505,1.502275,2.140661
NCI_H226,0.838398,0.286685,0.020127,0.069518,0.035271,0.028547,0.000000,0.264804,0.461380,0.060431,...,3.055124,3.270577,0.501549,1.414888,1.988946,0.040315,1.529901,6.423346,1.313037,2.195215
NCI_H23,0.662504,0.656841,0.000000,0.680351,0.517915,0.000000,0.000000,0.000000,1.200868,0.000000,...,3.119884,4.114867,0.717492,1.289604,2.712233,1.059715,1.729461,7.321189,1.872159,2.052920
NCI_H322M,0.650641,0.627746,0.000000,0.032171,0.198527,0.927342,0.000000,0.000000,3.125208,0.000000,...,2.499484,4.488952,0.409880,1.030774,2.196846,0.090183,1.067315,4.004412,1.371966,1.678744
NCI_H460,1.317466,0.286402,0.060136,0.043719,0.086571,0.095243,0.000000,1.628783,2.236777,0.047102,...,2.202643,3.654447,0.451344,0.811302,1.634463,0.407917,0.847372,4.932496,1.283987,1.037368
NCI_H522,0.870533,1.371235,0.033316,0.072972,0.483322,0.034023,0.000000,0.456816,0.862880,0.041820,...,3.098842,5.087594,1.635884,2.108846,2.239053,1.237790,1.752577,5.347634,1.265557,2.137117
IGROV1,0.524677,0.637974,0.000000,0.000000,0.214661,0.000000,0.000000,0.000000,1.858124,0.000000,...,2.188584,3.847716,0.478634,0.843296,2.085765,0.411463,1.584289,5.884019,1.398296,1.617393
OVCAR_3,0.817811,0.555374,0.022670,0.000000,0.000000,0.067640,0.000000,0.000000,0.490461,0.000000,...,1.761911,3.206415,0.271671,0.488833,1.988972,0.860634,0.700473,5.427707,0.900560,1.377862
OVCAR_4,1.239832,1.277259,0.017954,0.085341,0.096856,0.021942,0.000000,0.139429,1.998315,0.040983,...,1.790226,4.046447,0.295332,0.749709,2.387338,1.184883,1.188717,6.754861,1.114953,1.672231
OVCAR_5,0.361421,0.134705,0.056577,0.056299,0.000000,0.014644,0.000000,0.091694,0.062084,0.030664,...,2.633350,4.384533,0.052474,0.301610,2.040391,0.186418,0.887341,4.067854,0.344686,1.638959
OVCAR_8,1.147079,1.340488,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.868882,0.000000,...,1.573452,4.104630,0.205381,0.448423,2.491538,1.504605,1.263022,7.119616,1.720782,1.597827
SK_OV_3,0.871177,0.826886,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.465086,0.000000,...,2.257174,3.795684,0.374348,0.931595,2.317796,0.985476,1.884891,5.430657,1.297638,1.188901
NCI_ADR_RES,2.422618,2.752160,0.016345,0.024607,0.339376,0.000000,0.000000,0.000000,1.808731,0.000000,...,3.817726,5.635148,0.326622,0.795797,3.352103,1.946461,1.634096,8.637817,1.671239,2.703180
PC_3,0.206131,0.153104,0.225023,0.075167,0.238277,0.000000,0.000000,0.000000,0.624892,0.000000,...,2.823482,5.124841,0.659168,1.943730,1.920179,0.100480,2.242255,7.227934,1.626551,2.436690
DU_145,1.494467,0.384633,0.136934,0.166591,0.859956,0.173804,0.000000,2.073128,1.388250,0.132402,...,1.712054,2.713111,0.533587,0.665578,1.704469,0.843826,0.681730,5.246845,1.251816,0.940434
786_0,0.361155,0.000000,0.029955,0.056167,0.000000,0.016151,0.000000,0.000000,2.006872,0.000000,...,2.518782,4.195119,0.369624,0.660119,1.919836,0.043749,1.246694,6.732405,1.467530,1.762132
A498,0.440222,0.067594,0.078561,0.038646,0.083573,0.037460,0.000000,0.291472,1.424213,0.042165,...,1.470766,2.806258,0.411828,0.598354,1.297315,0.526957,0.662996,6.670161,1.290324,1.072373
ACHN,0.576425,0.220324,0.020986,0.067487,0.302748,0.014374,0.000000,0.332142,1.582792,0.176846,...,2.700318,4.206784,0.488145,0.751780,1.867363,0.064330,1.006600,6.743057,1.471234,1.944997
CAKI_1,0.882482,0.506823,0.000000,0.036152,0.000000,0.000000,0.000000,0.135979,2.266421,0.000000,...,2.167859,2.884453,0.400211,1.215057,1.710098,0.474023,1.266373,6.547058,0.761174,1.465400
RXF_393,0.572572,0.975728,0.019251,0.020413,0.147273,0.022726,0.000000,0.000000,2.311207,0.094547,...,2.707796,3.556245,0.707476,1.232096,1.799465,0.875894,1.497382,6.892488,1.406139,2.112423
SN12C,1.533733,0.660213,0.024985,0.035940,0.000000,0.000000,0.000000,0.000000,1.670165,0.000000,...,1.687773,4.720623,0.465862,0.630736,1.909151,0.920320,1.212538,7.071076,1.007346,0.865705
TK_10,0.076563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.572617,0.000000,...,2.771981,3.864523,0.365028,0.821460,1.604811,0.901689,1.590070,6.747535,0.994256,2.221326
UO_31,0.342318,0.471444,0.000000,0.000000,0.227863,0.000000,0.000000,0.000000,1.941689,0.000000,...,2.862285,4.035386,0.482844,1.157290,2.100184,0.325286,1.640838,7.231327,1.714553,2.178909

# Drug Response

In [3]:
drug_response = pd.read_csv("../nci_data/drugAct.csv", index_col=0)
drug_response.columns = gene_exp.index
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
1,-0.271314,-0.303539,-0.815183,-0.231499,1.934731,-0.357577,-0.719253,-0.380720,-1.281589,-0.175915,...,-0.403983,-0.434885,-0.519867,-1.648059,1.657273,-0.269717,0.002290,-0.390689,-0.379420,1.059515
17,-0.354110,-0.304675,-0.222024,1.483613,1.509397,0.335572,0.424922,1.140166,-0.941890,0.330808,...,1.302516,-0.941890,0.521200,-0.329639,-0.941890,0.717851,-0.239018,-0.315533,-0.761559,1.120673
89,NaN,NaN,NaN,NaN,NaN,-0.184194,-1.429903,-0.165433,-1.429903,-0.216723,...,NaN,NaN,0.368433,-0.655707,-0.144006,0.743888,-0.435620,-0.184805,-0.101929,-0.118807
185,NaN,NaN,NaN,NaN,NaN,0.539343,NaN,0.230402,-0.765829,-1.125208,...,NaN,NaN,-0.061612,NaN,NaN,1.675353,0.918722,1.391604,-0.904724,0.918522
295,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,...,-0.264586,-0.264586,4.822657,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900911,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,...,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,-0.167151,1.594059,-0.167151,-0.167151,-0.167151
900922,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,...,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786,-0.169786
900964,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,...,-0.158754,NaN,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754,-0.158754
900974,-0.132453,-0.132453,-0.132453,NaN,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,...,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,-0.132453,NaN,-0.132453,-0.132453,-0.132453
921923,0.513889,-0.600293,-0.816154,-0.604513,NaN,-0.126943,-0.961518,-0.268661,-0.927258,NaN,...,-0.268102,-0.152586,0.350261,-0.920821,-0.140812,-0.559582,-1.009885,0.705388,1.538064,-0.301852

In [4]:
nsc_smiles = pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
    ["NSC", "SMILES"]
]
nsc_smiles

          NSC                                             SMILES
0           1                                  CC1=CC(=O)C=CC1=O
1          17                   CCCCCCCCCCCCCCCC1=C(C=CC(=C1)O)N
2          89                         CN(C)CCC(=O)C1=CC=CC=C1.Cl
3         185            CC1CC(C(=O)C(C1)C(CC2CC(=O)NC(=O)C2)O)C
4      758187            CC1CC(C(=O)C(C1)C(CC2CC(=O)NC(=O)C2)O)C
...       ...                                                ...
23186  799649  C1CC2=C(C1)SC3=NC=NC(=C23)NC4=C(NN=C4)C(=O)NC5...
23187  803209  CCN1C2C(N(C1=O)CC)N3C(=O)C(=C4C5=CC=CC=C5N(C4=...
23188  803778  C1=CC=C(C=C1)C=NC2=C(C(C3=C(O2)C4=CC=CC=C4C=C3...
23189  807047  CC1=C(C=C(C=C1)NC(=O)C2=CC(=NC=C2)C(F)(F)F)C3=...
23190  707090     COC1=CC=C(C=C1)NC2=NC(=C(S2)C(=O)C3=CC=CC=C3)N

[23191 rows x 2 columns]

In [5]:
drug_response = drug_response[drug_response.index.isin(nsc_smiles["NSC"])]
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
1,-0.271314,-0.303539,-0.815183,-0.231499,1.934731,-0.357577,-0.719253,-0.380720,-1.281589,-0.175915,...,-0.403983,-0.434885,-0.519867,-1.648059,1.657273,-0.269717,0.002290,-0.390689,-0.379420,1.059515
17,-0.354110,-0.304675,-0.222024,1.483613,1.509397,0.335572,0.424922,1.140166,-0.941890,0.330808,...,1.302516,-0.941890,0.521200,-0.329639,-0.941890,0.717851,-0.239018,-0.315533,-0.761559,1.120673
89,NaN,NaN,NaN,NaN,NaN,-0.184194,-1.429903,-0.165433,-1.429903,-0.216723,...,NaN,NaN,0.368433,-0.655707,-0.144006,0.743888,-0.435620,-0.184805,-0.101929,-0.118807
185,NaN,NaN,NaN,NaN,NaN,0.539343,NaN,0.230402,-0.765829,-1.125208,...,NaN,NaN,-0.061612,NaN,NaN,1.675353,0.918722,1.391604,-0.904724,0.918522
295,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,...,-0.264586,-0.264586,4.822657,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586,-0.264586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830912,-0.376238,-0.376238,1.010516,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,-0.376238,...,-0.376238,-0.376238,-0.376238,3.525174,-0.376238,NaN,0.199423,0.443532,-0.376238,-0.376238
831147,1.072608,-0.972979,0.442335,-0.012315,-0.482196,-1.133923,0.744309,0.248854,-0.165824,0.413759,...,-0.351430,-0.514584,-0.611389,0.472510,-0.823481,0.742079,0.422323,-1.046201,-2.375068,-0.500730
831270,1.851876,-0.987088,-0.356117,-0.421592,-0.611842,-0.608036,-0.403236,-0.540247,-0.689865,-0.317744,...,-0.456405,-0.949046,-0.575863,0.841165,1.539347,2.607703,-0.341227,-0.708900,-0.597473,1.611968
831271,0.439331,-0.178969,-0.121072,0.238512,0.339249,-0.395609,-0.142904,-0.070311,-1.578078,-0.067484,...,0.108510,-0.416719,0.151945,0.340800,-0.311599,0.093151,0.349071,-0.108789,-0.327627,0.522628
831453,-0.407871,0.169410,-0.718427,-0.820520,-0.402455,-0.400405,-0.577882,-0.194282,-0.399358,-0.616924,...,-0.129208,-0.184982,0.406725,NaN,-0.101206,-0.255620,NaN,-0.366483,-0.404886,-0.456849

In [6]:
moa = pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
    ["NSC", "MECHANISM"]
]

In [7]:
moa["MECHANISM"].value_counts()

MECHANISM
Other          22245
Kinase           481
DNA              269
TUBB              45
HDAC              45
Apoptosis         36
HSP90             16
Ho                13
Methylation       13
PSM               13
BRD               11
Acetalax           4
Name: count, dtype: int64

In [8]:
not_other = moa[moa["MECHANISM"] != "Other"]
len(not_other)

946

# To fit into the memory for A100 80GB, we select MoA which is not "Other"

In [9]:
len(set(drug_response.index) & set(list(not_other["NSC"])))

945

In [10]:
drug_response = drug_response.loc[
    sorted(set(drug_response.index) & set(list(not_other["NSC"])))
]
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.703626,-1.219032,-1.892792,-0.877267,-1.156158,0.510978,0.536910,0.589970,-0.356387,-1.460314,...,0.626838,0.507493,0.682664,-0.891882,0.499337,0.541612,-1.400771,0.602244,-1.641942,0.231533
752,0.475296,-0.312852,-1.089067,-0.441030,-0.058619,0.057507,0.125700,0.111693,-3.285729,-0.114051,...,-0.321691,0.507798,0.384102,-1.314527,-0.318444,0.557175,0.345056,-0.047731,0.155244,-0.160223
755,0.704027,-0.438857,-0.548744,-1.441942,0.496864,0.096265,-0.082186,0.417634,-1.927502,-0.372021,...,0.123647,0.543639,0.623318,-1.374212,-0.173024,0.314436,-1.002183,-0.881252,0.491364,-0.183200
757,0.318209,NaN,NaN,NaN,NaN,0.307045,0.355509,0.385020,0.183820,-0.384083,...,NaN,NaN,0.009710,0.225675,-0.597319,-0.093596,0.357496,0.158630,-3.402035,-1.148675
762,0.547964,-1.033803,-1.399273,-0.538268,1.137432,0.135942,-0.094460,0.562628,-1.398911,-1.050409,...,-0.294845,0.934592,0.591263,-0.552673,1.797227,1.260987,0.172806,0.869675,-0.529810,-0.634413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.262070,-1.073717,0.164341,-0.606004,-0.826171,-0.633880,-0.087730,1.358718,-0.858798,0.491692,...,-0.807091,-0.638019,-0.843039,1.777181,0.279619,0.231262,0.182468,1.259046,-0.798737,0.073853
811429,0.088052,0.332208,1.572703,0.816968,-0.194672,0.607785,0.306740,1.381493,-0.240118,1.766007,...,-0.621433,-0.040864,0.201668,1.999485,0.432290,0.532053,1.847915,0.879530,-0.113922,1.113174
812926,-0.692843,-0.198620,-0.091472,-0.363542,0.716930,0.114785,-0.743516,-0.403585,-0.959310,0.424058,...,-0.737629,-0.105010,0.195539,1.856611,2.094631,0.843571,0.602042,-0.385549,3.111755,1.518265
812927,3.663091,0.176469,-0.137450,-0.461071,0.029122,-0.540453,-0.393660,0.141554,-0.019758,2.130226,...,-0.553986,-0.602355,-0.438735,0.000707,-0.047693,-1.150848,0.071027,-0.839514,0.103856,0.116587
813488,0.319494,0.259510,0.959946,1.353693,0.058727,0.236707,-0.821851,0.621550,-0.251549,2.256322,...,-0.563012,-0.240817,0.742293,5.112669,0.323573,-0.185610,1.349165,0.191249,0.266489,1.166435

In [11]:
df = pd.DataFrame()
for i in drug_response.columns:
    tmp = pd.DataFrame(drug_response[i]).reset_index().dropna()
    tmp["cell"] = [i] * len(tmp)
    tmp.columns = ["Drug", "Value", "Cell"]
    tmp = tmp[["Drug", "Cell", "Value"]]
    df = pd.concat([df, tmp])
df

       Drug   Cell     Value
0       740   MCF7  0.703626
1       752   MCF7  0.475296
2       755   MCF7  0.704027
3       757   MCF7  0.318209
4       762   MCF7  0.547964
..      ...    ...       ...
940  810717  UO_31  0.073853
941  811429  UO_31  1.113174
942  812926  UO_31  1.518265
943  812927  UO_31  0.116587
944  813488  UO_31  1.166435

[54536 rows x 3 columns]

# Zero shot prediction

In [12]:
unique_drugs = df["Drug"].unique()
unique_cells = df["Cell"].unique()

# Split drugs and cell lines into training, validation, and test sets
train_drugs, test_val_drugs = train_test_split(
    unique_drugs, test_size=0.5, random_state=42
)
val_drugs, test_drugs = train_test_split(test_val_drugs, test_size=0.5, random_state=42)

train_cells, test_val_cells = train_test_split(
    unique_cells, test_size=0.55, random_state=42
)
val_cells, test_cells = train_test_split(test_val_cells, test_size=0.5, random_state=42)

# Split the dataset
train_df = df[(df["Drug"].isin(train_drugs)) & (df["Cell"].isin(train_cells))]
val_df = df[(df["Drug"].isin(val_drugs)) & (df["Cell"].isin(val_cells))]
test_df = df[(df["Drug"].isin(test_drugs)) & (df["Cell"].isin(test_cells))]


# Function to balance label distribution
def balance_labels(df, threshold=0.5):
    positive = df[df["Value"] > 0]
    negative = df[df["Value"] <= 0]
    min_count = min(len(positive), len(negative))
    balanced_positive = positive.sample(min_count, random_state=42)
    balanced_negative = negative.sample(min_count, random_state=42)
    return pd.concat([balanced_positive, balanced_negative])


# Balance label distribution across all sets
train_df = balance_labels(train_df)
val_df = balance_labels(val_df)
test_df = balance_labels(test_df)

# Separate features and labels
X_train = train_df[["Drug", "Cell"]]
y_train = np.array(train_df["Value"] > 0, dtype=float)

X_val = val_df[["Drug", "Cell"]]
y_val = np.array(val_df["Value"] > 0, dtype=float)

X_test = test_df[["Drug", "Cell"]]
y_test = np.array(test_df["Value"] > 0, dtype=float)

# Calculate total samples
total_samples = len(X_train) + len(X_val) + len(X_test)


# Function to calculate and format label ratios
def get_label_ratio(y):
    unique, counts = np.unique(y, return_counts=True)
    total = len(y)
    ratio_str = ", ".join(
        [f"Label {label}: {count/total:.2%}" for label, count in zip(unique, counts)]
    )
    return ratio_str


# Display results with percentages and label ratios
print("Train:")
print(X_train.shape, y_train.shape)
print(f"Percentage: {len(X_train)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_train)}")

print("\nValidation:")
print(X_val.shape, y_val.shape)
print(f"Percentage: {len(X_val)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_val)}")

print("\nTest:")
print(X_test.shape, y_test.shape)
print(f"Percentage: {len(X_test)/total_samples:.2%}")
print(f"Label Ratio: {get_label_ratio(y_test)}")

print(f"\nTotal samples: {total_samples}")
print(
    f"Ratio (Train:Validation:Test): {len(X_train):.0f}:{len(X_val):.0f}:{len(X_test):.0f}"
)
print(
    f"Overall Label Ratio: {get_label_ratio(np.concatenate([y_train, y_val, y_test]))}"
)

X_train.to_csv("../nci_data/train.csv", index=False)
X_test.to_csv("../nci_data/test.csv", index=False)
X_val.to_csv("../nci_data/val.csv", index=False)

np.save("../nci_data/train_labels.npy", y_train)
np.save("../nci_data/test_labels.npy", y_test)
np.save("../nci_data/val_labels.npy", y_val)

Train:
(11636, 2) (11636,)
Percentage: 63.23%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Validation:
(2852, 2) (2852,)
Percentage: 15.50%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Test:
(3916, 2) (3916,)
Percentage: 21.28%
Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

Total samples: 18404
Ratio (Train:Validation:Test): 11636:2852:3916
Overall Label Ratio: Label 0.0: 50.00%, Label 1.0: 50.00%

In [13]:
drug_response = drug_response.fillna(0)
drug_response

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.703626,-1.219032,-1.892792,-0.877267,-1.156158,0.510978,0.536910,0.589970,-0.356387,-1.460314,...,0.626838,0.507493,0.682664,-0.891882,0.499337,0.541612,-1.400771,0.602244,-1.641942,0.231533
752,0.475296,-0.312852,-1.089067,-0.441030,-0.058619,0.057507,0.125700,0.111693,-3.285729,-0.114051,...,-0.321691,0.507798,0.384102,-1.314527,-0.318444,0.557175,0.345056,-0.047731,0.155244,-0.160223
755,0.704027,-0.438857,-0.548744,-1.441942,0.496864,0.096265,-0.082186,0.417634,-1.927502,-0.372021,...,0.123647,0.543639,0.623318,-1.374212,-0.173024,0.314436,-1.002183,-0.881252,0.491364,-0.183200
757,0.318209,0.000000,0.000000,0.000000,0.000000,0.307045,0.355509,0.385020,0.183820,-0.384083,...,0.000000,0.000000,0.009710,0.225675,-0.597319,-0.093596,0.357496,0.158630,-3.402035,-1.148675
762,0.547964,-1.033803,-1.399273,-0.538268,1.137432,0.135942,-0.094460,0.562628,-1.398911,-1.050409,...,-0.294845,0.934592,0.591263,-0.552673,1.797227,1.260987,0.172806,0.869675,-0.529810,-0.634413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.262070,-1.073717,0.164341,-0.606004,-0.826171,-0.633880,-0.087730,1.358718,-0.858798,0.491692,...,-0.807091,-0.638019,-0.843039,1.777181,0.279619,0.231262,0.182468,1.259046,-0.798737,0.073853
811429,0.088052,0.332208,1.572703,0.816968,-0.194672,0.607785,0.306740,1.381493,-0.240118,1.766007,...,-0.621433,-0.040864,0.201668,1.999485,0.432290,0.532053,1.847915,0.879530,-0.113922,1.113174
812926,-0.692843,-0.198620,-0.091472,-0.363542,0.716930,0.114785,-0.743516,-0.403585,-0.959310,0.424058,...,-0.737629,-0.105010,0.195539,1.856611,2.094631,0.843571,0.602042,-0.385549,3.111755,1.518265
812927,3.663091,0.176469,-0.137450,-0.461071,0.029122,-0.540453,-0.393660,0.141554,-0.019758,2.130226,...,-0.553986,-0.602355,-0.438735,0.000707,-0.047693,-1.150848,0.071027,-0.839514,0.103856,0.116587
813488,0.319494,0.259510,0.959946,1.353693,0.058727,0.236707,-0.821851,0.621550,-0.251549,2.256322,...,-0.563012,-0.240817,0.742293,5.112669,0.323573,-0.185610,1.349165,0.191249,0.266489,1.166435

# Masking

In [14]:
# Validation Mask
for _, row in X_val.iterrows():
    drug_response.loc[row["Drug"], row["Cell"]] = 0

# Test Mask
for _, row in X_test.iterrows():
    drug_response.loc[row["Drug"], row["Cell"]] = 0

# DTI

In [15]:
dti = pd.read_csv("../data/full_table.csv")
dti = dti.dropna(subset="NSC").reset_index(drop=True)
dti["NSC"] = dti["NSC"].astype(int)
dti.head()

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
0,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,APOD,122759
1,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,PTGDS,122759
2,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH12,122759
3,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH5,122759
4,Vitamin A,DB00162,445354.0,46508191.0,C\C(=C/CO)\C=C\C=C(/C)\C=C\C1=C(C)CCCC1(C)C,RDH13,122759

In [16]:
dti = dti[dti["NSC"].isin(drug_response.index)]
dti.head()

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
36,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB5,681239
37,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB1,681239
42,Nelfinavir,DB00220,64143.0,46507719.0,[H][C@@]12CCCC[C@]1([H])CN(C[C@@H](O)[C@H](CSC...,HIV-1 protease,747167
56,Carmustine,DB00262,2578.0,46506980.0,ClCCNC(=O)N(CCCl)N=O,GSR,409962
57,Amsacrine,DB00276,2179.0,46507539.0,COC1=C(NC2=C3C=CC=CC3=NC3=CC=CC=C23)C=CC(NS(C)...,TOP2A,249992

In [17]:
print("unique drugs:", len(set(dti.NSC)))
print("unique genes:", len(set(dti.Gene)))

unique drugs: 181
unique genes: 250

In [18]:
len(set(drug_response.index) & set(int(i) for i in set(dti.NSC)))

181

In [19]:
len(set(gene_exp.columns) & set(dti.Gene))

241

## All drugs are in drug response.

In [20]:
dti = dti[dti.Gene.isin(set(gene_exp.columns) & set(dti.Gene))]
dti

,Drug Name,DrugBank ID,PubChem CID,PubChem SID,SMILES,Gene,NSC
36,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB5,681239
37,Bortezomib,DB00188,387447.0,46508736.0,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,PSMB1,681239
56,Carmustine,DB00262,2578.0,46506980.0,ClCCNC(=O)N(CCCl)N=O,GSR,409962
57,Amsacrine,DB00276,2179.0,46507539.0,COC1=C(NC2=C3C=CC=CC3=NC3=CC=CC=C23)C=CC(NS(C)...,TOP2A,249992
58,Amsacrine,DB00276,2179.0,46507539.0,COC1=C(NC2=C3C=CC=CC3=NC3=CC=CC=C23)C=CC(NS(C)...,KCNH2,249992
...,...,...,...,...,...,...,...
1496,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR2,813488
1497,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR3,813488
1498,Futibatinib,DB15149,NaN,NaN,COC1=CC(=CC(OC)=C1)C#CC1=NN([C@H]2CCN(C2)C(=O)...,FGFR4,813488
1500,BMS-754807,DB15399,NaN,NaN,C[C@]1(CCCN1C1=NN2C=CC=C2C(NC2=NNC(=C2)C2CC2)=...,IGF1R,758243
1502,BMS-754807,DB15399,NaN,NaN,C[C@]1(CCCN1C1=NN2C=CC=C2C(NC2=NNC(=C2)C2CC2)=...,INSR,758243

# Selected highly variable genes

In [21]:
print(
    "Density: ",
    round((len(gene_exp.values.nonzero()[0]) / gene_exp.size) * 100, 2),
    "%",
)

Density:  75.09 %

In [22]:
variance = gene_exp.std()
variance = variance.sort_values(ascending=False)
variance = pd.DataFrame(variance > np.percentile(variance, 90))
variance = list(variance[variance[0]].index)
len(variance)

2383

In [23]:
gene_exp

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
MCF7,1.545084,1.960664,0.045797,0.048305,0.271383,0.000000,0.000000,0.000000,1.790422,0.000000,...,3.251321,4.553231,0.524880,1.325335,2.719968,0.979052,0.955984,2.997876,1.814542,2.017416
MDA_MB_231,0.577656,0.158440,0.023368,0.033706,0.000000,0.020794,0.000000,0.093408,0.281342,0.000000,...,4.150389,4.835798,0.399802,2.148645,1.286207,0.630559,1.366784,3.193204,0.534567,4.290867
HS578T,2.127485,1.114494,0.057868,0.053825,0.000000,0.122192,0.000000,0.000000,0.437279,0.375008,...,1.569525,2.078446,0.211162,0.425895,1.637754,0.183044,1.275240,6.707759,1.183093,1.404440
BT_549,2.807536,1.545173,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.705958,0.000000,...,1.551910,2.247581,0.538375,0.956725,1.921501,0.578255,1.148797,5.211335,1.806192,1.725314
T47D,2.240504,1.404554,0.014713,0.020456,0.083641,0.000000,0.000000,0.205220,0.775457,0.000000,...,2.328319,4.735132,0.634419,1.509372,2.627329,0.850154,1.326106,3.807767,1.399636,1.188945
SF_268,1.904164,0.224674,0.000000,0.066023,0.000000,0.000000,0.000000,0.256671,0.413970,0.126786,...,1.203840,3.447059,0.264858,0.741443,1.187052,0.000000,1.236389,5.422912,0.959441,1.258356
SF_295,1.645900,1.625902,0.021271,0.029497,0.000000,0.000000,0.000000,0.101272,0.493029,0.000000,...,3.338683,4.622304,0.355396,1.124633,2.284713,0.047663,1.388140,7.781976,1.643824,2.399661
SF_539,1.488978,1.449873,0.018674,0.302848,0.426903,0.000000,0.000000,0.116516,0.843719,0.000000,...,2.522377,3.481312,0.798670,1.482724,2.686960,0.119173,1.572594,7.108138,1.645789,2.314656
SNB_19,1.479329,0.274825,0.061902,0.483726,0.152568,0.076873,0.000000,0.145237,2.341513,0.302242,...,1.154635,1.465687,0.813209,1.270068,2.302293,0.121911,1.727816,4.974814,1.340579,1.763526
SNB_75,0.598351,0.248695,0.010085,6.973255,2.752582,0.027438,0.000000,0.167921,2.501286,0.093693,...,2.404099,4.063770,0.576326,1.084949,2.606243,0.095408,1.763505,6.493543,1.689898,2.246688
U251,0.638753,0.476393,0.041163,0.032769,0.065546,0.000000,0.000000,0.000000,1.569938,0.046399,...,3.543112,4.809898,0.669757,1.510223,2.378484,0.026790,2.086373,5.995444,1.864549,2.799361
COLO205,0.246667,0.000000,1.654981,0.024962,0.089178,0.020235,0.000000,0.185716,0.160210,0.000000,...,2.345189,3.655901,0.170633,0.490213,2.020484,0.047116,0.677649,2.606660,0.974401,0.967547
HCC_2998,0.250535,0.000000,0.373901,0.041253,0.094595,0.000000,0.000000,0.000000,2.512032,0.000000,...,2.401191,4.130478,0.571695,1.031155,2.511450,0.000000,1.430676,5.976073,1.938455,2.047629
HCT_116,0.307237,0.132078,0.068520,0.051264,0.398513,0.030822,0.000000,0.062921,1.069730,0.036591,...,3.128976,4.652573,0.542252,1.510572,2.439958,0.033921,1.933119,5.294235,1.246980,2.860160
HCT_15,0.390396,0.136813,0.000000,0.037231,0.201663,0.000000,0.000000,0.000000,0.401377,0.000000,...,2.140942,4.268554,0.747270,1.222514,2.739924,0.000000,1.679726,5.076414,1.942289,1.963755
HT29,0.521630,0.000000,0.021636,0.023163,0.000000,0.000000,0.000000,0.139856,1.846927,0.000000,...,2.723827,4.194647,0.171753,0.052821,2.653688,0.024624,0.650471,4.781496,0.993440,1.867035
KM12,0.455004,0.000000,0.047178,0.039222,0.067080,2.327751,0.000000,0.117796,1.676308,0.000000,...,3.173849,4.552082,0.167247,0.958492,1.989491,0.043580,1.026311,5.254987,0.948990,1.814567
SW_620,0.123572,0.000000,0.390645,0.064307,0.141200,0.049145,0.000000,0.257192,0.233616,0.000000,...,4.620944,4.561723,0.458652,2.637121,1.293276,0.227906,1.023042,0.495761,0.572585,2.283557
CCRF_CEM,3.415556,2.113584,0.023598,0.093839,0.034637,0.000000,0.000000,0.000000,0.087611,0.000000,...,4.266607,6.229944,0.701538,1.967988,3.482668,0.021588,1.424164,4.744215,1.963156,2.930277
HL_60,0.584909,0.189045,0.021053,0.047634,0.000000,0.032358,0.000000,0.215215,0.209344,0.000000,...,2.206553,3.844396,0.217071,1.212414,2.258242,0.089110,0.803203,5.615696,0.897406,1.945963
K_562,0.417591,0.286014,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141922,0.000000,...,2.175831,3.998620,0.066914,0.405356,1.393345,1.343266,1.295053,4.946525,0.982254,1.380064
MOLT_4,2.893638,0.925995,0.048294,0.258310,0.000000,0.052554,0.056831,0.668980,0.406011,0.061282,...,2.244345,4.572017,0.567292,1.138834,2.688968,0.136482,0.623449,1.241181,1.569914,1.686577
RPMI_8226,1.169085,0.912828,0.125867,0.105289,0.126067,0.119677,0.000000,0.412116,0.577380,0.317986,...,2.441191,2.030640,0.347761,0.801423,1.814058,0.529370,0.808631,2.084085,0.592319,0.865066
SR,0.579469,0.634189,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.517462,0.000000,...,2.157962,2.399961,0.163282,0.459376,1.622162,0.671210,0.642349,2.113334,0.592544,0.685140
LOXIMVI,0.185936,0.000000,0.043571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.643048,3.752481,0.247937,0.576799,1.557925,0.000000,0.817767,6.441324,1.120193,1.717772
MALME_3M,1.128029,1.686541,0.012960,5.145319,1.266355,0.021861,0.000000,0.000000,1.672462,0.000000,...,2.710287,3.321479,0.470055,1.072387,2.401445,0.000000,1.295235,5.702943,1.753810,1.765827
M14,1.382889,1.548910,0.078594,1.360617,0.673357,0.043225,0.055848,0.235252,0.181754,0.069082,...,2.269838,4.186604,0.305528,0.709368,2.670204,0.638157,1.218837,6.576282,2.070145,1.979685
SK_MEL_2,0.891387,1.708284,0.024977,2.032619,0.523482,0.019269,0.000000,0.086047,2.479383,0.000000,...,2.520900,2.986655,0.828408,1.578470,2.442790,0.018800,1.404195,6.194968,1.461151,1.981312
SK_MEL_28,1.188768,1.785739,0.000000,3.912430,0.725083,0.000000,0.000000,0.000000,0.910857,0.000000,...,1.764635,3.565561,0.438313,0.763754,2.484613,0.261266,1.181491,5.327429,1.539620,2.118699
SK_MEL_5,0.985070,0.321937,0.053715,3.319262,0.139690,0.063177,0.041588,0.257931,0.192075,0.042687,...,1.698605,2.880458,0.280925,0.630757,2.745594,0.074345,0.961779,5.381636,1.757501,1.192194
UACC_257,1.075779,0.612513,0.000000,2.605475,0.221317,0.035406,0.000000,0.193316,0.092515,0.000000,...,2.739410,4.122424,0.215420,0.952929,2.882845,0.037745,1.884563,4.567844,1.632040,2.758857
UACC_62,1.597913,2.124404,0.000000,3.040773,0.304673,0.000000,0.000000,0.000000,0.096365,0.000000,...,2.385795,3.768184,0.496423,1.076894,2.782882,0.030226,1.765072,6.695590,1.645651,1.443463
MDA_MB_435,0.813414,1.264128,0.000000,0.104453,0.000000,0.032089,0.000000,0.000000,0.000000,0.000000,...,2.922293,3.949012,0.427739,1.202073,2.557427,0.306827,1.437158,6.625117,2.311407,1.935486
MDA_N,1.028025,0.468561,0.128165,0.315368,0.343715,0.142585,0.000000,0.281589,0.224244,0.431887,...,1.988812,2.193040,0.332405,0.897409,1.612480,0.292948,0.980711,4.850084,0.956489,0.949319
A549,1.614870,0.417418,0.237778,0.000000,0.138358,0.000000,0.000000,0.000000,1.345135,0.164118,...,2.234161,3.374107,0.364849,0.945305,1.287856,0.489405,0.862357,4.814233,1.242243,0.751751
EKVX,0.618265,0.615816,0.029499,0.706799,0.781613,0.000000,0.000000,0.162985,1.537753,0.000000,...,3.121470,3.727703,0.789787,1.651715,2.089576,0.585060,2.542300,6.388582,1.966899,1.982254
HOP_62,0.584364,0.780409,0.018089,0.058614,0.000000,0.000000,0.000000,0.000000,1.409353,0.000000,...,2.442038,4.112533,0.463545,1.440123,2.774663,1.053660,1.568562,7.107259,1.623647,1.747985
HOP_92,1.137326,1.458041,0.000000,0.035569,0.000000,0.000000,0.000000,0.000000,1.858264,0.000000,...,2.254165,4.086317,0.513951,1.059044,2.436021,0.755965,1.508292,7.305505,1.502275,2.140661
NCI_H226,0.838398,0.286685,0.020127,0.069518,0.035271,0.028547,0.000000,0.264804,0.461380,0.060431,...,3.055124,3.270577,0.501549,1.414888,1.988946,0.040315,1.529901,6.423346,1.313037,2.195215
NCI_H23,0.662504,0.656841,0.000000,0.680351,0.517915,0.000000,0.000000,0.000000,1.200868,0.000000,...,3.119884,4.114867,0.717492,1.289604,2.712233,1.059715,1.729461,7.321189,1.872159,2.052920
NCI_H322M,0.650641,0.627746,0.000000,0.032171,0.198527,0.927342,0.000000,0.000000,3.125208,0.000000,...,2.499484,4.488952,0.409880,1.030774,2.196846,0.090183,1.067315,4.004412,1.371966,1.678744
NCI_H460,1.317466,0.286402,0.060136,0.043719,0.086571,0.095243,0.000000,1.628783,2.236777,0.047102,...,2.202643,3.654447,0.451344,0.811302,1.634463,0.407917,0.847372,4.932496,1.283987,1.037368
NCI_H522,0.870533,1.371235,0.033316,0.072972,0.483322,0.034023,0.000000,0.456816,0.862880,0.041820,...,3.098842,5.087594,1.635884,2.108846,2.239053,1.237790,1.752577,5.347634,1.265557,2.137117
IGROV1,0.524677,0.637974,0.000000,0.000000,0.214661,0.000000,0.000000,0.000000,1.858124,0.000000,...,2.188584,3.847716,0.478634,0.843296,2.085765,0.411463,1.584289,5.884019,1.398296,1.617393
OVCAR_3,0.817811,0.555374,0.022670,0.000000,0.000000,0.067640,0.000000,0.000000,0.490461,0.000000,...,1.761911,3.206415,0.271671,0.488833,1.988972,0.860634,0.700473,5.427707,0.900560,1.377862
OVCAR_4,1.239832,1.277259,0.017954,0.085341,0.096856,0.021942,0.000000,0.139429,1.998315,0.040983,...,1.790226,4.046447,0.295332,0.749709,2.387338,1.184883,1.188717,6.754861,1.114953,1.672231
OVCAR_5,0.361421,0.134705,0.056577,0.056299,0.000000,0.014644,0.000000,0.091694,0.062084,0.030664,...,2.633350,4.384533,0.052474,0.301610,2.040391,0.186418,0.887341,4.067854,0.344686,1.638959
OVCAR_8,1.147079,1.340488,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.868882,0.000000,...,1.573452,4.104630,0.205381,0.448423,2.491538,1.504605,1.263022,7.119616,1.720782,1.597827
SK_OV_3,0.871177,0.826886,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.465086,0.000000,...,2.257174,3.795684,0.374348,0.931595,2.317796,0.985476,1.884891,5.430657,1.297638,1.188901
NCI_ADR_RES,2.422618,2.752160,0.016345,0.024607,0.339376,0.000000,0.000000,0.000000,1.808731,0.000000,...,3.817726,5.635148,0.326622,0.795797,3.352103,1.946461,1.634096,8.637817,1.671239,2.703180
PC_3,0.206131,0.153104,0.225023,0.075167,0.238277,0.000000,0.000000,0.000000,0.624892,0.000000,...,2.823482,5.124841,0.659168,1.943730,1.920179,0.100480,2.242255,7.227934,1.626551,2.436690
DU_145,1.494467,0.384633,0.136934,0.166591,0.859956,0.173804,0.000000,2.073128,1.388250,0.132402,...,1.712054,2.713111,0.533587,0.665578,1.704469,0.843826,0.681730,5.246845,1.251816,0.940434
786_0,0.361155,0.000000,0.029955,0.056167,0.000000,0.016151,0.000000,0.000000,2.006872,0.000000,...,2.518782,4.195119,0.369624,0.660119,1.919836,0.043749,1.246694,6.732405,1.467530,1.762132
A498,0.440222,0.067594,0.078561,0.038646,0.083573,0.037460,0.000000,0.291472,1.424213,0.042165,...,1.470766,2.806258,0.411828,0.598354,1.297315,0.526957,0.662996,6.670161,1.290324,1.072373
ACHN,0.576425,0.220324,0.020986,0.067487,0.302748,0.014374,0.000000,0.332142,1.582792,0.176846,...,2.700318,4.206784,0.488145,0.751780,1.867363,0.064330,1.006600,6.743057,1.471234,1.944997
CAKI_1,0.882482,0.506823,0.000000,0.036152,0.000000,0.000000,0.000000,0.135979,2.266421,0.000000,...,2.167859,2.884453,0.400211,1.215057,1.710098,0.474023,1.266373,6.547058,0.761174,1.465400
RXF_393,0.572572,0.975728,0.019251,0.020413,0.147273,0.022726,0.000000,0.000000,2.311207,0.094547,...,2.707796,3.556245,0.707476,1.232096,1.799465,0.875894,1.497382,6.892488,1.406139,2.112423
SN12C,1.533733,0.660213,0.024985,0.035940,0.000000,0.000000,0.000000,0.000000,1.670165,0.000000,...,1.687773,4.720623,0.465862,0.630736,1.909151,0.920320,1.212538,7.071076,1.007346,0.865705
TK_10,0.076563,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.572617,0.000000,...,2.771981,3.864523,0.365028,0.821460,1.604811,0.901689,1.590070,6.747535,0.994256,2.221326
UO_31,0.342318,0.471444,0.000000,0.000000,0.227863,0.000000,0.000000,0.000000,1.941689,0.000000,...,2.862285,4.035386,0.482844,1.157290,2.100184,0.325286,1.640838,7.231327,1.714553,2.178909

In [24]:
print("DTI unique genes: ", len(set(dti["Gene"])))
print("Top 90% variable genes: ", len(variance))
print("Total: ", len(set(variance) | (set(dti["Gene"]))))

DTI unique genes:  241
Top 90% variable genes:  2383
Total:  2572

# Preprocessed data dims

In [25]:
genes = sorted(list(set(variance) | (set(dti["Gene"]))))
gene_exp = gene_exp[genes]
gene_exp.shape

(60, 2572)

In [26]:
drug_response.shape

(945, 60)

# Normalize

In [27]:
gene_norm_cell = pd.DataFrame(
    StandardScaler().fit_transform(gene_exp),
    index=gene_exp.index,
    columns=gene_exp.columns,
)
gene_norm_cell

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,-0.376324,2.310284,-0.370815,-0.397579,-0.579935,-0.932530,1.106057,0.387136,1.421020,-0.736827,...,-0.285390,-0.715825,-0.917886,-2.518276,-0.779108,0.932905,0.615674,1.805885,-0.815677,-1.575934
MDA_MB_231,-0.387264,-1.011604,-0.431717,-0.397579,-0.934955,-0.243114,0.676143,-1.412604,1.663180,-0.716900,...,-1.838190,-0.228654,0.227394,1.423209,-0.779108,-0.855846,1.578712,-0.832061,1.862555,-1.454818
HS578T,-0.372187,-0.980388,-0.325888,-0.225341,-1.300565,-0.591523,-0.370487,-0.159464,-0.827946,0.028936,...,0.802006,-1.185070,-0.243143,-0.324218,-0.114256,0.904508,-1.160363,-0.287149,-0.336022,0.724444
BT_549,-0.412522,1.331116,-0.431717,-0.397579,-1.021722,-0.142835,-1.038877,0.432084,-1.092816,0.217943,...,1.320986,-0.119063,-0.023918,-0.986399,1.449155,-0.673092,-1.450610,1.423024,2.390315,-0.203440
T47D,-0.397193,1.878022,-0.416104,-0.397579,-1.257820,-0.091678,2.024752,-0.322621,-0.186534,-0.118696,...,-0.332664,0.400231,0.451186,0.404201,1.552933,1.229210,1.145791,0.907319,1.683829,-1.073747
SF_268,-0.363046,0.115596,-0.431717,-0.397579,-1.719511,-1.131959,-1.968854,-0.957320,-0.854023,-0.862269,...,0.438404,-0.698035,0.812874,-0.098882,1.110562,-0.351052,-0.947517,-1.084631,-0.700465,-0.072248
SF_295,-0.390418,-0.249157,0.686757,-0.337212,1.219555,1.348892,-0.603617,0.719695,-0.192467,1.009630,...,1.055815,0.292586,-0.003184,0.989731,1.033240,0.322160,0.771929,2.211958,-0.882771,1.390531
SF_539,-0.185578,-1.011043,-0.431717,-0.365347,0.963972,0.293545,-0.435006,1.305936,0.220623,1.781673,...,0.520796,0.151541,-0.239729,-0.093653,0.197136,1.737417,0.314128,0.218988,-0.544703,0.972705
SNB_19,-0.050035,0.419132,-0.369670,-0.297337,-0.980557,1.303514,-0.520841,0.581188,0.084009,0.440593,...,2.691975,1.428340,-0.207826,0.057873,1.589442,0.204382,-1.600902,-1.091802,-0.757313,-0.350099
SNB_75,4.812989,-0.390628,-0.411499,-0.210385,0.746291,0.227105,0.296437,0.528289,-0.825563,1.304365,...,1.572359,1.134967,0.427799,-0.089610,1.824346,0.272590,-0.699092,-0.740624,1.296633,0.591615
U251,-0.387966,-0.620627,-0.230480,-0.397579,1.694171,1.374723,-0.016238,1.431536,0.684640,1.102155,...,0.305400,1.250825,0.640392,1.078655,0.962708,0.873619,-0.007329,-0.969120,-0.771126,0.282760
COLO205,-0.393816,-1.001787,-0.431717,-0.349813,0.138811,1.407657,-1.400144,0.128910,1.578786,0.691353,...,-1.807469,-1.831252,-0.756974,-0.958350,-0.779108,2.009910,-0.091106,0.817431,-0.891164,-1.818514
HCC_2998,-0.381608,-0.653948,-0.431717,-0.397579,1.230581,1.243305,1.097670,0.116560,1.383508,0.834634,...,-0.324316,-0.061510,-0.917886,-2.518276,-0.779108,1.591725,-0.007113,1.997756,-0.969005,0.270749
HCT_116,-0.374107,-0.428186,-0.083649,-0.355141,0.727586,0.111233,0.006738,-0.774246,1.205742,0.043659,...,-0.404518,0.041671,-0.881853,0.523702,-0.779108,-1.249498,1.325443,0.492904,-0.881651,-0.152037
HCT_15,-0.384622,1.544531,2.924612,-0.397579,0.644728,0.246107,-0.746591,-0.622619,0.056404,-0.263913,...,-0.103635,0.498288,-0.917886,-0.854926,-0.779108,1.085331,-0.483432,0.751411,-0.867086,-0.287100
HT29,-0.395164,-0.900272,-0.409384,-0.397579,-0.090345,1.772018,-1.833447,0.274781,1.135259,-0.759611,...,-1.269334,-1.933858,-0.885361,-0.120133,-0.779108,1.458266,0.020062,0.047128,-0.817687,-0.469969
KM12,-0.383130,1.012752,-0.406672,-0.397579,-0.072854,0.041203,-1.076922,-1.132484,2.819189,-0.154407,...,-2.179931,-0.137203,-0.875133,-2.423629,-0.779108,0.770770,0.098893,0.165719,-0.852894,-0.176373
SW_620,-0.364332,-0.927695,0.093071,-0.300697,-1.820210,-0.231994,0.938384,-1.514455,2.059352,-2.251674,...,-2.076198,-1.942947,-0.771045,-2.403439,-0.779108,-0.904660,0.590923,-1.528793,-0.797253,-3.127414
CCRF_CEM,-0.342202,-0.909908,0.110451,-0.361942,0.607104,-1.131959,2.943692,-0.326594,-0.267279,-2.260638,...,0.745790,-0.815727,0.649291,0.986655,-0.670655,-1.732985,3.520655,-0.773170,2.377623,-0.493086
HL_60,-0.376827,-0.827252,-0.396332,-0.361089,-1.111847,-1.050821,0.112309,-0.373536,-0.695170,-1.670426,...,-2.177302,-1.875286,-0.758773,0.084066,-0.779108,-1.652910,2.050291,-0.541100,-0.225396,0.047291
K_562,-0.412522,0.853591,0.026417,-0.397579,-0.109806,-1.131959,0.746618,-1.163972,-2.078436,-1.308958,...,-1.179407,-2.029919,0.188925,0.507101,-0.779108,-1.694218,1.589762,-0.972404,-0.837674,-0.367640
MOLT_4,-0.218953,-0.696978,-0.362249,-0.276261,-0.018417,-0.779673,1.288255,-0.484830,-1.562255,-1.772271,...,-1.713925,-0.657245,0.474653,0.820802,-0.470769,-1.413316,1.637121,0.108246,1.428510,-2.665203
RPMI_8226,-0.333622,-0.531197,0.065426,-0.071027,-2.002778,-0.908230,-0.606488,-0.682447,-0.410917,-0.947643,...,-0.917603,-1.762977,-0.576771,0.849997,1.224776,-1.408058,-0.301813,-0.682600,-0.000201,-2.142546
SR,-0.412522,-0.756697,-0.431717,-0.397579,-1.287040,-1.131959,-0.497409,-0.712458,-0.840823,-1.233904,...,-1.535931,-1.916641,-0.805509,0.061684,0.409525,-1.473036,0.190596,-0.862848,-0.910615,-2.124410
LOXIMVI,-0.412522,-1.024671,-0.431717,-0.397579,-1.043293,-1.084074,-0.577098,-1.135501,-0.882689,-0.353765,...,-0.422053,0.607489,-0.874722,0.203243,-0.779108,0.772310,0.439440,-1.292001,-0.969005,0.559236
MALME_3M,3.443198,-0.863670,-0.431717,2.037170,0.116974,-1.105437,0.225812,2.424287,0.886041,0.007434,...,-0.545689,0.777780,-0.513865,0.825469,-0.779108,0.924387,-0.594111,-0.841510,-0.910650,0.101390
M14,0.607077,-0.775931,-0.003895,-0.141589,-0.683776,-1.018384,1.255308,1.656863,1.917072,0.381550,...,0.618948,1.343957,-0.427528,0.416332,-0.631621,-0.838712,-0.847043,0.174024,-0.623153,0.642919
SK_MEL_2,1.110651,-0.960617,-0.263353,0.717720,-1.089864,-1.070521,-0.310564,2.600784,-0.504241,-0.072106,...,0.025252,0.797144,0.439571,0.351420,0.696162,0.060445,-0.780482,-0.042463,0.433775,0.406478
SK_MEL_28,2.519314,-0.999480,-0.431717,1.944324,-0.314705,-1.094078,0.910472,2.321673,0.708583,-0.369154,...,0.077472,0.822042,0.160860,-0.009224,-0.679993,1.433100,-0.886959,-1.403925,-0.890631,-0.131454
SK_MEL_5,2.074816,-0.587464,0.283818,2.202526,-1.307599,-1.063445,-0.456124,0.153770,-0.499296,0.114938,...,0.383292,-0.414078,-0.245260,0.517098,-0.475695,1.920305,-1.196813,0.956741,-0.721934,-0.097842
UACC_257,1.539929,-1.018908,-0.407906,4.785293,-1.132211,-1.131959,0.395205,1.028575,0.568685,0.222138,...,0.635346,0.067616,0.210369,0.797876,-0.779108,1.748692,0.191783,-1.229744,-0.862086,-0.602448
UACC_62,1.866126,-1.034076,-0.353060,2.323109,0.042429,-1.131959,1.544180,0.505745,0.727482,0.365121,...,0.755606,0.686232,0.891706,0.849516,-0.708944,0.466325,0.613609,0.120038,-0.800225,0.716898
MDA_MB_435,-0.334248,-0.983218,-0.431717,3.341539,-0.122034,-1.131959,0.609704,2.291710,1.333770,0.106623,...,0.761986,1.367465,-0.500030,0.866918,-0.779108,-0.413054,0.088179,-1.026267,-0.853150,0.673200
MDA_N,-0.176196,-0.928908,-0.319464,0.727040,-2.175680,-0.998720,-0.454724,1.389274,0.540219,-1.111123,...,0.317979,-0.371590,-0.417847,-0.161652,-0.779108,-0.899979,-1.624650,-1.019073,-0.633309,-0.427440
A549,-0.412522,0.115472,-0.407906,-0.397579,1.202263,1.439569,-1.534727,-1.095711,-0.609115,0.771827,...,-0.788346,-0.872986,-0.777817,0.090264,-0.779108,-0.535594,-0.918457,0.701517,-0.846226,-0.449670
EKVX,0.117129,1.516467,1.326672,-0.397579,1.586743,2.050263,-0.776119,-0.237235,0.677163,0.358320,...,0.513626,0.590759,-0.529739,0.820022,-0.003211,0.676473,-0.488569,0.501279,-0.413373,0.526533
HOP_62,-0.368599,-0.712512,0.086998,-0.397579,1.140747,0.624351,-0.634773,-0.097342,-0.124034,0.643957,...,0.057525,0.545965,0.361231,0.499590,0.040268,0.698790,0.375819,-1.101469,0.969644,0.972161
HOP_92,-0.385867,-0.620375,-0.431717,-0.397579,0.115615,0.504671,0.994395,0.594397,0.021764,1.339876,...,1.020267,0.495493,-0.003275,1.076711,-0.779108,-0.207803,-0.550679,0.021502,0.858660,1.095087
NCI_H226,-0.360428,-0.172497,-0.403404,-0.346301,-0.139874,0.618499,0.368113,-0.765941,0.059387,1.690584,...,-2.128636,0.388457,-0.720675,1.081478,-0.723607,0.474716,-0.125961,0.519807,-0.620577,0.548089
NCI_H23,0.097309,0.624160,-0.364076,-0.397579,0.745258,0.157004,1.222998,0.778244,-0.050087,0.282831,...,0.469477,0.760700,0.928938,0.381806,-0.779108,-1.107794,-0.194160,1.746977,1.245221,1.104811
NCI_H322M,-0.388414,-0.638158,-0.431717,-0.397579,1.206534,1.041908,-0.699271,-0.740540,1.396147,1.827037,...,0.307477,0.564598,0.439253,0.838778,0.904804,-1.554033,-0.280768,-1.219468,1.130294,-0.951814
NCI_H460,-0.379761,0.285637,-0.199132,0.022488,0.404812,1.068956,-0.774465,0.534856,-0.425208,0.929494,...,0.163785,-0.618148,-0.043575,-0.335919,0.515797,-0.325147,-0.998872,0.306499,0.551755,-0.376339
NCI_H522,-0.357839,1.780157,-0.410753,-0.342513,0.178451,-1.089672,1.484033,-0.087574,0.612760,-1.970527,...,0.929723,0.840495,1.198589,0.982855,3.256823,-0.954013,0.893085,2.444970,1.703797,-0.118926
IGROV1,-0.412522,0.439808,-0.373661,-0.397579,0.153564,-1.053473,-0.225400,-1.019082,-0.605447,-0.673311,...,-0.362640,-2.001117,0.303041,-0.489887,-0.779108,-1.187810,0.235576,-0.920935,0.082223,0.213669
OVCAR_3,-0.412522,-0.947561,-0.431717,-0.284508,-0.017928,-0.729724,-1.422334,-0.912961,-1.511876,-1.457553,...,-0.697638,0.296996,-0.917886,-0.903467,-0.522283,0.828934,-0.695712,-0.839125,0.109650,-0.069275
OVCAR_4,-0.348570,-0.216961,-0.412241,-0.366132,1.478018,-0.548861,-0.180158,0.226136,-0.624140,-0.627473,...,0.966982,0.876060,-0.210888,-0.261028,-0.033089,0.004316,-0.269424,-0.339715,-0.449285,0.753650
OVCAR_5,-0.370334,0.858070,-0.402945,-0.327589,-0.553640,1.415064,1.042340,-1.107004,-0.293503,-1.321075,...,0.338227,0.032561,-0.470363,0.462393,-0.749438,-1.038625,0.081378,-0.096306,-0.894754,-0.912476
OVCAR_8,-0.412522,1.734241,-0.259907,-0.397579,0.901740,-1.131959,-0.016428,-0.881237,-1.194046,0.053859,...,0.588697,0.467901,2.231180,-0.457853,0.775395,0.017439,0.033305,0.158667,1.287863,0.979823
SK_OV_3,-0.412522,0.670331,-0.388386,-0.397579,1.570761,0.452212,-0.787558,-0.654484,-0.664154,-0.315204,...,0.683417,-1.940562,2.713901,-0.530605,1.203235,0.170772,-0.058332,-0.785799,0.982898,-0.067446
NCI_ADR_RES,-0.394082,1.970265,5.916502,-0.397579,1.426236,-1.046980,2.264891,-0.526133,0.037242,1.473709,...,1.185808,-0.214550,3.693867,0.542850,2.539952,-0.015871,2.528447,1.561217,2.266906,1.921210
PC_3,-0.356194,1.064557,-0.431717,-0.397579,0.294594,0.737117,-0.020784,1.553651,-0.232705,0.900614,...,0.616415,0.362175,-0.848434,-2.383058,-0.621706,0.115317,0.148639,0.699065,-0.481323,1.046987
DU_145,-0.287685,0.446013,-0.278865,-0.130602,-0.366911,0.856885,-0.820118,-0.440503,0.104536,0.166059,...,0.258123,-0.201586,-0.390198,-0.358955,0.515992,-0.898040,-0.500302,0.217815,0.669220,-0.181422
786_0,-0.370432,-0.693298,-0.044742,-0.397579,0.297322,0.891908,-0.685529,-0.485696,-0.201143,0.041903,...,-0.181114,0.637731,-0.882948,0.528578,-0.013054,-0.141910,-0.509098,-0.335350,0.591355,0.739726
A498,-0.383562,-0.251763,0.659989,-0.366523,0.565353,1.294461,-0.773281,0.111221,-0.937671,1.699805,...,0.174261,0.413866,-0.852585,-2.381473,-0.703289,0.211338,-1.741676,1.254753,-0.576959,0.701130
ACHN,-0.361949,1.363690,0.287988,-0.356486,1.058970,1.460299,0.099174,-0.802260,-0.535678,0.950918,...,0.549893,1.061001,-0.879049,1.283624,-0.736882,0.180655,-0.625386,1.591469,-0.835957,0.746331
CAKI_1,-0.385430,-0.423729,1.718744,-0.397579,0.052081,0.637048,-1.016331,-0.353674,-1.105135,0.200305,...,0.609479,0.657301,-0.116333,-0.775794,-0.779108,-0.549772,-0.010604,-1.302681,0.029836,0.624798
RXF_393,-0.397225,0.994947,-0.226498,-0.397579,-0.194416,0.417522,-0.246060,0.173245,-0.495245,0.570675,...,0.290635,1.296649,-0.031213,0.350200,-0.779108,-0.555621,-0.888336,-0.516759,-0.823175,0.838988
SN12C,-0.385590,-0.607872,-0.431717,-0.397579,-0.913514,-1.070610,-0.441032,-0.753503,-1.668625,0.175779,...,0.071230,0.720948,3.445401,0.209637,2.153511,0.706708,0.962773,0.216988,0.840155,0.949725
TK_10,-0.412522,1.111490,-0.046114,-0.397579,0.105940,1.236563,-0.021378,-0.843028,-0.865751,-0.303890,...,0.282816,0.816970,-0.917886,-0.169731,0.805199,-0.485298,-0.200232,0.323617,0.742670,0.749108
UO_31,-0.412522,1.918705,2.069072,-0.397579,1.746604,0.728447,0.335499,-0.671492,-0.038543,0.903021,...,0.164655,1.051029,0.464573,0.844101,0.237918,0.313929,-0.306111,0.214178,0.529090,1.049091

In [28]:
gene_norm_gene = pd.DataFrame(
    StandardScaler().fit_transform(gene_exp.T),
    index=gene_exp.columns,
    columns=gene_exp.index,
).T
gene_norm_gene

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,-0.982632,0.567365,-0.975612,-1.003344,-0.030254,-0.866450,0.137648,-0.062088,0.538653,-0.213283,...,0.068483,-0.402432,-1.003344,-1.003344,-1.003344,0.542574,0.475096,0.731105,-0.927864,0.282072
MDA_MB_231,-0.897699,-0.870623,-0.910227,-0.910227,-0.149529,-0.381320,-0.034401,-0.852008,0.518998,-0.216972,...,-0.691346,-0.196190,-0.422722,0.764302,-0.910227,-0.428181,0.739053,-0.557505,0.298136,0.276676
HS578T,-1.124606,-1.083526,-1.096679,-1.060163,-0.283831,-0.737708,-0.380460,-0.398718,-0.537476,0.140956,...,0.679829,-0.720621,-0.781804,0.045575,-0.749920,0.551504,-0.375905,-0.392786,-0.803729,2.048335
BT_549,-1.139350,0.029909,-1.139350,-1.139350,-0.248574,-0.431278,-0.629337,-0.134973,-0.686427,0.166970,...,0.862373,-0.228086,-0.681564,-0.356407,0.118888,-0.453971,-0.546501,0.468523,0.585282,1.190944
T47D,-1.094615,0.218447,-1.096215,-1.103062,-0.341708,-0.415395,0.264635,-0.528584,-0.300250,-0.053835,...,-0.094900,-0.032899,-0.455670,0.276235,0.112937,0.543579,0.545517,0.131752,0.154576,0.469228
SF_268,-0.983557,-0.425280,-1.013106,-1.013106,-0.317626,-1.013106,-0.797687,-0.712201,-0.449956,-0.251883,...,0.504289,-0.377388,-0.126035,0.224533,0.054876,-0.141114,-0.188479,-0.721075,-0.875120,1.413927
SF_295,-1.245813,-0.886023,-0.779323,-1.231019,0.111281,0.341763,-0.674103,-0.221924,-0.477154,0.279056,...,0.413697,-0.260181,-0.835835,0.357080,-0.336007,-0.123140,0.195549,0.563313,-1.217820,1.876290
SF_539,-1.077930,-1.163169,-1.209841,-1.194438,0.200892,-0.215830,-0.526593,0.199644,-0.180733,0.832205,...,0.311095,-0.196490,-0.871568,-0.002732,-0.672869,0.812824,0.157126,-0.259178,-0.997656,1.886252
SNB_19,-0.909847,-0.360274,-1.108713,-1.087731,-0.179648,0.715624,-0.422448,0.009350,-0.082387,0.370083,...,1.793512,0.615307,-0.753055,0.261366,0.283488,0.128421,-0.582526,-0.833521,-1.024399,1.227678
SNB_75,1.773122,-0.964318,-1.295340,-1.214165,0.064446,-0.344468,-0.383574,-0.265293,-0.736508,0.526479,...,0.807630,0.185014,-0.624601,-0.079534,0.146322,-0.089564,-0.378917,-0.838587,-0.156668,1.561381
U251,-1.223829,-1.008929,-1.144856,-1.238130,0.375506,0.513276,-0.423962,0.236256,0.001147,0.472898,...,0.170152,0.288908,-0.459293,0.556187,-0.278156,0.302021,-0.012534,-0.894180,-1.138977,1.378511
COLO205,-0.990656,-0.951039,-1.001393,-0.978851,0.168909,0.747425,-0.620945,-0.182952,0.615257,0.485296,...,-0.731833,-0.910256,-0.922128,-0.234455,-1.001393,1.147335,0.169510,0.239552,-0.962951,0.119841
HCC_2998,-1.108214,-0.904278,-1.126983,-1.126983,0.422764,0.603094,0.081026,-0.267654,0.491699,0.519198,...,-0.011455,-0.171861,-1.126983,-1.126983,-1.126983,0.900250,0.150772,0.815911,-1.126983,1.591989
HCT_116,-1.149397,-0.871958,-1.019483,-1.151316,0.090673,-0.358235,-0.402489,-0.811365,0.206816,-0.058646,...,-0.210155,-0.268839,-1.153477,0.248403,-1.170314,-0.848442,0.534057,-0.148571,-1.129392,0.989909
HCT_15,-1.054888,0.339903,0.698333,-1.073394,0.436836,0.023175,-0.403490,-0.550767,0.017090,0.108064,...,0.280278,0.266802,-1.073394,-0.128400,-1.073394,0.816465,0.079358,0.322066,-1.015232,1.449843
HT29,-1.095044,-1.010319,-1.094812,-1.104731,-0.027059,0.839530,-0.863291,-0.239889,0.276461,-0.344901,...,-0.565697,-1.061886,-1.089154,0.041616,-1.104731,0.686658,0.081448,-0.276312,-1.032075,0.894948
KM12,-1.026810,-0.117007,-1.031950,-1.042778,0.010762,-0.278174,-0.589421,-0.849838,1.006270,-0.024728,...,-0.974251,-0.221001,-1.022846,-0.998736,-1.042778,0.339845,0.144880,-0.179680,-0.988507,1.096590
SW_620,-0.725771,-0.677243,-0.544632,-0.710345,-0.201695,-0.220059,0.184611,-0.734238,0.812901,-0.701270,...,-0.640654,-0.715319,-0.687614,-0.701173,-0.749398,-0.296065,0.508088,-0.701197,-0.676949,-0.567254
CCRF_CEM,-0.913539,-0.871840,-0.748265,-0.932311,0.088123,-0.945719,0.413540,-0.470159,-0.307439,-0.904271,...,0.346672,-0.501656,-0.330261,0.428088,-0.898753,-0.889186,1.259886,-0.596594,0.371909,0.681201
HL_60,-0.824478,-0.726676,-0.828315,-0.827378,-0.104088,-0.793088,-0.096031,-0.333767,-0.300208,-0.542062,...,-0.777189,-0.779725,-0.773123,0.292374,-0.842655,-0.740313,1.035352,-0.350229,-0.516874,1.300245
K_562,-0.855109,0.079540,-0.638931,-0.855109,0.284391,-0.855109,0.214018,-0.660386,-0.855109,-0.323643,...,-0.233265,-0.855109,-0.291938,0.681319,-0.855109,-0.759632,1.121423,-0.506666,-0.788115,1.342694
MOLT_4,-0.817647,-0.745629,-0.889442,-0.866361,0.101980,-0.698724,0.167415,-0.448342,-0.711763,-0.656438,...,-0.629544,-0.348584,-0.297699,0.566726,-0.766656,-0.693495,0.831526,-0.119561,0.152789,-0.435250
RPMI_8226,-0.913247,-0.653330,-0.700180,-0.785724,-0.272650,-0.785775,-0.236881,-0.470464,-0.102501,-0.157576,...,-0.098426,-0.822815,-0.769406,0.974346,0.309256,-0.671837,0.296761,-0.399546,-0.405636,0.084224
SR,-0.874145,-0.702587,-0.874145,-0.874145,-0.048853,-0.874145,-0.184979,-0.444797,-0.299149,-0.295035,...,-0.439762,-0.819528,-0.815964,0.459020,-0.195553,-0.647945,0.487312,-0.461468,-0.843838,0.081276
LOXIMVI,-1.023228,-0.983977,-1.023228,-1.023228,-0.184197,-0.990720,-0.400739,-0.823702,-0.502122,-0.058302,...,-0.034491,0.169567,-1.002266,0.295908,-1.023228,0.417818,0.362216,-0.849735,-1.023228,1.708323
MALME_3M,1.255787,-1.038963,-1.163539,0.092479,0.109302,-1.143574,-0.205712,0.953640,0.268923,0.098253,...,-0.138779,0.244411,-0.945986,0.633508,-1.163539,0.526559,-0.126512,-0.722557,-1.132036,1.517981
M14,-0.552075,-0.986602,-0.945189,-1.020448,-0.186123,-1.063406,0.057912,0.433824,0.638826,0.205129,...,0.424783,0.418525,-0.898688,0.312708,-1.061487,-0.570130,-0.298271,-0.218424,-0.970034,1.710347
SK_MEL_2,-0.161565,-1.074534,-1.065918,-0.556216,-0.202213,-1.105164,-0.344881,1.140964,-0.363952,0.112127,...,0.252798,0.317683,-0.394783,0.446973,-0.244325,0.056407,-0.170605,-0.238113,-0.367467,1.868968
SK_MEL_28,0.662458,-1.055665,-1.109811,0.054078,-0.006347,-1.082340,0.032797,0.877201,0.187595,-0.086962,...,0.224805,0.267973,-0.550207,0.189272,-1.053114,0.815811,-0.247000,-0.983994,-1.069051,1.303430
SK_MEL_5,0.515452,-0.777081,-0.683728,0.296828,-0.190497,-0.988390,-0.311817,-0.135071,-0.279407,0.274492,...,0.517023,-0.232347,-0.678865,0.585807,-0.860257,1.246615,-0.296439,0.388575,-0.906871,1.481773
UACC_257,-0.041308,-1.069744,-1.099876,1.222657,-0.321425,-1.110250,-0.225244,0.088464,0.005826,0.090241,...,0.380167,-0.192486,-0.580156,0.444806,-1.110250,0.800887,0.125756,-0.912424,-1.059888,0.763789
UACC_62,0.071564,-1.174055,-1.173616,0.048063,-0.088673,-1.208789,0.042446,-0.227897,0.005364,0.091311,...,0.383153,0.010914,-0.336209,0.412032,-1.171481,0.055769,0.242160,-0.338693,-1.127196,1.610466
MDA_MB_435,-1.059613,-1.045189,-1.105986,0.715246,0.029182,-1.105986,-0.080813,0.826341,0.450784,0.135127,...,0.575987,0.502568,-0.893543,0.611781,-1.105986,-0.276530,0.184260,-0.785891,-1.046934,1.835251
MDA_N,-0.912979,-0.979622,-1.021664,-0.404066,-0.385396,-0.969531,-0.226321,0.757552,0.403361,-0.301104,...,0.708731,-0.107788,-0.770430,0.404747,-1.087717,-0.400705,-0.452159,-0.683544,-0.874168,1.599599
A549,-1.087305,-0.489854,-1.075801,-1.087305,0.454183,0.785520,-0.728337,-0.852755,-0.400378,0.526411,...,-0.231678,-0.525994,-1.014332,0.269080,-1.087305,-0.309292,-0.235512,0.163251,-1.023177,1.102817
EKVX,-0.993030,-0.022920,-0.458523,-1.318530,0.353109,1.027595,-0.707490,-0.633272,-0.014389,0.099890,...,0.285490,-0.031395,-1.113824,0.438686,-0.867303,0.189456,-0.252913,-0.160811,-1.024747,1.623590
HOP_62,-1.255418,-1.082886,-1.024732,-1.282885,0.286897,0.034719,-0.614157,-0.511332,-0.341677,0.311693,...,0.086289,0.004475,-0.596437,0.333569,-0.798002,0.265090,0.217490,-0.986369,-0.239844,2.047705
HOP_92,-1.170468,-0.949802,-1.186490,-1.186490,0.032541,-0.006237,-0.023441,-0.091870,-0.214251,0.700518,...,0.663328,0.026750,-0.714672,0.664489,-1.186490,-0.225544,-0.172896,-0.307734,-0.241256,2.104376
NCI_H226,-1.159711,-0.783180,-1.175590,-1.165048,-0.162991,-0.059725,-0.327144,-0.829813,-0.303382,0.657948,...,-1.094532,-0.149546,-1.096787,0.468448,-1.159482,0.025518,-0.106408,-0.167062,-1.026674,1.397789
NCI_H23,-0.860904,-0.315788,-1.142593,-1.175846,0.259870,-0.220629,0.094354,0.045419,-0.210924,0.210429,...,0.411323,0.201846,-0.196804,0.358600,-1.175846,-0.726027,0.035261,0.664676,0.000953,2.213209
NCI_H322M,-1.122266,-0.911239,-1.136582,-1.136582,0.372451,0.412071,-0.521909,-0.728127,0.452374,0.972464,...,0.300452,0.094728,-0.444975,0.570911,-0.190323,-0.960449,-0.011929,-0.916642,-0.064042,0.645366
NCI_H460,-1.226201,-0.572577,-1.134674,-1.038388,0.054256,0.340466,-0.647984,-0.182205,-0.480963,0.431367,...,0.128428,-0.568009,-0.795093,-0.122829,-0.509671,-0.353628,-0.440076,-0.216989,-0.459789,0.974857
NCI_H522,-1.013425,0.199756,-1.033777,-1.018465,0.059271,-1.015542,0.132865,-0.377455,0.067312,-0.862640,...,0.560742,0.185953,-0.069907,0.563441,1.002850,-0.573046,0.455555,0.881897,0.188929,1.103616
IGROV1,-1.079648,-0.327635,-1.051726,-1.079648,0.156681,-1.022746,-0.301976,-0.806851,-0.394121,-0.212694,...,0.009353,-1.065737,-0.446449,-0.029700,-1.079648,-0.686354,0.305070,-0.697137,-0.533070,1.585039
OVCAR_3,-1.079420,-0.992072,-1.079420,-1.017543,0.228571,-0.758230,-0.646100,-0.719003,-0.789006,-0.566535,...,-0.085616,0.158389,-1.079420,-0.158793,-0.917653,0.652002,-0.031385,-0.610227,-0.461711,1.627871
OVCAR_4,-1.200895,-0.793805,-1.231079,-1.224628,0.421928,-0.804953,-0.424108,-0.301067,-0.543035,-0.322867,...,0.645696,0.206070,-0.862763,-0.036292,-0.800942,-0.117066,-0.055450,-0.527963,-0.962177,1.912666
OVCAR_5,-1.081064,-0.195646,-1.092171,-1.072223,-0.119020,0.653991,0.023327,-0.888416,-0.313896,-0.595154,...,0.304336,-0.156285,-0.884225,0.364626,-1.089188,-0.647567,0.145609,-0.323305,-1.068572,0.649814
OVCAR_8,-1.176154,0.261354,-1.090057,-1.176154,0.333673,-1.176154,-0.295974,-0.818242,-0.747301,0.114841,...,0.510921,0.080823,0.525503,-0.064903,-0.249884,-0.032401,0.168600,-0.179697,0.046493,2.183296
SK_OV_3,-1.104616,-0.189041,-1.082527,-1.104616,0.632958,0.112762,-0.471607,-0.617223,-0.406950,0.008540,...,0.667590,-1.058871,0.891831,-0.014061,0.097018,0.153909,0.218218,-0.623037,-0.028894,1.502204
NCI_ADR_RES,-1.327747,-0.086143,1.219214,-1.337077,0.001015,-1.285494,-0.016633,-0.896964,-0.512693,0.308589,...,0.297191,-0.602992,0.665419,-0.010439,0.252117,-0.434309,0.715195,0.087803,0.071585,1.938073
PC_3,-1.188731,-0.178011,-1.222432,-1.222432,0.041271,0.119134,-0.387482,0.354221,-0.371997,0.433209,...,0.395896,-0.078624,-1.186772,-1.153138,-1.133314,-0.079018,0.108445,0.008763,-0.971394,2.018234
DU_145,-1.149450,-0.318769,-1.151808,-1.079524,0.088662,0.520847,-0.524452,-0.545429,0.000180,0.343049,...,0.512344,-0.162280,-0.907147,0.124578,-0.336341,-0.553907,0.032554,-0.034238,-0.200492,1.662795
786_0,-1.136475,-0.960795,-0.977135,-1.161700,0.104860,0.293369,-0.536992,-0.619846,-0.295293,0.060945,...,0.018545,0.115975,-1.143731,0.402286,-0.727258,-0.165485,-0.132009,-0.473714,-0.357165,1.861781
A498,-1.176390,-0.748060,-0.631771,-1.178612,0.257070,0.692428,-0.549440,-0.280305,-0.625494,1.038051,...,0.294409,0.071305,-1.158830,-1.119186,-1.148643,0.104308,-0.696180,0.456163,-0.976444,2.046098
ACHN,-1.245316,-0.147354,-0.949019,-1.254842,0.128482,0.490529,-0.446030,-0.913457,-0.599888,0.320283,...,0.225923,0.127612,-1.255100,0.573698,-1.251339,-0.153801,-0.349898,0.338951,-1.209062,1.593107
CAKI_1,-1.204690,-0.884264,-0.175558,-1.221243,-0.000445,0.075436,-0.691701,-0.600335,-0.763272,0.107231,...,0.427513,0.090945,-0.800953,-0.309336,-1.221243,-0.446582,0.062985,-1.039662,-0.696172,1.776430
RXF_393,-1.279126,-0.198670,-1.183613,-1.288996,-0.074606,-0.089569,-0.465754,-0.344692,-0.502296,0.316284,...,0.262452,0.426437,-0.798015,0.296329,-1.288996,-0.474565,-0.368689,-0.651210,-1.208039,2.043723
SN12C,-1.085907,-0.873544,-1.101084,-1.101084,-0.231152,-1.059609,-0.440467,-0.719669,-0.923236,0.112475,...,0.139863,0.137821,1.009032,0.215622,0.462798,0.298182,0.505550,-0.180391,-0.223934,1.884982
TK_10,-1.166274,-0.116519,-0.985626,-1.166274,0.024811,0.506378,-0.344966,-0.812581,-0.616525,-0.137670,...,0.244878,0.173059,-1.166274,0.017875,-0.283728,-0.383228,-0.014911,-0.149311,-0.299376,1.810245
UO_31,-1.288298,0.143094,-0.116405,-1.288298,0.357637,0.025874,-0.355144,-0.848776,-0.363302,0.342295,...,0.059071,0.161538,-0.589727,0.407486,-0.721607,-0.049909,-0.184610,-0.327740,-0.529367,1.902490

# Make matrices association matrices by setting 0 threshold and min max scaler.

In [29]:
def min_max_scale(data):
    data = data[data > 0].fillna(0)
    scaler = MinMaxScaler(feature_range=(0, 1))
    return pd.DataFrame(
        scaler.fit_transform(data), index=data.index, columns=data.columns
    )

In [30]:
A_dc = min_max_scale(drug_response)
A_dc

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
740,0.128977,0.000000,0.000000,0.000000,0.000000,0.218376,0.073738,0.159753,0.000000,0.000000,...,0.169317,0.162567,0.000000,0.000000,0.113296,0.089914,0.000000,0.125217,0.000000,0.031215
752,0.087123,0.000000,0.000000,0.000000,0.000000,0.024577,0.017263,0.030245,0.000000,0.000000,...,0.000000,0.162665,0.158043,0.000000,0.000000,0.092498,0.088293,0.000000,0.047244,0.000000
755,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.113088,0.000000,0.000000,...,0.000000,0.174146,0.256472,0.000000,0.000000,0.052200,0.000000,0.000000,0.149532,0.000000
757,0.058329,0.000000,0.000000,0.000000,0.000000,0.131221,0.048824,0.104256,0.113286,0.000000,...,0.000000,0.000000,0.000000,0.038995,0.000000,0.000000,0.000000,0.032982,0.000000,0.000000
762,0.100444,0.000000,0.000000,0.000000,0.330479,0.058097,0.000000,0.152350,0.000000,0.000000,...,0.000000,0.299381,0.243282,0.000000,0.407777,0.209339,0.044218,0.180820,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.048038,0.000000,0.041192,0.000000,0.000000,0.000000,0.000000,0.367916,0.000000,0.074767,...,0.000000,0.000000,0.000000,0.307086,0.063443,0.038392,0.046690,0.261777,0.000000,0.009957
811429,0.016140,0.102516,0.394201,0.235867,0.000000,0.259748,0.042127,0.374084,0.000000,0.268540,...,0.000000,0.000000,0.082979,0.345499,0.098083,0.088327,0.472846,0.182869,0.000000,0.150076
812926,0.000000,0.000000,0.000000,0.000000,0.208303,0.049056,0.000000,0.000000,0.000000,0.064482,...,0.000000,0.000000,0.080457,0.320812,0.475256,0.140043,0.154051,0.000000,0.946972,0.204690
812927,0.671458,0.054456,0.000000,0.000000,0.008461,0.000000,0.000000,0.038330,0.000000,0.323923,...,0.000000,0.000000,0.000000,0.000122,0.000000,0.000000,0.018175,0.000000,0.031606,0.015718
813488,0.058565,0.080082,0.240613,0.390826,0.017063,0.101161,0.000000,0.168305,0.000000,0.343097,...,0.000000,0.000000,0.305425,0.883439,0.073416,0.000000,0.345225,0.039764,0.081098,0.157257

In [31]:
A_cg = min_max_scale(gene_norm_gene + gene_norm_cell)
A_cg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
MCF7,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.370455,0.086871,0.512271,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.465903,0.228169,0.762576,0.000000,0.000000
MDA_MB_231,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.191152,0.000000,0.570435,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.484833,0.000000,0.726137,0.000000
HS578T,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060687,...,0.330362,0.000000,0.000000,0.000000,0.000000,0.459756,0.000000,0.000000,0.000000,0.718470
BT_549,0.000000,0.472964,0.000000,0.000000,0.000000,0.000000,0.000000,0.079404,0.000000,0.137493,...,0.486761,0.000000,0.000000,0.000000,0.368114,0.000000,0.000000,0.568567,1.000000,0.255878
T47D,0.000000,0.728535,0.000000,0.000000,0.000000,0.000000,0.681927,0.000000,0.000000,0.000000,...,0.000000,0.179744,0.000000,0.311055,0.391079,0.559783,0.353790,0.312327,0.617828,0.000000
SF_268,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.210165,0.000000,0.154192,0.057440,0.273598,0.000000,0.000000,0.000000,0.000000,0.347650
SF_295,0.000000,0.000000,0.000000,0.000000,0.603905,0.549296,0.000000,0.133032,0.000000,0.460327,...,0.327615,0.015856,0.000000,0.615682,0.163682,0.062843,0.202378,0.834200,0.000000,0.846484
SF_539,0.000000,0.000000,0.000000,0.000000,0.528590,0.025250,0.000000,0.402374,0.010427,0.933694,...,0.185463,0.000000,0.000000,0.000000,0.000000,0.805275,0.098578,0.000000,0.000000,0.740800
SNB_19,0.000000,0.020454,0.000000,0.000000,0.000000,0.656021,0.000000,0.157824,0.000424,0.289579,...,1.000000,1.000000,0.000000,0.145937,0.439689,0.105087,0.000000,0.000000,0.000000,0.227394
SNB_75,1.000000,0.000000,0.000000,0.000000,0.367895,0.000000,0.000000,0.070287,0.000000,0.653989,...,0.530598,0.645895,0.000000,0.000000,0.462634,0.057793,0.000000,0.000000,0.383105,0.557875
U251,0.000000,0.000000,0.000000,0.000000,0.939175,0.613414,0.000000,0.445725,0.179269,0.562619,...,0.106020,0.753424,0.040656,0.747353,0.160705,0.371225,0.000000,0.000000,0.000000,0.430461
COLO205,0.000000,0.000000,0.000000,0.000000,0.139636,0.700189,0.000000,0.000000,0.573537,0.420307,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.996945,0.016401,0.317711,0.000000,0.000000
HCC_2998,0.000000,0.000000,0.000000,0.000000,0.750252,0.599898,0.351092,0.000000,0.490191,0.483598,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.786877,0.030051,0.845741,0.000000,0.482664
HCT_116,0.000000,0.000000,0.000000,0.000000,0.371308,0.000000,0.000000,0.000000,0.369252,0.000000,...,0.000000,0.000000,0.000000,0.352960,0.000000,0.000000,0.388973,0.103501,0.000000,0.217106
HCT_15,0.000000,0.654852,0.507720,0.000000,0.490791,0.087490,0.000000,0.000000,0.019212,0.000000,...,0.039381,0.374375,0.000000,0.000000,0.000000,0.600519,0.000000,0.322669,0.000000,0.301285
HT29,0.000000,0.000000,0.000000,0.000000,0.000000,0.848495,0.000000,0.009325,0.369033,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.677290,0.021234,0.000000,0.000000,0.110119
KM12,0.000000,0.311277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.350692,0.050993,0.000000,0.000000,0.238443
SW_620,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334500,0.000000,0.750826,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.229893,0.000000,0.000000,0.000000
CCRF_CEM,0.000000,0.000000,0.000000,0.000000,0.315479,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.243555,0.000000,0.071621,0.646737,0.000000,0.000000,1.000000,0.000000,0.924027,0.048744
HL_60,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004849,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.172086,0.000000,0.000000,0.645459,0.000000,0.000000,0.349167
K_562,0.000000,0.324269,0.000000,0.000000,0.079223,0.000000,0.286139,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.543275,0.000000,0.000000,0.567129,0.000000,0.000000,0.252652
MOLT_4,0.000000,0.000000,0.000000,0.000000,0.037919,0.000000,0.433592,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.039725,0.634295,0.000000,0.000000,0.516395,0.000000,0.531423,0.000000
RPMI_8226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.833981,0.360129,0.000000,0.000000,0.000000,0.000000,0.000000
SR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.238035,0.050232,0.000000,0.141806,0.000000,0.000000,0.000000
LOXIMVI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.380230,0.000000,0.228182,0.000000,0.375800,0.167691,0.000000,0.000000,0.587560
MALME_3M,0.713469,0.000000,0.000000,0.354472,0.102679,0.000000,0.005987,0.902767,0.301915,0.037752,...,0.000000,0.500180,0.000000,0.666958,0.000000,0.458157,0.000000,0.000000,0.000000,0.419604
M14,0.008351,0.000000,0.000000,0.000000,0.000000,0.000000,0.391161,0.558746,0.668128,0.209566,...,0.232691,0.862420,0.000000,0.333274,0.000000,0.000000,0.000000,0.000000,0.000000,0.609768
SK_MEL_2,0.144104,0.000000,0.000000,0.026882,0.000000,0.000000,0.000000,1.000000,0.000000,0.014296,...,0.061989,0.545508,0.010055,0.364978,0.106073,0.036898,0.000000,0.000000,0.022284,0.589604
SK_MEL_28,0.483103,0.000000,0.000000,0.332626,0.000000,0.000000,0.280966,0.854914,0.234267,0.000000,...,0.067390,0.533367,0.000000,0.082307,0.000000,0.710126,0.000000,0.000000,0.000000,0.303677
SK_MEL_5,0.393292,0.000000,0.000000,0.416008,0.000000,0.000000,0.000000,0.004997,0.000000,0.139107,...,0.200717,0.000000,0.000000,0.504183,0.000000,1.000000,0.000000,0.404379,0.000000,0.358598
UACC_257,0.227543,0.000000,0.000000,1.000000,0.000000,0.000000,0.050625,0.298534,0.150181,0.111584,...,0.226400,0.000000,0.000000,0.568080,0.000000,0.805066,0.066423,0.000000,0.000000,0.041806
UACC_62,0.294208,0.000000,0.000000,0.394672,0.000000,0.000000,0.472600,0.074256,0.191571,0.163040,...,0.253876,0.341128,0.124707,0.576705,0.000000,0.164859,0.179011,0.000000,0.000000,0.603056
MDA_MB_435,0.000000,0.000000,0.000000,0.675236,0.000000,0.000000,0.157538,0.833314,0.466494,0.086355,...,0.298289,0.915047,0.000000,0.675973,0.000000,0.000000,0.056989,0.000000,0.000000,0.649979
MDA_N,0.000000,0.000000,0.000000,0.053758,0.000000,0.000000,0.000000,0.573749,0.246658,0.000000,...,0.228896,0.000000,0.000000,0.111129,0.000000,0.000000,0.000000,0.000000,0.000000,0.303724
A549,0.000000,0.000000,0.000000,0.000000,0.751660,0.722934,0.000000,0.000000,0.000000,0.463739,...,0.000000,0.000000,0.000000,0.164271,0.000000,0.000000,0.000000,0.259935,0.000000,0.169240
EKVX,0.000000,0.519016,0.121663,0.000000,0.880263,1.000000,0.000000,0.000000,0.173253,0.163675,...,0.178156,0.273709,0.000000,0.575407,0.000000,0.273430,0.000000,0.102339,0.000000,0.557130
HOP_62,0.000000,0.000000,0.000000,0.000000,0.647834,0.214133,0.000000,0.000000,0.000000,0.341365,...,0.032062,0.269342,0.000000,0.380871,0.000000,0.304359,0.124109,0.000000,0.245262,0.782494
HOP_92,0.000000,0.000000,0.000000,0.000000,0.067230,0.161942,0.289213,0.134303,0.000000,0.728842,...,0.375343,0.255544,0.000000,0.795973,0.000000,0.000000,0.000000,0.000000,0.207489,0.829030
NCI_H226,0.000000,0.000000,0.000000,0.000000,0.000000,0.181546,0.012203,0.000000,0.000000,0.838911,...,0.000000,0.116904,0.000000,0.708534,0.000000,0.157956,0.000000,0.106029,0.000000,0.504207
NCI_H23,0.000000,0.107161,0.000000,0.000000,0.456105,0.000000,0.392392,0.220128,0.000000,0.176196,...,0.196367,0.470994,0.164361,0.338470,0.000000,0.000000,0.000000,0.724902,0.418798,0.859750
NCI_H322M,0.000000,0.000000,0.000000,0.000000,0.716509,0.472400,0.000000,0.000000,0.483215,1.000000,...,0.135532,0.322622,0.000000,0.644426,0.167731,0.000000,0.000000,0.000000,0.358332,0.000000
NCI_H460,0.000000,0.000000,0.000000,0.000000,0.208315,0.457923,0.000000,0.094248,0.000000,0.486108,...,0.065146,0.000000,0.000000,0.000000,0.001438,0.000000,0.000000,0.026905,0.030907,0.155085
NCI_H522,0.000000,0.688032,0.000000,0.000000,0.107873,0.000000,0.481616,0.000000,0.177775,0.000000,...,0.332286,0.502263,0.253384,0.706875,1.000000,0.000000,0.282110,1.000000,0.636083,0.255148
IGROV1,0.000000,0.038981,0.000000,0.000000,0.140782,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.113093,0.000000,0.000000,0.466073
OVCAR_3,0.000000,0.000000,0.000000,0.000000,0.095585,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.222829,0.000000,0.000000,0.000000,0.467627,0.000000,0.000000,0.000000,0.403856
OVCAR_4,0.000000,0.000000,0.000000,0.000000,0.862155,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.359532,0.529509,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.690884
OVCAR_5,0.000000,0.230197,0.000000,0.000000,0.000000,0.672238,0.317424,0.000000,0.000000,0.000000,...,0.143254,0.000000,0.000000,0.378064,0.000000,0.000000,0.047481,0.000000,0.000000,0.000000
OVCAR_8,0.000000,0.693481,0.000000,0.000000,0.560604,0.000000,0.000000,0.000000,0.000000,0.060261,...,0.245150,0.268502,0.618863,0.000000,0.123369,0.000000,0.042235,0.000000,0.448433,0.819613
SK_OV_3,0.000000,0.167251,0.000000,0.000000,1.000000,0.183561,0.000000,0.000000,0.000000,0.000000,...,0.301195,0.000000,0.809471,0.000000,0.305247,0.102523,0.033445,0.000000,0.320609,0.371768
NCI_ADR_RES,0.000000,0.654743,1.000000,0.000000,0.647656,0.000000,0.669676,0.000000,0.000000,0.636648,...,0.330622,0.000000,0.978640,0.243387,0.655466,0.000000,0.678509,0.495667,0.785890,1.000000
PC_3,0.000000,0.308080,0.000000,0.000000,0.152408,0.278197,0.000000,0.509888,0.000000,0.476450,...,0.225686,0.138748,0.000000,0.000000,0.000000,0.011462,0.053777,0.212761,0.000000,0.794246
DU_145,0.000000,0.044218,0.000000,0.000000,0.000000,0.447627,0.000000,0.000000,0.027373,0.181857,...,0.171769,0.000000,0.000000,0.000000,0.042175,0.000000,0.000000,0.055180,0.157524,0.383847
786_0,0.000000,0.000000,0.000000,0.000000,0.182501,0.385098,0.000000,0.000000,0.000000,0.036738,...,0.000000,0.368805,0.000000,0.425536,0.000000,0.000000,0.000000,0.000000,0.078704,0.674091
A498,0.000000,0.000000,0.003955,0.000000,0.373197,0.645543,0.000000,0.000000,0.000000,0.977980,...,0.104486,0.237405,0.000000,0.000000,0.000000,0.099669,0.000000,0.514272,0.000000,0.711850
ACHN,0.000000,0.422684,0.000000,0.000000,0.538840,0.633826,0.000000,0.000000,0.000000,0.454081,...,0.172961,0.581614,0.000000,0.849058,0.000000,0.008480,0.000000,0.580252,0.000000,0.606185
CAKI_1,0.000000,0.000000,0.216262,0.000000,0.023431,0.231487,0.000000,0.000000,0.000000,0.109854,...,0.231188,0.366133,0.000000,0.000000,0.000000,0.000000,0.010957,0.000000,0.000000,0.622196
RXF_393,0.000000,0.276711,0.000000,0.000000,0.000000,0.106552,0.000000,0.000000,0.000000,0.316828,...,0.123306,0.843142,0.000000,0.295555,0.000000,0.000000,0.000000,0.000000,0.000000,0.746955
SN12C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.102966,...,0.047061,0.420214,1.000000,0.194403,0.614204,0.317308,0.307146,0.011000,0.207092,0.734517
TK_10,0.000000,0.345758,0.000000,0.000000,0.059332,0.566284,0.000000,0.000000,0.000000,0.000000,...,0.117645,0.484443,0.000000,0.000000,0.122420,0.000000,0.000000,0.052393,0.148976,0.663168
UO_31,0.000000,0.716487,0.273647,0.000000,0.954859,0.245080,0.000000,0.000000,0.000000,0.444835,...,0.049878,0.593335,0.000000,0.572151,0.000000,0.083368,0.000000,0.000000,0.000000,0.764800

In [32]:
A_dg = (
    pd.DataFrame(
        np.ones([len(A_dc.index), len(A_cg.columns)]),
        index=A_dc.index,
        columns=A_cg.columns,
    )
    / 2
)
for _, i in dti.iterrows():
    A_dg.loc[int(i["NSC"]), i["Gene"]] = 1
A_dg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
752,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
755,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
757,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
762,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
811429,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812926,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812927,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
813488,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

In [33]:
A_dg.sum().sum()

1215552.5

In [34]:
print(
    "Drug Density: ",
    round(len(A_dc.values.nonzero()[0]) / drug_response.size, 4) * 100,
    "%",
)
print("Cell Density: ", round(len(A_cg.values.nonzero()[0]) / A_cg.size, 4) * 100, "%")
print("Gene Density: ", round(len(A_dg.values.nonzero()[0]) / A_dg.size, 5) * 100, "%")

Drug Density:  38.74 %
Cell Density:  45.540000000000006 %
Gene Density:  100.0 %

# Similarity

In [35]:
def normalize_similarity_matrix(df, gamma=None):
    similarity_matrix = rbf_kernel(df.values, gamma=gamma)
    scaler = MinMaxScaler()
    normalized_matrix = scaler.fit_transform(similarity_matrix.reshape(-1, 1))
    normalized_df = pd.DataFrame(
        normalized_matrix.reshape(similarity_matrix.shape),
        index=df.index,
        columns=df.index,
    )

    return normalized_df

In [36]:
cell_sim = normalize_similarity_matrix(drug_response.T)
cell_sim.to_csv("../nci_data/cell_sim.csv")
cell_sim

,MCF7,MDA_MB_231,HS578T,BT_549,T47D,SF_268,SF_295,SF_539,SNB_19,SNB_75,...,PC_3,DU_145,786_0,A498,ACHN,CAKI_1,RXF_393,SN12C,TK_10,UO_31
MCF7,1.000000,0.090531,0.095900,0.180825,0.256157,0.271033,0.307666,0.304364,0.184508,0.138386,...,0.284152,0.247726,0.287262,0.100862,0.265450,0.155487,0.293325,0.290709,0.091236,0.157978
MDA_MB_231,0.090531,1.000000,0.232787,0.308877,0.172754,0.260258,0.133964,0.144332,0.251758,0.059027,...,0.342434,0.212203,0.236239,0.047582,0.148558,0.093923,0.228379,0.256381,0.246700,0.121524
HS578T,0.095900,0.232787,1.000000,0.248394,0.141432,0.161340,0.128405,0.146928,0.122860,0.147777,...,0.268438,0.090173,0.172876,0.113248,0.097370,0.071809,0.264719,0.152804,0.160351,0.096088
BT_549,0.180825,0.308877,0.248394,1.000000,0.350510,0.454899,0.263582,0.343155,0.367783,0.144353,...,0.426096,0.314730,0.448054,0.108579,0.245028,0.176371,0.365588,0.386630,0.208495,0.217904
T47D,0.256157,0.172754,0.141432,0.350510,1.000000,0.363311,0.282350,0.252988,0.302173,0.123443,...,0.398544,0.306273,0.353015,0.095717,0.279035,0.191598,0.291979,0.362506,0.194020,0.253133
SF_268,0.271033,0.260258,0.161340,0.454899,0.363311,1.000000,0.406679,0.463802,0.609566,0.149242,...,0.463956,0.605697,0.617291,0.083953,0.434390,0.276777,0.382451,0.681362,0.188751,0.238589
SF_295,0.307666,0.133964,0.128405,0.263582,0.282350,0.406679,1.000000,0.369646,0.291196,0.139236,...,0.336974,0.312142,0.378843,0.095841,0.296616,0.187985,0.301786,0.388796,0.108936,0.174433
SF_539,0.304364,0.144332,0.146928,0.343155,0.252988,0.463802,0.369646,1.000000,0.300679,0.208595,...,0.310818,0.341978,0.487190,0.121688,0.336182,0.198752,0.422823,0.434596,0.096562,0.169208
SNB_19,0.184508,0.251758,0.122860,0.367783,0.302173,0.609566,0.291196,0.300679,1.000000,0.085396,...,0.391853,0.483069,0.442068,0.046300,0.283359,0.169318,0.243674,0.493894,0.157144,0.156158
SNB_75,0.138386,0.059027,0.147777,0.144353,0.123443,0.149242,0.139236,0.208595,0.085396,1.000000,...,0.149572,0.083606,0.153697,0.131088,0.127400,0.087126,0.306834,0.151246,0.056327,0.112334
U251,0.320910,0.206723,0.145777,0.348151,0.307983,0.631487,0.407226,0.506800,0.534681,0.154209,...,0.447718,0.501323,0.527297,0.085946,0.367912,0.215222,0.364307,0.556515,0.132139,0.177363
COLO205,0.205376,0.240160,0.159288,0.179348,0.145932,0.205102,0.169963,0.172655,0.160210,0.091218,...,0.280710,0.170630,0.181426,0.073712,0.151735,0.098684,0.247520,0.229138,0.164953,0.108315
HCC_2998,0.172740,0.368489,0.159562,0.347723,0.256488,0.420669,0.218107,0.232855,0.445181,0.073251,...,0.417126,0.421404,0.384702,0.058370,0.229135,0.154494,0.264987,0.392456,0.228487,0.168786
HCT_116,0.423583,0.230201,0.148081,0.286781,0.255460,0.464840,0.337765,0.402649,0.326521,0.151369,...,0.415857,0.420682,0.442443,0.110308,0.387069,0.271459,0.407759,0.483511,0.179394,0.231722
HCT_15,0.156977,0.258175,0.149506,0.259842,0.185883,0.274352,0.182262,0.180994,0.217345,0.073773,...,0.351432,0.261524,0.281189,0.061300,0.256521,0.234526,0.234865,0.263975,0.220257,0.267702
HT29,0.354755,0.270918,0.177334,0.255931,0.247575,0.339405,0.260732,0.289409,0.252904,0.122612,...,0.402477,0.321062,0.351821,0.108957,0.269597,0.189606,0.350192,0.358176,0.208177,0.207704
KM12,0.136158,0.167533,0.133638,0.153582,0.091440,0.190326,0.160994,0.182568,0.127835,0.076593,...,0.214825,0.155570,0.179698,0.068510,0.129876,0.105874,0.238797,0.217122,0.102313,0.100316
SW_620,0.351237,0.264118,0.140064,0.280331,0.231153,0.480986,0.303813,0.342410,0.397961,0.117017,...,0.424843,0.444971,0.400946,0.081724,0.315162,0.212738,0.352872,0.476455,0.188003,0.178087
CCRF_CEM,0.196012,0.052298,0.028876,0.116179,0.121119,0.231536,0.179560,0.235403,0.144002,0.056353,...,0.168483,0.212639,0.231990,0.027500,0.180204,0.109841,0.141200,0.250870,0.032319,0.072493
HL_60,0.286660,0.132089,0.063886,0.177205,0.173581,0.301961,0.205424,0.251264,0.204363,0.081381,...,0.244062,0.271499,0.295043,0.053900,0.248231,0.176294,0.233197,0.310953,0.090553,0.130061
K_562,0.129349,0.146833,0.073852,0.146956,0.119895,0.225204,0.155570,0.200086,0.155462,0.057290,...,0.192392,0.186749,0.198309,0.040000,0.151301,0.096344,0.161885,0.212845,0.070918,0.088013
MOLT_4,0.247961,0.070527,0.043840,0.163116,0.196546,0.326369,0.241924,0.287459,0.212911,0.078376,...,0.230786,0.286940,0.338159,0.044506,0.264016,0.155683,0.191593,0.340457,0.053257,0.119949
RPMI_8226,0.184429,0.204763,0.102781,0.248284,0.245245,0.302772,0.196500,0.213397,0.246387,0.066361,...,0.385483,0.243589,0.285906,0.048868,0.185410,0.134332,0.208057,0.275935,0.128329,0.140983
SR,0.171651,0.013051,0.012688,0.039992,0.042172,0.101669,0.099936,0.141932,0.049139,0.054310,...,0.060227,0.075773,0.084432,0.024783,0.093156,0.063336,0.095506,0.102048,0.011298,0.035837
LOXIMVI,0.358379,0.207759,0.130299,0.307550,0.289893,0.485118,0.340731,0.453076,0.321150,0.155552,...,0.380085,0.422622,0.502545,0.115750,0.417806,0.272118,0.406845,0.505103,0.146720,0.249047
MALME_3M,0.143356,0.260506,0.138660,0.268996,0.292807,0.275997,0.183870,0.183509,0.230778,0.083477,...,0.319508,0.234920,0.273206,0.075711,0.210690,0.147052,0.256333,0.287360,0.198532,0.214624
M14,0.280937,0.293603,0.136130,0.356094,0.298279,0.497427,0.323846,0.360060,0.372020,0.110269,...,0.413801,0.473798,0.485722,0.108460,0.390707,0.264630,0.354942,0.493182,0.184739,0.272054
SK_MEL_2,0.145258,0.388908,0.231243,0.344515,0.225866,0.326040,0.193631,0.201075,0.280555,0.081645,...,0.367392,0.272226,0.261524,0.078763,0.213487,0.144578,0.296805,0.303115,0.281286,0.165196
SK_MEL_28,0.094307,0.374605,0.164657,0.265263,0.212817,0.249762,0.130071,0.116892,0.262727,0.049341,...,0.317373,0.202107,0.211560,0.041031,0.141325,0.081928,0.182351,0.233585,0.228317,0.132619
SK_MEL_5,0.299163,0.244600,0.155270,0.361646,0.363878,0.507787,0.362141,0.394073,0.408546,0.131609,...,0.470798,0.418651,0.441241,0.098364,0.343153,0.235985,0.359143,0.465611,0.165141,0.218441
UACC_257,0.133640,0.328435,0.131870,0.298622,0.257548,0.312124,0.181298,0.164141,0.298167,0.056856,...,0.331150,0.254650,0.255679,0.058493,0.197579,0.131416,0.208147,0.295774,0.268985,0.178909
UACC_62,0.317299,0.185470,0.112887,0.289945,0.338492,0.485049,0.364832,0.383742,0.325621,0.138560,...,0.355102,0.391739,0.450814,0.109044,0.420961,0.270634,0.346933,0.475275,0.148708,0.246611
MDA_MB_435,0.225019,0.208815,0.152105,0.220334,0.177913,0.262707,0.203452,0.237676,0.187405,0.115524,...,0.329200,0.223184,0.238615,0.080112,0.180066,0.129232,0.285395,0.262584,0.131724,0.142031
MDA_N,0.373719,0.440490,0.297929,0.523052,0.417867,0.620309,0.416672,0.457960,0.483332,0.191429,...,0.656012,0.532533,0.583880,0.157647,0.445966,0.301458,0.524324,0.602971,0.337579,0.327807
A549,0.351182,0.260720,0.177675,0.384055,0.352763,0.603301,0.406914,0.409243,0.515463,0.138799,...,0.510675,0.574725,0.546411,0.104773,0.427968,0.292771,0.377412,0.581927,0.220641,0.272199
EKVX,0.082900,0.291544,0.190038,0.247584,0.193150,0.210859,0.115004,0.089787,0.193245,0.061011,...,0.287259,0.189135,0.178049,0.062348,0.166983,0.124196,0.184709,0.183236,0.336374,0.176190
HOP_62,0.293448,0.259959,0.155233,0.390406,0.340638,0.634653,0.395939,0.449079,0.511580,0.140908,...,0.450879,0.565994,0.611240,0.087001,0.396954,0.264876,0.366585,0.572332,0.165724,0.252330
HOP_92,0.066050,0.047373,0.045705,0.060398,0.065237,0.052130,0.059234,0.045337,0.035607,0.043882,...,0.084753,0.031665,0.054208,0.074057,0.058252,0.047939,0.098497,0.063606,0.052490,0.080946
NCI_H226,0.165204,0.216936,0.148735,0.363339,0.253956,0.427843,0.240072,0.263417,0.357833,0.101841,...,0.295908,0.313181,0.339297,0.087027,0.284382,0.184311,0.277093,0.398385,0.165797,0.185955
NCI_H23,0.263422,0.255525,0.109459,0.361784,0.293156,0.573631,0.352792,0.368624,0.505266,0.092048,...,0.380186,0.568083,0.487433,0.061879,0.367493,0.225095,0.303834,0.577620,0.145698,0.185650
NCI_H322M,0.120887,0.281993,0.168246,0.296711,0.234724,0.342669,0.160350,0.149165,0.321097,0.063839,...,0.322196,0.330345,0.286333,0.069986,0.259418,0.174983,0.207100,0.316889,0.335643,0.192073
NCI_H460,0.380562,0.066843,0.051593,0.161675,0.196521,0.352600,0.311036,0.335790,0.241171,0.084189,...,0.247078,0.344691,0.327896,0.052112,0.310796,0.185700,0.212201,0.355858,0.059011,0.120629
NCI_H522,0.214166,0.175564,0.119387,0.251705,0.286967,0.392191,0.236256,0.301741,0.248138,0.128339,...,0.319470,0.345403,0.326983,0.080800,0.299770,0.214700,0.289504,0.375284,0.168426,0.176609
IGROV1,0.222915,0.275834,0.220480,0.338023,0.331227,0.376351,0.247111,0.248989,0.308922,0.132358,...,0.430968,0.342180,0.392154,0.138523,0.337973,0.228438,0.392805,0.395045,0.351196,0.309268
OVCAR_3,0.220327,0.367753,0.304511,0.413318,0.322862,0.430923,0.263915,0.277380,0.348305,0.123172,...,0.538248,0.383265,0.377451,0.083714,0.241895,0.162785,0.342478,0.365283,0.257900,0.182206
OVCAR_4,0.104339,0.367045,0.187183,0.348011,0.219285,0.275838,0.151455,0.152236,0.245409,0.065915,...,0.310491,0.214592,0.237152,0.055995,0.175002,0.114382,0.213660,0.245665,0.245288,0.164380
OVCAR_5,0.122031,0.334693,0.138079,0.260242,0.199250,0.306807,0.153023,0.133319,0.290281,0.046190,...,0.317963,0.300237,0.252577,0.048062,0.188304,0.116159,0.200443,0.273329,0.272185,0.146651
OVCAR_8,0.222478,0.290270,0.135442,0.370044,0.331421,0.575096,0.319497,0.334806,0.511432,0.087986,...,0.465621,0.606985,0.490206,0.053812,0.354177,0.209487,0.298440,0.550174,0.191527,0.201310
SK_OV_3,0.132242,0.197775,0.124506,0.274477,0.251162,0.276608,0.171791,0.199759,0.227467,0.099877,...,0.270600,0.288133,0.262639,0.078107,0.236561,0.166260,0.229691,0.272173,0.237524,0.171992
NCI_ADR_RES,0.020687,0.079300,0.023363,0.095650,0.071333,0.126319,0.056657,0.040375,0.116162,0.006125,...,0.109761,0.133756,0.111426,0.002711,0.080230,0.099981,0.044685,0.095855,0.054453,0.106252
PC_3,0.284152,0.342434,0.268438,0.426096,0.398544,0.463956,0.336974,0.310818,0.391853,0.149572,...,1.000000,0.396391,0.438299,0.109797,0.290368,0.219924,0.397601,0.438285,0.252945,0.259044
DU_145,0.247726,0.212203,0.090173,0.314730,0.306273,0.605697,0.312142,0.341978,0.483069,0.083606,...,0.396391,1.000000,0.524321,0.053454,0.441893,0.266365,0.284083,0.587259,0.177686,0.207866
786_0,0.287262,0.236239,0.172876,0.448054,0.353015,0.617291,0.378843,0.487190,0.442068,0.153697,...,0.438299,0.524321,1.000000,0.105442,0.447086,0.298768,0.422277,0.564293,0.171283,0.283963
A498,0.100862,0.047582,0.113248,0.108579,0.095717,0.083953,0.095841,0.121688,0.046300,0.131088,...,0.109797,0.053454,0.105442,1.000000,0.112529,0.080370,0.224718,0.097566,0.074064,0.135925
ACHN,0.265450,0.148558,0.097370,0.245028,0.279035,0.434390,0.296616,0.336182,0.283359,0.127400,...,0.290368,0.441893,0.447086,0.112529,1.000000,0.422541,0.336958,0.506578,0.204967,0.340941
CAKI_1,0.155487,0.093923,0.071809,0.176371,0.191598,0.276777,0.187985,0.198752,0.169318,0.087126,...,0.219924,0.266365,0.298768,0.080370,0.422541,1.000000,0.230117,0.306223,0.150634,0.358632
RXF_393,0.293325,0.228379,0.264719,0.365588,0.291979,0.382451,0.301786,0.422823,0.243674,0.306834,...,0.397601,0.284083,0.422277,0.224718,0.336958,0.230117,1.000000,0.391111,0.197918,0.268127
SN12C,0.290709,0.256381,0.152804,0.386630,0.362506,0.681362,0.388796,0.434596,0.493894,0.151246,...,0.438285,0.587259,0.564293,0.097566,0.506578,0.306223,0.391111,1.000000,0.197901,0.270375
TK_10,0.091236,0.246700,0.160351,0.208495,0.194020,0.188751,0.108936,0.096562,0.157144,0.056327,...,0.252945,0.177686,0.171283,0.074064,0.204967,0.150634,0.197918,0.197901,1.000000,0.212084
UO_31,0.157978,0.121524,0.096088,0.217904,0.253133,0.238589,0.174433,0.169208,0.156158,0.112334,...,0.259044,0.207866,0.283963,0.135925,0.340941,0.358632,0.268127,0.270375,0.212084,1.000000

In [37]:
print("Min:", np.min(cell_sim.values))
print("Max:", np.max(cell_sim.values))
print("Mean:", np.mean(cell_sim.values))
print("Median:", np.median(cell_sim.values))

Min: 0.0
Max: 0.9999999999999999
Mean: 0.26115614745943533
Median: 0.2434565725556461

In [38]:
gene_sim = normalize_similarity_matrix(gene_norm_cell.T)
os.makedirs("../nci_data/gene_sim", exist_ok=True)
chunks = np.array_split(gene_sim, 25)

for i, chunk in tqdm(enumerate(chunks)):
    chunk.to_parquet(
        f"../nci_data/gene_sim/gene_sim_part_{i}.parquet", compression="gzip"
    )
gene_sim

/Users/inouey2/miniconda3/envs/torch/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
25it [00:05,  4.41it/s]

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
A2M,1.000000,0.060190,0.090301,0.391793,0.099959,0.062216,0.166070,0.340668,0.138102,0.156964,...,0.185882,0.210333,0.128977,0.165382,0.119324,0.222604,0.069420,0.076629,0.097455,0.140388
ABCA3,0.060190,1.000000,0.275980,0.048084,0.215076,0.174623,0.159356,0.058527,0.087342,0.135836,...,0.194404,0.154588,0.187560,0.078862,0.244293,0.101630,0.123893,0.361435,0.203343,0.167400
ABCB1,0.090301,0.275980,1.000000,0.087243,0.240955,0.132595,0.166354,0.080465,0.104796,0.189396,...,0.176134,0.141762,0.229688,0.131027,0.180989,0.128992,0.187949,0.200042,0.174078,0.223905
ABCB5,0.391793,0.048084,0.087243,1.000000,0.063024,0.041796,0.164287,0.373311,0.186304,0.119026,...,0.162311,0.170567,0.114037,0.193312,0.068295,0.224850,0.086748,0.064751,0.059511,0.115838
ABCC1,0.099959,0.215076,0.240955,0.063024,1.000000,0.349966,0.127889,0.114741,0.122463,0.340527,...,0.202791,0.227102,0.182738,0.139628,0.134596,0.157619,0.154868,0.230891,0.160625,0.333414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.222604,0.101630,0.128992,0.224850,0.157619,0.175506,0.071109,0.230201,0.185125,0.284584,...,0.141732,0.190102,0.101912,0.068699,0.103096,1.000000,0.058706,0.178124,0.050863,0.194664
ZNRD1,0.069420,0.123893,0.187949,0.086748,0.154868,0.054900,0.418163,0.054293,0.126994,0.045645,...,0.055761,0.058149,0.244632,0.189314,0.128546,0.058706,1.000000,0.126709,0.250182,0.083467
ZP3,0.076629,0.361435,0.200042,0.064751,0.230891,0.211739,0.172942,0.119484,0.133095,0.218610,...,0.155753,0.153724,0.125526,0.079986,0.181292,0.178124,0.126709,1.000000,0.159002,0.197240
ZSCAN18,0.097455,0.203343,0.174078,0.059511,0.160625,0.085757,0.245629,0.075171,0.062191,0.103212,...,0.188774,0.133152,0.415823,0.193341,0.380405,0.050863,0.250182,0.159002,1.000000,0.135090
ZYX,0.140388,0.167400,0.223905,0.115838,0.333414,0.154194,0.112346,0.214361,0.067639,0.404464,...,0.392216,0.406016,0.217109,0.164701,0.156548,0.194664,0.083467,0.197240,0.135090,1.000000

In [39]:
print("Min:", np.min(gene_sim.values))
print("Max:", np.max(gene_sim.values))
print("Mean:", np.mean(gene_sim.values))
print("Median:", np.median(gene_sim.values))

Min: 0.0
Max: 1.0
Mean: 0.14949442651149006
Median: 0.12742479880719748

# NSC to SMILES

In [40]:
convert = dict(
    pd.read_csv("../Figs/nsc_cid_smiles_class_name.csv", index_col=0)[
        ["NSC", "SMILES"]
    ].values
)
SMILES = [convert[i] for i in drug_response.index]
SMILES

['CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O',
 'C1=NC2=C(N1)C(=S)N=C(N2)N',
 'C1=NC2=C(N1)C(=S)N=CN2',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC',
 'CN(CCCl)CCCl.Cl',
 'C1=NNC2=C1C(=O)NC=N2',
 'C1(=NC(=NN1)N)N',
 'CC1C(C(=O)NC(C(=O)N2CCCC2C(=O)N(CC(=O)N(C(C(=O)O1)C(C)C)C)C)C(C)C)NC(=O)C3=C4C(=C(C=C3)C)OC5=C(C(=O)C(=C(C5=N4)C(=O)NC6C(OC(=O)C(N(C(=O)CN(C(=O)C7CCCN7C(=O)C(NC6=O)C(C)C)C)C)C(C)C)C)N)C',
 'C1=CC(=CC=C1CCCC(=O)O)N(CCCl)CCCl',
 'C1CN1P(=S)(N2CC2)N3CC3',
 'C1=CC(=CC=C1CC(C(=O)O)N)N(CCCl)CCCl.Cl',
 'C1CN1C2=NC(=NC(=N2)N3CC3)N4CC4',
 'CCC(=O)OC1CCC2C1(CCC3C2CCC4C3(CC(C(=O)C4)C)C)C',
 'CCN(CC)CCCC(C)NC1=C2C=C(C=CC2=NC3=C1C=CC(=C3)Cl)OC.Cl',
 'C1=C(C(=O)NC(=O)N1)F',
 'CC12CCC3C(C1CCC2OC(=O)CCC4=CC=CC=C4)CCC5=CC(=O)CCC35',
 'CC12CCC3C(C1CCC(=O)O2)CCC4=CC(=O)C=CC34C',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)O)OC8CC(C(C(O8)C)O)(C)O)C(=C4C(=C3C)O)O)O)O',
 'C1CN(CCN1C(=O)CCBr)C(=O)CCBr',
 'C1CNP(=O)(OC1)N(CCCl)CCCl',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N4)N',
 'C1C(C(OC1N2C=C(C(=O)NC2=O)F)CO)O',
 'C(=O)(N)NO',
 'COC1=C(C=CC(=C1)C=CC(=O)CC(=O)C=CC2=CC(=C(C=C2)O)OC)O',
 'COC1=CC=C2C(=CC1=O)C(CCC3=CC(=C(C(=C32)OC)OC)OC)NC(=O)C4=CC=CC=C4',
 'C1=C(C(=O)NC(=O)N1)N(CCCl)CCCl',
 'CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C',
 'C[N+]1=C2C(=C3C=CC(=C(C3=C1)OC)OC)C=CC4=CC5=C(C=C42)OCO5.[Cl-]',
 'C1=CC=C(C(=C1)C(C2=CC=C(C=C2)Cl)C(Cl)Cl)Cl',
 'CN(C)N=NC1=C(NC=N1)C(=O)N',
 'CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)O.OS(=O)(=O)O',
 'C1CN2C(=CC=N2)N1',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N4C)N',
 'CC(=O)OC1=CC=C(C=C1)C2(C3=CC=CC=C3NC2=O)C4=CC=C(C=C4)OC(=O)C',
 'C1=CC=C2C(=C1)C(C(=O)N2)(C3=CC=C(C=C3)O)C4=CC=C(C=C4)O',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O.Cl',
 'C1C(OC(C1O)N2C=NC3=C(N=CN=C32)N)CO',
 'CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C=O)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)O.OS(=O)(=O)O',
 'C1C(C(OC1N2C=NC3=C2NC(=NC3=S)N)CO)O',
 'CC1=CC2C(CCC3(C2CCC3(C(=O)C)OC(=O)C)C)C4(C1=CC(=O)CC4)C',
 'CC1=C2C=CN=CC2=C(C3=C1NC4=CC=CC=C43)C',
 'C1C(C(OC1N2C=NC3=C2NC(=NC3=S)N)CO)O',
 'CC1=C(C(=O)NC(=O)N1)N(CCF)CCCl',
 'CC(C)NC(=O)C1=CC=C(C=C1)CNNC.Cl',
 'C1CCC(CC1)NC(=O)N(CCCl)N=O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N)O.Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N)O.Cl',
 'C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3)SCC(C(=O)O)N',
 'CN(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O',
 'CC1CC2=CC(=O)CCC2(C3C1C4CCC(C4(CC3)C)(C)O)C',
 'CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)OC(=O)N(CCCl)CCCl',
 'CCC12CN3CCC4=C(C(CC(C3)C1O2)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)NC1=CC=CC=C41.OS(=O)(=O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C',
 'CC1CCC(CC1)NC(=O)N(CCCl)N=O',
 'C1CC(=O)NC(=O)C1NC(=O)N(CCCl)N=O',
 'C1=CC(=C(N=C1)C=NNC(=S)N)O',
 'CCC(C1=C(C(=O)N2CC3=CC4=CC=CC=C4N=C3C2=C1)CO)(C(=O)O)O.[Na+]',
 'CS(=O)(=O)OCCCNCCCOS(=O)(=O)C.Cl',
 'C1=NC(=NC(=O)N1C2C(C(C(O2)CO)O)O)N',
 'C(C(C(C(C(CBr)O)O)O)O)Br',
 'C1C(C(OC1N2C=NC3=C(N=C(N=C32)Cl)N)CO)O',
 'CCC1C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)O)O',
 'C1=CC(=NC=C1O)C=NNC(=S)N',
 'C1CN(P(=O)(OC1)NCCCl)CCCl',
 'COC(=O)NC1=NC2=CC=CC=C2N1',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)OC)O',
 'CC(=O)OC1=CC=C(C=C1)C2(C3=CC=CC=C3NC2=O)C4=CC=C(C=C4)OC(=O)C',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)O)F)N',
 'C1=NC2=C(C(=O)N1)N=CN2C(C=O)OC(CO)C=O',
 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CC(=O)O)C)C',
 'COC1=CC(=CC(=C1O)OC)C2C3C(COC3=O)C(C4=CC5=C(C=C24)OCO5)OC6C(C(C7C(O6)COC(O7)C8=CC=CS8)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N)O.Cl',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)O)F)N',
 'CC1=C(N=C(N=C1N)C(CC(=O)N)NCC(C(=O)N)N)C(=O)NC(C(C2=CN=CN2)OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(C(O4)CO)O)OC(=O)N)O)C(=O)NC(C)C(C(C)C(=O)NC(C(C)O)C(=O)NCCC5=NC(=CS5)C6=NC(=CS6)C(=O)NCCC[S+](C)C)O.OS(=O)(=O)[O-]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C',
 'C1=CC=C2C(=C1)C(=C(C(=O)C2=O)CC=C(Cl)Cl)O',
 'C1C(C(OC1N2C=NC(=NC2=O)N)CO)O',
 'C1C(O1)C(C(C2CO2)O)O',
 'CC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC(=C(C=C3)Cl)C(=O)NC(CC(=O)O)C(=O)O',
 'C1=CC2=C(C=C1CNC3=CC(=C(C=C3)C(=O)NC(CC(=O)O)C(=O)O)Cl)C(=NC(=N2)N)N',
 'CC1=C(C(=O)C(=C(C1=O)N2CC2)C(COC(=O)N)OC)N3CC3',
 'CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)NCCO)OC)N4)N',
 'C1CC(NCC1Cl)C2C(=O)NC(C(=O)N2)C3CCC(CN3)Cl.Cl',
 'CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O.Cl',
 'CCS(=O)(=O)O.CC1(N=C(N=C(N1C2=CC(=C(C=C2)OCC3=CC(=CC=C3)C(=O)N(C)C)Cl)N)N)C',
 'CC1OCC2C(O1)C(C(C(O2)OC3C4COC(=O)C4C(C5=CC6=C(C=C35)OCO6)C7=CC(=C(C(=C7)OC)O)OC)O)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.Cl',
 'CC(C)(CCCC(CC(=O)OC)(C(=O)OC1C2C3=CC4=C(C=C3CCN5C2(CCC5)C=C1OC)OCO4)O)O',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)OC8CC(C(C(O8)C)O)(C)O)O)C(=C4C(=C3C)O)O)O)O.[Mg+2]',
 'C(C1C(C(C(O1)C2=NNC(=C2O)C(=O)N)O)O)O',
 'C1=CN2C3C(C(C(O3)CO)O)OC2=NC1=N.Cl',
 'C1CC(OC1)N2C=C(C(=O)NC2=O)F',
 'C(C(C(=O)O)N)[N+](=NO)[O-].[Na+]',
 'CC1C2CC(C(C=CC=C(CC3=CC(=C(C(=C3)OC)Cl)N(C(=O)CC(C4(C1O4)C)OC(=O)C(C)N(C)C(=O)C)C)C)OC)(NC(=O)O2)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.CS(=O)(=O)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42.CS(=O)(=O)O',
 'CC1=CCCC2(C(O2)C3C(CC1)C(=C)C(=O)O3)C',
 'C1C(ON=C1Cl)C(C(=O)O)N',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=NNC(=O)C6=CC=CC=C6)C)O)N)O.Cl',
 'CCOC(=O)C(CC(C)C)NC(=O)C(CC1=CC=C(C=C1)N(CCCl)CCCl)NC(=O)C',
 'CC(CN1CC(=O)NC(=O)C1)N2CC(=O)NC(=O)C2',
 'C1CCC2(CC1)C(=O)N(C(=O)N2)CCN(CCCl)CCCl',
 'CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C4=CC=CC=C43)C(=O)NC(CCC(=O)O)C(=O)O',
 'CN(C(=S)C1=CC=CC=C1)NC(=O)CC(=O)NN(C)C(=S)C2=CC=CC=C2',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5OC)N=C4C3=C2)O',
 'C(CCl)N(C(=O)NC(C=O)C(C(C(CO)O)O)O)N=O',
 'CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3.C(C(=O)O)C(CC(=O)O)(C(=O)O)O',
 'CCOC(=O)NC1=C(C(=O)C(=C(C1=O)N2CC2)NC(=O)OCC)N3CC3',
 'CCC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC=C(C=C3)C(=O)NC(CC(=O)O)C(=O)O',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)SC)OC)OC)OC',
 'C1C(C(OC1N2C=NC3=C2NC=NCC3O)CO)O',
 'CC(=O)OC1CC2(C(CCC2=O)C3=C1C4(C(OC(=O)C5=COC(=C54)C3=O)COC)C)C',
 'C(C(C(=O)O)NC(=O)CP(=O)(O)O)C(=O)O.[Na+]',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)O)C)C)O)OC)C)C)C)OC',
 'C1CC(C1)(C(=O)O)C(=O)O.[NH2-].[NH2-].[Pt+2]',
 'CCCCC(=O)OCC(=O)C1(CC(C2=C(C1)C(=C3C(=C2O)C(=O)C4=C(C3=O)C=CC=C4OC)O)OC5CC(C(C(O5)C)O)NC(=O)C(F)(F)F)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)Cl)O',
 'COC1=C(C=CC(=C1)NS(=O)(=O)C)NC2=C3C=CC=CC3=NC4=CC=CC=C42',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)N)C)OC)OC(=O)N)C)C)O)OC',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=CC=CC=C5C4=O)O)(C(=O)C)O)N)O',
 'CC(C)[NH-].CC(C)[NH-].O.O.Cl[Pt+2]Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N)O.Cl',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=C3C=C(C=C4)O)C)C.CC(=O)[O-]',
 'C1N=C(NC(=O)N1C2C(C(C(O2)CO)O)O)N.Cl',
 'C1CCC(C(C1)N)N.C(=O)(C(=O)[O-])[O-].[Pt+4]',
 'CC1CC(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N.Cl',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)C)O)N(CC6=CC=CC=C6)CC7=CC=CC=C7)O.Cl',
 'CC1(CC(C2=C(C3=C(C=C2C1)C(=O)C4=C5C(=CC(=C4C3=O)O)C6(C(C(C(C(O5)O6)O)N(C)C)O)C)O)OC)O',
 'C1CCC(C(C1)[NH-])[NH-].C1=CC(=C(C=C1C(=O)O)C(=O)O)C(=O)O.[Pt+2]',
 'CC1=C(N=C(N=C1N)C(CC(=O)N)NCC(C(=O)N)N)C(=O)NC(C(C2=CN=CN2)OC3C(C(C(C(O3)CO)O)O)OC4C(C(C(C(O4)CO)O)OC(=O)N)O)C(=O)NC(C)C(C(C)C(=O)NC(C(C)O)C(=O)NCCC5=NC(=CS5)C6=NC(=CS6)C(=O)NCCCNC(C)C7=CC=CC=C7)O.OS(=O)(=O)O',
 'C1=CC(=C2C(=C1NCCNCCO)C(=O)C3=C(C=CC(=C3C2=O)O)O)NCCNCCO',
 'CN1C2=NC=NC3=C2C(=CN3C4C(C(C(O4)COP(=O)(O)O)O)O)C(=N1)N',
 'CC1=C(C=CC(=C1)N(CCOS(=O)(=O)C)CCOS(=O)(=O)C)C=O',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O',
 'COC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC(=O)N5CCOCC5)O)C2=NC6=CC=CC=C61',
 'COC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC(=O)OC)O)C2=NC5=CC=CC=C51',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)OC)O',
 'C1C(O1)CN2C(=O)N(C(=O)N(C2=O)CC3CO3)CC4CO4',
 'C1=CC(=C2C(=C1NCCNCCO)C(=O)C3=C(C=CC(=C3C2=O)O)O)NCCNCCO.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)O',
 'CC12CCC(C(C1CCC3C24CCC(C(C3)C4)(COC(=O)CN)O)(C)CO)O.Cl',
 'CN(C)CCN1C(=O)C2=CC=CC3=CC(=CC(=C32)C1=O)N',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)COP(=O)(O)O)O)O)F)N',
 'CN1C2=C(C3=CC(=C(C=C3C1=O)OC)OC)C(=O)C4=CC5=C(C=C42)OCO5',
 'COC1=C(C(=C2C(=C1)CCC(C3=CC(=O)C(=CC=C32)SC)NC(=O)C(F)(F)F)OC)OC',
 'C1C2=C(C=CC(=C2)N)N=C3N1C(=O)C4=CC=CC=C43',
 'CCC(C)C1C(=O)NC2CSSCC(C(=O)NC(C(=O)NC(C(=O)N1)CC(C)C)C(C)C)NC2=O',
 'CCCCS(=N)(=O)CCC(C(=O)O)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C(=CC5=C4)OC)OC)O',
 'C(CCCOS(=O)(=O)N)CCCOS(=O)(=O)N',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=CC(=C2O)C1OC)O)C)C)OC(=O)N)C)C)OC)OC',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)NCC=C)C)OC)OC(=O)N)C)C)O)OC',
 'CC1C=CC2C(O2)(C(CC(OC(=O)C3C(O3)CC4CC1OC(=O)C4)C(C)C(C(=CC=CC(=CC5=COC(=N5)C)C)C)OC)O)C',
 'C1CN=C(N1)NN=CC2=C3C=CC=CC3=C(C4=CC=CC=C42)C=NNC5=NCCN5.Cl',
 'CS(=O)(=O)CS(=O)(=O)OCCCl',
 'CC1=C2C(=CC=C1)C(=C3C=CC=C(C3=N2)C(=O)NC)NC4=C(C=C(C=C4)NS(=O)(=O)C)OC.C(CS(=O)(=O)O)O',
 'C1CN(CCN1CCCCl)CCCl.Cl',
 'C1COS(=O)(=O)CS(=O)(=O)O1',
 'C1=CC(=NCCCN)C2=C(C3=C(C=CC(=O)C3=C4C2=C1N(N4)CCNCCO)O)O.Cl',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=CC=CC=C43)C)C.[I-]',
 'CC1=C(C=CC2=C1C(=NC(=N2)N)N)CNC3=CC(=C(C(=C3)OC)OC)OC.C(=O)C(C(C(C(C(=O)O)O)O)O)O',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=CC=CC=C43)C)C.CS(=O)(=O)[O-]',
 'C1=NC(=C2N1C(=O)N(N=N2)CCCl)C(=O)N',
 'C1=NC(=C2C(=N1)N(C(=N2)Cl)C3C(C(C(O3)CO)O)O)N',
 'CC1CC=CC(=O)C2C(O2)CC(C(C3=C(C(=CC(=C3)OC)O)C(=O)O1)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N6CCOCC6)O.Cl',
 'CC(=O)O.CNCCN=C1C=CC2=C3C1=C(C4=C(C=CC(=O)C4=C3NN2CCNCCO)O)O',
 'CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C(C4=O)C(=CC=C5)OC)O)(C(=O)CO)O)N6CCOCC6C#N)O',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)SC)OC)OC)O',
 'C1CCC(C(C1)[NH-])[NH-].Cl[Pt+2](Cl)(Cl)Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN(CC)CC.Cl',
 'C1=CC(=C(C=C1C=CC2=CC(=CC(=C2)O)O)O)O',
 'CN(C)CCCN1C2=C3C(=C(C=C2)[N+](=O)[O-])NC4=C(C3=N1)C=C(C=C4)OC.CS(=O)(=O)O',
 'CC1=C(C2=C(C=CC(=C2)F)N=C1C3=CC=C(C=C3)C4=CC=CC=C4F)C(=O)O.[Na+]',
 'CC(C)CN1C=NC2=C1C3=CC=CC=C3N=C2N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=CC5=C4)N)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN6CCN(CC6)CCO',
 'CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CC(=O)NC2=CC=C(C=C2)O)C)C',
 'CCC(C)C(C(CC(=O)N1CCCC1C(C(C)C(=O)NC(CC2=CC=CC=C2)C3=NC=CS3)OC)OC)N(C)C(=O)C(C(C)C)NC(=O)C(C(C)C)N(C)C',
 'CC(=O)NC1CCC2=CC(=C(C(=C2C3=C1C=C(C=C3)C(=O)OC)OC)OC)OC',
 'C(CCl)NC(=O)N(CCCl)N=O',
 'CC1C(C(CC(O1)OC2CC(OC(C2O)C)OC3=CC4=CC5=C(C(=O)C(C(C5)C(C(=O)C(C(C)O)O)OC)OC6CC(C(C(O6)C)O)OC7CC(C(C(O7)C)O)OC8CC(C(C(O8)C)O)(C)O)C(=C4C(=C3C)O)O)O)O.[Mg+2]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)OC(=O)CCC(=O)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)OC(=O)CCC(=O)O)C)OC(=O)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5N=C4C3=C2)N)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5[N+](=O)[O-])OC)N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5[N+](=O)[O-])O)N=C4C3=C2)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5NC(=O)C)O)N=C4C3=C2)O',
 'C1CC(OC1CO)N2C=CC(=NC2=O)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C=CC5=C4)C=O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C(C=CC5=C4)CO)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CNCC.Cl',
 'CCCNCC(=O)OC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)CC.Cl',
 'CCCCNCC(=O)OC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)CC.Cl',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)O)C)C)OC(=O)CN(C)C)OC)C)C)C)OC.CS(=O)(=O)O',
 'C1=NC2=C(N=C(N=C2N1C3C(C(C(O3)CO)O)F)Cl)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CNC.Cl',
 'CCC1=CC2CC(C3=C(CN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC.C(C(C(=O)O)O)(C(=O)O)O',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)OC(=O)CCCC(=O)NCCCN(C)C)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C.Cl',
 'CC1CC2CCC3C(=C)CC(O3)CCC45CC6C(O4)C7C(O6)C(O5)C8C(O7)CCC(O8)CC(=O)OC9C(C3C(CC4C(O3)CC3(O4)CC4C(O3)C(CC3(O4)CC(C4C(O3)CC(O4)C(CC(CO)O)O)C)C)OC9CC(C1=C)O2)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5CN(C)C)O)N=C4C3=C2)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CCC(=O)O.[Na+]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C(CCCCN)N.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OP(=O)(O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)C(CCC(=O)O)N.Cl',
 'C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)(F)F.Cl',
 'CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=C1C=C(C=C5)OC(=O)N6CCC(CC6)N7CCCCC7.Cl',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)CNC6=O)NC)OC',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)OC(=O)CN(C)C.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5NC(=O)CN)N=C4C3=C2)O',
 'C1=CC=C(C(=C1)C(=O)NCCCC(C(=O)O)NC(=O)C2=CC=C(C=C2)NCC3=CN=C4C(=N3)C(=NC(=N4)N)N)C(=O)O',
 'CN(C)CCCN1C2=C3C(=C(C=C2)[N+](=O)[O-])NC4=C(C3=N1)C=C(C=C4)OC',
 'CC1=C2C=C[N+](=CC2=C(C3=C1NC4=C3C=C(C=C4)OC)C)C.CC(=O)[O-]',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)OC(C)(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5N=C4C3=C2)N)O',
 'CC=C1C(=O)NC(C(=O)OC2CC(=O)NC(C(=O)NC(CSSCCC=C2)C(=O)N1)C(C)C)C(C)C',
 'CCC(C)(C)C(=O)OC1CC(C=C2C1C(C(C=C2)C)CCC3CC(CC(=O)O3)O)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=C6C(=CC5=C4)OCO6)O',
 'C1=CC=C(C=C1)COC2=NC(=NC3=C2NC=N3)N',
 'CC1=C2CN(C=CC2=C(C3=C1C4=C(N3)C=CC(=C4)OC)C)C',
 'CC1=C2C=C[N+](=CC2=C(C3=C1SC4=CC=CC=C43)C)C.[I-]',
 'C1COCCN1CCC(=O)N2CC(=CC3=CC(=C(C=C3)Cl)Cl)C(=O)C(=CC4=CC(=C(C=C4)Cl)Cl)C2.Cl',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)C(NC6=O)O)NC)OC',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC=C5NC(=O)CN)N=C4C3=C2)O.Cl',
 'CC1=NC2=C(C=C(C=C2)CN(C)C3=CC=C(S3)C(=O)NC(CCC(=O)O)C(=O)O)C(=O)N1',
 'CCCCCCCCCCCCCCCCCCOP(=O)([O-])OC1CC[N+](CC1)(C)C',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2Cl)O',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1O)O)OC(=O)C5=CC=CC=C5)(CO4)OC(=O)C)O)C)O',
 'CC12C(C(CC(O1)N3C4=CC=CC=C4C5=C6C(=C7C8=CC=CC=C8N2C7=C53)CNC6=O)N(C)C(=O)C9=CC=CC=C9)OC',
 'CC(C(=O)O)OC1=CC=C(C=C1)OC2=CN=C3C=CC(=CC3=N2)Cl.[Na+]',
 'CCCCCC(=O)NC(C1=CC=CC=C1)C(C(=O)OC2CC3(C(C4C(C(CC5C4(CO5)OC(=O)C)OC6C(C(C(CO6)O)O)O)(C(=O)C(C(=C2C)C3(C)C)O)C)OC(=O)C7=CC=CC=C7)O)O',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C2(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)C(=C)C)OC(=O)C7=CC(=CC(=C7)F)F)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C(C)(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)CC(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC6=CC=CC=C6C=C5)NC(=O)C7=CC=CC=C7)O)O)OC(=O)C8=CC=CC=C8)(CO4)OC(=O)C)O)C)OC(=O)C',
 'COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=CC=C3)Br)OC.C(CS(=O)(=O)O)O',
 'CS(=O)(=O)O.C1=CC(=CC(=C1)Br)NC2=NC=NC3=CC(=NC=C32)N',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)OC(C)(C)C)O)O)OC(=O)C6CCCCC6)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=CC=CC=C1C(C(C(=O)OC2CC3(C(C4C(C(CC5C4(CO5)OC(=O)C)O)(C(=O)C(C(=C2C)C3(C)C)OC(=O)C)C)OC(=O)C6=CC=CC=C6)O)O)NC(=O)C7=CC=CC=C7',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CO7)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=C(C=C7)F)(CO4)OC(=O)C)O)C)OC(=O)C',
 'CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=C1C=C(C=C5)O',
 'COC1=CC=CC(=C1N)C2=CC(=O)C3=CC=CC=C3O2',
 'B(C(CC(C)C)NC(=O)C(CC1=CC=CC=C1)NC(=O)C2=NC=CN=C2)(O)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CC=C(C=C6)O)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CO)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC(C)C)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CCSC)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(C)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)CN)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C6CCCN6)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CN=CN6)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CC6=CNC7=CC=CC=C76)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C6=CC=C(C=C6)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(CS)N)O.Cl',
 'CCC(C)C(C(=O)NN=CC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=CC=CC=C51)N.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C[N+](C)(C)C)O.[Cl-]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C(=O)N)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NNC(=O)C[N+]6=CC=CC=C6)O.[Cl-]',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3=C2)N',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=C(C=C6)NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=C(C=C6)NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=CC=C6NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)C=NC6=CC=CC=C6NC7C8COC(=O)C8C(C9=CC1=C(C=C79)OCO1)C1=CC(=C(C(=C1)OC)O)OC)O.Cl',
 'CC1=C(C2=C(C3(CC3)C(C(=O)C2=C1)(C)O)C)CO',
 'CC1CCC2CC(C(=CC=CC=CC(CC(C(=O)C(C(C(=CC(C(=O)CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)OC(=O)C(C)(CO)CO)C)C)O)OC)C)C)C)OC',
 'CC1CCCC2(C(O2)CC(OC(=O)CC(C(C(=O)C(C1O)C)(C)C)O)C(=CC3=CSC(=N3)C)C)C',
 'COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=CC=C3)Cl)OC',
 'COC1=C(C=C2C(=C1)C(=O)N3CC(=C)CC3C=N2)OCCCOC4=C(C=C5C(=C4)N=CC6CC(=C)CN6C5=O)OC',
 'C1COCCN1C2=CC(=O)C3=C(O2)C(=CC=C3)C4=CC=CC=C4',
 'CC1=C(C(=O)C(=C(C1=O)N2CC2)CO)N3CC3',
 'CC(C(=O)O)OC1=CC=C(C=C1)OC2=CN=C3C=CC(=CC3=N2)Cl',
 'C1C(C(OC1N2C=C(C(=O)NC2=O)F)COP(=O)(O)OC3CC(OC3COP(=O)(O)OC4CC(OC4COP(=O)(O)OC5CC(OC5COP(=O)(O)OC6CC(OC6COP(=O)(O)OC7CC(OC7COP(=O)(O)OC8CC(OC8COP(=O)(O)OC9CC(OC9COP(=O)(O)OC1CC(OC1COP(=O)(O)OC1CC(OC1CO)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)N1C=C(C(=O)NC1=O)F)O',
 'C1=CC(=CC=C1CCC2=CNC3=C2C(=O)NC(=N3)N)C(=O)NC(CCC(=O)O)C(=O)O',
 'CCC(CO)NC1=NC(=C2C(=N1)N(C=N2)C(C)C)NCC3=CC=CC=C3',
 'C1=CC=C(C=C1)NC(=O)CCCCCCC(=O)NO',
 'CC12CCC3C(C1CCC2OP(=O)(O)O)CCC4=C3C=CC(=C4)OC(=O)N(CCCl)CCCl.[Na+]',
 'COC1=C(C=C2C(=C1)C3=C(C4=CC5=C(C=C4C3=O)OCO5)N(C2=O)CCCNCCO)OC.Cl',
 'C1=CC=C(C(=C1)N)NC(=O)C2=CC=C(C=C2)CNC(=O)OCC3=CN=CC=C3',
 'CC1CC2CCC3C(=C)CC(O3)CCC45CC6C(O4)C7C(O6)C(O5)C8C(O7)CCC(O8)CC(=O)CC9C(CC(C1=C)O2)OC(C9OC)CC(CN)O.CS(=O)(=O)O',
 'CC1CC(C(C(C=C(C(C(C=CC=C(C(=O)NC2=CC(=O)C(=C(C1)C2=O)NCCN(C)C)C)OC)OC(=O)N)C)C)O)OC.Cl',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=C(C=CC(=C5)O)N=C4C3=C2)[Si](C)(C)C(C)(C)C)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=C(C=CC(=C5)O)N=C4C3=C2)CC[Si](C)(C)C)O',
 'CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C5=CC=CC=C5N=C4C3=C2)CC[Si](C)(C)C)O',
 'CCCCCCCCCCCCCCCCCCOCC(COP(=O)(O)OC1C(CC(C(C1O)O)O)O)OC',

In [41]:
def get_morgan_fingerprint(SMILES):
    # Initialize parser parameters
    params = Chem.SmilesParserParams()
    params.useChirality = True  # Preserve stereochemistry information
    params.removeHs = False  # Keep hydrogen atoms
    mfp = []

    for smi in SMILES:
        mol = None
        # Sanitization attempt strategies
        sanitize_attempts = [
            {"sanitize": True},  # First try with standard sanitization
            {
                "sanitize": False,
                "partial_sanitize": True,
            },  # Fallback: partial sanitization
        ]

        for attempt in sanitize_attempts:
            try:
                # Update parameters for this attempt
                current_params = Chem.SmilesParserParams()
                current_params.sanitize = attempt["sanitize"]
                current_params.useChirality = params.useChirality
                current_params.removeHs = params.removeHs

                # Molecule object creation
                mol = Chem.MolFromSmiles(smi, params=current_params)

                if mol and "partial_sanitize" in attempt:
                    # Perform partial sanitization (skip property validation)
                    Chem.SanitizeMol(mol, Chem.SANITIZE_ALL ^ Chem.SANITIZE_PROPERTIES)

                if mol:  # Successfully processed molecule
                    # Generate Morgan fingerprint
                    fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=2048)
                    mfp.append(np.array(fp))
                    break  # Exit attempt loop on success

            except Exception as e:
                if attempt == sanitize_attempts[-1]:  # Final attempt failed
                    print(f"Processing failed: {smi}")
                    print(f"Error details: {str(e)}")
                continue  # Try next attempt

        if not mol:  # All attempts failed
            print(f"Complete processing failure: {smi}")
            mfp.append(np.zeros(2048))  # Insert zero-vector placeholder

    return np.array(mfp)

In [42]:
mfp = get_morgan_fingerprint(SMILES)
mfp = pd.DataFrame(mfp, index=drug_response.index)

In [43]:
drug_sim = normalize_similarity_matrix(mfp)
drug_sim

,740,752,755,757,762,1390,1895,3053,3088,6396,...,808507,808790,808792,809693,810341,810717,811429,812926,812927,813488
740,1.000000,0.685936,0.685936,0.574218,0.699994,0.685936,0.709376,0.445523,0.709376,0.681255,...,0.574218,0.509650,0.564967,0.560345,0.537268,0.537268,0.523449,0.597385,0.551107,0.551107
752,0.685936,1.000000,0.932532,0.685936,0.813195,0.855989,0.870295,0.528053,0.747000,0.832191,...,0.676576,0.602025,0.657884,0.625260,0.639228,0.648551,0.597385,0.653216,0.643888,0.643888
755,0.685936,0.932532,1.000000,0.714071,0.841703,0.884622,0.860755,0.537268,0.775314,0.870295,...,0.685936,0.629913,0.676576,0.634569,0.667226,0.667226,0.625260,0.662554,0.671900,0.662554
757,0.574218,0.685936,0.714071,1.000000,0.728170,0.714071,0.709376,0.472953,0.681255,0.728170,...,0.564967,0.564967,0.611312,0.588111,0.564967,0.620608,0.588111,0.597385,0.588111,0.606667
762,0.699994,0.813195,0.841703,0.728170,1.000000,0.822688,0.865524,0.541879,0.855989,0.884622,...,0.671900,0.625260,0.671900,0.629913,0.653216,0.653216,0.592747,0.648551,0.667226,0.657884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.537268,0.648551,0.667226,0.620608,0.653216,0.676576,0.662554,0.436398,0.615959,0.671900,...,0.518847,0.537268,0.602025,0.505055,0.518847,1.000000,0.523449,0.569591,0.541879,0.514248
811429,0.523449,0.597385,0.625260,0.588111,0.592747,0.625260,0.629913,0.395444,0.574218,0.611312,...,0.486697,0.541879,0.551107,0.472953,0.523449,0.523449,1.000000,0.509650,0.564967,0.500463
812926,0.597385,0.653216,0.662554,0.597385,0.648551,0.653216,0.676576,0.450089,0.620608,0.667226,...,0.643888,0.523449,0.625260,0.546492,0.588111,0.569591,0.509650,1.000000,0.555725,0.667226
812927,0.551107,0.643888,0.671900,0.588111,0.667226,0.690620,0.667226,0.440959,0.611312,0.685936,...,0.541879,0.551107,0.569591,0.509650,0.541879,0.541879,0.564967,0.555725,1.000000,0.574218
813488,0.551107,0.643888,0.662554,0.606667,0.657884,0.662554,0.676576,0.431838,0.620608,0.685936,...,0.597385,0.514248,0.597385,0.555725,0.625260,0.514248,0.500463,0.667226,0.574218,1.000000

In [44]:
os.makedirs("../nci_data/drug_sim", exist_ok=True)
chunks = np.array_split(drug_sim, 25)

for i, chunk in tqdm(enumerate(chunks)):
    chunk.to_parquet(
        f"../nci_data/drug_sim/drug_sim_part_{i}.parquet", compression="gzip"
    )

/Users/inouey2/miniconda3/envs/torch/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
25it [00:02,  9.52it/s]

In [45]:
# # How to read
# def natural_sort_key(s):
#     return [int(c) if c.isdigit() else c for c in re.split(r'(\d+)', s)]

# file_paths = glob.glob("../nci_data/drug_sim/drug_sim_part_*.parquet")
# sorted_file_paths = sorted(file_paths, key=natural_sort_key)

# drug_sim_reconstructed = pd.concat([pd.read_parquet(file) for file in tqdm(sorted_file_paths)])

In [46]:
print("Min:", np.min(drug_sim.values))
print("Max:", np.max(drug_sim.values))
print("Mean:", np.mean(drug_sim.values))
print("Median:", np.median(drug_sim.values))

Min: 0.0
Max: 1.0
Mean: 0.577293123276587
Median: 0.5834776271411233

# Unified Graph

In [47]:
A_dg

,A2M,ABCA3,ABCB1,ABCB5,ABCC1,ABCC3,ABCC5,ABCD1,ABHD17C,ABHD4,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
752,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
755,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
757,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
762,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810717,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
811429,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812926,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
812927,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
813488,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5

In [48]:
indexes = list(A_dc.index) + list(A_cg.index) + list(A_dg.columns)
n_all = len(indexes)
base = pd.DataFrame(np.zeros([n_all, n_all]), index=indexes, columns=indexes)
base

,740,752,755,757,762,1390,1895,3053,3088,6396,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZNRD1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZP3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZSCAN18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZYX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
base.loc[A_cg.index, A_cg.columns] = A_cg
base.loc[A_cg.columns, A_cg.index] = A_cg.T
base.loc[A_dc.index, A_dc.columns] = A_dc
base.loc[A_dc.columns, A_dc.index] = A_dc.T
base.loc[A_dg.index, A_dg.columns] = A_dg
base.loc[A_dg.columns, A_dg.index] = A_dg.T

In [50]:
np.save(
    "../nci_data/idxs.npy",
    pd.DataFrame([list(range(len(base.index))), base.index]).values,
)

In [51]:
edge_index = np.array(base.values.nonzero())
edge_attr = np.array(base.values[base.values.nonzero()])

In [52]:
os.makedirs("../nci_data/edge_idxs", exist_ok=True)
chunk_size = 3000000

num_chunks_index = math.ceil(edge_index.shape[1] / chunk_size)
for i in range(num_chunks_index):
    start = i * chunk_size
    end = min((i + 1) * chunk_size, edge_index.shape[1])
    chunk = edge_index[:, start:end]
    np.save(f"../nci_data/edge_idxs/edge_idxs_chunk_{i}.npy", chunk)

In [53]:
os.makedirs("../nci_data/edge_attrs", exist_ok=True)
chunk_size = 6000000

num_chunks_attr = math.ceil(edge_attr.shape[0] / chunk_size)
for i in range(num_chunks_attr):
    start = i * chunk_size
    end = min((i + 1) * chunk_size, edge_attr.shape[0])
    chunk = edge_attr[start:end]
    np.save(f"../nci_data/edge_attrs/edge_attr_chunk_{i}.npy", chunk)

In [54]:
# # How to read
# def load_and_combine_chunks(pattern, axis=0):
#     chunk_files = sorted(
#         glob.glob(pattern), key=lambda x: int(x.split("_")[-1].split(".")[0])
#     )

#     chunks = [np.load(f) for f in chunk_files]
#     return np.concatenate(chunks, axis=axis)


# edge_index = load_and_combine_chunks("../nci_data/edge_idxs/*.npy", axis=1)
# edge_attr = load_and_combine_chunks("../nci_data/edge_attrs/*.npy", axis=0)