In [1]:
import optuna
import os, sys
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_3051819/2054579058.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_rbf.sqlite3",
    study_name=f"{method}_wo_rbf",
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-07 11:04:31,216] Using an existing study with name 'GATv2_wo_rbf' instead of creating a new one.

(181, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
992,0.6659 (± 0.0048),0.7237 (± 0.0077),0.7298 (± 0.0048),0.6659 (± 0.0048),0.6472 (± 0.0213),0.6157 (± 0.0595),0.6872 (± 0.0253),NaN,gelu,0.25,0.50,500,2,718,69,38,0.005493,AdamW,None,0.000289
712,0.6634 (± 0.0054),0.7233 (± 0.0042),0.729 (± 0.0045),0.6634 (± 0.0054),0.6364 (± 0.0222),0.5912 (± 0.0482),0.6923 (± 0.0159),NaN,gelu,0.25,0.50,500,2,718,96,55,0.005493,AdamW,None,0.000289
1150,0.6652 (± 0.003),0.7224 (± 0.0057),0.7278 (± 0.0053),0.6652 (± 0.003),0.6467 (± 0.0201),0.6151 (± 0.0514),0.6855 (± 0.0206),NaN,relu,0.50,0.15,200,6,1010,89,49,0.001865,Adam,None,0.000017
1187,0.6633 (± 0.009),0.7204 (± 0.0028),0.7278 (± 0.0027),0.6633 (± 0.009),0.6363 (± 0.0325),0.5931 (± 0.0662),0.6917 (± 0.0167),NaN,gelu,0.35,0.50,1100,2,398,219,85,0.000017,Adam,None,0.001300
1106,0.6623 (± 0.004),0.7184 (± 0.0031),0.725 (± 0.0042),0.6623 (± 0.004),0.6307 (± 0.0111),0.5773 (± 0.0219),0.6958 (± 0.0065),NaN,gelu,0.15,0.35,600,2,268,129,79,0.000043,Adam,None,0.000017

In [3]:
study = optuna.create_study(
    storage=f"sqlite:///{method}.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-07 11:04:32,204] Using an existing study with name 'GATv2' instead of creating a new one.

(126, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1013,0.6588 (± 0.0093),0.7261 (± 0.0081),0.7336 (± 0.0086),0.6588 (± 0.0093),0.6064 (± 0.039),0.5307 (± 0.0714),0.7173 (± 0.0282),1882.0,relu,0.30,0.25,5400,2,654,144,34,0.000069,AdamW,Cosine,0.000418
10,0.667 (± 0.0071),0.7254 (± 0.0083),0.7331 (± 0.007),0.667 (± 0.0071),0.6347 (± 0.0187),0.5798 (± 0.0362),0.7028 (± 0.0103),NaN,gelu,0.25,0.35,5400,2,471,132,103,0.000069,Adam,None,0.000935
952,0.6683 (± 0.0048),0.7249 (± 0.0027),0.7325 (± 0.0035),0.6683 (± 0.0048),0.6454 (± 0.0116),0.6043 (± 0.0231),0.6931 (± 0.006),1877.0,gelu,0.20,0.25,5400,3,554,89,33,0.005098,AdamW,Cosine,0.000001
262,0.6594 (± 0.0136),0.7248 (± 0.0037),0.7297 (± 0.0028),0.6594 (± 0.0136),0.6056 (± 0.044),0.5285 (± 0.0741),0.7184 (± 0.0189),NaN,relu,0.10,0.30,3800,2,393,146,32,0.000343,AdamW,None,0.000005
921,0.659 (± 0.0094),0.7242 (± 0.0063),0.7307 (± 0.0057),0.659 (± 0.0094),0.6084 (± 0.0291),0.5321 (± 0.0503),0.7144 (± 0.0162),NaN,gelu,0.50,0.30,4200,4,743,122,38,0.000015,AdamW,None,0.002128

In [4]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-07 11:04:33,026] Using an existing study with name 'Transformer' instead of creating a new one.

(208, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1078,0.6649 (± 0.0101),0.7262 (± 0.0074),0.7324 (± 0.0067),0.6649 (± 0.0101),0.6356 (± 0.0389),0.5901 (± 0.0773),0.6969 (± 0.0236),NaN,gelu,0.35,0.10,7900,2,804,165,34,0.000621,Adam,None,0.000743
998,0.6685 (± 0.0066),0.7261 (± 0.0071),0.7331 (± 0.0072),0.6685 (± 0.0066),0.6387 (± 0.0126),0.5864 (± 0.0237),0.7019 (± 0.01),NaN,relu,0.35,0.25,5900,3,935,146,134,0.000448,AdamW,None,0.000022
1015,0.6678 (± 0.0047),0.7259 (± 0.0027),0.7312 (± 0.0042),0.6678 (± 0.0047),0.6459 (± 0.0097),0.6061 (± 0.0192),0.6916 (± 0.0064),NaN,gelu,0.10,0.35,1900,2,563,128,76,0.000014,AdamW,None,0.000097
1318,0.6695 (± 0.003),0.7258 (± 0.0082),0.7314 (± 0.0048),0.6695 (± 0.003),0.6532 (± 0.0081),0.6228 (± 0.0189),0.6871 (± 0.0067),1170.0,relu,0.35,0.20,2600,4,744,73,67,0.000011,Adam,Cosine,0.000405
985,0.6667 (± 0.0063),0.7256 (± 0.0076),0.73 (± 0.0062),0.6667 (± 0.0063),0.6424 (± 0.0124),0.599 (± 0.0226),0.6929 (± 0.0058),NaN,relu,0.15,0.10,1400,2,413,160,104,0.000014,AdamW,None,0.000003

In [5]:
study = optuna.create_study(
    storage=f"sqlite:///{method}_rbf.sqlite3",
    study_name=f"{method}_wo_rbf",
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-07 11:04:34,235] Using an existing study with name 'Transformer_wo_rbf' instead of creating a new one.

(140, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
223,0.659 (± 0.0061),0.7111 (± 0.0123),0.7194 (± 0.0104),0.659 (± 0.0061),0.6503 (± 0.0076),0.6347 (± 0.0282),0.668 (± 0.0171),1204.0,relu,0.50,0.15,3300,2,784,66,57,0.001846,Adam,Cosine,0.000128
753,0.6563 (± 0.0088),0.7107 (± 0.0092),0.7187 (± 0.0101),0.6563 (± 0.0088),0.6244 (± 0.0206),0.5728 (± 0.0405),0.6886 (± 0.0164),165.0,relu,0.10,0.40,400,3,769,118,68,0.001874,AdamW,Cosine,0.001168
1000,0.6541 (± 0.0064),0.7057 (± 0.0031),0.714 (± 0.0046),0.6541 (± 0.0064),0.63 (± 0.0096),0.589 (± 0.015),0.6772 (± 0.0068),1361.0,gelu,0.10,0.25,3200,3,282,140,83,0.000023,AdamW,Cosine,0.000083
908,0.6551 (± 0.0027),0.7056 (± 0.0035),0.7135 (± 0.0032),0.6551 (± 0.0027),0.6356 (± 0.0044),0.6015 (± 0.0104),0.6738 (± 0.0058),NaN,relu,0.45,0.50,1700,4,279,135,33,0.002644,Adam,None,0.000001
893,0.6547 (± 0.0067),0.7045 (± 0.0051),0.7113 (± 0.0054),0.6547 (± 0.0067),0.6323 (± 0.0157),0.5946 (± 0.0302),0.676 (± 0.0077),NaN,relu,0.40,0.35,300,2,585,179,127,0.000021,AdamW,None,0.000936