In [1]:
import optuna
import os, sys
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

/data/inouey2/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_3095823/2054579058.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [8]:
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 20:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-08 14:23:24,188] Using an existing study with name 'GATv2' instead of creating a new one.

(182, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
74,0.6086 (± 0.0322),0.7183 (± 0.0027),0.7183 (± 0.0053),0.6086 (± 0.0322),0.4392 (± 0.1182),0.3219 (± 0.1238),0.7687 (± 0.0416),NaN,gelu,0.40,0.5,5,992,82,48,0.000319,AdamW,None,0.000167
809,0.6113 (± 0.0335),0.7155 (± 0.0065),0.719 (± 0.0055),0.6113 (± 0.0335),0.4531 (± 0.1252),0.3435 (± 0.1525),0.7591 (± 0.0484),NaN,relu,0.45,0.1,2,609,183,123,0.000655,AdamW,None,0.000017
726,0.5564 (± 0.0468),0.7095 (± 0.0099),0.7168 (± 0.0038),0.5564 (± 0.0468),0.2357 (± 0.1961),0.1593 (± 0.1578),0.8511 (± 0.0917),NaN,gelu,0.45,0.5,3,930,67,52,0.000319,Adam,None,0.000890
421,0.5814 (± 0.0385),0.7078 (± 0.0067),0.7111 (± 0.0047),0.5814 (± 0.0385),0.3409 (± 0.1591),0.2339 (± 0.1288),0.7977 (± 0.0671),NaN,relu,0.45,0.4,2,273,116,38,0.001033,AdamW,None,0.000017
792,0.6325 (± 0.0239),0.7052 (± 0.0115),0.7122 (± 0.0117),0.6325 (± 0.0239),0.5606 (± 0.1107),0.5005 (± 0.1859),0.7007 (± 0.0615),NaN,relu,0.20,0.1,3,609,70,61,0.000392,Adam,None,0.000003

In [9]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 20:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-08 14:23:33,258] Using an existing study with name 'Transformer' instead of creating a new one.

(180, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
843,0.6685 (± 0.0064),0.7234 (± 0.0083),0.7298 (± 0.0069),0.6685 (± 0.0064),0.652 (± 0.0093),0.6214 (± 0.0221),0.6865 (± 0.0126),NaN,gelu,0.15,0.15,2,320,182,57,0.000237,AdamW,None,0.000175
644,0.6688 (± 0.0015),0.7231 (± 0.0043),0.7306 (± 0.0028),0.6688 (± 0.0015),0.6529 (± 0.0096),0.6237 (± 0.0249),0.6858 (± 0.0083),NaN,gelu,0.10,0.20,4,689,95,68,0.000091,Adam,None,0.000117
463,0.6696 (± 0.0025),0.7223 (± 0.0018),0.7301 (± 0.003),0.6696 (± 0.0025),0.6557 (± 0.0112),0.6301 (± 0.0295),0.6847 (± 0.0111),NaN,gelu,0.15,0.20,3,640,160,124,0.000393,Adam,None,0.000029
829,0.6684 (± 0.0043),0.7214 (± 0.0052),0.7294 (± 0.0036),0.6684 (± 0.0043),0.6519 (± 0.0151),0.6222 (± 0.0367),0.6864 (± 0.013),NaN,relu,0.20,0.25,2,470,298,100,0.000237,Adam,None,0.000283
844,0.6609 (± 0.0113),0.7212 (± 0.0051),0.7282 (± 0.0063),0.6609 (± 0.0113),0.6323 (± 0.043),0.5909 (± 0.0924),0.6915 (± 0.0289),NaN,gelu,0.15,0.15,2,320,188,180,0.000237,Adam,None,0.000175