In [1]:
import optuna

In [2]:
name = "NCI_GAT_New"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe()
df = df.dropna(subset=[i for i in df.columns if "values" in i])
df

[I 2025-04-02 09:44:06,879] Using an existing study with name 'NCI_GAT_New' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
4,4,0.497145,0.516736,0.518957,0.183523,2025-03-31 13:20:57.919567,2025-03-31 13:44:49.682984,0 days 00:23:51.763417,NaN,relu,...,0.000064,NaN,NaN,AdamW,5.0,Plateau,NaN,0.000202,0.000112,COMPLETE
7,7,0.584883,0.613506,0.632382,0.605613,2025-03-31 13:22:48.767231,2025-03-31 14:02:44.627027,0 days 00:39:55.859796,NaN,gelu,...,0.004693,NaN,NaN,AdamW,NaN,Step,29.0,NaN,0.000047,COMPLETE
25,25,0.525710,0.603028,0.627153,0.179323,2025-03-31 14:02:44.668392,2025-03-31 14:22:25.034267,0 days 00:19:40.365875,NaN,gelu,...,0.001500,NaN,NaN,AdamW,NaN,Step,30.0,NaN,0.004611,COMPLETE
27,27,0.564131,0.618395,0.640694,0.388247,2025-03-31 14:51:10.721083,2025-03-31 15:38:59.104437,0 days 00:47:48.383354,NaN,gelu,...,0.001284,NaN,NaN,AdamW,NaN,Step,10.0,NaN,0.002739,COMPLETE
28,28,0.651947,0.705376,0.715863,0.617357,2025-03-31 15:38:59.153238,2025-03-31 16:22:48.080712,0 days 00:43:48.927474,NaN,gelu,...,0.002769,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000009,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,632,0.639622,0.681404,0.690107,0.629321,2025-04-02 08:28:56.377990,2025-04-02 09:26:09.470070,0 days 00:57:13.092080,46.0,gelu,...,0.005955,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000005,COMPLETE
635,635,0.539502,0.595021,0.610249,0.377558,2025-04-02 08:30:02.093272,2025-04-02 09:26:41.132741,0 days 00:56:39.039469,NaN,gelu,...,0.006608,NaN,NaN,AdamW,5.0,Plateau,NaN,0.003014,0.000005,COMPLETE
636,636,0.519769,0.554681,0.559845,0.425505,2025-04-02 08:35:03.822791,2025-04-02 09:30:28.099870,0 days 00:55:24.277079,NaN,gelu,...,0.006358,NaN,NaN,AdamW,5.0,Plateau,NaN,0.003124,0.000005,COMPLETE
640,640,0.621546,0.654256,0.669144,0.610051,2025-04-02 08:37:12.213546,2025-04-02 09:33:39.250748,0 days 00:56:27.037202,41.0,gelu,...,0.005423,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000005,COMPLETE
641,641,0.599955,0.664892,0.681203,0.469902,2025-04-02 08:41:04.343997,2025-04-02 09:37:13.613898,0 days 00:56:09.269901,45.0,gelu,...,0.002421,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000004,COMPLETE

In [7]:
df.params_gnn_layer.value_counts()

params_gnn_layer
GATv2          162
GAT            115
Transformer     36
Name: count, dtype: int64

In [8]:
tmp = df.loc[df[["values_0", "values_1", "values_2", "values_3"]].max(axis=1).sort_values(ascending=False).index]
tmp[tmp['params_gnn_layer'] == 'GAT'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
137,137,0.658982,0.727157,0.730925,0.609317,2025-04-01 12:35:37.260208,2025-04-01 13:33:22.498690,0 days 00:57:45.238482,NaN,gelu,...,0.000424,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000004,COMPLETE
110,110,0.669377,0.726080,0.730606,0.658676,2025-04-01 07:32:04.028621,2025-04-01 08:17:53.230158,0 days 00:45:49.201537,NaN,gelu,...,0.000642,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000005,COMPLETE
138,138,0.667335,0.725615,0.730318,0.656339,2025-04-01 12:39:43.610710,2025-04-01 13:32:22.412917,0 days 00:52:38.802207,NaN,gelu,...,0.000457,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000004,COMPLETE
202,202,0.663270,0.725286,0.729510,0.631938,2025-04-01 14:55:52.832534,2025-04-01 16:17:58.393935,0 days 01:22:05.561401,NaN,gelu,...,0.000498,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000701,COMPLETE
238,238,0.648253,0.724047,0.729089,0.562393,2025-04-01 16:35:29.695510,2025-04-01 18:24:31.382038,0 days 01:49:01.686528,49.0,gelu,...,0.000123,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000143,COMPLETE

In [9]:
tmp[tmp['params_gnn_layer'] == 'GATv2'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
41,41,0.668189,0.726975,0.735155,0.631522,2025-03-31 18:21:31.357879,2025-03-31 19:27:02.660820,0 days 01:05:31.302941,49.0,swish,...,0.000134,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
542,542,0.666370,0.722787,0.733260,0.634348,2025-04-02 02:00:52.746260,2025-04-02 03:57:06.131959,0 days 01:56:13.385699,NaN,swish,...,0.000164,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000135,COMPLETE
586,586,0.666704,0.724445,0.732611,0.633240,2025-04-02 04:52:14.327336,2025-04-02 05:49:00.496059,0 days 00:56:46.168723,NaN,gelu,...,0.000293,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000005,COMPLETE
584,584,0.665627,0.724168,0.732580,0.629836,2025-04-02 04:44:05.313694,2025-04-02 05:39:51.644280,0 days 00:55:46.330586,NaN,gelu,...,0.000293,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000005,COMPLETE
265,265,0.668003,0.721713,0.732098,0.638492,2025-04-01 17:13:29.049096,2025-04-01 18:17:57.826137,0 days 01:04:28.777041,40.0,gelu,...,0.000059,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000005,COMPLETE

In [10]:
tmp[tmp['params_gnn_layer'] == 'Transformer'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
301,301,0.667966,0.722647,0.731535,0.644109,2025-04-01 19:01:32.522359,2025-04-01 19:35:52.097021,0 days 00:34:19.574662,NaN,gelu,...,0.000023,NaN,NaN,AdamW,NaN,None,NaN,NaN,0.000007,COMPLETE
332,332,0.666203,0.723327,0.731430,0.639014,2025-04-01 19:35:52.168620,2025-04-01 20:39:17.554569,0 days 01:03:25.385949,24.0,swish,...,0.000245,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
416,416,0.665720,0.723275,0.730733,0.637341,2025-04-01 21:59:22.851305,2025-04-01 23:04:30.378615,0 days 01:05:07.527310,50.0,swish,...,0.000396,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002987,COMPLETE
333,333,0.668393,0.723474,0.730569,0.655292,2025-04-01 19:35:55.510220,2025-04-01 20:39:20.430508,0 days 01:03:24.920288,49.0,swish,...,0.000251,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
293,293,0.663808,0.721290,0.730305,0.634862,2025-04-01 18:51:07.260877,2025-04-01 19:32:21.270916,0 days 00:41:14.010039,33.0,relu,...,0.000546,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000003,COMPLETE

In [13]:
name = "NCI_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe()
df = df.dropna(subset=[i for i in df.columns if "values" in i])
df

[I 2025-04-01 22:05:57,815] Using an existing study with name 'NCI_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
4,4,0.501336,0.588053,0.619029,0.133738,2025-03-27 18:52:25.978912,2025-03-27 18:53:00.823902,0 days 00:00:34.844990,49.0,gelu,...,0.000322,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000384,COMPLETE
9,9,0.578926,0.607132,0.630760,0.492099,2025-03-27 18:56:53.760916,2025-03-27 19:05:09.782713,0 days 00:08:16.021797,NaN,swish,...,0.000038,0.885878,True,SGD,10.0,Plateau,NaN,0.002235,0.000003,COMPLETE
19,19,0.540466,0.573717,0.583789,0.424409,2025-03-27 19:05:09.820280,2025-03-27 19:13:22.232750,0 days 00:08:12.412470,NaN,swish,...,0.000012,0.900961,True,SGD,10.0,Plateau,NaN,0.009414,0.001454,COMPLETE
20,20,0.544716,0.563176,0.583635,0.301777,2025-03-27 19:13:22.270217,2025-03-27 19:21:34.679790,0 days 00:08:12.409573,NaN,swish,...,0.000014,0.899814,True,SGD,10.0,Plateau,NaN,0.007552,0.000001,COMPLETE
21,21,0.543566,0.578581,0.596934,0.367810,2025-03-27 19:14:58.049922,2025-03-27 19:23:15.875121,0 days 00:08:17.825199,NaN,swish,...,0.000011,0.903169,True,SGD,10.0,Plateau,NaN,0.004694,0.000001,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1746,1746,0.629599,0.663559,0.682700,0.621197,2025-03-29 06:55:40.649190,2025-03-29 06:59:16.403606,0 days 00:03:35.754416,NaN,relu,...,0.001109,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000303,COMPLETE
1747,1747,0.540485,0.578166,0.586291,0.288875,2025-03-29 06:59:16.439311,2025-03-29 07:06:16.517454,0 days 00:07:00.078143,NaN,relu,...,0.003016,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000648,COMPLETE
1748,1748,0.628170,0.672267,0.676860,0.604883,2025-03-29 07:06:16.551606,2025-03-29 07:20:01.137222,0 days 00:13:44.585616,NaN,relu,...,0.002357,0.884724,True,SGD,NaN,None,NaN,NaN,0.000142,COMPLETE
1749,1749,0.591063,0.624801,0.649375,0.518090,2025-03-29 07:20:01.172847,2025-03-29 07:20:54.278752,0 days 00:00:53.105905,NaN,relu,...,0.000150,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000001,COMPLETE
1750,1750,0.609850,0.629855,0.653590,0.601221,2025-03-29 07:20:54.316331,2025-03-29 07:56:58.520944,0 days 00:36:04.204613,NaN,relu,...,0.001676,NaN,NaN,Adam,NaN,None,NaN,NaN,0.000922,COMPLETE

In [14]:
tmp = df.loc[df[["values_0", "values_1", "values_2", "values_3"]].max(axis=1).sort_values(ascending=False).index]
tmp[tmp['params_gnn_layer'] == 'GAT'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
160,160,0.624735,0.719452,0.722817,0.496675,2025-03-27 20:53:16.307973,2025-03-27 21:20:07.227282,0 days 00:26:50.919309,NaN,gelu,...,0.000517,NaN,NaN,AdamW,NaN,Step,14.0,NaN,0.000008,COMPLETE
166,166,0.615826,0.719626,0.722793,0.466746,2025-03-27 20:56:38.012351,2025-03-27 21:39:25.630032,0 days 00:42:47.617681,NaN,gelu,...,0.000483,NaN,NaN,AdamW,NaN,Step,14.0,NaN,0.000020,COMPLETE
161,161,0.613134,0.718582,0.721524,0.457692,2025-03-27 20:53:20.548401,2025-03-27 21:20:19.770297,0 days 00:26:59.221896,NaN,gelu,...,0.000491,NaN,NaN,AdamW,NaN,Step,14.0,NaN,0.000009,COMPLETE
172,172,0.637340,0.715814,0.720569,0.552936,2025-03-27 20:57:44.304099,2025-03-27 21:25:49.143047,0 days 00:28:04.838948,NaN,gelu,...,0.000459,NaN,NaN,AdamW,NaN,Step,14.0,NaN,0.000009,COMPLETE
1072,1072,0.637264,0.716112,0.719541,0.549971,2025-03-28 10:41:34.170841,2025-03-28 11:11:55.641865,0 days 00:30:21.471024,31.0,gelu,...,0.000386,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.005713,COMPLETE

In [15]:
tmp[tmp['params_gnn_layer'] == 'GATv2'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
625,625,0.661322,0.721197,0.731638,0.621818,2025-03-28 03:54:35.312570,2025-03-28 04:57:16.695830,0 days 01:02:41.383260,50.0,relu,...,0.000261,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002416,COMPLETE
1012,1012,0.660337,0.718751,0.724071,0.638834,2025-03-28 09:53:29.215260,2025-03-28 11:01:35.271705,0 days 01:08:06.056445,46.0,gelu,...,0.000976,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.001482,COMPLETE
645,645,0.656105,0.714253,0.723488,0.619781,2025-03-28 04:10:58.732735,2025-03-28 04:49:28.863816,0 days 00:38:30.131081,33.0,relu,...,0.000222,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002579,COMPLETE
879,879,0.634332,0.709931,0.717773,0.541402,2025-03-28 08:13:36.294432,2025-03-28 08:53:23.502206,0 days 00:39:47.207774,21.0,gelu,...,0.000069,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000003,COMPLETE
674,674,0.652392,0.709576,0.717485,0.606384,2025-03-28 04:23:59.419981,2025-03-28 04:45:55.591218,0 days 00:21:56.171237,47.0,relu,...,0.000261,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.003851,COMPLETE

In [16]:
tmp[tmp['params_gnn_layer'] == 'Transformer'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
1646,1646,0.670175,0.727932,0.734073,0.650164,2025-03-29 02:45:20.989755,2025-03-29 03:18:22.860243,0 days 00:33:01.870488,NaN,relu,...,0.000108,NaN,NaN,Adam,NaN,None,NaN,NaN,0.001208,COMPLETE
308,308,0.671641,0.725700,0.733264,0.657096,2025-03-27 23:03:14.061755,2025-03-27 23:40:32.266604,0 days 00:37:18.204849,46.0,gelu,...,0.000082,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.007806,COMPLETE
776,776,0.671363,0.726728,0.732812,0.657413,2025-03-28 06:34:41.382684,2025-03-28 07:13:04.803949,0 days 00:38:23.421265,29.0,gelu,...,0.000060,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.007478,COMPLETE
802,802,0.670602,0.726419,0.732666,0.660993,2025-03-28 06:58:41.725706,2025-03-28 07:36:01.686054,0 days 00:37:19.960348,NaN,swish,...,0.000078,NaN,NaN,Adam,NaN,None,NaN,NaN,0.005358,COMPLETE
699,699,0.670249,0.725987,0.732572,0.650872,2025-03-28 04:40:32.573452,2025-03-28 05:20:02.185916,0 days 00:39:29.612464,32.0,gelu,...,0.000062,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.001571,COMPLETE

In [3]:
df.params_gnn_layer.value_counts()

params_gnn_layer
Transformer    667
GAT            112
GATv2           92
Name: count, dtype: int64

In [7]:
name = "NCI"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe()
df = df.dropna(subset=[i for i in df.columns if "values" in i])
df

[I 2025-03-31 13:03:11,723] Using an existing study with name 'NCI' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
0,0,0.551047,0.582520,0.590306,0.451088,2025-03-27 21:16:45.151125,2025-03-27 21:16:56.858329,0 days 00:00:11.707204,39.0,swish,...,0.000017,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.003676,COMPLETE
2,2,0.486356,0.478938,0.451412,0.368080,2025-03-27 21:16:57.319319,2025-03-27 21:17:12.063325,0 days 00:00:14.744006,30.0,swish,...,0.000027,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.009806,COMPLETE
3,3,0.523165,0.513990,0.514583,0.430057,2025-03-27 21:17:12.097647,2025-03-27 21:17:21.685686,0 days 00:00:09.588039,NaN,relu,...,0.003580,0.939732,False,SGD,NaN,Step,24.0,NaN,0.000003,COMPLETE
5,5,0.492927,0.567854,0.571228,0.382407,2025-03-27 21:17:22.175385,2025-03-27 21:17:33.615280,0 days 00:00:11.439895,24.0,gelu,...,0.003247,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.000155,COMPLETE
7,7,0.489978,0.519969,0.506463,0.391485,2025-03-27 21:17:34.053370,2025-03-27 21:17:42.828438,0 days 00:00:08.775068,NaN,swish,...,0.000746,0.879989,True,SGD,NaN,Step,24.0,NaN,0.000533,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,649,0.499963,0.499319,0.486332,0.291888,2025-03-28 09:11:08.203565,2025-03-28 09:11:28.555869,0 days 00:00:20.352304,NaN,relu,...,0.009955,NaN,NaN,Adam,9.0,Plateau,NaN,0.000159,0.000019,COMPLETE
653,653,0.514369,0.545103,0.566819,0.350853,2025-03-28 09:11:27.408904,2025-03-28 09:11:42.907566,0 days 00:00:15.498662,NaN,relu,...,0.008343,NaN,NaN,Adam,8.0,Plateau,NaN,0.000125,0.000011,COMPLETE
657,657,0.497108,0.525200,0.515841,0.282509,2025-03-28 09:11:28.597679,2025-03-28 09:11:46.617164,0 days 00:00:18.019485,NaN,relu,...,0.008495,NaN,NaN,Adam,8.0,Plateau,NaN,0.000115,0.000012,COMPLETE
658,658,0.493150,0.474617,0.449805,0.523621,2025-03-28 09:11:42.957392,2025-03-28 09:11:58.298790,0 days 00:00:15.341398,NaN,relu,...,0.008502,NaN,NaN,Adam,8.0,Plateau,NaN,0.000307,0.000016,COMPLETE
659,659,0.428498,0.424866,0.393182,0.384914,2025-03-28 09:11:46.650977,2025-03-28 09:12:04.609994,0 days 00:00:17.959017,NaN,relu,...,0.009842,NaN,NaN,Adam,8.0,Plateau,NaN,0.000234,0.000014,COMPLETE

In [8]:
df.params_gnn_layer.value_counts()

params_gnn_layer
MPNN    370
GCN     188
Name: count, dtype: int64

In [9]:
tmp = df.loc[df[["values_0", "values_1", "values_2", "values_3"]].max(axis=1).sort_values(ascending=False).index]
tmp[tmp['params_gnn_layer'] == 'MPNN'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
644,644,0.506682,0.514177,0.499915,0.668069,2025-03-28 09:11:08.123751,2025-03-28 09:11:27.371461,0 days 00:00:19.247710,NaN,relu,...,0.008778,NaN,NaN,Adam,9.0,Plateau,NaN,0.000137,0.000013,COMPLETE
222,222,0.547744,0.559552,0.570804,0.650167,2025-03-27 21:28:55.346099,2025-03-27 21:29:08.545951,0 days 00:00:13.199852,NaN,relu,...,0.000015,NaN,NaN,Adam,NaN,Step,21.0,NaN,0.001603,COMPLETE
296,296,0.487584,0.428419,0.386390,0.645187,2025-03-27 21:33:57.095598,2025-03-27 21:34:11.529669,0 days 00:00:14.434071,NaN,gelu,...,0.005122,NaN,NaN,Adam,NaN,Step,18.0,NaN,0.001030,COMPLETE
440,440,0.555040,0.581519,0.587394,0.644860,2025-03-27 21:53:04.808359,2025-03-27 21:53:22.941097,0 days 00:00:18.132738,NaN,swish,...,0.003638,NaN,NaN,Adam,6.0,Plateau,NaN,0.000908,0.000011,COMPLETE
180,180,0.549001,0.614498,0.644547,0.446000,2025-03-27 21:27:04.122457,2025-03-27 21:27:18.704052,0 days 00:00:14.581595,NaN,swish,...,0.005555,NaN,NaN,Adam,NaN,Step,16.0,NaN,0.001355,COMPLETE

In [10]:
tmp[tmp['params_gnn_layer'] == 'GCN'].head()

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_lr,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,state
143,143,0.497420,0.469276,0.446590,0.662940,2025-03-27 21:25:49.482585,2025-03-27 21:25:59.510917,0 days 00:00:10.028332,NaN,swish,...,0.000025,NaN,NaN,Adam,NaN,Step,14.0,NaN,0.000004,COMPLETE
124,124,0.496139,0.469940,0.444852,0.661376,2025-03-27 21:25:06.473990,2025-03-27 21:25:14.749131,0 days 00:00:08.275141,NaN,relu,...,0.002991,0.882446,True,SGD,8.0,Plateau,NaN,0.000273,0.001837,COMPLETE
117,117,0.524814,0.517510,0.508565,0.660376,2025-03-27 21:24:55.724311,2025-03-27 21:25:04.093275,0 days 00:00:08.368964,33.0,relu,...,0.000019,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.001828,COMPLETE
427,427,0.529549,0.625946,0.653591,0.290059,2025-03-27 21:51:38.040761,2025-03-27 21:51:52.322749,0 days 00:00:14.281988,NaN,swish,...,0.005850,NaN,NaN,Adam,7.0,Plateau,NaN,0.000203,0.000002,COMPLETE
433,433,0.527565,0.624855,0.651845,0.255167,2025-03-27 21:52:26.303314,2025-03-27 21:52:41.619922,0 days 00:00:15.316608,NaN,swish,...,0.004595,NaN,NaN,Adam,6.0,Plateau,NaN,0.000127,0.000002,COMPLETE