In [1]:
import optuna

In [2]:
name = "NCI_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe()
df = df.dropna(subset=[i for i in df.columns if "values" in i])
df

[I 2025-03-22 17:15:55,110] Using an existing study with name 'NCI_GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,state
3,3,0.495343,0.508992,0.506209,0.595880,2025-03-22 16:54:53.572324,2025-03-22 16:55:01.966375,0 days 00:00:08.394051,NaN,gelu,...,NaN,NaN,AdamW,6.0,Plateau,NaN,0.005973,0.000330,NaN,COMPLETE
4,4,0.497555,0.508218,0.503569,0.608704,2025-03-22 16:55:01.992561,2025-03-22 16:55:26.042149,0 days 00:00:24.049588,NaN,gelu,...,NaN,NaN,Adam,5.0,Plateau,NaN,0.001601,0.000016,NaN,COMPLETE
9,9,0.525146,0.524217,0.536337,0.516534,2025-03-22 16:55:28.793781,2025-03-22 16:55:35.470989,0 days 00:00:06.677208,21.0,swish,...,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000001,NaN,COMPLETE
10,10,0.492899,0.494344,0.493391,0.192735,2025-03-22 16:55:35.497194,2025-03-22 16:55:42.251278,0 days 00:00:06.754084,22.0,swish,...,0.806697,False,SGD,NaN,Cosine,NaN,NaN,0.000002,NaN,COMPLETE
11,11,0.502445,0.505722,0.496750,0.305041,2025-03-22 16:55:42.276864,2025-03-22 16:55:46.649786,0 days 00:00:04.372922,NaN,swish,...,NaN,NaN,Adam,3.0,Plateau,NaN,0.000178,0.000012,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,197,0.587658,0.628981,0.639333,0.529223,2025-03-22 17:12:53.591903,2025-03-22 17:14:53.764161,0 days 00:02:00.172258,29.0,swish,...,0.900578,True,SGD,NaN,Cosine,NaN,NaN,0.003978,NaN,COMPLETE
198,198,0.577489,0.626915,0.635027,0.427553,2025-03-22 17:12:54.748389,2025-03-22 17:14:54.724162,0 days 00:01:59.975773,30.0,swish,...,0.905764,True,SGD,NaN,Cosine,NaN,NaN,0.003877,NaN,COMPLETE
200,200,0.567672,0.607644,0.641236,0.395884,2025-03-22 17:13:40.014142,2025-03-22 17:15:39.152275,0 days 00:01:59.138133,31.0,swish,...,0.905328,True,SGD,NaN,Cosine,NaN,NaN,0.005897,NaN,COMPLETE
201,201,0.525245,0.609275,0.621565,0.170343,2025-03-22 17:13:42.274367,2025-03-22 17:15:41.918297,0 days 00:01:59.643930,29.0,swish,...,0.900840,True,SGD,NaN,Cosine,NaN,NaN,0.000741,NaN,COMPLETE
204,204,0.583450,0.614289,0.640283,0.509901,2025-03-22 17:13:54.072210,2025-03-22 17:15:57.486231,0 days 00:02:03.414021,30.0,swish,...,0.848714,True,SGD,NaN,Cosine,NaN,NaN,0.000851,NaN,COMPLETE

In [3]:
df.params_gnn_layer.value_counts()

params_gnn_layer
Transformer    54
GAT            24
GATv2          23
Name: count, dtype: int64

In [4]:
name = "NCI"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
df = study.trials_dataframe()
df = df.dropna(subset=[i for i in df.columns if "values" in i])
df

[I 2025-03-22 17:15:58,149] Using an existing study with name 'NCI' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_momentum,params_nesterov,params_optimizer,params_patience_plateau,params_scheduler,params_step_size,params_thresh_plateau,params_weight_decay,user_attrs_early_stopping_epoch,state
1,1,0.591164,0.666411,0.680842,0.432879,2025-03-22 16:31:37.341043,2025-03-22 16:31:49.325960,0 days 00:00:11.984917,NaN,gelu,...,0.810822,False,SGD,NaN,Step,22.0,NaN,0.005654,NaN,COMPLETE
4,4,0.591164,0.664047,0.679818,0.432879,2025-03-22 16:31:50.046443,2025-03-22 16:32:07.548441,0 days 00:00:17.501998,NaN,gelu,...,NaN,NaN,AdamW,NaN,Step,19.0,NaN,0.000506,NaN,COMPLETE
5,5,0.500000,0.426968,0.364241,0.000000,2025-03-22 16:32:07.577750,2025-03-22 16:32:09.940283,0 days 00:00:02.362533,NaN,gelu,...,0.906423,True,SGD,NaN,None,NaN,NaN,0.008374,NaN,COMPLETE
9,9,0.500000,0.666461,0.683160,0.000000,2025-03-22 16:32:10.971344,2025-03-22 16:33:35.892805,0 days 00:01:24.921461,24.0,gelu,...,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.002675,NaN,COMPLETE
10,10,0.500000,0.637319,0.668235,0.000000,2025-03-22 16:33:35.920438,2025-03-22 16:33:44.102502,0 days 00:00:08.182064,NaN,relu,...,0.803615,False,SGD,NaN,Step,29.0,NaN,0.000002,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,319,0.631136,0.640307,0.672263,0.599391,2025-03-22 17:13:15.023296,2025-03-22 17:13:36.259265,0 days 00:00:21.235969,NaN,swish,...,NaN,NaN,Adam,NaN,None,NaN,NaN,0.003432,NaN,COMPLETE
320,320,0.500000,0.618895,0.656689,0.666667,2025-03-22 17:13:31.370999,2025-03-22 17:13:51.564483,0 days 00:00:20.193484,47.0,swish,...,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002453,NaN,COMPLETE
321,321,0.500000,0.655903,0.677238,0.000000,2025-03-22 17:13:36.289011,2025-03-22 17:13:57.711399,0 days 00:00:21.422388,47.0,swish,...,NaN,NaN,Adam,NaN,Cosine,NaN,NaN,0.002367,NaN,COMPLETE
322,322,0.535063,0.646999,0.651761,0.190476,2025-03-22 17:13:51.600192,2025-03-22 17:14:12.630365,0 days 00:00:21.030173,43.0,gelu,...,0.941160,False,SGD,NaN,Cosine,NaN,NaN,0.000447,NaN,COMPLETE
325,325,0.591164,0.659786,0.677968,0.432879,2025-03-22 17:14:24.572043,2025-03-22 17:15:48.108398,0 days 00:01:23.536355,28.0,relu,...,NaN,NaN,AdamW,NaN,Cosine,NaN,NaN,0.000001,NaN,COMPLETE

In [5]:
df.params_gnn_layer.value_counts()

params_gnn_layer
MPNN    162
GCN      78
Name: count, dtype: int64